- charts/tradestream/templates/kafka-service.yaml
- charts/tradestream/templates/kafka-statefulset.yaml
This pull request updates the Helm chart templates for the **TradeStream** project by explicitly adding the `namespace` field to ensure proper deployment and compatibility with Argo CD. 
- **`kafka-service.yaml`**: Added `namespace: {{ .Release.Namespace }}` to both `kafka-headless` and `kafka` service metadata.
- **`kafka-statefulset.yaml`**: Added `namespace: {{ .Release.Namespace }}` to the StatefulSet metadata.
- Ensures that all resources are deployed in the specified namespace when managed by Argo CD or other Kubernetes deployment tools.
- Prevents `InvalidSpecError` issues related to missing namespaces, improving compatibility with GitOps workflows and automated deployment systems.
- This change enforces the deployment of Kafka services and StatefulSets into the namespace provided …
> Add Namespace to Kafka Templates in Helm Chart

- charts/tradestream/values.yaml
This pull request updates the `values.yaml` file in the TradeStream Helm chart to use a more recent ARM-compatible version of Kafka and ensures the image is always pulled during deployment.
- **Updated Image Tag:**
- Changed from `3.4.0-debian-11-r0` to `3.8.1` to use a more current and ARM-compatible Kafka version.
- **Added `pullPolicy`:**
- Set `imagePullPolicy` to `Always` to ensure the latest image version is pulled every time a pod is created or restarted.
- The `bitnami/kafka:3.8.1` image is verified to support `linux/arm64`, making it suitable for ARM-based clusters such as Raspberry Pi 4.
- Setting `imagePullPolicy` to `Always` guarantees that the deployment pulls the latest image updates, which is essential for environments requiring frequent updates or security patches.
- …
> Update Kafka Image to Latest ARM-Compatible Version with Pull Policy

- .github/workflows/bazel-test.yaml
This commit changes the Bazel test command in the CI workflow to show all test output, including standard output and standard error streams, for all tests. This change improves debugging by making it easier to see the output of failing tests, even if they don't explicitly print to stderr.
> chore:  Show all Bazel test output in CI

- MODULE.bazel
This PR upgrades the XChange and RxJava dependencies to newer versions:
- XChange: 5.0.9 -> 5.2.0
- RxJava: 2.2.21 -> 3.1.6 (to match XChange Stream's requirement)
- Other dependencies updated for consistency and to resolve potential conflicts.
This upgrade brings several benefits, including:
- Support for newer exchanges and features.
- Performance improvements.
- Bug fixes.
- Compatibility with newer Kafka clients.
The upgrade also required changing the Kafka client dependency to 3.6.1 for compatibility reasons.
> feat: Upgrade XChange and RxJava dependencies

- protos/marketdata.proto
This commit updates the protobuf syntax from `syntax = "proto3";` to `edition = "2023";`.  This leverages the latest Protobuf features and best practices, including performance improvements.  While functionally equivalent to `proto3` in most cases, the newer syntax allows for future enhancements and compatibility with newer Protobuf tools.
> chore: Update protobuf syntax to proto3

- MODULE.bazel
This PR updates the `MODULE.bazel` file to include the `com.google.truth:truth:1.4.4` dependency. The Truth library enhances the readability and reliability of assertions in Java unit tests, allowing for expressive, fluent assertions. This addition supports the testing framework for the `CandleKey` class introduced in previous changes.
- **Updated Dependencies:** Adds `"com.google.truth:truth:1.4.4"` to `maven.install` for improved assertion support in unit tests.
- **Purpose:** Truth provides fluent assertion methods that increase test clarity and ease of maintenance, which is valuable for testing components like `CandleKey`.
This improvement is part of ongoing efforts to build a robust testing framework for the TradeStream project.
> Add Google Truth Library Dependency for Enhanced Assertions in Tests

- MODULE.bazel
This pull request adds the `com.google.inject:guice:7.0.0` dependency to the Bazel module to enable dependency injection support across the project. Guice provides a lightweight and flexible approach to managing dependencies, which will enhance the modularity and testability of components within the application. This addition is compatible with existing dependencies and aligns with the current module configuration. 
- Added `com.google.inject:guice:7.0.0` to `maven.install` in `MODULE.bazel`. 
The inclusion of Guice allows for improved code structure and cleaner dependency management, which is particularly beneficial for large-scale applications or services that require flexible injection and configuration of components.
> Add Guice Dependency for Dependency Injection

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
This PR adds a `java_binary` rule to the BUILD file in the `src/main/java/com/verlumen/tradestream/ingestion` directory. This change allows for the creation of executable binaries from the Java code in this package.
This is likely needed to:
* **Run ingestion processes directly:**  Enable running ingestion tasks as standalone applications.
* **Facilitate testing and debugging:** Simplify testing and debugging of ingestion logic by running it independently.
* **Improve deployment:**  Package ingestion processes into easily deployable binaries.
This PR only modifies the BUILD file to include the `java_binary` rule and does not introduce any changes to the Java code itself. Further changes may be needed to configure the binary and its dependencies depending on the specific use case.
> Ingestion: Add java_binary rule to BUILD file

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
This PR refactors the `real-time-data-ingestion` target in the `BUILD` file by creating a separate `java_library` target, `real-time-data-ingestion-lib`, for the source files. The original `java_binary` target is updated to depend on this library target and now only defines the main class and runtime dependencies.
- Created `real-time-data-ingestion-lib` as a `java_library` target, containing `RealTimeDataIngestion.java`.
- Updated `real-time-data-ingestion` to a `java_binary` target with `main_class` specified as `com.verlumen.tradestream.RealTimeDataIngestion`.
- Added `real-time-data-ingestion-lib` as a `runtime_dep` for the `real-time-data-ingestion` binary target.
This refactor improves modularity by separating the library logic from the binary entry point, facilitating better reuse …
> Refactor `real-time-data-ingestion` Target to Separate Library and Binary Components

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
This PR cleans up the `BUILD` file for `CandleKeyTest` by removing an outdated or redundant comment specifying `test_class`.
- Deleted the commented line `# test_class = "com.verlumen.tradestream.ingestion.CandleKeyTest",` from the `java_test` target in the `BUILD` file.
Removing this line improves readability and avoids potential confusion, as the `test_class` attribute is unnecessary in this context.
> Remove Redundant `test_class` Comment in `CandleKeyTest` BUILD Configuration

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
This update corrects the path for the entrypoint in the `oci_image` configuration within the `TradeStream` ingestion module's `BUILD` file. Key changes include:
- **Entrypoint Path Update:** Modified the entrypoint path from `/java-maven_deploy.jar` to `/src/main/java/com/verlumen/tradestream/ingestion/java-maven_deploy.jar` to reflect the accurate file location within the container.
- **Improved Build Accuracy:** Ensures the OCI image runs the correct JAR file, aligning with the updated directory structure.
This fix aligns the image entrypoint with the directory structure, ensuring accurate execution of the `java-maven_deploy.jar` file during runtime.
> Update OCI Image Entrypoint Path in TradeStream Ingestion Module

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
This minor update removes the unused `java_test` load statement from the `BUILD` file for the `TradeStream` ingestion module. Key changes include:
- **Removed `java_test` Load:** The `java_test` rule was removed from `@rules_java//java:defs.bzl` as it is not utilized in this specific `BUILD` file.
- **Improved Clarity:** Streamlines the `BUILD` configuration by removing unnecessary dependencies.
This cleanup simplifies the Bazel configuration, improving readability and maintainability.
> Remove Unused `java_test` Load Statement in TradeStream Ingestion Build File

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml
- **Renamed Targets:** `java-maven-lib` to `app-lib` and `java-maven` to `app`.
- **Entrypoint Update:** Adjusted `oci_image` and `container-structure-test.yaml` to use `/src/main/java/com/verlumen/tradestream/ingestion/app_deploy.jar`.
These changes improve naming consistency and keep the configuration aligned with updated target names.
> Rename Library and Binary Targets in TradeStream Ingestion Module

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- **Dependency Addition:** Added `@maven//:com_google_inject_guice` to `app-lib` to support dependency injection.
This update introduces Guice for better dependency management within the `app-lib` library.
> Add Guice Dependency to `app-lib` in TradeStream Ingestion Module

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- **Removed Binary Target:** Deleted the unused `real-time-data-ingestion` binary target, leaving only the library version.
- **Streamlined Dependencies:** Consolidates `real-time-data-ingestion` as a library for dependency injection.
This cleanup reduces redundancy and focuses on the modular library approach for `real-time-data-ingestion`.
> Remove Unused `real-time-data-ingestion` Binary Target

- MODULE.bazel
- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/test/java/com/verlumen/tradestream/ingestion/AppTest.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
Enhanced `App.run` test coverage by introducing `AppTest`, which uses Guice for dependency injection and Mockito for mocking. Added `guice-testlib` dependency to facilitate injection of `MarketDataIngestion` mock, ensuring `App.run` correctly initiates `marketDataIngestion.start()`. Updated `BUILD` file to include necessary dependencies for the new test.
> Add Guice and Mockito Unit Test for `App.run` Method

- src/test/java/com/verlumen/tradestream/ingestion/CandleKeyTest.java
Simplified assertions in `CandleKeyTest` by replacing fully qualified `Truth.assertThat` with static imports for `assertThat`. This change enhances readability and maintains consistency with other test files. No functional changes were made.
> Refactor `CandleKeyTest` to Use Static Imports for Truth Assertions

- .github/workflows/release.yaml
Simplified `release.yaml` by removing the step that commits version changes to `hubitat_lock_manager/version.py`. Now, the workflow only tags the release, reducing unnecessary commits to the `main` branch.
> Remove Version Commit Step from Release Workflow

- .github/workflows/release.yaml
Modified `release.yaml` to handle version suffixes based on branch. Adds `-develop` suffix for tags generated from `develop` branch, distinguishing prerelease artifacts. This enables separate versioning for `main` and `develop` branches, streamlining prerelease management.
> Add Suffix for `develop` Branch to Release Workflow

- .github/workflows/release.yaml
- charts/tradestream/templates/data-ingestion-deployment.yaml
- charts/tradestream/values.yaml
Introduced `data-ingestion-deployment.yaml` template for deploying the data ingestion component, configured to pull the Docker image with dynamically updated repository and tag from `values.yaml`. Added replica count and service port configuration under `data-ingestion` in `values.yaml`, enabling flexible scaling and port management. This setup ensures the data ingestion component is independently configurable within the Helm chart.
> Add Data Ingestion Deployment Template and Service Configuration to Helm Chart

- platforms/BUILD
Introduces platform definitions for Linux and macOS with ARM64 and AMD64 architecture support in the `BUILD` file. Enables Bazel builds to target specific OS and CPU configurations for native binaries.
> Add Platform Configurations for Linux and macOS Architectures

- platforms/transition.bzl
Adds a multi-platform transition rule for `oci_image` to support builds across multiple architectures. This rule allows setting target platforms dynamically via Bazel transitions. Copied from [rules_oci](https://github.com/bazel-contrib/rules_oci/blob/fdfbe2498feb17571db4ec0d5726d6c3ce13d21f/examples/multi_arch/transition.bzl).
> Add Multiarch Transition Rule for OCI Images

- MODULE.bazel
- WORKSPACE
- charts/tradestream/values.yaml
- platforms/BUILD
- platforms/docker.bzl
This pull request introduces several updates and enhancements to improve compatibility, dependency management, and configurability within the TradeStream project:
- **Bazel Dependencies**: 
- Added the `bazel_skylib` dependency in `MODULE.bazel` to utilize additional native Bazel rules required for dependency configuration.
- **Docker Dependency Management**: 
- Updated the `WORKSPACE` file to load Docker dependencies using `setup_docker_deps()`.
- Introduced `docker.bzl` with the `setup_docker_deps` function to download and configure Docker CLI binaries and `jd` tools for multiple platforms, enhancing cross-platform support (macOS arm64, macOS amd64, and Linux amd64).
- Modified `platforms/BUILD` to define `native_binary` targets and `config_setting` conditions for platform-specific …
> Add Bazel Skylib Dependency, Update Docker Dependencies, and Version Bump for TradeStream Chart

- .bazelrc
- MODULE.bazel
- platforms/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- **Java Toolchain Configuration**: Set up Java 17 toolchain in `.bazelrc` and `MODULE.bazel` to standardize the Java runtime and language version across builds.
- **Platform-Based Toolchains**: Enabled platform-based toolchain resolution in `.bazelrc` for more efficient builds.
- **Multi-Arch OCI Image Index**: Updated `BUILD` file to add multi-architecture support using `multi_arch` and `oci_image_index` for `linux_arm64` and `linux_amd64`, allowing platform-specific Docker images.
- **Toolchain Extensions**: Integrated `jq` and `tar` toolchains using `aspect_bazel_lib` in `MODULE.bazel` to support multi-arch builds and image indexing.
> Configure Java Toolchain, Enable Multi-Arch Image Index, and Add Platform-Based Toolchains

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
This pull request deletes the unused `main` method from the `RealTimeDataIngestion.java` class. Removing this method streamlines the class by eliminating redundant code, as the real-time data ingestion is now managed through other mechanisms within the application.
**Changes:**
- Removed the `main` method that printed "Starting real-time data ingestion..."
- Cleaned up the class by deleting unnecessary lines.
> Remove Unnecessary `main` Method from RealTimeDataIngestion

- src/test/java/com/verlumen/tradestream/ingestion/CandleManagerTest.java
This pull request refactors the `CandleManagerTest` by replacing manual mock initialization with `MockitoRule`. Utilizing `MockitoRule` simplifies the setup process, enhances readability, and ensures consistent mock behavior across tests.
**Changes:**
- **Modified:**
- `CandleManagerTest.java`:
- Added `@Rule` annotation with `MockitoRule` for automatic mock initialization.
- Removed manual invocation of `MockitoAnnotations.openMocks(this)` in the `setUp` method.
- Updated import statements to include `org.junit.Rule`, `org.mockito.junit.MockitoJUnit`, and `org.mockito.junit.MockitoRule`.
**Rationale:**
- **Simplified Setup:** Leveraging `MockitoRule` eliminates the need for explicit mock initialization, reducing boilerplate code.
- **Enhanced Readability:** The test setup becomes cleaner …
> Update `CandleManagerTest` to Use `MockitoRule` for Mock Initialization

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/PriceTracker.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/PriceTrackerTest.java
Refactored the `PriceTracker` class to use Guice for dependency injection by adding the `@Inject` annotation to its constructor. Updated `PriceTrackerTest` to utilize Guice's injector for initializing dependencies. Added Guice as a dependency in the `BUILD` files to support the injection framework.
**Changes:**
- **Modified:**
- `PriceTracker.java`:
- Added `@Inject` to the constructor.
- Changed method visibility from `public` to package-private.
- `PriceTrackerTest.java`:
- Updated to use Guice's `Injector` for injecting `PriceTracker`.
- **Updated:**
- `BUILD`:
- Added `@maven//:com_google_inject_guice` to `price-tracker` and its test dependencies.
> Integrate Guice DI into `PriceTracker` and Tests

- src/main/java/com/verlumen/tradestream/ingestion/TradeProcessor.java
This refactor improves the encapsulation of the `TradeProcessor` class by making it package-private and marking its methods as package-private instead of public. The class is also declared `final` to prevent subclassing, ensuring its behavior remains consistent.
**Changes:**
- **Class:**
- Made `TradeProcessor` package-private.
- Declared the class `final` to prevent subclassing.
- **Methods:**
- Updated `isProcessed` and `getMinuteTimestamp` to package-private.
- Removed unnecessary `public` access modifiers.
**Rationale:**
- **Encapsulation:** Restricting access to the `TradeProcessor` class and its methods ensures better control over its usage within the package.
- **Consistency:** Declaring the class `final` aligns with its intended use as a utility without extensibility.
- …
> Make `TradeProcessor` Package-Private and Finalize Methods

- src/test/java/com/verlumen/tradestream/ingestion/CandlePublisherTest.java
This update replaces manual mock initialization in `CandlePublisherTest` with `MockitoRule`. This simplifies the setup process and ensures consistency across test cases.
**Changes:**
- **Added:**
- `@Rule` field with `MockitoRule` for automatic mock initialization.
- **Removed:**
- Manual call to `MockitoAnnotations.openMocks(this)` in the `setUp` method.
**Rationale:**
- **Simplified Setup:** Eliminates boilerplate code for mock initialization.
- **Consistency:** Ensures all mocks are initialized uniformly before each test.
- **Readability:** Makes the test setup cleaner and more maintainable.
> Refactor `CandlePublisherTest` to Use `MockitoRule` for Mock Initialization

- src/main/java/com/verlumen/tradestream/ingestion/CandleBuilder.java
This refactor limits the visibility of the `CandleBuilder` class and its methods by making it package-private. This improves encapsulation and ensures the class is used only within its intended scope.
**Changes:**
- **Class:**
- Changed `CandleBuilder` from `public` to package-private.
- **Methods:**
- Updated `addTrade`, `hasTrades`, and `build` methods to package-private.
- Removed unnecessary `public` access modifiers.
**Rationale:**
- **Encapsulation:** Reduces unnecessary exposure of `CandleBuilder`, keeping it scoped to the package.
- **Simplicity:** Aligns visibility with usage, improving code maintainability.
- **Consistency:** Ensures access is restricted to where it is actually needed.
> Restrict `CandleBuilder` Access and Scope for Better Encapsulation

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CandlePublisher.java
Introduced `CandlePublisher` as an interface with a nested `Factory` for creating instances. Updated `BUILD` to include the new interface.
> Add `CandlePublisher` Interface with Factory

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
Renamed `trade-processor` to `trade_processor` in `BUILD` files to align with naming conventions. Updated dependencies in test configurations accordingly.
> Rename `trade-processor` to `trade_processor` for Consistency

- src/test/java/com/verlumen/tradestream/ingestion/CandlePublisherImplTest.java
Replaced `MockitoAnnotations.openMocks` with `MockitoRule` for mock initialization in `CandlePublisherImplTest`. Simplified the setup process and improved test readability.
> Use `MockitoRule` in `CandlePublisherImplTest`

- src/test/java/com/verlumen/tradestream/ingestion/TradeProcessorTest.java
Moved `TradeProcessor` initialization to an `@Before` method in `TradeProcessorTest` for cleaner and consistent test setup. Removed redundant initialization from individual test cases.
> Refactor `TradeProcessorTest` to Use `@Before` Setup Method

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/TradeProcessorTest.java
Replaced `TestParameterInjector` with `JUnit4` in `TradeProcessorTest`. Removed unnecessary `TestParameterInjector` dependency from the `BUILD` file. Simplified the test configuration.
> Simplify `TradeProcessorTest` by Removing TestParameterInjector

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CandleManager.java
- src/main/java/com/verlumen/tradestream/ingestion/CandlePublisherImpl.java
Updated `CandleManager` to depend on the `CandlePublisher` interface instead of `CandlePublisherImpl`. Adjusted `BUILD` files to reflect this change, ensuring proper dependency linkage. Made `CandlePublisherImpl` implement `CandlePublisher` for consistency.
> Replace `CandlePublisherImpl` with `CandlePublisher` in Dependencies

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
Standardized the naming convention by renaming `real-time-data-ingestion` to `real_time_data_ingestion` across the `BUILD` file. Updated all relevant dependencies to ensure consistency.
> Rename `real-time-data-ingestion` to `real_time_data_ingestion`

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
Merged the `app-lib` library into the `app` binary to simplify the build structure. Updated the `app` target to directly reference `App.java` as its source and set the `main_class` accordingly. Adjusted the `BUILD` files to remove the now-redundant `app-lib` target and updated dependencies in test targets to point to `app`.
> Combine `app-lib` and `app` into a single `java_binary`

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CandlePublisherImpl.java
Integrated Google's `@AutoFactory` annotation to generate a factory class for `CandlePublisherImpl`. Updated the `BUILD` file to include a dependency on the `autofactory` library. This simplifies the instantiation of `CandlePublisherImpl` by automating the creation of its factory.
> Add AutoFactory Support to `CandlePublisherImpl`

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
Updated the target name for `candle-builder` to `candle_builder` in both the `BUILD` files for source and test directories to ensure consistent naming conventions across the project. This change aligns with the project's standard naming style.
> Rename `candle-builder` to `candle_builder`

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
Renamed the target `candle-manager` to `candle_manager` in both source and test `BUILD` files to maintain consistency with the project's naming conventions. This update ensures uniformity across all build target names.
> Rename `candle-manager` to `candle_manager`

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
Updated Bazel build files to standardize naming conventions and dependency ordering, ensuring consistency across the project.
1. Renamed `price-tracker` to `price_tracker` in both target names and references.
2. Adjusted dependency orders to maintain uniformity:
- Moved `junit_junit` below `com_google_testparameterinjector_test_parameter_injector` where applicable.
- Grouped dependencies logically.
3. Updated references to `price-tracker` in test targets to `price_tracker`.
4. Rearranged dependencies in `CandleBuilderTest` and `CandlePublisherImplTest` for consistency.
These changes improve clarity and align the build configuration with standard naming practices.
> Refactor and Standardize Naming in Build Files

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
Updated naming conventions for `market-data-ingestion` to `market_data_ingestion` across all Bazel build and test files.
1. **Renamed Target:**
- `market-data-ingestion` renamed to `market_data_ingestion` in `BUILD` files.
2. **Updated References:**
- Adjusted all references to `market-data-ingestion` to match the new naming convention (`market_data_ingestion`).
3. **Maintained Dependency Integrity:**
- Updated dependencies in related targets to ensure proper referencing of `market_data_ingestion`.
These changes improve consistency and adhere to the project's naming standards.
> Standardize Naming for Market Data Ingestion Targets

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/CandleManagerTest.java
- Replaced `CandlePublisherImpl` with `CandlePublisher` in `CandleManagerTest` to align with updated interface usage.  
- Simplified `BUILD` dependencies by removing `TestParameterInjector` where unnecessary.  
- Updated test runner in `CandleManagerTest` to use `JUnit4` for consistency across the test suite.  
- Adjusted `BUILD` file references to match refactored dependency names (`candle_publisher` instead of `candle_publisher_impl`).  
This update improves test clarity, aligns dependencies with the refactored codebase, and simplifies test configurations.
> Refactor Candle Manager Tests and Dependency References

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/CandlePublisherImplTest.java
- Removed `TestParameterInjector` dependency from `CandlePublisherImplTest` as it was unused.  
- Updated `BUILD` file to exclude `@maven//:com_google_testparameterinjector_test_parameter_injector`.  
- Switched test runner in `CandlePublisherImplTest` to `JUnit4` for consistency with other tests.  
This cleanup simplifies dependencies and standardizes test configurations across the project.
> Remove TestParameterInjector from CandlePublisherImplTest

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/CandlePublisherImplTest.java
- Added `com.google.inject:guice` as a dependency in the `BUILD` file for the `CandlePublisherImplTest`.  
- Refactored `CandlePublisherImplTest` to use Guice for injecting the `CandlePublisherImpl` instance.  
- Simplified test initialization by leveraging dependency injection for mocked `KafkaProducer`.  
This update ensures a cleaner and more scalable test structure, aligning with best practices for dependency injection.
> Integrate Guice Dependency Injection in `CandlePublisherImplTest`

- src/test/java/com/verlumen/tradestream/ingestion/AppTest.java
- Updated `AppTest` to use `JUnit4` instead of `MockitoJUnitRunner`.  
- Introduced `MockitoRule` for improved flexibility and better integration with `JUnit4`.  
- Adjusted dependency binding for `MarketDataIngestion` mock to align with the new test runner.
This change modernizes the test setup and provides a more modular and maintainable testing framework.
> Refactor `AppTest` to Use `JUnit4` and Mockito Rule

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- Added `com_google_inject_extensions_guice_testlib` as a dependency for `CandlePublisherImplTest`.  
- Removed redundant `com_google_inject_guice` dependency from the `deps` list.  
- Ensured the test setup supports injection testing using the Guice test library.
This update enhances dependency injection testing capabilities, making `CandlePublisherImplTest` more robust and aligned with modern practices.
> Add Guice Test Library to `CandlePublisherImplTest` Dependencies

- MODULE.bazel
- Reordered dependencies in `MODULE.bazel` to align related libraries for better logical grouping and readability.  
- Moved the `auto-value-gson` dependencies below `gson` to reflect their dependency hierarchy and maintain consistency.  
This enhancement improves the maintainability of the Bazel module configuration by making the dependencies list easier to understand and navigate.
> Reorder Dependencies in `MODULE.bazel`

- MODULE.bazel
- Moved `auto-value-gson` dependencies (`auto-value-gson`, `auto-value-gson-annotations`, `auto-value-gson-factory`) below core libraries like `guava` and `protobuf` to maintain logical grouping.  
- Ensures that dependent libraries (`auto-value-gson`) appear after their base dependencies (`gson`) for better readability and logical structure.
This update improves clarity and alignment within the `MODULE.bazel` file, enhancing maintainability.
> Reposition `auto-value-gson` Dependencies in `MODULE.bazel`

- MODULE.bazel
- Consolidated and reorganized duplicate dependency entries in `MODULE.bazel` for clarity and efficiency:
- Removed duplicate references to `auto-value-gson` artifacts:
- `com.ryanharter.auto.value:auto-value-gson:1.3.1`
- `com.ryanharter.auto.value:auto-value-gson-annotations:0.8.0`
- `com.ryanharter.auto.value:auto-value-gson-factory:1.3.1`
- Ensured the following dependencies appear only once:
- `org.knowm.xchange` family (`core`, `stream-core`, `coinbasepro`, `stream-coinbasepro`)
- `io.reactivex.rxjava3:rxjava:3.1.6`
- `javax.inject:javax.inject:1`
This cleanup enhances maintainability by eliminating redundancy and improving readability while preserving functionality.
> Remove and Consolidate Duplicate Dependencies in `MODULE.bazel`

- BUILD
- Added `@maven//:com_google_auto_auto_common` and `@maven//:javax_annotation_javax_annotation_api` to the `java_library` target to ensure all necessary exports are included.
- Updated `autofactory_plugin` to include the same missing dependencies for completeness.
- These changes ensure that the build includes all required dependencies, improving consistency and avoiding potential missing dependency issues.
>  Add missing dependencies to `java_library` and `java_plugin` targets

- BUILD
- MODULE.bazel
- Reorganized and modularized the `BUILD` file to improve readability and maintainability:
- Introduced separate `java_plugin` definitions for `auto_value`, `auto_factory`, and `auto_service`.
- Added `common` and `service` modules for shared configurations.
- Consolidated plugin references and updated export declarations for clarity.
- Updated `MODULE.bazel` to include:
- `com.google.auto.service:auto-service:1.1.1` and its dependencies.
- `com.squareup:javapoet:1.13.0` for enhanced code generation support.
- Simplified the build by removing unnecessary annotations and redundant references.
- Ensured plugins and libraries are tagged and scoped correctly for compilation and runtime needs.  
This refactor makes the build system more modular and paves the way for smoother future …
> Refactor Plugins and Dependencies for Auto* Frameworks

- .github/workflows/bazel-test.yaml
This PR improves the GitHub Actions workflow for Bazel tests by adding a caching mechanism to speed up build and test times. 
- Replaced the "Mount bazel cache" step with a dedicated caching mechanism using `actions/cache@v4`.
- Configured caching to include relevant Bazel files such as `WORKSPACE`, `BUILD`, `.bzl`, and `bazel.rc` files.
- Added `restore-keys` to ensure partial cache retrieval in case of cache misses.
- Updated the Bazel test command to output errors only for better readability in logs.
These updates aim to reduce workflow runtime and improve the efficiency of CI builds.
> Enhance Bazel Test Workflow with Caching for Faster Builds

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CandleManager.java
- src/main/java/com/verlumen/tradestream/ingestion/CandlePublisherImpl.java
This PR refactors the `ingestion` module of the TradeStream project by removing dependencies on Google AutoFactory. The changes simplify class constructors and eliminate unnecessary factory generation, improving code clarity and maintainability.
- Removed AutoFactory annotations and related imports from:
- `CandleManager.java`
- `CandlePublisherImpl.java`
- Updated constructor signatures to directly accept dependencies without requiring `@Provided` annotations.
- Deleted `//:autofactory` dependency from the `BUILD` file for `CandleManager` and `CandlePublisherImpl`.
These changes streamline the code by relying on manual dependency injection, reducing reliance on external libraries and enhancing testability.
> Remove AutoFactory Dependencies from Ingestion Module

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/config.properties
This PR adds Kafka producer configuration and the necessary build setup to access it at runtime.
Changes:
- Added config.properties with standard Kafka producer settings
- Added Bazel runfiles dependency to access configuration file at runtime
- Updated BUILD file to include config.properties as a data dependency
Technical Details:
- Kafka configuration includes common producer settings like bootstrap servers, acks, batching, and serializers
- Using bazel_tools//tools/java/runfiles to properly access the config file in both development and production environments
> Add Kafka producer configuration file and Bazel runfiles dependency

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
- src/main/java/com/verlumen/tradestream/ingestion/StreamingExchangeProvider.java
- src/main/java/com/verlumen/tradestream/ingestion/config.properties
This update enhances the TradeStream ingestion module by adding support for `StreamingExchange` integration. It introduces a `StreamingExchangeProvider` class to dynamically provide a streaming exchange instance based on configuration properties. The `RealTimeDataIngestion` class is updated to utilize the `StreamingExchange` for real-time market data. Corresponding build files are updated to include the new dependencies and module configurations. The configuration now supports specifying the exchange name via `config.properties`.
> Integrate StreamingExchange Support for Real-Time Market Data Ingestion

- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This update introduces support for passing command-line arguments to the `IngestionModule` via a new `AutoValue`-based design. The `main` method in `App` is updated to utilize the `IngestionModule.create(args)` factory method. The build file now includes dependencies for Guava and AutoValue to support the new implementation. These changes improve modularity and enable runtime configuration via command-line inputs.
> Enhance Ingestion Module with Command-Line Arguments Support and AutoValue Integration 

- MODULE.bazel
- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This update adds the `ConfigArguments` class to handle command-line argument parsing using Argparse4j, enabling dynamic configuration of Kafka producer and exchange settings. The `IngestionModule` is updated to bind `Namespace` to `ConfigArguments`, providing parsed configurations at runtime. Dependencies for Argparse4j are included in the `MODULE.bazel` and build files, and `ConfigArguments` supports key Kafka and exchange parameters with defaults and detailed help descriptions.
> Introduce Command-Line Argument Parsing with Argparse4j for Configurable Ingestion

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/KafkaProperties.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/KafkaPropertiesTest.java
This update refactors the `KafkaProperties` class to leverage Argparse4j's `Namespace` for managing configuration, replacing the previous use of `Properties`. The tests for `KafkaProperties` are updated to use a `Namespace` backed by a `HashMap`, aligning with the new implementation. Dependency updates for Argparse4j are added to the relevant build files, ensuring streamlined and dynamic argument parsing. This change enhances flexibility and integration with command-line argument configurations.
> Refactor Kafka Properties to Use Argparse4j Namespace for Configuration

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This update introduces a configurable `candleIntervalSeconds` argument in `ConfigArguments`, allowing users to specify the candle interval duration dynamically. The `IngestionModule` is updated to provide a `TradeProcessor` instance based on the parsed `candleIntervalSeconds`. The build file now includes a dependency on `trade_processor` to integrate this functionality seamlessly. These changes enhance flexibility and improve configuration for real-time trading data processing.
> Add Candle Interval Configuration and TradeProcessor Integration

- MODULE.bazel
- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
This update integrates Google's Flogger as the logging framework for the TradeStream ingestion application. The `App` class replaces standard `System.out.println` statements with Flogger's structured logging. The build configuration includes dependencies for `flogger` and its system backend. Tests and runtime environments are updated to include the necessary backend, ensuring consistent and robust logging throughout the application.
> Add Flogger for Enhanced Logging in TradeStream Ingestion

- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/KafkaProperties.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
This update introduces significant enhancements to the TradeStream ingestion module:  
1. **Configurable Candle Publisher and Manager**:  
- Added a new `--candlePublisherTopic` argument for specifying the Kafka topic to publish candle data.
- Updated `IngestionModule` to provide a `CandleManager` and `CandlePublisher` configured dynamically from the namespace.
2. **Namespace Integration in KafkaProperties**:  
- Fixed namespace integration to retrieve Kafka-specific properties using `getString` for type safety.
3. **Simplified RealTimeDataIngestion**:  
- Replaced factories with direct injection of `CandleManager` and `CandlePublisher`, simplifying the class and aligning it with the dependency injection best practices.
These changes improve runtime flexibility and ensure easier …
> Improve Candle Configuration and Real-Time Data Ingestion in TradeStream

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairMetadata.java
- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairSupplier.java
This update introduces the following features to enhance currency pair management in the TradeStream ingestion module:  
1. **CurrencyPairMetadata Class**:  
- Implements metadata for currency pairs, including a `MarketCap` nested class for storing value and currency information.
- Uses `AutoValue` for immutability and easy instantiation.  
2. **CurrencyPairSupplier Interface**:  
- Defines a supplier for a set of `CurrencyPairMetadata` objects, leveraging Guava's `ImmutableSet` for efficient collection management.  
3. **Build File Updates**:  
- Adds two new library targets, `currency_pair_metadata` and `currency_pair_supplier`, to the `BUILD` file.  
- Includes dependencies for `xchange_core`, `AutoValue`, and `Guava` to support the new classes.  
These changes enable efficient …
> Add Support for Currency Pair Metadata and Suppliers 

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
This update improves the `RealTimeDataIngestion` class by:  
1. Adding a `subscriptions` list to manage `Disposable` subscriptions for RxJava streams.  
2. Introducing a `thinMarketTimer` for additional timed operations.  
3. Enhancing the `shutdown` method to:  
- Dispose of all active subscriptions.  
- Cancel the `thinMarketTimer` if initialized.  
- Disconnect the `StreamingExchange` gracefully.  
- Close the `CandlePublisher` resource.  
Dependency updates in the `BUILD` file include adding RxJava to support the new functionality. These changes ensure robust resource management and improve the reliability of the ingestion lifecycle.
> Enhance RealTimeDataIngestion with Subscription and Resource Cleanup

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairSupplierImpl.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
This update enhances the TradeStream ingestion module with the following additions:  
1. **CurrencyPairSupplierImpl Class**:  
- Implements the `CurrencyPairSupplier` interface.
- Provides a placeholder implementation with `UnsupportedOperationException`, ready for customization.  
2. **Integration in RealTimeDataIngestion**:  
- Adds `CurrencyPairSupplier` as a dependency in the `RealTimeDataIngestion` class for supplying currency pair metadata.  
3. **Build File Enhancements**:  
- Adds the `currency_pair_supplier_impl` target to the build file with dependencies on `Guava`, `currency_pair_metadata`, and `currency_pair_supplier`.  
- Updates the `real_time_data_ingestion` target to depend on `currency_pair_supplier`.  
These changes prepare the system for future enhancements involving …
> Add Currency Pair Supplier Implementation and Integration in RealTimeDataIngestion  

- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This change modifies the `IngestionModule` to include a binding for the `Timer` class. The `Timer` instances are now provided using a `Provider`, ensuring a clean and centralized configuration for creating `Timer` objects in the dependency injection framework.  
1. **`Timer` Binding:**
- Added `bind(Timer.class).toProvider(Timer::new);` to the `configure()` method.
- This ensures that `Timer` instances are created and injected properly when needed.
2. **Whitespace Adjustment:**
- Minor formatting updates for code cleanliness.
- Centralized and explicit configuration for `Timer` instances simplifies dependency injection.
- Improves modularity and flexibility for managing `Timer` objects in the application.  
- Adheres to best practices in dependency injection by avoiding direct …
> Update `IngestionModule` to Bind `Timer` via Provider

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
This update introduces a `convertTrade` method in the `RealTimeDataIngestion` class to streamline the conversion of `org.knowm.xchange.dto.marketdata.Trade` objects into `Trade` protobuf objects. This addition simplifies the processing of raw trade data and ensures consistency when integrating data from different exchanges.
---
1. **New Method: `convertTrade`**
- Converts `xchangeTrade` objects from the XChange library to `Trade` protobuf objects.
- Includes mapping for:
- **Timestamp**: Extracts the trade timestamp.
- **Exchange**: Sets the exchange name from the specification.
- **Currency Pair**: Uses the provided currency pair string.
- **Price**: Converts the trade price to a double.
- **Volume**: Converts the trade volume to a double.
- **Trade ID**: Uses the provided ID or …
> Add Trade Conversion Method to RealTimeDataIngestion

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
Simplifies the `shutdown` method in `RealTimeDataIngestion` by replacing the `for` loop with a `forEach` to dispose of subscriptions. Ensures the `ThinMarketTimer` cancellation remains intact for proper cleanup. Enhances readability and maintains existing functionality.
> Refactor `shutdown` Method in `RealTimeDataIngestion`

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
Adds functionality to `subscribeToTradeStreams` in `RealTimeDataIngestion`. This method now subscribes to all currency pairs provided by the `CurrencyPairSupplier` by mapping each pair to a `Disposable` subscription and storing them in the `subscriptions` list. Improves trade stream management and ensures all relevant streams are handled dynamically.
> Implement Trade Stream Subscription in `RealTimeDataIngestion`

- protos/BUILD
This update modifies the visibility of the `marketdata_proto` and `marketdata_java_proto` Protobuf libraries to restrict access. The `marketdata_proto` library is now private, and the `marketdata_java_proto` library is limited to subpackages using `//:__subpackages__`. These changes enhance encapsulation and maintain better control over library access within the codebase.
> Update Visibility of MarketData Protobuf Libraries

- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
This update enhances the `RealTimeDataIngestionImpl` class by integrating `ProductSubscription` for more granular control over streaming subscriptions. Key changes include:
- Adding a `provideProductSubscription` method in the `IngestionModule` to supply a default `ProductSubscription` instance.
- Updating `RealTimeDataIngestionImpl` to inject and utilize `ProductSubscription` when connecting to the exchange.
- Modifying the `start` method in `RealTimeDataIngestionImpl` to connect using the `ProductSubscription` instance.
These changes improve the flexibility and scalability of subscription handling, making it easier to define and manage specific product streams for real-time data ingestion.
> Add ProductSubscription to RealTimeDataIngestionImpl for Streamlined Exchange Connectivity

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/HttpClient.java
This update introduces a new `HttpClient` interface to standardize HTTP GET operations within the application. Key features include:  
- A `get` method accepting a URL and headers, designed to handle HTTP GET requests.  
- Capability to throw `IOException` for robust error handling.  
- A new build target, `http_client`, is added to manage the interface in the Bazel configuration.  
This foundational update enables flexible and reusable HTTP operations across the codebase.
> Add HttpClient Interface for HTTP GET Requests 

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairSupply.java
This update adds the `CurrencyPairSupply` class to centralize the management and transformation of currency pair metadata. Key features include:  
- **AutoValue Integration:** The class leverages `AutoValue` for immutability and streamlined object creation.  
- **Metadata Handling:** Accepts a list of `CurrencyPairMetadata` objects and provides an `ImmutableList` of `CurrencyPair` objects.  
- **Utility Method:** Includes a `currencyPairs()` method to extract currency pairs from metadata.  
- **Build Configuration:** A new Bazel target, `currency_pair_supply`, is added with dependencies on Guava, AutoValue, and XChange Core.  
This enhancement simplifies currency pair management, improving modularity and code clarity.
> Introduce CurrencyPairSupply for Managing Currency Pair Metadata

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This update incorporates `CurrencyPairSupply` into the `IngestionModule` for streamlined currency pair management. Key changes include:
- **Binding Addition:** `CurrencyPairSupply` is bound as a singleton instance using an empty `ImmutableList` for initialization.
- **Build Dependency:** The `currency_pair_supply` target is added to the relevant Bazel library to ensure proper inclusion.
- **Improved Modular Design:** This integration enhances modularity by centralizing currency pair metadata handling in the ingestion pipeline.
These changes prepare the system for efficient currency pair metadata management, improving scalability and code clarity.
> Integrate CurrencyPairSupply into Ingestion Module

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairMetadata.java
- src/main/java/com/verlumen/tradestream/ingestion/ThinMarketTimerTaskImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/CurrencyPairSupply.java
- src/test/java/com/verlumen/tradestream/ingestion/ThinMarketTimerTaskImplTest.java
This update transitions the `ThinMarketTimerTaskImpl` class to use `CurrencyPairSupply` instead of `CurrencyPairSupplier`. Key updates include:  
- **Dependency Injection Refactor:** `CurrencyPairSupply` is now injected into `ThinMarketTimerTaskImpl` to align with the updated architecture.  
- **Method Adjustment:** Replaces references to `currencyPairSupplier` with `currencyPairSupply` for fetching and processing currency pairs.  
- **Build File Update:** Updates the Bazel build configuration to replace `currency_pair_supplier` with `currency_pair_supply` as a dependency.  
These changes improve consistency with the new `CurrencyPairSupply` abstraction, ensuring modularity and maintainability across the codebase.
> Refactor ThinMarketTimerTaskImpl to Use CurrencyPairSupply

- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
This update refines the `provideProductSubscription` method in the `IngestionModule` to dynamically include currency pairs from `CurrencyPairSupply`. Key changes include:  
- **Dynamic Subscription Creation:** The `ProductSubscription` now utilizes a builder pattern to add trade subscriptions for all currency pairs supplied by `CurrencyPairSupply`.  
- **Enhanced Flexibility:** Automatically integrates available currency pairs into the subscription, reducing manual configuration and improving scalability.  
This improvement streamlines the creation of `ProductSubscription`, ensuring it reflects the current set of currency pairs dynamically.
> Enhance ProductSubscription Provider to Include Currency Pairs

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This update adds a binding for the `HttpURLConnectionFactory` interface to the `HttpURLConnectionFactoryImpl` implementation in the `IngestionModule`, complementing the existing `HttpClient` binding. Additionally, the `BUILD` file has been updated to include both `http_url_connection_factory` and `http_url_connection_factory_impl` libraries as dependencies. These changes enable robust HTTP connection management and enhance the modularity and extensibility of the ingestion system.
> Add HttpURLConnectionFactory Binding and Update Dependencies

- charts/tradestream/templates/sealed-secret.yaml
The `sealedsecrety.yaml` file has been renamed to `sealed-secret.yaml` and relocated to the `charts/tradestream/templates/` directory. This update aligns the file naming convention with standard practices and organizes the Helm chart structure for better maintainability and clarity. The file continues to define a `SealedSecret` resource for secure key management.
> Rename and Relocate `sealedsecrety.yaml` to `sealed-secret.yaml` 

- charts/tradestream/templates/data-ingestion-deployment.yaml
Updated the `data-ingestion-deployment.yaml` template to include an environment variable `COINMARKETCAP_API_KEY` in the container spec. This variable fetches its value from a Kubernetes `Secret` named `coinmarketcap-api-key` with the key `apiKey`. This change enables secure access to the CoinMarketCap API by injecting the API key directly into the container environment, adhering to best practices for managing sensitive data.
> Add API Key Environment Variable to Data Ingestion Deployment

- charts/tradestream/templates/_helpers.tpl
- charts/tradestream/templates/data-ingestion-deployment.yaml
This update centralizes the naming logic in the Helm chart by introducing a new `_helpers.tpl` file and moving `tradestream.fullname` and `tradestream.name` template definitions into it.  
1. **New `_helpers.tpl` File:**  
- Created a `_helpers.tpl` file in the `templates` directory to define reusable helper templates for naming.  
- Added the following helper templates:  
- `tradestream.fullname`: Generates a full name by combining the release name and chart name, ensuring a maximum length of 63 characters.  
- `tradestream.name`: Resolves the chart name or uses a custom override (`nameOverride`).  
2. **Simplified `data-ingestion-deployment.yaml`:**  
- Removed inlined naming logic from the deployment manifest.  
- Updated to use the centralized `tradestream.fullname` and …
> Refactor Helm Templates with Centralized Helper Definitions 

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- Added `coinmarketcap.apiKey` and `coinmarketcap.topN` arguments to `ConfigArguments`.  
- Defaults the API key to the `TRADESTREAM_COINMARKETCAP_API_KEY` environment variable.  
- Introduced a `provideCoinMarketCapConfig` method in `IngestionModule` for injecting `CoinMarketCapConfig`.  
- Updated dependencies in the BUILD file to include `coin_market_cap_config`.
> Add CoinMarketCap Configuration Support

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- Updated `IngestionModule` to bind `CurrencyPairSupply` to `CurrencyPairSupplyProvider` for dynamic provisioning of currency pairs at runtime.  
- Replaced `currency_pair_supply_impl` with `currency_pair_supply_provider` in the BUILD file to align with the new binding approach.  
- Enhances flexibility by integrating live data sourcing capabilities via `CurrencyPairSupplyProvider`.
> Transition `CurrencyPairSupply` to Dynamic Provider

- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- Modified `IngestionModule` to bind `StreamingExchange` with `Singleton` scope.  
- Ensures a single instance of `StreamingExchange` across the application's lifecycle, reducing resource consumption and improving efficiency.  
- Updated dependencies to reflect best practices for managing long-lived connections.
> Add Singleton Scope for `StreamingExchange`

- .github/workflows/ci.yaml
- charts/tradestream/templates/data-ingestion-deployment.yaml
- charts/tradestream/values.yaml
- Added support for passing configurable `args` to the `data-ingestion` container via Helm.  
- Updated `data-ingestion-deployment.yaml` to set container `args` dynamically using `Values.dataIngestion.args`.  
- Set default `args` value in `values.yaml` to `--runMode=wet`.  
- Modified the CI workflow to override the `args` value for testing (`--runMode=dry`).  
This change provides flexibility to customize runtime configurations for the `data-ingestion` container directly through Helm, enhancing deployment adaptability.
> Enable Configurable Command-Line Arguments for Data Ingestion in Helm

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- Introduced a log statement in the `subscribeToTradeStream` method to log when a trade stream subscription starts.  
- The log includes the currency pair being subscribed to, providing better traceability and debugging insights.  
This change enhances observability, helping to monitor which currency pairs are actively being processed.
> Add Logging for Trade Stream Subscription

- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- Updated the default value for the `--coinmarketcap.topN` argument in `ConfigArguments` from **100** to **10**.
- This change reduces the number of top cryptocurrencies tracked by default when using the CoinMarketCap API.
This adjustment optimizes resource usage and better aligns with scenarios requiring a smaller dataset by default.
> Adjust Default Top Cryptocurrencies Tracked in `ConfigArguments`

- .github/workflows/release.yaml
- Added the `bazel-contrib/setup-bazel@0.9.1` action to the release workflow to streamline Bazel builds.
- Enables Bazelisk caching for faster builds.
- Configures a per-workflow disk cache and shared repository cache to optimize build times.
This integration improves build efficiency and ensures better utilization of caching mechanisms across workflows.
> Bazel Integration in GitHub Release Workflow

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CandlePublisherImpl.java
Implement comprehensive logging in CandlePublisher to track Kafka publishing events and errors. This will help monitor the reliability of our data pipeline and quickly identify any publishing issues.
> Add logging to CandlePublisher for monitoring Kafka interactions

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- Simplified the `subscribeToTradeStreams` method by replacing the explicit `forEach` block with a streamlined `.map(...).forEach(...)` chain.
- The new implementation maps each currency pair to a subscription and directly adds it to the `subscriptions` list.
This change improves readability and conciseness while maintaining the same functionality.
> Streamlined Subscription to Trade Streams in `RealTimeDataIngestionImpl`

- charts/tradestream/values.yaml
Refactored the `dataIngestion.args` section in the `values.yaml` file for the `tradestream` Helm chart. The previous inline array format:  
```yaml
args: ["--runMode=wet"]
```  
has been updated to a multi-line YAML array format:  
```yaml
args: 
- "--runMode=wet"
```  
This change improves readability and scalability, making it easier to manage additional arguments in the future while maintaining YAML best practices.
> Refactor Helm Chart Values for Data Ingestion Arguments

- charts/tradestream/values.yaml
Updated the `dataIngestion.args` section in the `tradestream` Helm chart `values.yaml` file by adding the argument:  
```yaml
- "--candlePublisherTopic=candles"
```  
This enhancement allows the configuration of the `candlePublisherTopic` to specify the Kafka topic (`candles`) used for publishing candle data, improving flexibility and alignment with the application's data flow requirements.
> Add Candle Publisher Topic to Data Ingestion Arguments

- charts/tradestream/values.yaml
This update refines the Kafka configuration by removing the node selector targeting ARM64 architecture. Key changes include:
1. **Node Selector Removal**:  
- The `nodeSelector` for ARM64 has been removed, enabling Kafka pods to deploy on any available node regardless of architecture.
2. **Unchanged Persistence Settings**:  
- Persistence remains enabled with a 10Gi volume size to maintain data durability across restarts.
This change improves deployment flexibility, making Kafka compatible with a broader range of Kubernetes clusters and node architectures.
> Simplify Kafka Deployment Configuration for Tradestream

- src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java
The `MessageHandler` class in `CoinbaseStreamingClient` was converted to a static inner class for better encapsulation. A reference to the parent `CoinbaseStreamingClient` instance is passed to the `MessageHandler` during construction, enabling access to instance-specific fields like `tradeHandler` and methods like `getExchangeName`. This approach improves clarity and maintains a clean separation of concerns while allowing `MessageHandler` to interact with the outer class effectively.
> Refactor `MessageHandler` to a Static Inner Class in `CoinbaseStreamingClient`

- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairMetadata.java
The `create` method in `CurrencyPairMetadata` that accepts a `CurrencyPair` and a `BigDecimal` for market capitalization was changed from `static` with package-private access to `private`. This limits the creation of `CurrencyPairMetadata` instances to within the class itself, enforcing better encapsulation and preventing unintended usage from other classes.
> Restrict `create` Method Access in `CurrencyPairMetadata`

- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairMetadata.java
- src/test/java/com/verlumen/tradestream/ingestion/ThinMarketTimerTaskImplTest.java
1. **Removed Redundant Overload**:
- The overloaded `create` method in `CurrencyPairMetadata` that accepted a `CurrencyPair` and a `long` market capitalization was removed. This simplifies the API and reduces redundancy.
2. **Dynamic Counter Currency**:
- Updated the remaining `create` method to dynamically use the counter currency from the `CurrencyPair` for the `MarketCap` creation, improving flexibility and aligning the metadata with the specific currency context.
3. **Test Adjustments**:
- Modified tests in `ThinMarketTimerTaskImplTest` to use the simplified `create` method that directly accepts a string representing the currency pair and a `BigDecimal` for market capitalization, ensuring consistency with the refactored implementation.
> Refactor `CurrencyPairMetadata` Factory Method for Enhanced Flexibility

- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairMetadata.java
This update modifies the `create` method in the `CurrencyPairMetadata` class to use the counter currency from the provided `CurrencyPair` for `MarketCap` creation. 
1. **Dynamic Counter Currency**:
- Replaced the static use of `Currency.USD` with `currencyPair.getCounter()` when creating a `MarketCap`. This ensures the metadata reflects the specific counter currency associated with the `CurrencyPair`.
2. **Improved Flexibility**:
- Allows `CurrencyPairMetadata` to support diverse currency pairs dynamically, aligning metadata construction with the actual trading pair context.
This change simplifies the handling of non-USD counter currencies and increases adaptability in multi-currency trading environments.
> Enhance `CurrencyPairMetadata` MarketCap Initialization with Dynamic Counter Currency

- src/main/java/com/verlumen/tradestream/ingestion/CurrencyPairMetadata.java
This update refactors the `CurrencyPairMetadata` class to simplify how `MarketCap` is represented and used.
1. **MarketCap Simplification**:
- Removed the nested `MarketCap` class and replaced it with a straightforward `BigDecimal` to represent market capitalization directly.
- This change eliminates unnecessary abstraction and reduces the overall complexity of the class.
2. **Updated Method Signatures**:
- Added a public `create` method that accepts a `CurrencyPair` and a `long` for market capitalization, delegating to an internal `BigDecimal`-based `create` method.
- Simplifies client-side interaction by supporting both numeric and `BigDecimal` inputs.
3. **Streamlined `create` Logic**:
- The `marketCap` property now directly reflects a `BigDecimal`, reducing overhead and improving …
> Simplify `CurrencyPairMetadata` and `MarketCap` Handling

- src/main/java/com/verlumen/tradestream/ingestion/ExchangeStreamingClient.java
Enhance the `ExchangeStreamingClient` interface by introducing a default method to check the support status of a specific currency pair, allowing for future extensibility without breaking existing implementations.  
---
1. **Added `isSupportedCurrencyPair` Method**:  
- Introduced a default method `isSupportedCurrencyPair` to the `ExchangeStreamingClient` interface.  
- Provides a default implementation that always returns `true`.  
2. **Future-Proofing for Exchange-Specific Logic**:  
- The method enables exchange-specific implementations to override the default behavior and implement currency pair validation as needed.  
3. **Preserved Backward Compatibility**:  
- Existing implementations of `ExchangeStreamingClient` remain unaffected due to the default method implementation.  
---
- …
> Add Default Support Check for Currency Pairs in `ExchangeStreamingClient`  

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
- **New Method**: Introduced `supportedSymbols()` to filter symbols based on exchange support.  
- **Improved Start Logic**: `startMarketDataIngestion()` now ingests only supported symbols.  
- **Streamlined Flow**: Enhances compatibility checks and reduces runtime errors.  
Simplifies real-time ingestion by validating exchange compatibility upfront.
> Filter Unsupported Symbols for Market Data Ingestion

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- **Simplified Dependencies**: Removed `org_knowm_xchange_xchange_core` from the `BUILD` file.
- **Reason**: The project no longer relies on this library, ensuring cleaner and more efficient builds.
- **Impact**: Reduces overhead and potential confusion by maintaining only actively used dependencies.
> Remove Unused Dependency on `org_knowm_xchange_xchange_core`

- charts/tradestream/values.yaml
This update introduces the `--kafka.bootstrap.servers` argument under the `dataIngestion.args` in the Helm chart's `values.yaml` file.
1. **Kafka Bootstrap Server Argument**:
- Added `--kafka.bootstrap.servers` with a dynamically generated service address.
- Service address uses Helm templating:
```
{{ include "tradestream.fullname" . }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092
```
- Ensures the Kafka service is correctly resolved in the cluster.
2. **Namespace Awareness**:
- The argument dynamically resolves the namespace using `.Release.Namespace`, allowing the Helm chart to function across multiple namespaces without manual configuration.
3. **Default Kafka Port**:
- Specifies `9092` as the default Kafka bootstrap server port.
- **Dynamic and Scalable**:
- Simplifies …
> Add Kafka Bootstrap Server Argument in `values.yaml` for Helm Chart

- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
1. Removed `.setDefault("wet")` for the `--runMode` argument.
2. Requires explicit `"wet"` or `"dry"` configuration.
> Remove Default Value for `--runMode` Argument in `ConfigArguments`

- src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java
- src/main/java/com/verlumen/tradestream/ingestion/ExchangeStreamingClient.java
1. **`CoinbaseStreamingClient.java`**:
- Implemented `supportedCurrencyPairs` to fetch supported pairs from the Coinbase API.
- Parses product IDs into `CurrencyPair` instances using a customizable delimiter.
- Logs success and error states during API calls.
2. **`ExchangeStreamingClient.java`**:
- Added `supportedCurrencyPairs` abstract method to fetch exchange-supported pairs.
> Add Coinbase API Support for Fetching Supported Currency Pairs

- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml
1. **`ConfigArguments.java`**:
- Removed default value for `--kafka.bootstrap.servers`.
2. **`container-structure-test.yaml`**:
- Added explicit `--kafka.bootstrap.servers` argument with `localhost:9092` for tests.
> Remove Kafka Bootstrap Servers Default and Update Tests

- .github/workflows/ci.yaml
Upgraded `actions/checkout` from `v3` to `v4` for enhanced features and performance.
> Update GitHub Actions Checkout Version

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
Removed unnecessary logging of `supportedPairs` during extraction to streamline the `supportedCurrencyPairs` method.
> Remove Logging from Supported Pairs Extraction

- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
1. Removed redundant arrangement code in `start_initiatesStreaming`.  
2. Verified streaming with the pre-defined `SUPPORTED_CURRENCY_PAIRS` to ensure consistency.
> Simplify Streaming Test Assertions

- src/main/java/com/verlumen/tradestream/ingestion/ExchangeStreamingClient.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
1. Removed `isSupportedCurrencyPair` method from `ExchangeStreamingClient`.  
2. Deleted unused filtering logic in `RealTimeDataIngestionImpl`.  
3. Disabled outdated test cases related to unsupported currency pairs in `RealTimeDataIngestionImplTest`.
> Simplify Currency Pair Validation

- src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java
- src/main/java/com/verlumen/tradestream/instruments/CurrencyPair.java
- src/test/java/com/verlumen/tradestream/ingestion/ThinMarketTimerTaskImplTest.java
1. Removed unnecessary methods and inner classes from `CurrencyPair`, including `SymbolParts` and `withCustomDelimiter`.  
2. Consolidated symbol parsing into a single `splitSymbol` method for delimiter-based extraction.  
3. Updated `CoinbaseStreamingClient` to simplify symbol handling logic.
> Simplify CurrencyPair Logic

- charts/tradestream/values.yaml
- src/test/java/com/verlumen/tradestream/ingestion/KafkaPropertiesTest.java
1. Introduced `configurationOverrides` to allow custom Kafka settings in Helm `values.yaml`.  
2. Updated `dataIngestion.args` to include `kafka.acks`, `kafka.retries`, and `kafka.linger.ms`.  
3. Added unit test in `KafkaPropertiesTest` to validate these Kafka properties.
> Add Kafka Configuration Overrides

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/KafkaProperties.java
1. Added `Mug` dependency (`@maven//:com_google_mug_mug`) to `KafkaProperties` in the Bazel `BUILD` file.  
2. Refactored the `KafkaProperties` implementation to leverage `Mug`’s `BiStream` for streamlined property transformation:  
- Filtered keys with prefix `kafka.`.  
- Removed the `kafka.` prefix from keys.  
- Converted non-null values to strings and applied to `Properties`.  
3. Simplified code and improved readability using functional constructs from `Mug`.
> Enhance `KafkaProperties` with `Mug` BiStream  

- charts/tradestream/values.yaml
- Removed Kafka authentication settings (`auth` block) from the Helm `values.yaml`.
- Simplified the `kafka.configurationOverrides` by retaining essential overrides like `offset.storage`, `transaction.state.log.replication.factor`, and `transaction.state.log.min.isr`.
- Ensured Kafka configuration is streamlined for environments that do not require SASL authentication.
> Remove Kafka Authentication Configuration

- src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java
- src/main/java/com/verlumen/tradestream/ingestion/ExchangeStreamingClient.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
- Removed the `delimiter` parameter from the `supportedCurrencyPairs` method in `ExchangeStreamingClient` and its implementation in `CoinbaseStreamingClient`.
- Updated `CoinbaseStreamingClient` to handle product ID mapping without custom delimiters.
- Adjusted `RealTimeDataIngestionImpl` to align with the updated `supportedCurrencyPairs` method signature.
- Simplified `supportedCurrencyPairs` logic by directly copying supported pairs as an `ImmutableSet`.
- Updated unit tests in `RealTimeDataIngestionImplTest` to reflect the method signature changes.
> Remove Delimiter from Supported Currency Pairs Method

- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- **Value Serializer Update**:
- Changed the default Kafka value serializer from `StringSerializer` to `ByteArraySerializer` for enhanced flexibility in message handling.
- **New SASL Configuration**:
- Introduced the following SASL-related arguments to support secure Kafka authentication:
- `--kafka.security.protocol`: Defines the protocol used (e.g., `PLAINTEXT`, `SASL_SSL`).
- `--kafka.sasl.mechanism`: Specifies the SASL mechanism (e.g., `PLAIN`, `SCRAM-SHA-256`).
- `--kafka.sasl.jaas.config`: Allows providing the JAAS configuration string.
- **Purpose**:
- These changes ensure compatibility with secure Kafka setups, enabling authentication and encryption using SASL mechanisms when required.
> Add SASL Configuration Options for Kafka in ConfigArguments

- src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
- **Default Protocol Change**:
- Updated the default value of `--kafka.security.protocol` from `PLAINTEXT` to `SASL_PLAINTEXT`.
- **Purpose**:
- Aligns with secure Kafka configurations, ensuring authentication is enabled by default while maintaining backward compatibility with plaintext setups.
> Update Default Kafka Security Protocol to SASL_PLAINTEXT

- .github/workflows/release.yaml
- **Key Changes**:
- Appended the current branch name to the Git tag during release workflow.
- Adjusted the tag creation step to include the extracted branch name using `${{ steps.extract_branch.outputs.branch }}`.
- **Purpose**:
- Helps differentiate tags when releases are made from multiple branches.
- Ensures clarity and traceability in version tags by explicitly including the branch name.
- **Workflow Update**:
- Extracts branch name in an earlier step and uses it during the tag creation.
- The final image tag also includes the branch name for consistency.
- **Example**:
- Before: `v1.2.3`
- After: `v1.2.3-main` (where `main` is the branch name).
This change simplifies tag management across branches and avoids potential conflicts between branch-based releases.
> Add Branch Name to Git Tags in Release Workflow

- .github/workflows/release.yaml
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- **Release Workflow Updates**:
- Added steps to **push the Strategy Engine image** to the container registry as part of the release workflow.
- Extended `yq` processing to update the **strategy engine** image repository and tag in `values.yaml`.
- Unified the commit message to reflect updates for multiple images.
- **Bazel Updates**:
- Added an `oci_push` target in the `strategies/BUILD` file to push the Strategy Engine image to `tradestreamhq/tradestream-strategy-engine`.
1. **`.github/workflows/release.yaml`**:
- Introduced `STRATEGY_ENGINE_REPO` and `STRATEGY_ENGINE_SECTION_KEY`.
- Added a step to **push the Strategy Engine image** using Bazel.
- Modified `yq` script to update the `strategyEngine` section in `values.yaml` alongside `dataIngestion`.
- Unified commit message to reflect …
> Add Image Push for Strategy Engine to Release Workflow

- charts/tradestream/values.yaml
- **`values.yaml` Updates**:
- Removed the `pullPolicy` field from the `dataIngestion.image` section in the Helm chart.
- Simplifies the Helm chart configuration by relying on Kubernetes' default pull policy:
- `IfNotPresent` for locally built or cached images.
- `Always` for images tagged with `latest` or `sha256` digests.
- Ensures flexibility in image pulling behavior based on tag usage.
- Reduces unnecessary configuration overhead in the Helm chart.
> Remove Image Pull Policy from Helm Chart

- .github/workflows/ci.yaml
Removed the `pullPolicy` setting for `dataIngestion.image` in the CI workflow to rely on the default Kubernetes behavior.
> Remove Pull Policy from CI Workflow

- .github/workflows/ci.yaml
Replaced `tradestream-app` references with `tradestream-data-ingestion` across the CI workflow to align with the updated repository naming convention. Adjusted image pull, retagging, and Minikube load steps accordingly.
> Update Image Repository and Tag References

- MODULE.bazel
- protos/marketdata.proto
- protos/strategies.proto
Updated Protobuf syntax to `edition = "2023"` in `marketdata.proto` and `strategies.proto` for compatibility with modern Protobuf features. Added the `protobuf` Bazel dependency (version 29.1) in `MODULE.bazel` to support the new Protobuf edition. This ensures consistency and readiness for advanced Protobuf capabilities in the project.
> Upgrade Protobuf Syntax to Edition 2023 and Add Dependency

- MODULE.bazel
- protos/BUILD
- protos/backtesting.proto
Introduced a new `backtesting.proto` file for defining messages related to strategy backtesting. Added dependencies on `marketdata.proto` and `strategies.proto`, as well as Google's `any.proto`. Key features include:
1. **New Messages**:
- `BacktestRequest`: Standard backtest request with candles and a strategy type.
- `ParameterizedBacktestRequest`: Adds support for strategy parameters using `google.protobuf.Any`.
- `TimeframeResult`: Metrics for backtesting results over specific timeframes.
- `BacktestResult`: Aggregates multiple `TimeframeResult` objects, providing an overall strategy evaluation.
2. **Bazel Integration**:
- Added `backtesting_proto` and `backtesting_java_proto` targets in `protos/BUILD`.
These changes establish the foundation for implementing and evaluating trading …
> Add Backtesting Protobufs and Integration

- MODULE.bazel
- protos/BUILD
Updated the `protobuf` Bazel dependency to use the repository name `com_google_protobuf` for better clarity and consistency. Key changes include:
1. **MODULE.bazel**:
- Changed `protobuf` dependency to include `repo_name = "com_google_protobuf"`.
2. **Protobuf BUILD File**:
- Updated `backtesting_proto` target to reference `@com_google_protobuf//:any_proto` instead of `@protobuf//:any_proto`.
This change ensures naming consistency across the project and aligns with standard Bazel practices for external dependencies.
> Update Protobuf Dependency Naming and References

- MODULE.bazel
- protos/BUILD
- protos/backtest_service.proto
Introduced gRPC support for the backtesting module to enable remote invocation of backtest operations. Changes include:
1. **MODULE.bazel**:
- Added `grpc-java` dependency with version `1.68.1`.
2. **Protobuf and BUILD Updates**:
- Added `backtest_service.proto` to define the `BacktestService` and `ParameterizedBacktestService` gRPC services.
- Updated `BUILD` file to include:
- `proto_library` for `backtest_service.proto`.
- `java_proto_library` and `java_grpc_library` for generating Java bindings.
These changes facilitate the integration of gRPC-based remote backtesting functionality in the application.
> Add gRPC Support for Backtesting Service

- protos/BUILD
Added support for generating Java bindings for the `google.protobuf.Any` type to enhance integration with existing protobuf services. Changes include:
1. **`BUILD` File Updates**:
- Introduced a `java_proto_library` target named `any_java_proto` to generate Java bindings for the `google.protobuf.Any` type.
This update ensures compatibility with protobuf messages that use the `Any` type, streamlining development for services requiring dynamic message structures.
> Add Java Bindings for Protobuf Any Type

- protos/BUILD
This PR refines the visibility and packaging configurations for protobuf targets to enhance reusability and standardization across modules.
1. **Set Default Visibility**:
- Introduced `default_visibility = ["//visibility:public"]` for all protobuf-related targets.
2. **Simplified Visibility Declarations**:
- Removed explicit `visibility = ["//:__subpackages__"]` from individual `java_proto_library` targets to rely on the default visibility.
These changes simplify the build configuration while maintaining flexibility for target reuse across projects.
> Refactor Protobuf Build Visibility and Default Configurations

- MODULE.bazel
This PR updates the Protobuf Java dependency in `MODULE.bazel` to align with newer library versions and maintain compatibility with recent changes in protobuf tools.
- **Updated Dependency**:
- `com.google.protobuf:protobuf-java` bumped from `3.21.12` to `4.29.1`.
This ensures the project benefits from the latest features, bug fixes, and performance improvements in the Protobuf library.
> Update Protobuf Java Dependency to Version 4.29.1

- MODULE.bazel
- protos/BUILD
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
This PR introduces the `StrategyFactory` interface and updates dependencies to support the implementation.
- **New Class**: 
- `StrategyFactory.java`: A generic interface to create Ta4j strategies based on protobuf `Any` parameters and `BarSeries`.
- **Dependency Updates**:
- Added `org.ta4j:ta4j-core:0.17` for technical analysis and strategy implementation.
- Updated Protobuf dependency to version `4.29.1`.
- **Build Changes**:
- Added `strategy_factory` in `BUILD` for `StrategyFactory` with relevant dependencies.
- Adjusted `MODULE.bazel` to include `ta4j-core`.
This enables dynamic strategy creation and parameter handling for backtesting and live trading scenarios.
> Add StrategyFactory Interface and Update Dependencies

- protos/BUILD
This PR removes the unused `any_java_proto` target from the `protos/BUILD` file. 
- **Removed**: 
- The `java_proto_library` definition for `any_java_proto` was removed as it was not referenced elsewhere in the project.
- **Impact**:
- Cleans up unnecessary targets from the build file to improve maintainability and clarity.
No functional changes were introduced with this update.
> Remove Unused `any_java_proto` Target from Protos BUILD

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
This PR refactors the `StrategyFactory` interface by simplifying the `createStrategy` method. 
- **Updated**:
- The `createStrategy` method signature now accepts a single parameter of type `T` instead of both `Any` and `BarSeries`.
- Removed the `BarSeries` dependency from the method parameters.
- **Impact**:
- Improves the design by decoupling the `StrategyFactory` interface from `BarSeries`, enhancing flexibility and reusability.
- Simplifies the interface for implementing classes, focusing purely on parameter unpacking.
No functional changes were introduced; this is a structural improvement.
> Refactor StrategyFactory to Remove BarSeries Dependency

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
Enhanced the `StrategyFactory` interface by adding a default method to handle `Any` parameters directly:
- Introduced a `createStrategy(Any parameters)` method to simplify strategy creation by unpacking `Any` into the required parameter type.
- Retained the original `createStrategy(T parameters)` for flexibility and backward compatibility.
- Improved `getParameterClass` implementation for clarity and type safety.
This update makes it easier to integrate with systems providing serialized parameters, improving usability and reducing boilerplate.
> Enhance `StrategyFactory` with Default `Any` Parameter Support

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
Refactored the `StrategyFactory` interface to include `BarSeries` as a parameter for strategy creation:
- Added a `BarSeries` parameter to the `createStrategy` methods for better integration with Ta4j's data requirements.
- Updated the default `createStrategy(Any parameters)` method to delegate to the new method with `BarSeries`.
- Enhanced JavaDocs for better clarity, explaining the purpose and usage of the interface and its methods.
This change improves flexibility and aligns with the Ta4j library's design patterns, enabling more robust strategy implementations.
> Update `StrategyFactory` to Include BarSeries Parameter

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
Enhanced the `StrategyFactory` interface by adding support for creating strategies directly from entry and exit rules:
- Introduced a new default method `createStrategy(BarSeries series, Rule entryRule, Rule exitRule)` that returns a `BaseStrategy`.
- Ensures compatibility with custom strategies by leveraging the Ta4j `Rule` interface.
- Updated documentation for better clarity and usage instructions.
This addition simplifies the process of creating strategies programmatically when entry and exit rules are pre-defined, improving developer productivity and flexibility.
> Add Rule-Based Strategy Creation to `StrategyFactory`

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
This PR refines the `createStrategy` method in the `StrategyFactory` interface. The `BarSeries` parameter was removed from the method signature as it was unnecessary for the creation of a `BaseStrategy` instance. The updated method now focuses solely on the `Rule` objects for entry and exit signals, improving clarity and reducing redundancy in the API.
>  Simplify `createStrategy` Method in `StrategyFactory`

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
This commit introduces a new `unstableBars` parameter to the `createStrategy` method in the `StrategyFactory` interface.
The `unstableBars` parameter allows specifying the number of initial bars to ignore when evaluating the strategy, helping to avoid potentially misleading early signals.
Additionally, the Javadoc for the `createStrategy` method has been improved to provide clearer explanations for all parameters:
- `entryRule`: Clarified as the rule triggering the opening of a position.
- `exitRule`: Clarified as the rule triggering the closing of a position.
- `unstableBars`: Documented the purpose of ignoring initial bars.
These changes enhance the flexibility and understandability of strategy creation.
> feat: Add `unstableBars` parameter to `createStrategy` and improve Javadoc

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactoryTest.java
This PR introduces the `DoubleEmaCrossoverStrategyFactory` for creating Double EMA Crossover strategies using Ta4j. The implementation defines strategy rules based on EMA crossovers. 
Key Changes:
1. Added `DoubleEmaCrossoverStrategyFactory` under `strategies/movingaverages`.
2. Implemented a comprehensive test suite for the factory, including:
- Verification of entry and exit rules.
- Functional tests with engineered BarSeries to trigger crossovers.
3. Updated Bazel `BUILD` files for the new library and test dependencies. 
This enhancement aligns with the modular design of the strategies module.
> Add `DoubleEmaCrossoverStrategyFactory` Implementation and Tests

- src/test/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactoryTest.java
This PR updates the unit tests for `DoubleEmaCrossoverStrategyFactory` to replace `assertTrue` and `assertFalse` with `Truth` assertions for consistency and improved readability.
**Changes Include:**  
- Replaced `assertTrue` and `assertFalse` with `assertThat(...).isTrue()` and `assertThat(...).isFalse()` respectively in:
- `entryRule_shouldTrigger_whenShortEmaCrossesAboveLongEma`
- `exitRule_shouldTrigger_whenShortEmaCrossesBelowLongEma`
These changes align the test assertions with the `Truth` framework, ensuring consistency and clarity across the test suite.
> Simplify Assertions in DoubleEmaCrossoverStrategyFactoryTest

- .github/workflows/ci.yaml
This PR updates the GitHub Actions CI workflow to integrate the Strategy Engine image into the TradeStream deployment process. It includes building, tagging, pushing, and deploying the Strategy Engine Docker image alongside the existing Data Ingestion image.
1. **Build and Push the Strategy Engine Image:**
- Added steps to build the `Strategy Engine` image using Bazel.
- Pushed the image to the local registry (`localhost:5000`).
2. **Pull and Retag Images:**
- Added steps to pull both the `Data Ingestion` and `Strategy Engine` images from the local registry.
- Retagged images to remove the registry prefix, ensuring compatibility with Minikube's image cache.
3. **Minikube Integration:**
- Loaded both `Data Ingestion` and `Strategy Engine` images into Minikube's image cache for use in local …
> Add Strategy Engine to CI Workflow with Helm Integration  

- .github/workflows/ci.yaml
- charts/tradestream/templates/strategy_engine.yaml
- charts/tradestream/values.yaml
This PR introduces a new deployment configuration for the `Strategy Engine` as part of the TradeStream Helm chart. It adds support for deploying the `Strategy Engine` microservice, allowing for better modularity and configurability within the TradeStream architecture.
---
- Introduced a Kubernetes `Deployment` for the `Strategy Engine` component:
- Configurable replicas via `strategyEngine.replicaCount`.
- Includes runtime arguments via the `strategyEngine.args` value, allowing seamless customization.
- Connects to Kafka by dynamically resolving the Kafka service address.
- Uses configurable image repository, tag, and pull policy.
- Added `strategyEngine` block:
- `image.repository`: Default image location for the `Strategy Engine`.
- `image.tag`: Specifies the version/tag to use for …
> Add Strategy Engine Deployment Template to TradeStream Helm Chart

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java
This PR introduces the `StrategyManager` interface and its implementation, which is responsible for creating `ta4j` Strategy instances based on the provided StrategyType and serialized strategy parameters. This is a foundational step for allowing dynamic strategy creation within the system.
- Added a new `StrategyManager.java` file defining the `StrategyManager` interface.
- Updated the `BUILD` file to include the `strategy_manager` target.
- The `StrategyManager` interface defines the `createStrategy` method which takes a `StrategyType` and protobuf `Any` message as inputs, and returns a `ta4j` `Strategy` instance.
- The `strategy_manager` target depends on `@maven//:com_google_protobuf_protobuf_java`, `@maven//:org_ta4j_ta4j_core`, `//protos:strategies_java_proto`, and …
> Add `StrategyManager` interface and implementation

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java
- src/main/java/com/verlumen/tradestream/strategies/StrategyManagerImpl.java
- src/test/java/com/verlumen/tradestream/strategies/BUILD
- src/test/java/com/verlumen/tradestream/strategies/StrategyManagerImplTest.java
This PR introduces the `StrategyManagerImpl` class to centralize the management and delegation of strategy creation to specific `StrategyFactory` instances. It refines the architecture by providing a configurable `Config` object that maps `StrategyType` to their respective `StrategyFactory`.
1. **Core Implementation**:
- Added `StrategyManagerImpl` to implement the `StrategyManager` interface.
- Included a nested `Config` class that uses `ImmutableMap` to associate `StrategyType` with their respective `StrategyFactory`.
2. **Interface Enhancements**:
- Updated `StrategyManager` to include a `BarSeries` parameter for strategy creation.
3. **Testing**:
- Created `StrategyManagerImplTest` to validate the behavior of `StrategyManagerImpl`.
- Tests include successful strategy creation, …
> Add `StrategyManagerImpl` for Managing and Delegating Strategy Creation

- third_party/BUILD
This PR refactors the `third_party/BUILD` file to modularize and streamline the definitions of frequently used third-party libraries. These changes improve maintainability and enable easier reuse of dependencies across the codebase.
1. **Modularized Library Definitions**:
- Extracted commonly used third-party libraries (e.g., `flogger`, `gson`, `guava`, `guice`, `kafka_clients`, etc.) into separate `java_library` targets within the `third_party/BUILD` file.
- Provided consistent naming and visibility settings for each library.
2. **New Library Targets**:
- Added `argparse4j` for argument parsing.
- Added `flogger` and `flogger_system_backend` for structured logging.
- Added `xchange_core` and `xchange_stream_core` for financial exchange API integration.
- Defined additional dependencies …
> Refactor Third-Party Library Definitions for Enhanced Modularity and Reusability

- src/main/java/com/verlumen/tradestream/instruments/BUILD
Replaced the direct Maven dependency on `com_google_guava_guava` with the curated `third_party:guava` dependency for the `currency_pair` target in the `BUILD` file. This aligns the dependency management with the project's centralized `third_party` strategy, ensuring consistency and simplifying future updates.
> Migrate `currency_pair` Guava Dependency to `third_party:guava`

- src/main/java/com/verlumen/tradestream/strategies/BUILD
Replaced direct Maven dependencies in the `strategies` module with corresponding `third_party` curated targets. Specifically, updated the dependencies for `strategy_manager_impl` and `App` targets to use `third_party:flogger`, `third_party:guice`, `third_party:guava`, `third_party:auto_value`, and `third_party:mug`. This change centralizes dependency management, promotes consistency, and simplifies future updates across the project.
> Transition `strategies` Module to `third_party` Dependencies

- third_party/BUILD
Introduced `third_party:protobuf_java` and `third_party:ta4j_core` targets to encapsulate `com.google.protobuf` and `org.ta4j.core` Maven dependencies, respectively. These additions improve dependency organization, provide a standardized interface for these libraries, and align with the project's centralized dependency management practices.
> Add `protobuf_java` and `ta4j_core` to `third_party` Dependencies  

- src/main/java/com/verlumen/tradestream/strategies/BUILD
Replaced direct Maven references for `com.google.protobuf` and `org.ta4j.core` in the `strategy_factory`, `strategy_manager`, and `strategy_manager_impl` targets with the corresponding `third_party:protobuf_java` and `third_party:ta4j_core` abstractions. This change centralizes dependency management, enhances maintainability, and ensures consistency across the project.
> Refactor Dependencies for `strategy_*` Targets to Use `third_party`  

- src/main/java/com/verlumen/tradestream/strategies/dataconsumption/BUILD
- src/main/java/com/verlumen/tradestream/strategies/dataconsumption/CandleWindow.java
Introduced a new `data_consumption` module to support data handling for strategies. Added the following:  
1. **`CandleWindow` Interface**: Defines methods for managing a window of candles, including adding candles and retrieving a fixed window size as an immutable list.  
2. **`data_consumption_lib`**: Bazel target managing the module, with dependencies on `marketdata_java_proto` and `third_party:guava`.  
This forms the foundation for implementing candle data management functionality in the strategy engine.
> Add `data_consumption` Module with `CandleWindow` Interface 

- src/main/java/com/verlumen/tradestream/strategies/BUILD
Adjusted the order of dependencies in the Bazel `BUILD` file for `strategy_manager` and `strategy_manager_impl` to align with project conventions and improve readability. Specifically:  
- Moved `//third_party:ta4j_core` to follow `//third_party:protobuf_java` and `//protos:strategies_java_proto` for consistent grouping.  
These changes enhance maintainability and ensure logical organization of dependencies within the `strategies` module.
> Fix Dependency Ordering in `strategy_manager` and `strategy_manager_impl`  

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestRunner.java
Introduced the foundational components for the backtesting module:  
- **`BacktestRunner` Interface:** Defines the contract for running backtests with methods to configure and execute strategy evaluations over bar series data.  
- Added `BacktestRequest` as a nested class for encapsulating parameters and configurations, leveraging `@AutoValue` for immutability and type safety.  
- **Bazel Build Rule:** Added `backtest_runner` to the `BUILD` file in the `backtesting` package, with dependencies on:  
- Protocol buffer definitions (`backtesting_java_proto`, `strategies_java_proto`).  
- External libraries (`auto_value`, `ta4j_core`).  
These changes set the stage for implementing and testing backtesting functionality in the `tradestream` project.
> Add BacktestRunner Interface and Build Rules for Backtesting Module

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/ParameterizedBacktestServiceImpl.java
- src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java
- third_party/BUILD
This update introduces foundational gRPC support and a new implementation for running parameterized backtests:  
- **`ParameterizedBacktestServiceImpl`:**  
- Implements `ParameterizedBacktestServiceGrpc.ParameterizedBacktestServiceImplBase` for handling backtest requests.  
- Injects dependencies for `StrategyManager` and `BacktestRunner` to facilitate strategy creation and backtest execution.  
- **Enhancements to Strategy Management:**  
- Updated `StrategyManager` interface visibility to `public` to enable broader usage in the backtest service.  
- **Bazel Build Updates:**  
- Added a new `parameterized_backtest_service_impl` target in the `backtesting` package with dependencies on:  
- Protocol buffers (`backtest_service_java_proto`, `marketdata_java_proto`, etc.).  
- Core …
> Add Parameterized Backtest Service Implementation and gRPC Support 

- MODULE.bazel
This update introduces the `module` statement in the `MODULE.bazel` file to define `tradestream` as a Bazel module with the following attributes:  
- **Name:** `tradestream`  
- **Version:** `0.0.1`  
- **Compatibility Level:** 1  
Additionally, comments were added to improve the readability of the configuration by grouping and labeling different dependency configurations and toolchain registrations.  
- Added the `module` declaration for better integration with Bazel's module system.  
- Updated comments to categorize sections such as Maven dependencies, OCI setup, and Bazel libraries.  
This PR is focused on clarifying and organizing the existing `MODULE.bazel` file with minimal structural changes.
> Add Bazel Module Declaration to `MODULE.bazel`

- MODULE.bazel
This update enhances the `MODULE.bazel` configuration by integrating Python support using `rules_python` and setting up pip dependencies for Python 3.10.  
1. **Dependencies Added:**
- Added `rules_python` version `1.0.0` for Python support in Bazel.
2. **Python Toolchain Configuration:**
- Configured the Python toolchain with coverage support enabled and defaulted to Python version `3.10`.
- Added support for additional Python versions (`3.9` and `3.10`) via `python_versions`.
3. **Pip Integration:**
- Integrated `pip` for Python dependency management.
- Configured pip dependencies specifically for Python 3.10 using `pip.parse`.
4. **Improved Organization:**
- Included additional comments to categorize and clarify the new configurations.
This PR introduces Python-related functionality, …
> Add Python Support with `rules_python` and Configure Pip in `MODULE.bazel`

- protos/BUILD
This PR updates the `BUILD` file in the `protos` directory to streamline the configuration of proto and Java proto libraries.  
1. **Standardized Visibility:**  
- Adjusted visibility of proto and Java proto libraries to `//visibility:public` where appropriate, enabling broader accessibility for dependent modules.  
- Ensures consistent application across `backtesting`, `marketdata`, and `strategies` libraries.  
2. **Refactored `java_grpc_library`:**  
- The `backtesting_java_grpc` target now explicitly includes visibility and maintains dependencies on its respective proto library.  
- Refactored to align with updated project standards for proto build files.  
3. **Introduced `proto_library` Loading:**  
- Explicitly loaded the `proto_library` rule from Bazel's protobuf package for …
> Refactor Proto Build Configuration for Enhanced Visibility and Consistency

- protos/BUILD
This PR introduces `py_proto_library` targets to the `protos/BUILD` file, enabling Python-based projects to consume the same proto definitions used by Java and other services.  
1. **Python Proto Libraries:**  
- Added `py_proto_library` targets for `backtesting_proto`, `marketdata_proto`, and `strategies_proto`.  
- Ensured these targets have `//visibility:public` for accessibility across the project.  
2. **Dependencies:**  
- Each Python proto library depends on its respective `proto_library` target, ensuring alignment with the core proto definitions.  
3. **Updated BUILD File Loading:**  
- Included the `py_proto_library` rule from Bazel's Python proto package to support the new Python libraries.  
- Expands multi-language support, enabling Python-based services and applications to …
> Add Python Proto Libraries for Enhanced Multi-Language Support

- MODULE.bazel
This PR updates `MODULE.bazel` to align with Python 3.9 compatibility and incorporates OCI image integration for enhanced containerized builds.  
1. **Python Configuration Adjustments:**  
- Downgraded the configured Python version from `3.10` to `3.9` for broader compatibility across systems.  
- Updated related `use_repo` and `pip.parse` configurations to reflect the Python 3.9 version.  
2. **Pip Requirements Parsing:**  
- Adjusted the `requirements_lock` target to `requirements.txt` to ensure alignment with Python 3.9.  
3. **OCI Image Integration:**  
- Introduced an `oci.pull` configuration to pull the latest `ubuntu` image with support for `linux/arm64/v8` and `linux/amd64` platforms.  
- Added `use_repo` for the `ubuntu` OCI image to enable streamlined builds using the pulled …
> Update MODULE.bazel for Python 3.9 Compatibility and OCI Image Integration

- MODULE.bazel
This PR updates the `MODULE.bazel` file to include the `grpc` dependency alongside the existing `grpc-java`.  
1. **gRPC Dependency Addition:**  
- Added `bazel_dep(name = "grpc", version = "1.68.0")` to explicitly include the gRPC library for Bazel-based builds.  
- Aligns the `grpc` versioning with the existing `grpc-java` dependency for consistency.  
2. **Existing Dependencies Maintained:**  
- Preserved the existing `grpc-java` dependency (`1.68.1`), ensuring compatibility across both Java and non-Java gRPC implementations.  
- **Improved Compatibility:** Adds support for gRPC-based features in environments requiring native gRPC implementations.  
- **Consistency:** Ensures that the gRPC and gRPC-Java libraries are version-aligned, minimizing integration issues.  
- **Enhanced …
> Add gRPC Dependency to MODULE.bazel

- third_party/requirements.in
- third_party/requirements.txt
This update adds `grpcio-testing==1.68.1` to the `requirements.in` and regenerates `requirements.txt` to include dependency hashes for `grpcio-testing` and its associated dependencies. It ensures compatibility with `grpcio==1.68.1` and updates protobuf to `5.29.2` to support gRPC testing requirements. These changes enhance the testing capabilities for gRPC components, improving test coverage and reliability.
> Add `grpcio-testing` and Update Dependency Hashes

- MODULE.bazel
This PR addresses duplicate artifact version issues identified in Bazel's `rules_jvm_external` integration, as revealed by debug logs.  
1. **Updated Artifact Versions:**
- **`auto-value` and `auto-value-annotations`:** Upgraded from `1.10` to `1.11.0` for consistency.
- **`gson`:** Upgraded from `2.9.1` to `2.11.0`.
- **`truth`:** Upgraded from `1.1.2` to `1.4.2`.
2. **Log Motivation:**  
Debug logs indicated multiple versions for several artifacts:
- `auto-value` and `auto-value-annotations`: `1.10`, `1.11.0`
- `gson`: `2.9.1`, `2.11.0`
- `truth`: `1.1.2`, `1.4.2`
- `guava`: `31.1-jre`, `33.2.1-android`
3. **Duplicate Version Resolution:**
- Ensured that only the latest and most stable versions compatible with the project are specified in `MODULE.bazel`.
- Eliminates warnings from Bazel …
> Resolve Duplicate Artifact Versions in Maven Dependencies

- MODULE.bazel
- protos/BUILD
This update improves Bazel module configurations and modernizes the `BUILD` files for Python protobuf and gRPC support. Key changes include:
1. **MODULE.bazel updates:**
- Adds dependencies for `rules_proto_grpc`, `rules_proto_grpc_java`, and `rules_proto_grpc_python` (version 5.0.1) to enhance protobuf and gRPC rules.
- Updates `rules_python` to version 0.37.2 for better compatibility with the latest Python build rules.
2. **protos/BUILD adjustments:**
- Replaces the deprecated `py_proto_library` with the modern `python_proto_library` rule from `rules_proto_grpc_python`.
- Updates the `protos` attribute to align with the new `python_proto_library` syntax for cleaner and more maintainable BUILD files.
- Removes unused `py_grpc_library` comments for clarity.
These changes align with …
> Update Bazel Module Dependencies and Replace Python Protobuf Rules

- MODULE.bazel
- protos/BUILD
- protos/backtesting.proto
- protos/marketdata.proto
- protos/strategies.proto
This update enhances protobuf and gRPC integration within Bazel's build system for the `protos` directory, focusing on modernizing and standardizing configurations for Python and Java. The changes include:
1. **`BUILD` File Improvements:**
- Adds `python_grpc_library` from `rules_proto_grpc_python` to support Python gRPC targets.
- Refactors previously commented `py_grpc_library` rule into an active `python_grpc_library` rule for the `backtesting_proto`.
- Ensures consistent visibility declarations for gRPC and proto rules.
2. **Protobuf Syntax Standardization:**
- Updates `.proto` files (`backtesting.proto`, `marketdata.proto`, `strategies.proto`) to use the `syntax = "proto3";` directive, replacing the outdated `edition = "2023";`.
3. **Package Integrity:**
- Retains existing package …
> Refactor Protobuf and gRPC Build Files for Bazel

- protos/backtesting.proto
- protos/marketdata.proto
- protos/strategies.proto
This update reverts the Protobuf syntax from `proto3` to the edition-based format (`edition = "2023";`) across the `backtesting.proto`, `marketdata.proto`, and `strategies.proto` files. The changes include:
1. **Protobuf Syntax Reversion:**
- Replaces `syntax = "proto3";` with `edition = "2023";` in all `.proto` files to align with the newer edition-based Protobuf specification.
2. **Maintained Package Names:**
- Ensures the package declarations (`backtesting`, `marketdata`, and `strategies`) remain intact for consistency and compatibility.
This adjustment supports environments leveraging Protobuf's 2023 edition for enhanced features and future-proofing while maintaining backward compatibility with tools and workflows that support the edition-based syntax.
> Revert Protobuf Syntax to Edition-Based Format

- MODULE.bazel
- third_party/BUILD
This update integrates the **Jenetics** library (version 8.1.0) into the Bazel build system for the project, enabling its use in Java components. The changes include:
1. **MODULE.bazel Updates:**
- Added `"io.jenetics:jenetics:8.1.0"` to the Maven dependencies list for installation using `maven.install`.
2. **third_party/BUILD Updates:**
- Created a new `java_library` target named `"jenetics"`.
- Set its visibility to `public`, allowing usage across the repository.
- Exported the Jenetics Maven artifact (`@maven//:io_jenetics_jenetics`) for use in dependent modules.
These changes allow seamless inclusion and use of Jenetics, a Java library for evolutionary algorithms and genetic programming, in the project's Java modules while maintaining a clean and modular build configuration.
> Add Jenetics Library Integration to Bazel Configuration

- charts/tradestream/templates/kafka-ui.yaml
- charts/tradestream/values.yaml
This PR adds a Kafka UI deployment to the Tradestream Helm chart. This will allow users to easily monitor and manage their Kafka clusters deployed by the chart.
**Key changes:**
* Adds a new `kafka-ui.yaml` template file to define the Kafka UI deployment and service.
* Adds a new `kafkaUi` section to the `values.yaml` file to configure the Kafka UI, including:
* `replicaCount`: Number of replicas for the Kafka UI deployment.
* `image`: Configuration for the Kafka UI Docker image.
* `service`: Configuration for the Kafka UI service.
* Sets the default Kafka UI image to `provectuslabs/kafka-ui:latest`.
* Configures the Kafka UI to connect to the Kafka cluster deployed by the chart.
**Benefits:**
* Provides a user-friendly interface for monitoring Kafka topics, consumer groups, and other …
> Add Kafka UI to Tradestream Chart

- src/main/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
- src/main/java/com/verlumen/tradestream/strategies/oscillators/BUILD
This change refactors dependency declarations for the `movingaverages_lib` and `oscillators_lib` in the respective Bazel `BUILD` files.  
- **Dependency Standardization:**  
- Replaced references to Maven-resolved dependencies (e.g., `@maven//:`) with references to centralized third-party libraries (`//third_party:`).  
- Consolidated dependencies for `guava`, `guice`, `protobuf_java`, and `ta4j_core` under `//third_party`.  
- **Impacted Targets:**  
- `movingaverages_lib` in `strategies/movingaverages/BUILD`.  
- `oscillators_lib` in `strategies/oscillators/BUILD`.  
- Improves maintainability by centralizing dependency management under `//third_party`.  
- Reduces duplication and ensures consistency across the project.  
- Simplifies updates to third-party dependencies in the future. …
> Update Dependency References for Moving Averages and Oscillators Strategies  

- third_party/BUILD
This update introduces the `test_parameter_injector` library to the Bazel `third_party/BUILD` file, allowing for parameterized testing capabilities in the project.  
- **New Dependency Target:**  
- Added a `java_library` target named `test_parameter_injector`.  
- **Details:**  
- **Visibility:** Public (`//visibility:public`).  
- **Exports:** The `@maven//:com_google_testparameterinjector_test_parameter_injector` library.  
- **Test-only:** Marked as a test-only library (`testonly = True`).  
- Enables usage of `TestParameterInjector` for robust, parameterized test cases.  
- Facilitates cleaner and more modular testing patterns, enhancing test coverage and maintainability.  
This addition ensures flexibility and reusability for parameterized test scenarios across the codebase.
> Add `test_parameter_injector` Library to Third-Party Dependencies

- MODULE.bazel
This update modifies the `MODULE.bazel` file to upgrade the versions of critical dependencies, **Guava** and **Truth**, ensuring compatibility with the latest features and improvements.  
1. **Guava Library:**  
- Upgraded from `31.1-jre` to `33.4.0-jre`.  
- Brings enhanced features, performance optimizations, and security patches.  
2. **Truth Library:**  
- Upgraded from `1.4.2` to `1.4.4`.  
- Ensures compatibility with newer testing frameworks and bug fixes.  
- Improves overall stability and security of the codebase by aligning with the latest library versions.  
- Facilitates access to new APIs and features introduced in these updates.  
- Enhances maintainability and future-proofing for dependency management.  
These upgrades are integral for keeping the project dependencies …
> Update Guava and Truth Library Versions in Maven Dependencies  

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency declarations for `CandleBuilderTest` to align with the project's standard practice of using `third_party` libraries. This promotes consistency and simplifies dependency management.
- **Changes:**
- Replaced direct Maven dependencies for Truth, Test Parameter Injector, and JUnit with their corresponding `third_party` declarations.
- Ensures consistent dependency management across build files.
- Centralizes dependency definitions in the `third_party` directory.
- Facilitates easier updates and reduces potential conflicts.
> Refactor `CandleBuilderTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency declarations in the `AppTest` target to utilize the project's `third_party` library definitions. This promotes a consistent approach to dependency management throughout the project.
- **Changes:**
- Replaced direct Maven dependency declarations for Guice, Guice Testlib, Truth, JUnit, and Mockito with their corresponding `third_party` equivalents.
- Updated the `runtime_deps` to use the `third_party` definition for Flogger System Backend.
- Improves consistency in dependency management across all build targets.
- Centralizes dependency versioning and configurations within the `third_party` directory.
> Refactor `AppTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change standardizes the dependency management for the `CandlePublisherImplTest` by switching from direct Maven references to using the project's `third_party` dependency declarations. This promotes consistency and simplifies dependency updates.
- **Changes:**
- Removed direct Maven dependencies for Guice, JUnit, Kafka Clients, and Mockito.
- Added corresponding `third_party` dependencies for the same libraries.
- Improves consistency in dependency management across the project.
- Centralizes dependency versions and configurations within the `third_party` directory.
- Simplifies future dependency updates and reduces potential version conflicts.
> Refactor `CandlePublisherImplTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency declarations for `ThinMarketTimerTaskImplTest` to utilize the project's standardized `third_party` library definitions. This ensures consistency in dependency management across the project.
- **Changes:**
- Replaced direct Maven dependencies for Guava, Guice Testlib, Guice, Truth, JUnit, and Mockito with their corresponding `third_party` declarations.
- Promotes a consistent approach to dependency management within the project's build files.
- Centralizes dependency versioning and management within the `third_party` directory.
> Refactor `ThinMarketTimerTaskImplTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency management for `ThinMarketTimerImplTest` to align with the project's standard practice of using `third_party` libraries. This ensures consistency and simplifies dependency maintenance.
- **Changes:**
- Replaced direct Maven dependencies for Guice Testlib, Guice, Guava, Truth, JUnit, and Mockito with their corresponding `third_party` declarations.
- Improves consistency in dependency management across the project's build files.
- Centralizes dependency versions and configurations within the `third_party` directory.
- Facilitates easier dependency updates and reduces the risk of version conflicts.
> Refactor `ThinMarketTimerImplTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency management for the `RealTimeDataIngestionImplTest` target to use the project's standard `third_party` library definitions. This ensures consistent dependency management practices throughout the project.
- **Changes:**
- Replaced direct Maven dependencies for Guava, Guice Testlib, Guice, Truth, JUnit, and Mockito with their corresponding `third_party` declarations.
- Improves consistency in dependency management across all build files.
- Centralizes dependency versioning and configuration within the `third_party` directory.
- Simplifies dependency updates and reduces the potential for version conflicts.
> Refactor `RealTimeDataIngestionImplTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency declarations for `PriceTrackerTest` to use the project's `third_party` library definitions. This promotes consistency and simplifies dependency management across the project.
- **Changes:**
- Replaced direct Maven dependencies for Guice, Truth, and JUnit with their corresponding `third_party` declarations.
- Ensures a consistent approach to dependency management within the project's build files.
- Centralizes dependency versioning and management within the `third_party` directory.
- Simplifies dependency updates and reduces the risk of dependency conflicts.
> Refactor `PriceTrackerTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency declarations for `KafkaPropertiesTest` to utilize the project's standard `third_party` library definitions. This promotes consistency and simplifies dependency management across the project.
- **Changes:**
- Replaced direct Maven dependencies for Guice Testlib, Guice, Truth, and Argparse4j with their corresponding `third_party` declarations.
- Ensures consistent dependency management across build files.
- Centralizes dependency definitions within the `third_party` directory.
- Facilitates easier updates and reduces the potential for conflicts.
> Refactor `KafkaPropertiesTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency declarations for `HttpClientImplTest` to use the project's standard `third_party` library definitions. This ensures consistent dependency management throughout the project.
- **Changes:**
- Replaced direct Maven dependencies for Guice Testlib, Guice, Truth, JUnit, and Mockito with their corresponding `third_party` declarations.
- Promotes a consistent approach to dependency management within the project.
- Centralizes dependency versioning and configuration within the `third_party` directory.
> Refactor `HttpClientImplTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change updates the dependency declarations for `TradeProcessorTest` to utilize the project's standardized `third_party` library definitions. This ensures consistency in dependency management across the project.
- **Changes:**
- Replaced direct Maven dependencies for Truth and JUnit with their corresponding `third_party` declarations.
- Promotes a consistent approach to dependency management within the project's build files.
- Centralizes dependency versioning and management within the `third_party` directory.
> Refactor `TradeProcessorTest` Dependencies to Use `third_party`

- src/test/java/com/verlumen/tradestream/instruments/BUILD
- **Context:** This change updates the dependency declarations for `CurrencyPairTest` to use the project's standardized `third_party` library definitions. This ensures a consistent approach to dependency management throughout the project.
- **Changes:**
- Replaced direct Maven dependencies for Truth and JUnit with their corresponding `third_party` declarations.
- Improves consistency in dependency management across the project's build files.
- Centralizes dependency versioning and management within the `third_party` directory.
> Refactor `CurrencyPairTest` Dependencies to Use `third_party`

- .github/workflows/release.yaml
- **Context:** This change enhances the release workflow to automatically update the `version` attribute in the `MODULE.bazel` file during the release process. This ensures that the declared module version is consistent with the released tag.
- **Changes:**
- Renamed the `version` job to `release` for better clarity.
- Added a new step to the `release` job that updates the `version` attribute in `MODULE.bazel` using `sed`.
- Modified the commit step to include the updated `MODULE.bazel` file and use a more general commit message "Bump version to ${{ steps.version.outputs.version_tag }}".
- Ensures consistency between the Git tag and the declared version in `MODULE.bazel`.
- Automates the version update process, reducing the risk of manual errors.
- Improves the …
> Enhance Release Workflow to Update `MODULE.bazel` Version

- MODULE.bazel
- third_party/BUILD
- **Context:** This change introduces the `grpc-api` and `grpc-stub` dependencies. These libraries are fundamental for building gRPC services and clients, providing core API definitions and stub generation capabilities.
- **Changes:**
- Added `io.grpc:grpc-api:1.69.0` and `io.grpc:grpc-stub:1.69.0` to the `maven.install` block in `MODULE.bazel`.
- Added `java_library` targets named `grpc_java_api` and `grpc_java_stub` in `third_party/BUILD` to wrap these Maven dependencies, making them available for use in Bazel targets.
- Enables the development of gRPC services and clients within the project.
- Provides the necessary building blocks for defining gRPC interfaces and generating client/server code.
> Add `grpc-api` and `grpc-stub` Dependencies

- .github/workflows/release.yaml
- **Context:** This change refines the release workflow to more accurately update the version in `MODULE.bazel`. The previous implementation could potentially modify unintended lines containing "version =".
- **Changes:**
- Modified the `sed` command in the "Update MODULE.bazel version" step to restrict the version replacement to only lines within the `module(...)` block. This is achieved by using a range in `sed`: `'/^module(/,/^)/ s/.../'`.
- Ensures that only the intended `version` attribute within the `module` definition in `MODULE.bazel` is modified during the release process.
- Reduces the risk of unintended side effects from the version update script.
- Improves the robustness and reliability of the release workflow.
> Improve Release Workflow: Scope `MODULE.bazel` Version Update

- MODULE.bazel
- **Context:** This change reverts unintended version updates in `MODULE.bazel`. These updates were a side effect of a previous issue where the version replacement logic in the release workflow was too broad, as described in [bazel-contrib/rules_jvm_external#916](https://github.com/bazel-contrib/rules_jvm_external/issues/916).
- **Changes:**
- The versions for the following `bazel_dep` entries have been reverted to their intended values:
- `aspect_bazel_lib`
- `bazel_skylib`
- `container_structure_test`
- `grpc-java`
- `protobuf`
- `rules_java`
- `rules_jvm_external`
- `rules_oci`
- Corrects the declared versions of dependencies in `MODULE.bazel`.
- Ensures that the project uses the intended versions of its dependencies.
> Revert Accidental Version Updates in `MODULE.bazel`

- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- **Context:** This change reorganizes the dependencies in the `BacktestRunnerImplTest` target. Moving the dependencies on the project's own modules (`backtest_runner` and `backtest_runner_impl`) to the top of the `deps` list improves readability and clarifies the primary dependencies of the test.
- **Changes:**
- Moved `//src/main/java/com/verlumen/tradestream/backtesting:backtest_runner` from the end of the `deps` list to the beginning.
- Moved `//src/main/java/com/verlumen/tradestream/backtesting:backtest_runner_impl` from the end of the `deps` list to follow the `backtest_runner` dependency.
- Enhances the readability of the `BUILD` file by grouping the test's direct dependencies on project modules.
- Makes it easier to quickly identify the key components being tested. …
> Refactor `BacktestRunnerImplTest` Dependencies: Move to Top of List

- MODULE.bazel
- third_party/BUILD
- **Context:** This change adds the `grpc-inprocess` dependency to facilitate more efficient and isolated testing of gRPC services. This builds upon the previously added `grpc-api` and `grpc-stub` dependencies, providing a comprehensive set of gRPC tools.
- **Changes:**
- Added `io.grpc:grpc-inprocess:1.69.0` to the `maven.install` block in `MODULE.bazel`.
- Created a new `java_library` target named `grpc_java_inprocess` in `third_party/BUILD` to wrap the `grpc-inprocess` Maven dependency.
- Enables in-process testing of gRPC services, eliminating network overhead and simplifying test setup.
- Allows for more reliable and faster unit and integration tests for gRPC components.
> Introduce gRPC InProcess Dependency for Enhanced Testing

- MODULE.bazel
- **Context:** This change updates the specified version of the `grpc-java` Bazel dependency.
- **Changes:**
- The `version` attribute for the `grpc-java` bazel_dep is updated from "1.68.1" to "1.69.0".
- Ensures the project is using the desired version of the `grpc-java` library.
> Update `grpc-java` Bazel Dependency to Version 1.69.0

- src/main/java/com/verlumen/tradestream/backtesting/params/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/params/ChromosomeSpec.java
- src/main/java/com/verlumen/tradestream/backtesting/params/DoubleChromosomeSpec.java
- src/main/java/com/verlumen/tradestream/backtesting/params/IntegerChromosomeSpec.java
- **Context:** This change introduces a new mechanism for specifying chromosome constraints used in backtesting parameter optimization. This provides a structured way to define the types and valid ranges for optimizable parameters.
- **Changes:**
- Created new files:
- `ChromosomeSpec.java`: Defines the interface for chromosome specifications, including methods for getting the valid range and creating a chromosome.
- `IntegerChromosomeSpec.java`: Implementation of `ChromosomeSpec` for integer-valued parameters.
- `DoubleChromosomeSpec.java`: Implementation of `ChromosomeSpec` for double-valued parameters.
- Modified `src/main/java/com/verlumen/tradestream/backtesting/params/BUILD`:
- Renamed the `java_library` from `param_config` to `params_lib`.
- Updated `srcs` to use `glob(["*.java"])` …
>  Introduce Chromosome Specifications for Backtesting Parameter Optimization

- src/main/java/com/verlumen/tradestream/backtesting/params/ChromosomeSpec.java
- src/main/java/com/verlumen/tradestream/backtesting/params/DoubleChromosomeSpec.java
- src/main/java/com/verlumen/tradestream/backtesting/params/IntegerChromosomeSpec.java
- **Context:** This change relaxes the generic type constraint on the `ChromosomeSpec` interface to better accommodate various numeric types supported by Jenetics.
- **Changes:**
- Updated the generic type parameter `T` of `ChromosomeSpec` from `T extends Comparable<T>` to `T extends Number & Comparable<? super T>`. This allows `ChromosomeSpec` to work with subtypes of `Number`.
- The `DoubleChromosomeSpec` and `IntegerChromosomeSpec` implementations are now `final` and have reduced visibility (package-private).
- The `createChromosome()` method in `ChromosomeSpec` now returns `NumericChromosome<T, ?>` instead of `Chromosome<? extends Gene<T, ?>>`.
- Improves compatibility with Jenetics' `NumericChromosome` and `NumericGene` hierarchy.
- Provides more flexibility in …
> Relax Generic Type Constraint on `ChromosomeSpec` for Numeric Types

- .bazelrc
- MODULE.bazel
- **Context:** This change updates the Java Development Kit (JDK) version used for building the project to Java 21. This ensures that the project leverages the latest features and improvements in the Java ecosystem.
- **Changes:**
- In `.bazelrc`, updated `java_runtime_version` and `tool_java_runtime_version` to `remotejdk_21`.
- In `.bazelrc`, updated `java_language_version` and `tool_java_language_version` to `21`.
- In `MODULE.bazel`, updated `JAVA_LANGUAGE_LEVEL` to `"21"`.
- In `MODULE.bazel`, updated the `java.toolchain` to use `@rules_java//toolchains:remotejdk_21`.
- Leverages new language features and performance improvements in Java 21.
- Keeps the project aligned with current Java standards and best practices.
- Potentially improves build performance and …
> Upgrade Java Toolchain to Version 21

- src/main/java/com/verlumen/tradestream/backtesting/params/ParamConfig.java
- src/main/java/com/verlumen/tradestream/backtesting/params/SmaRsiParamConfig.java
- **Context:** This change introduces a `getStrategyType()` method to the `ParamConfig` interface. This allows associating a given parameter configuration with a specific trading strategy, which is needed for identifying the right configuration for a given strategy during optimization.
- **Changes:**
- Added the `getStrategyType()` method to the `ParamConfig` interface, returning a `StrategyType` enum.
- Implemented the `getStrategyType()` method in `SmaRsiParamConfig`, returning `StrategyType.SMA_RSI`.
- Allows the system to programmatically identify the trading strategy that a given `ParamConfig` applies to.
- Facilitates better management and organization of strategy-specific parameter configurations during backtesting.
> Add `getStrategyType()` to `ParamConfig` and Implement in `SmaRsiParamConfig`

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyEngine.java
- **Context:** This change introduces the `StrategyEngine` interface, which defines the core functionality of a trading strategy engine. This includes handling incoming candle data, optimizing strategy parameters, and accessing the current active strategy.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/StrategyEngine.java`: This new interface defines methods for `handleCandle`, `optimizeStrategy`, and `getCurrentStrategy`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a build target for the `strategy_engine` library and its dependencies.
- Provides a standardized interface for various strategy implementations.
- Decouples the strategy implementations from specific trading logic.
- Enables easier management and …
> Introduce `StrategyEngine` Interface for Trading Strategies

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
- **Context:** This change introduces the `StrategiesModule`, a Guice module designed to handle the configuration of strategy-related components. This module provides a way to manage dependencies and settings required by strategies.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java`: This new class is a Guice module that provides a mechanism to pass command-line arguments to the strategy components, and potentially other strategy related dependency binding logic in the future.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a build target for the `strategies_module` library and its dependencies.
- Provides a standard way to configure and inject strategy-specific dependencies.
- Improves the …
> Introduce `StrategiesModule` for Strategy Configuration

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/MarketDataConsumer.java
- **Context:** This change introduces the `MarketDataConsumer` interface, which defines how market data (specifically candles) is consumed and processed. This abstraction is intended to decouple the consumption logic from the strategy engine.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/MarketDataConsumer.java`: This new interface defines methods `startConsuming` and `stopConsuming` for handling the market data stream.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a build target for the `market_data_consumer` library, and its dependencies.
- Provides a standard way to consume and process market data within the strategy engine.
- Decouples the strategy engine from the specific data source.
- Enables easier testing …
> Introduce `MarketDataConsumer` Interface for Handling Market Data

- protos/BUILD
- protos/strategies.proto
- **Context:** This change adds a new `Strategy` message to `strategies.proto` and updates the `BUILD` file to include a dependency to `any_proto`. This new message will be used to represent a strategy and its parameters.
- **Changes:**
- Added a `Strategy` message to `strategies.proto` that includes a `StrategyType` and a `google.protobuf.Any` field for the strategy parameters.
- Updated the `strategies_proto` target in `protos/BUILD` to depend on `@com_google_protobuf//:any_proto`.
- Introduces a new message to represent trading strategies with their associated parameters.
- Allows for more flexible and dynamic representation of strategy parameters, enabling different parameter types for different strategies without needing to define separate fields.
> Add `Strategy` Message to `strategies.proto` and Update Dependencies

- src/main/java/com/verlumen/tradestream/signals/BUILD
- src/main/java/com/verlumen/tradestream/signals/TradeSignalPublisher.java
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/TradeSignalPublisher.java
- **Context:** This change reorganizes the location of the `TradeSignalPublisher` interface. Since it's primarily related to signal processing, it is more appropriate to move it to the `com.verlumen.tradestream.signals` package.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/signals/BUILD`: This new `BUILD` file defines the target for `trade_signal_publisher`.
- Created `src/main/java/com/verlumen/tradestream/signals/TradeSignalPublisher.java`: Moved the `TradeSignalPublisher` interface from `com.verlumen.tradestream.strategies`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Removed the `trade_signal_publisher` library.
- Removed `src/main/java/com/verlumen/tradestream/strategies/TradeSignalPublisher.java`.
- Improves code …
> Move `TradeSignalPublisher` Interface to the `signals` Package

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java
- **Context:** This change adds a dependency on `StrategyManager` to `StrategyEngineImpl`. This dependency will be used by the Strategy Engine to manage and access the current active strategy.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java`: Added a `StrategyManager` field and updated the constructor to inject it.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a dependency on `:strategy_manager` to the `strategy_engine_impl` target.
- Allows `StrategyEngineImpl` to interact with and manage the current strategy via the `StrategyManager`.
- Sets up the dependency required for the implementation of strategy selection/management logic.
> Add `StrategyManager` Dependency to `StrategyEngineImpl`

- src/main/java/com/verlumen/tradestream/strategies/App.java
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- **Context:** This change updates the `App` class to use `StrategiesModule` when creating the Guice injector, so that command line arguments are available for binding logic in the future.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/App.java` to pass `StrategiesModule.create(args)` to `Guice.createInjector(...)`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD` to add a dependency on `:strategies_module` to the `app` target.
- Enables the use of command-line arguments within the Guice dependency injection context.
- Provides a centralized way to pass arguments and control the configuration of the application.
> Inject `StrategiesModule` into `App`

- src/main/java/com/verlumen/tradestream/execution/BUILD
- src/main/java/com/verlumen/tradestream/execution/RunMode.java
- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/RunMode.java
- src/main/java/com/verlumen/tradestream/mode/RunMode.java
- src/test/java/com/verlumen/tradestream/ingestion/AppTest.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- **Context:** This change relocates the `RunMode` enum from the `com.verlumen.tradestream.ingestion` package to a new `com.verlumen.tradestream.execution` package. This move is part of an effort to better organize the codebase.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/execution/BUILD`: Defines the build target for `run_mode`.
- Created `src/main/java/com/verlumen/tradestream/execution/RunMode.java`: Defines the `RunMode` enum.
- Modified `src/main/java/com/verlumen/tradestream/ingestion/BUILD`: Removed the `run_mode` target and updated the dependencies to use the new location of the `RunMode` enum.
- Removed `src/main/java/com/verlumen/tradestream/ingestion/RunMode.java`.
- Modified `src/test/java/com/verlumen/tradestream/ingestion/AppTest.java` to use the new …
> Move `RunMode` Enum to `execution` Package

- src/main/java/com/verlumen/tradestream/execution/BUILD
- src/main/java/com/verlumen/tradestream/execution/ExecutionModule.java
- **Context:** This change introduces the `ExecutionModule`, a Guice module for configuring execution-related settings, such as the `RunMode`. This allows for runtime configuration of the application.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/execution/ExecutionModule.java`: This new class is a Guice module that allows to bind a specific `RunMode` instance.
- Modified `src/main/java/com/verlumen/tradestream/execution/BUILD`: Added a build target for the `execution_module` and its dependencies.
- Provides a way to configure the application's `RunMode` via dependency injection.
- Facilitates runtime configuration of the application behavior.
- Enhances modularity and testability by decoupling the `RunMode` from the application logic.
> Introduce `ExecutionModule` for Runtime Configuration

- src/main/java/com/verlumen/tradestream/execution/RunMode.java
- **Context:** This change adds a static `fromString` method to the `RunMode` enum. This method allows creating a `RunMode` instance from a string, which is useful for parsing runtime arguments.
- **Changes:**
- Added a static `fromString` method to the `RunMode` enum that converts a string to its corresponding `RunMode` enum value (case-insensitive).
- Provides a convenient way to parse string-based inputs for `RunMode` values.
- Enhances the flexibility of configuring the application's `RunMode` using external inputs like command-line arguments or configuration files.
> Add `fromString` Method to `RunMode` Enum

- src/main/java/com/verlumen/tradestream/execution/ExecutionModule.java
- src/main/java/com/verlumen/tradestream/execution/RunMode.java
- **Context:** This change modifies the `ExecutionModule` to use the newly added `RunMode.fromString` method instead of directly calling `RunMode.valueOf`. This ensures the consistency of parsing and creation of `RunMode` instances.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/execution/ExecutionModule.java`: Updated `ExecutionModule.create()` to use `RunMode.fromString()` to create the `RunMode` instance.
- Improves code consistency by using a single method to handle the string conversion for `RunMode`.
- Makes it easier to maintain and evolve the way `RunMode` instances are created from strings.
> Use `RunMode.fromString` in `ExecutionModule`

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/MarketDataConsumerImpl.java
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
- **Context:** This change introduces a concrete implementation, `MarketDataConsumerImpl`, of the `MarketDataConsumer` interface, and binds it in `StrategiesModule`. This provides a specific implementation for consuming market data.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/MarketDataConsumerImpl.java`: Implements the `MarketDataConsumer` interface. Currently it has placeholder methods that throw `UnsupportedOperationException`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a build target for `market_data_consumer_impl` and its dependencies.
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java`: Binds the `MarketDataConsumer` interface to the `MarketDataConsumerImpl` implementation.
- …
> Introduce `MarketDataConsumerImpl` and Bind in `StrategiesModule`

- src/main/java/com/verlumen/tradestream/strategies/App.java
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- **Context:** This change adds a dependency on `MarketDataConsumer` to the `App` class. This enables the `App` to utilize the market data consumption functionality.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/App.java`: Added a `MarketDataConsumer` field and updated the constructor to inject it.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a dependency on `:market_data_consumer` to the `app` target.
- Enables the `App` to use the `MarketDataConsumer` for consuming and processing market data.
- Sets up the dependency required for future initialization logic of `MarketDataConsumer`.
>  Inject `MarketDataConsumer` into `App`

- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java
- **Context:** This change introduces the `MovingAverageStrategies` class. This class centralizes the collection of all moving average-based strategy factories and provides a single point of access for them.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java`: This new class contains a public static immutable list called `ALL_FACTORIES` that provides access to the available moving average strategy factories.
- Provides a central location for all moving average strategy factories, improving code organization.
- Simplifies access to all moving average strategy factories by making them available through a single immutable list.
> Introduce `MovingAverageStrategies` for Centralized Strategy Factory Access

- src/main/java/com/verlumen/tradestream/strategies/oscillators/OscillatorStrategies.java
- **Context:** This change introduces the `OscillatorStrategies` class. This class centralizes the collection of all oscillator-based strategy factories and provides a single point of access for them.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/oscillators/OscillatorStrategies.java`: This new class contains a public static immutable list called `ALL_FACTORIES` that provides access to the available oscillator strategy factories.
- Provides a central location for all oscillator strategy factories, improving code organization.
- Simplifies access to all oscillator strategy factories by making them available through a single immutable list.
> Introduce `OscillatorStrategies` for Centralized Oscillator Strategy Factory Access

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyFactories.java
- **Context:** This change introduces the `StrategyFactories` class. This class serves as a central registry, providing a single point of access to all strategy factories across different categories (e.g., moving averages, oscillators). It aggregates strategy factories from child packages.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/StrategyFactories.java`: This new class contains a public static immutable list `ALL_FACTORIES` that aggregates all strategy factories across all categories.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a build target for the `strategy_factories` library and its dependencies.
- Provides a centralized and easily accessible way to manage all strategy factories.
- Simplifies the …
> Introduce `StrategyFactories` for Centralized Access to All Strategy Factories

- src/main/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactoryTest.java
- **Context:** This change modifies the `DoubleEmaCrossoverStrategyFactory` to be immutable and uses a static method (`create()`) for instantiation. This ensures proper construction and usage of the factory.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactory.java`: Made the class `final` and the constructor `private`, and introduced a static `create()` method for object instantiation.
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java`: Updated how `DoubleEmaCrossoverStrategyFactory` is added to the list of strategy factories.
- Modified `src/test/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactoryTest.java`: Updated the …
> Make `DoubleEmaCrossoverStrategyFactory` Immutable and Create via Static Method

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
- **Context:** This change modifies `StrategiesModule` to provide a binding for a list of all `StrategyFactory` instances. This allows dependency injection of the full list of strategy factories in classes that need it.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java`: Added a binding for an `ImmutableList<StrategyFactory<?>>` to `StrategyFactories.ALL_FACTORIES`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added `strategy_factories` and `strategy_factory` to the dependencies of `strategies_module`.
- Makes the list of all available strategy factories easily accessible via dependency injection.
- Improves the flexibility and modularity of the application.
- Enables the usage of all strategy …
> Bind `StrategyFactory` List in `StrategiesModule`

- src/test/java/com/verlumen/tradestream/strategies/StrategyManagerImplTest.java
- **Context:** This change refactors `StrategyManagerImplTest` to remove the Guice field binder. This simplifies the test setup and removes the dependency on Guice's testing extensions.
- **Changes:**
- Removed the Guice `@Bind` annotations and `BoundFieldModule` usage.
- Updated the test setup to directly initialize the `StrategyManagerImpl` with mocked dependencies.
- Simplifies the test setup and removes unnecessary dependencies on Guice's testing framework.
- Improves the readability of the test by having simpler dependency declarations.
- Makes the test less coupled to a specific dependency injection framework.
> Refactor `StrategyManagerImplTest` to Remove Guice Bindings

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyManagerImpl.java
- src/test/java/com/verlumen/tradestream/strategies/StrategyManagerImplTest.java
- **Context:** This change refactors `StrategyManagerImpl` to directly use a list of strategy factories passed via constructor injection instead of using a separate config object.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategyManagerImpl.java`: Removed the inner `Config` class and updated the constructor to receive an `ImmutableList<StrategyFactory<?>>`. The field `factoryMap` is now initialized directly in the constructor.
- Modified `src/test/java/com/verlumen/tradestream/strategies/StrategyManagerImplTest.java`: Updated the test to use Guice field binding to provide an immutable list of factories, rather than creating a config object.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Removed the dependency on `auto_value`.
- …
> Refactor `StrategyManagerImpl` and Test for Immutable Factory List

- src/main/java/com/verlumen/tradestream/strategies/App.java
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
- **Context:** This change removes the command-line argument handling from `StrategiesModule` and updates the `App` class to no longer require command-line args when creating the `StrategiesModule`. The `StrategiesModule` is no longer auto value.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java`: Removed the field for command line args, and the `create` method no longer accepts args.
- Modified `src/main/java/com/verlumen/tradestream/strategies/App.java`: Updated Guice injector creation to no longer pass args into the create method.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Removed the dependency on `auto_value` for the `strategies_module`.
- Simplifies `StrategiesModule` by removing unnecessary …
> Remove Command-Line Args from `StrategiesModule` and Update App

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
- **Context:** This change adds a binding for the `StrategyManager` interface to its concrete implementation, `StrategyManagerImpl`, within the `StrategiesModule`. This enables dependency injection for the strategy manager.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java`: Added a binding for `StrategyManager` to `StrategyManagerImpl`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added `strategy_manager` and `strategy_manager_impl` to the dependencies of `strategies_module`.
- Allows the `StrategyManagerImpl` to be injected by Guice using its interface.
- Sets up dependency injection for the strategy manager for consuming classes.
> Bind `StrategyManager` to `StrategyManagerImpl` in `StrategiesModule`

- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactoryTest.java
- **Context:** This change modifies the `MomentumSmaCrossoverStrategyFactory` to be immutable and uses a static method (`create()`) for instantiation. This ensures proper construction and usage of the factory.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactory.java`: Made the class `final` and the constructor `private`, and introduced a static `create()` method for object instantiation.
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java`: Updated how `MomentumSmaCrossoverStrategyFactory` is added to the list of strategy factories.
- Modified `src/test/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactoryTest.java`: …
> Make `MomentumSmaCrossoverStrategyFactory` Immutable and Create via Static Method

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java
- **Context:** This change introduces the `BacktestingModule`, a Guice module, intended to handle configuration of the backtesting module.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java`: This new class is a Guice module with an empty `configure()` method.
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BUILD`: Added a build target for the `backtesting_module`.
- Provides a centralized place to configure components within the `backtesting` package.
- Allows for cleaner dependency injection within the module.
- Sets the foundation for future module configurations.
> Introduce `BacktestingModule` for Backtesting Configuration

- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/TripleEmaCrossoverStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/TripleEmaCrossoverStrategyFactoryTest.java
- **Context:** This change modifies the `TripleEmaCrossoverStrategyFactory` to be immutable and uses a static method (`create()`) for instantiation. This ensures proper construction and usage of the factory.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/TripleEmaCrossoverStrategyFactory.java`: Made the class `final` and the constructor `private`, and introduced a static `create()` method for object instantiation.
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java`: Updated how `TripleEmaCrossoverStrategyFactory` is added to the list of strategy factories.
- Modified `src/test/java/com/verlumen/tradestream/strategies/movingaverages/TripleEmaCrossoverStrategyFactoryTest.java`: Updated the …
> Make `TripleEmaCrossoverStrategyFactory` Immutable and Create via Static Method

- src/main/java/com/verlumen/tradestream/strategies/oscillators/OscillatorStrategies.java
- src/main/java/com/verlumen/tradestream/strategies/oscillators/SmaRsiStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/oscillators/SmaRsiStrategyFactoryTest.java
- **Context:** This change modifies the `SmaRsiStrategyFactory` to be immutable and uses a static method (`create()`) for instantiation. This enforces proper construction of the class and improves thread safety.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/oscillators/SmaRsiStrategyFactory.java`: Made the class `final` and the constructor `private`, and introduced a static `create()` method for object instantiation.
- Modified `src/main/java/com/verlumen/tradestream/strategies/oscillators/OscillatorStrategies.java`: Updated how `SmaRsiStrategyFactory` is added to the list of strategy factories.
- Modified `src/test/java/com/verlumen/tradestream/strategies/oscillators/SmaRsiStrategyFactoryTest.java`: Updated the test class to use the `create()` method.
- …
> Make `SmaRsiStrategyFactory` Immutable and Create via Static Method

- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactoryTest.java
- **Context:** This change modifies the `SmaEmaCrossoverStrategyFactory` to be immutable and uses a static method (`create()`) for instantiation. This enforces proper construction of the class and improves thread safety.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactory.java`: Made the class `final` and the constructor `private`, and introduced a static `create()` method for object instantiation.
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java`: Updated how `SmaEmaCrossoverStrategyFactory` is added to the list of strategy factories.
- Modified `src/test/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactoryTest.java`: Updated …
> Make `SmaEmaCrossoverStrategyFactory` Immutable and Create via Static Method

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/GAServiceClientImpl.java
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/GAServiceClientImplTest.java
- **Context:** This change introduces `GAServiceClientImpl`, a concrete implementation of the `GAServiceClient` interface. It also introduces a test class for the new implementation.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/backtesting/GAServiceClientImpl.java`: This new class provides an implementation of the `GAServiceClient` using gRPC blocking stub.
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BUILD`: Created a build target for `ga_service_client_impl`.
- Created `src/test/java/com/verlumen/tradestream/backtesting/GAServiceClientImplTest.java`: Contains unit tests for the `GAServiceClientImpl`, verifying the connection with the fake gRPC server, and verifies that correct values are returned from the server.
- Modified …
> Introduce `GAServiceClientImpl` and Test for GA Service Interaction

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java
- **Context:** This change adds a binding for the `GAServiceClient` interface to its concrete implementation, `GAServiceClientImpl`, within the `BacktestingModule`. This allows dependency injection for the GA service client.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java`: Added a binding for `GAServiceClient` to `GAServiceClientImpl`.
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BUILD`: Added dependencies for `ga_service_client` and `ga_service_client_impl` to the `backtesting_module` target.
- Enables the `GAServiceClientImpl` to be injected by Guice using its interface.
- Sets up dependency injection for the GA service client for consuming classes.
> Bind `GAServiceClient` to `GAServiceClientImpl` in `BacktestingModule`

- src/main/java/com/verlumen/tradestream/strategies/oscillators/BUILD
- **Context:** This change removes the unused dependency on `guice` from the oscillator strategies build file.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/oscillators/BUILD`: Removed the dependency on `//third_party:guice`.
- Improves the accuracy of the dependency declaration.
- Removes unnecessary dependencies.
- Simplifies build configuration.
> Remove Unused `guice` Dependency from Oscillator Strategies

- src/main/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactory.java
- **Context:** This change removes the unused dependency on `guice` from the moving average strategies build file and updates the `MomentumSmaCrossoverStrategyFactory` to remove the inject annotation.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/BUILD`: Removed the dependency on `//third_party:guice`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactory.java`: Removed the `@Inject` annotation.
- Improves the accuracy of the dependency declaration.
- Removes unnecessary dependencies.
- Simplifies build configuration.
> Remove Unused `guice` Dependency from Moving Average Strategies

- src/test/java/com/verlumen/tradestream/strategies/oscillators/BUILD
- **Context:** This change removes an unused dependency on `guice` from the oscillator strategy tests build file.
- **Changes:**
- Modified `src/test/java/com/verlumen/tradestream/strategies/oscillators/BUILD`: Removed the dependency on `//third_party:guice`.
- Improves the accuracy of the dependency declaration.
- Removes unnecessary dependencies.
- Simplifies build configuration.
> Remove Unused `guice` Dependency from Oscillator Strategy Tests

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
- **Context:** This change configures the gRPC clients in the `BacktestingModule` and installs the module into `StrategiesModule`. This enables access to gRPC stubs to communicate with the backtesting service from within strategy logic.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java`: Configured the gRPC client by adding methods to create and provide the `BacktestServiceBlockingStub` and `GAServiceBlockingStub`.
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BUILD`: Added a dependency on the gRPC API to the `backtesting_module` target.
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java`: Installed the `BacktestingModule` to make the stubs available through injection.
- Modified …
> Configure gRPC Clients in Backtesting Module and Install in Strategies Module

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java
- **Context:** This change adds a binding for the `BacktestServiceClient` interface to its concrete implementation, `BacktestServiceClientImpl`, within the `BacktestingModule`. This enables dependency injection for the backtest service client.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java`: Added a binding for `BacktestServiceClient` to `BacktestServiceClientImpl`.
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BUILD`: Added dependencies for `backtest_service_client` and `backtest_service_client_impl` to the `backtesting_module` target.
- Enables the `BacktestServiceClientImpl` to be injected by Guice using its interface.
- Sets up dependency injection for the backtest service client for consuming …
> Bind `BacktestServiceClient` to `BacktestServiceClientImpl` in `BacktestingModule`

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java
- src/main/java/com/verlumen/tradestream/strategies/StrategyManagerImpl.java
- src/test/java/com/verlumen/tradestream/strategies/StrategyManagerImplTest.java
- **Context:** This change adds a `getStrategyTypes()` method to the `StrategyManager` interface and its implementation, `StrategyManagerImpl`. This allows access to the supported strategy types in the system.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java`: Added a `getStrategyTypes()` method.
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategyManagerImpl.java`: Implemented the `getStrategyTypes()` method.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added guava to the dependencies of `strategy_manager` target.
- Modified `src/test/java/com/verlumen/tradestream/strategies/StrategyManagerImplTest.java`: Added a test case to verify correct operation of `getStrategyTypes()`.
- …
> Implement `getStrategyTypes()` in `StrategyManager` and Test

- src/main/java/com/verlumen/tradestream/time/Timestamps.java
- src/test/java/com/verlumen/tradestream/time/TimestampsTest.java
- **Context:** This change adds a new `toTimestamp(long)` method to the `Timestamps` utility class. This method allows converting an epoch timestamp (milliseconds) directly into a Protobuf `Timestamp` object.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/time/Timestamps.java`: Added the static `toTimestamp(long)` method that creates a `Timestamp` from epoch milliseconds. Also added a private method to convert from `java.time.Instant` to `com.google.protobuf.Timestamp`.
- Modified `src/test/java/com/verlumen/tradestream/time/TimestampsTest.java`: Added a test case to verify that `toTimestamp(long)` functions correctly.
- Provides a more convenient way to convert from epoch milliseconds to Protobuf Timestamps.
- Reduces boilerplate code by providing the …
> Add `toTimestamp(long)` Method to `Timestamps`

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/kafka/BUILD
- src/main/java/com/verlumen/tradestream/kafka/KafkaModule.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaProducerProvider.java
- **Context:** The Kafka integration in the ingestion module was tightly coupled, requiring better modularization for maintainability and reusability.  
- **Changes Made:**  
- Introduced a new `KafkaModule` in the `kafka` package to handle Kafka-specific bindings.  
- Updated `IngestionModule` to install the `KafkaModule` and removed direct Kafka producer binding.  
- Moved `KafkaProducerProvider` from the `ingestion` package to the `kafka` package to align with modular structure.  
- Updated Bazel BUILD files to reflect the new dependencies and structure:  
- Added a target for `kafka_module` in `kafka/BUILD`.  
- Removed redundant Kafka dependencies from `ingestion/BUILD`.  
- **Benefits:**  
- Decouples Kafka-specific logic, enhancing modularity and promoting code reuse.  
- …
> Refactor Kafka Integration with Dedicated `KafkaModule`  

- src/main/java/com/verlumen/tradestream/signals/BUILD
- src/main/java/com/verlumen/tradestream/signals/SignalsModule.java
- src/main/java/com/verlumen/tradestream/signals/TradeSignalPublisher.java
- src/main/java/com/verlumen/tradestream/signals/TradeSignalPublisherImpl.java
- src/test/java/com/verlumen/tradestream/signals/BUILD
- src/test/java/com/verlumen/tradestream/signals/TradeSignalPublisherImplTest.java
- **Feature Introduction:**  
- Introduced a new `SignalsModule` to manage trade signal publishing via Kafka.  
- Added a Kafka-based implementation of `TradeSignalPublisher` for publishing trade signals to a specified Kafka topic.  
- **Implementation Details:**  
- **TradeSignalPublisher Interface:**  
- Defines methods `publish` and `close`.  
- Includes a factory interface for creating instances with specified topics.  
- **TradeSignalPublisherImpl:**  
- Uses `KafkaProducer` to publish serialized trade signals to a Kafka topic.  
- Logs publishing details, including strategy type and metadata.  
- Ensures graceful producer shutdown with a flush and close mechanism.  
- **SignalsModule:**  
- Configures factory-based DI for `TradeSignalPublisher` using Guice.  
- **Testing:**  
- …
> Add Trade Signal Publishing Module with Kafka Integration and Unit Tests  

- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
Refactored `App` initialization and `IngestionModule` creation to streamline argument parsing and dependency injection.  
1. **App.java:**
- Replaced the indirect `Namespace`-based `IngestionModule.create()` with direct parameterized initialization in `App`.
- Parsed key arguments (`candlePublisherTopic`, `coinMarketCapApiKey`, `topNCryptocurrencies`, `exchangeName`, etc.) in `App` and passed them to `IngestionModule.create()`.  
2. **IngestionModule.java:**
- Removed redundant `Namespace`-based `create()` method to simplify module construction.
- Updated the API to enforce direct dependencies for `IngestionModule` parameters.  
3. **BUILD File Updates:**
- Adjusted dependencies for `App` and `IngestionModule` to remove `Namespace` dependency (`argparse4j`) and centralize Kafka-related …
> Simplify Initialization of `IngestionModule` in `App` 

- src/main/java/com/verlumen/tradestream/ingestion/App.java
This change removes the default value `"candles"` for the `--candlePublisherTopic` argument in the `App.java` class of the data ingestion module.  
1. **Argument Definition Update:**  
- Eliminated `.setDefault("candles")` from the `--candlePublisherTopic` argument in the `createParser` method.  
2. **Rationale:**  
- Avoids hardcoding default Kafka topics, ensuring that the topic is explicitly specified at runtime for improved flexibility and configuration transparency.
3. **Impact:**  
- Users must now explicitly provide a value for `--candlePublisherTopic` during execution.  
- Prevents accidental reliance on default values, reducing configuration errors in production.
This update enforces stricter configuration practices while maintaining backward compatibility by allowing users to …
> Remove Default Value for `--candlePublisherTopic` in Data Ingestion App

- .github/workflows/ci.yaml
This PR enhances the Kubernetes pod readiness check within the CI workflow by using `kubectl wait` with improved error handling and logging. It ensures the workflow waits for all pods to be in a "Ready" state, and if that fails provides detailed logs and descriptions of pods that are not ready, to aid in debugging deployment failures. The changes also allow for label selectors to be passed via workflow dispatch inputs.
- Replaced the manual pod readiness check loop with `kubectl wait --for=condition=Ready`.
- Added a `label_selector` input to the workflow dispatch which can be used to target specific pods.
- Improved error handling to capture and display detailed pod statuses and logs for non-ready pods when a timeout occurs.
- The pod status is retrieved using `kubectl get pods -o …
> Improve Kubernetes pod readiness check in CI workflow

- charts/tradestream/values.yaml
This PR updates the Helm chart `values.yaml` file to include the `-jar` and path to the executable jar file in the `args` for both the `dataIngestion` and `strategyEngine` deployments. This ensures the correct jar files are executed when deploying these services.
- Added `-jar` and `/src/main/java/com/verlumen/tradestream/ingestion/app_deploy.jar` to `dataIngestion.args`.
- Added `-jar` and `/src/main/java/com/verlumen/tradestream/strategies/app_deploy.jar` to `strategyEngine.args`.
- N/A - This is a configuration change. Testing will be done by deploying the updated helm chart.
- This change affects the deployment configuration for the `dataIngestion` and `strategyEngine` services.
- No breaking changes to existing code or other components are expected.
> Update `dataIngestion` and `strategyEngine` args in Helm chart

- .github/workflows/ci.yaml
This PR simplifies and improves the pod readiness check in the CI workflow. It removes the label selector complexity and streamlines the logic to focus on checking for pods that are not in a `Ready` or `Running` state or that are in a `Running` state but have failing readiness probes. It provides detailed logs and descriptions for failed pods, making it easier to diagnose deployment issues.
- Removed the `label_selector` input and associated logic.
- Uses a simpler `kubectl wait` command to check for pod readiness.
- If `kubectl wait` fails, it retrieves pods that are not `Running` or `Succeeded` using a field selector.
- It also gets pods that are in the `Running` state but not `Ready` by inspecting the container statuses.
- Combines these lists of problem pods and iterates through them …
> Simplify and improve pod readiness check in CI workflow

- src/main/java/com/verlumen/tradestream/strategies/App.java
- src/main/java/com/verlumen/tradestream/strategies/BUILD
This PR updates the strategy engine application to include Kafka properties for configuration. It ensures that the application can properly configure Kafka producers and consumers by parsing command-line arguments, and injecting the necessary properties.
- Updated `App.java` to parse Kafka related command line arguments.
- Modified `App.java` to include `KafkaModule` in the Guice injector setup, passing the `KafkaProperties` instance.
- Updated the `BUILD` file to add a dependency on `kafka_module` and `kafka_properties`.
- N/A - The correctness of the change will be verified with integration tests.
- Verified that the application starts with the correct Kafka properties being parsed.
- This change introduces new dependencies on the `kafka_module` and `kafka_properties` targets.
- No …
> Add Kafka properties to strategy engine app

- charts/tradestream/values.yaml
This PR removes the explicit `-jar` and jar file path arguments from the `dataIngestion` and `strategyEngine` deployments within the Helm chart's `values.yaml`. The JAR file is now being configured as the image's entry point so these arguments are no longer required.
- Removed `-jar` and `/src/main/java/com/verlumen/tradestream/ingestion/app_deploy.jar` from `dataIngestion.args`.
- Removed `-jar` and `/src/main/java/com/verlumen/tradestream/strategies/app_deploy.jar` from `strategyEngine.args`.
- N/A - This change is a configuration update. Verification will be done during deployment.
- This change affects the deployment configuration for `dataIngestion` and `strategyEngine` services.
- It simplifies the configuration by removing redundant JAR execution arguments.
- No breaking changes …
> Remove JAR path arguments from Helm chart

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/KafkaConsumerProvider.java
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
- src/test/java/com/verlumen/tradestream/strategies/BUILD
- src/test/java/com/verlumen/tradestream/strategies/KafkaConsumerProviderTest.java
This PR introduces a `KafkaConsumerProvider` class for creating and configuring Kafka consumers, along with a corresponding test. This provider centralizes the configuration of Kafka consumers and makes them available for dependency injection.
- Added `KafkaConsumerProvider.java` to provide configured `KafkaConsumer` instances.
- Added `KafkaConsumerProviderTest.java` to verify the correct configuration of the provider.
- Updated the `BUILD` files to include `kafka_consumer_provider` and update existing dependencies.
- Added `kafka_consumer_provider` target.
- Added `//third_party:kafka_clients` to `strategy_engine_impl` dependencies.
- The Kafka consumer is configured with `ByteArrayDeserializer` and with settings to disable auto-commit, max poll records and interval and the group id is …
> Add `KafkaConsumerProvider` and test

- charts/tradestream/templates/data-ingestion.yaml
- charts/tradestream/templates/strategy-engine.yaml
- charts/tradestream/values.yaml
This PR updates the Helm chart to dynamically inject the Kafka bootstrap server address into the `dataIngestion` and `strategyEngine` deployments. Additionally, it adds default Kafka configuration arguments to the `strategyEngine`.
- Renamed `data-ingestion-deployment.yaml` to `data-ingestion.yaml`.
- Added a dynamically generated Kafka bootstrap server argument to the `args` of `dataIngestion` and `strategyEngine` deployments using the Helm template function `include "tradestream.fullname" .`.
- Added default Kafka configuration arguments (`--kafka.acks`, `--kafka.retries`, `--kafka.linger.ms`) to `strategyEngine.args`.
- Update the `strategyEngine` args to include a `kafka.linger.ms` default.
- N/A - These are configuration changes, verification will be during deployment.
- This change …
> Add Kafka bootstrap server arg and update strategy engine args in Helm chart

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
This PR adds the `grpc-netty-shaded` dependency to the backtesting module. This is required to use the gRPC client for communication with the GA service.
- Added `//third_party:grpc_java_netty_shaded` to the dependencies of the `backtesting_module` target.
- N/A - This is a dependency change. It will be implicitly tested during the integration tests.
- This change adds a new dependency on `grpc-netty-shaded` to the backtesting module.
- No breaking changes to existing components.
- This dependency will allow the backtesting module to communicate with the gRPC service.
> Add gRPC netty shaded dependency to backtesting module

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/signals/BUILD
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/strategies/BUILD
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
- src/test/java/com/verlumen/tradestream/strategies/oscillators/BUILD
- third_party/BUILD
This PR removes the explicit `flogger_system_backend` runtime dependency from various `BUILD` files across the project. The `flogger_system_backend` is now a runtime dependency of `flogger`, so we can remove the explicit runtime depenencies for targets that use `flogger`. This change simplifies dependency management and ensures consistency across the project.
- Removed `//third_party:flogger_system_backend` from `runtime_deps` in the following targets:
- `src/main/java/com/verlumen/tradestream/ingestion/BUILD`
- `src/main/java/com/verlumen/tradestream/signals/BUILD`
- `src/main/java/com/verlumen/tradestream/strategies/BUILD`
- `src/test/java/com/verlumen/tradestream/backtesting/BUILD`
- `src/test/java/com/verlumen/tradestream/ingestion/BUILD`
- …
> Remove explicit flogger runtime dependency from BUILD files

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/DoubleEmaCrossoverStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/TripleEmaCrossoverStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/oscillators/AdxStochasticStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/oscillators/SmaRsiStrategyFactory.java
This PR adds a `getDefaultParameters()` method to the `StrategyFactory` interface and implements it in all existing strategy factories. This allows strategies to have default parameters that can be used when no parameters are provided, or to simplify the creation of strategies with common settings.
- Added a `getDefaultParameters()` method to the `StrategyFactory` interface.
- Implemented the `getDefaultParameters()` method in all strategy factories to return a default instance of their parameter type.
- Added default values to each of the parameter messages.
- Updated all the strategy factories to use the builder pattern to construct the default parameter messages.
> Add default parameter getter to `StrategyFactory`

- src/main/java/com/verlumen/tradestream/backtesting/BacktestServiceImpl.java
- src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java
- src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java
- src/main/java/com/verlumen/tradestream/strategies/StrategyManagerImpl.java
- src/test/java/com/verlumen/tradestream/strategies/StrategyEngineImplTest.java
- src/test/java/com/verlumen/tradestream/strategies/StrategyManagerImplTest.java
This PR refactors how strategies are created and introduces a mechanism to retrieve default parameters for each strategy type. The `StrategyManager` now uses the `StrategyFactory` to create strategies with default parameters if none are provided or a default parameter.
- Modified `StrategyManager` interface to include `createStrategy(StrategyType, BarSeries)` to create strategy with default params.
- Updated `StrategyManager` interface to include `getDefaultParameters(StrategyType)` to get the default parameters for a given strategy type.
- Updated the `createStrategy` method in `StrategyManager` to use the `StrategyFactory` to create strategies.
- Updated the `StrategyManagerImpl` to call `getStrategyFactory` to get the correct strategy factory.
- Updated the `StrategyEngineImpl` to use …
> Refactor strategy creation and add default strategy parameters

- src/main/java/com/verlumen/tradestream/strategies/App.java
This PR changes the injection of the `StrategyEngine` in the `App` class from a `Provider<StrategyEngine>` to a direct `StrategyEngine` dependency. This simplifies the code by removing unnecessary indirection and allows direct access to the `StrategyEngine` instance.
- Changed the `StrategyEngine` injection in `App.java` from `Provider<StrategyEngine>` to `StrategyEngine`.
- Updated the `start()` method to directly use the injected `strategyEngine` instance without calling `get()`.
- N/A - This is a code change and will be covered by existing integration tests.
- This change removes the dependency on `Provider<StrategyEngine>` in the `App` class.
- No breaking changes are expected, the code is more clear and direct.
> Inject `StrategyEngine` directly into `App`

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/GAServer.java
This PR introduces the `GAServer` class, which sets up and starts a gRPC server for the backtesting module. It uses Guice for dependency injection and starts the server to handle optimization requests. This provides a server implementation for the GA Service.
- Added `GAServer.java` which sets up and starts a gRPC server on port 50051.
- The server uses a Guice injector for dependency injection.
- The `GAServiceImpl` is added as a service to the gRPC server.
- The `GAServer` waits for termination to keep the server running.
- Added a `ga_server` target to `src/main/java/com/verlumen/tradestream/backtesting/BUILD`.
- N/A - This is infrastructure change. Integration tests will be added later.
- This change introduces the `GAServer` class to the backtesting module.
- No breaking changes to …
> Add GA server implementation

- third_party/BUILD
This PR updates the gRPC java library dependencies in the `third_party/BUILD` file. It changes the maven coordinates to use the explicit bazel targets provided by the `io_grpc_grpc_java` module.
- Updated the export for `grpc_java_api` from `@tradestream_maven//:io_grpc_grpc_api` to `@io_grpc_grpc_java//api`.
- Updated the export for `grpc_java_stub` from `@tradestream_maven//:io_grpc_grpc_stub` to `@io_grpc_grpc_java//stub`.
> Update gRPC java library dependencies

- .github/workflows/ci.yaml
- charts/tradestream/Chart.yaml
This PR adds cert-manager to the CI workflow and adds the flink-kubernetes-operator to the Helm chart dependencies. This is necessary for the upcoming integration of Flink. It sets up cert-manager in the cluster and ensures the flink operator is installed when the Helm chart is deployed.
- Added a step to the CI workflow to install cert-manager.
- Added a step to wait for cert-manager to be ready.
- Added `flink-kubernetes-operator` as a dependency to the `charts/tradestream/Chart.yaml` file.
- The CI workflow was manually triggered to verify the cert-manager installation.
- The helm chart was updated locally to verify that the flink operator dependency is correctly added.
- This change introduces a dependency on cert-manager.
- This change introduces a dependency on the …
> Add cert-manager and flink operator to CI and Helm Chart

- MODULE.bazel
- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/Pipeline.java
- third_party/BUILD
This PR adds an initial Apache Beam pipeline to the project. It sets up a simple pipeline that prints some input strings to demonstrate the integration with Apache Beam and lays the groundwork for more complex data processing pipelines.
- Added a new `src/main/java/com/verlumen/tradestream/pipeline/App.java` file which contains the implementation of the Apache Beam pipeline.
- The pipeline reads a default input string, and also takes in an input string as an arg and prints them to the console.
- Added a `src/main/java/com/verlumen/tradestream/pipeline/BUILD` file to build the pipeline binary.
- Added `org.apache.beam:beam-sdks-java-core` dependency to `MODULE.bazel`
- Added `beam_sdks_java_core` to `third_party/BUILD`
- Added `beam_sdks_java_core` as dependency to the `app` target in …
> Add initial Apache Beam pipeline

- .github/workflows/bazel-test.yaml
This PR adds the `--verbose_failures` flag to the `bazel test` command in the CI workflow. This will provide more detailed output for failed tests, making it easier to debug issues.
- Added `--verbose_failures` flag to the `bazel test` command in `.github/workflows/bazel-test.yaml`.
- N/A - This change does not require specific testing, as it affects test output only.
- No new dependencies are introduced.
- This change only affects the test output in the CI workflow.
> Add verbose failures to bazel test action

- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
This PR introduces the `PipelineModule` which provides a Guice module for dependency injection in the pipeline package. This facilitates the use of dependency injection in future pipeline code.
- Added `PipelineModule.java` which implements a basic Guice AbstractModule.
- Added `pipeline_module` to `src/main/java/com/verlumen/tradestream/pipeline/BUILD`
- Currently does not bind any dependencies.
- N/A - This is a setup change and no specific testing is required for this PR.
- This change introduces a dependency on Guice.
- No breaking changes to existing components.
- This provides dependency injection for the pipeline module.
> Add PipelineModule for dependency injection

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
This PR modifies the Apache Beam application to use dependency injection with Guice. It allows dependency injection of the App class to facilitate modular design and testability.
- Updated `src/main/java/com/verlumen/tradestream/pipeline/App.java` to use dependency injection by using Guice in the main method, and the injection of the App class.
- Updated `src/main/java/com/verlumen/tradestream/pipeline/BUILD` to include a dependency on `guice`
- The `runPipeline` method has been added for testability purposes, the `main` method will now be used as a simple entry point for the app, but without being directly invoked for testing.
- The main method was manually invoked to confirm that the pipeline starts correctly.
- Introduces a dependency on Guice in the pipeline module.
- The change …
> Use dependency injection in Apache Beam app

- src/main/java/com/verlumen/tradestream/pipeline/App.java
This PR removes the `InputText` parameter from the Apache Beam pipeline options as it's not being used in the pipeline. This simplifies the options interface and removes unnecessary configuration.
- Removed the `getInputText()` and `setInputText()` methods from the `Options` interface in `src/main/java/com/verlumen/tradestream/pipeline/App.java`.
- N/A - This is a code removal and no tests are required.
- No new dependencies are introduced.
- This change simplifies the options interface of the Apache Beam pipeline.
> Remove unused input text parameter from Apache Beam pipeline options

- src/main/java/com/verlumen/tradestream/kafka/BUILD
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransform.java
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
- src/test/java/com/verlumen/tradestream/kafka/KafkaReadTransformTest.java
This PR removes the dynamic read interval configuration from the `KafkaReadTransform`. This simplifies the transform and removes the need for dynamic reads for now.
- Removed `dynamicReadIntervalHours` from `KafkaReadTransform` and its builder.
- Removed `joda_time` dependency in the kafka build file
- Removed the call to `.withDynamicRead()` in `KafkaReadTransform`
- Updated the builder tests accordingly.
- Removed unused `dynamicReadIntervalHours` field from the options and pipeline module
- Verified that the tests for `KafkaReadTransform` are passing.
- Removes `joda_time` dependency.
- This change simplifies the configuration of the `KafkaReadTransform`.
- Dynamic read intervals are removed, which makes the transform easier to configure.
> Remove dynamic read interval from Kafka read transform

- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/kafka/BUILD
- src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java
- src/test/java/com/verlumen/tradestream/kafka/KafkaPropertiesTest.java
This PR removes the SASL-related configurations from `KafkaProperties` and introduces a `KafkaDefaults` class that defines default values for properties that are needed by the services. The goal is to simplify the configuration and remove SASL config that is not currently used.
- Removed `securityProtocol`, `saslMechanism`, and `saslJaasConfig` from the `KafkaProperties` record.
- Modified the `create` method to no longer take in these parameters, and to set default values from `KafkaDefaults` for those parameters.
- Added a `KafkaDefaults` class that defines the default values for the security protocol.
- Updated the `KafkaProperties` constructor to include the default SASL properties and use the defaults from `KafkaDefaults`
- Updated the Ingestion App to use the new Kafka properties …
> Remove SASL config and add defaults to Kafka properties

- charts/tradestream/values.yaml
- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaDefaults.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java
- src/test/java/com/verlumen/tradestream/kafka/KafkaPropertiesTest.java
- src/test/java/com/verlumen/tradestream/strategies/KafkaConsumerProviderTest.java
This PR removes unused configurations for Kafka from the Helm chart and the ingestion application. It removes the configurations that are now defaulted in the code, and are not intended to be customized by the user.
- Removed `kafka.acks`, `kafka.retries`, and `kafka.linger.ms` from `charts/tradestream/values.yaml`
- Removed `kafka.acks`, `kafka.retries`, and `kafka.linger.ms` argument parsing in `src/main/java/com/verlumen/tradestream/ingestion/App.java`.
- N/A - This change is just removing configurations.
- This change removes unused configurations from the project, and simplifies both the helm chart and ingestion app.
> Remove unused Kafka config from Helm chart and ingestion app

- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java
This PR modifies the Ingestion app to use the default Kafka properties as defined in the `KafkaDefaults` class. It removes the need for manual specification of Kafka properties via command-line arguments. It updates the `KafkaProperties` create method to take no parameters, and removes command line args for these parameters from the ingestion app.
- Updated the `KafkaProperties.create()` method in `src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java` to no longer take any arguments and to use the defaults defined in `KafkaDefaults`
- Updated the `App` class in `src/main/java/com/verlumen/tradestream/ingestion/App.java` to call the `KafkaProperties.create()` method without any arguments.
- Removed command line argument parsing for the kafka properties that are being defaulted …
> Use default Kafka properties in Ingestion app

- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaModule.java
This PR modifies the `KafkaModule` to use default Kafka properties, removing the need for passing properties during module initialization. It updates the module to create the properties by itself and remove the explicit binding.
- Removed the `KafkaProperties` field from the `KafkaModule`
- Updated the `KafkaModule` to use `KafkaProperties::create` as the provider for the binding.
- Removed the `KafkaProperties` parameter from the `KafkaModule.create()` method in `src/main/java/com/verlumen/tradestream/kafka/KafkaModule.java`
- Updated `src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java` to create the KafkaModule without parameters.
- Updated the `IngestionConfig` to remove `KafkaProperties`.
- Updated the `App` class in …
> Use default Kafka properties in Kafka module

- src/main/java/com/verlumen/tradestream/kafka/BUILD
This PR reorders the dependencies within the `kafka_module` and `kafka_producer_provider` targets in the `src/main/java/com/verlumen/tradestream/kafka/BUILD` file. This change ensures that the dependencies are listed in a consistent and logical order.
- Reordered dependencies in `kafka_module` target to list internal dependencies before external dependencies.
- Reordered dependencies in `kafka_producer_provider` target to list internal dependencies before external dependencies.
- N/A - This is a dependency ordering change and no tests are required.
- No new dependencies are introduced or removed.
- This change only affects the order of dependencies within the `BUILD` file for organization and readability.
> Reorder Kafka Module dependencies

- src/main/java/com/verlumen/tradestream/kafka/BUILD
- src/main/java/com/verlumen/tradestream/kafka/DryRunKafkaReadTransform.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransformFactory.java
- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
This PR adds a dry run mode to the Apache Beam pipeline, which simulates reading data from Kafka without actually connecting to it. This allows for development and testing without real-time Kafka connections. It also adds a dynamic read interval option that allows configuration for how often Beam reads from Kafka.
- Added `DryRunKafkaReadTransform` class to simulate reading from Kafka in dry run mode.
- Added `runMode` and `dynamicReadIntervalHours` options to `App.Options`.
- Updated `KafkaReadTransformFactory` to return a `DryRunKafkaReadTransform` in dry run mode.
- Updated `App` to read the `bootstrapServers` and `candleTopic` options and use them to create the `KafkaReadTransform`.
- Updated `App` to read the `dynamicReadIntervalHours` and pass it to the `KafkaReadTransformFactory`. …
> Add dry run mode to Apache Beam pipeline and allow for dynamic read interval

- charts/tradestream/templates/data-ingestion.yaml
- charts/tradestream/values.yaml
This PR simplifies the configuration of the `dataIngestion` service within the Helm chart. Instead of using a generic `args` list, it now uses dedicated properties (`candlePublisherTopic` and `runMode`) directly within the `values.yaml` and template for clarity and easier management.
- **`charts/tradestream/templates/data-ingestion.yaml`**:
- Modified the container `args` to directly reference `{{ .Values.dataIngestion.candlePublisherTopic }}` and `{{ .Values.dataIngestion.runMode }}` instead of iterating over a generic `args` list.
- **`charts/tradestream/values.yaml`**:
- Replaced the `dataIngestion.args` list with specific properties:
- `dataIngestion.candlePublisherTopic`: Defines the candle publisher topic.
- `dataIngestion.runMode`: Defines the run mode for data ingestion.
- N/A - …
> Simplify dataIngestion args in Helm chart

- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaModule.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java
- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
This pull request introduces the ability to configure Kafka bootstrap servers via a command-line argument for the ingestion application. This enhancement allows users to easily specify different Kafka clusters without modifying the application code directly. Additionally, it removes the unused `dynamicReadIntervalHours` option from the pipeline application.
- **`src/main/java/com/verlumen/tradestream/ingestion/App.java`**:
- Added a new command-line argument `--kafka.bootstrap.servers` to allow users to specify Kafka bootstrap servers.
- Modified the application to pass this argument to the `IngestionConfig`.
- **`src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java`**:
- Added a `kafkaBootstrapServers` field to store the Kafka bootstrap server configuration.
- …
> Feat: Configure Kafka Bootstrap Servers via Command-Line Argument

- .bazelrc
- MODULE.bazel
This PR downgrades the Java version from **21 to 17** across the project for better compatibility and stability. Key updates include:
1. **Bazel Configuration Updates**:
- `.bazelrc`: Changes Java runtime and tool versions from `remotejdk_21` to `remotejdk_17`.
- `MODULE.bazel`: Updates Java toolchain configuration to use Java 17 instead of Java 21.
2. **Dependency Adjustments**:
- Downgrades `io.jenetics:jenetics` from version **8.1.0** to **7.2.0** to maintain compatibility with Java 17.
- Some dependencies may not fully support Java 21 yet.
- Java 17 is a **long-term support (LTS) release**, ensuring stability for production workloads.
- Prevents potential issues with toolchain resolution in Bazel.
- Ensures compatibility across all Java dependencies.
- Avoids breaking changes that …
> Downgrade Java Version from 21 to 17 and Adjust Dependencies

- MODULE.bazel
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
This PR updates the base image for the **pipeline container** to use **Flink 1.18 with Java 17**, ensuring compatibility with Apache Flink runtime. Key changes include:
1. **OCI Image Update**:
- Pulls `flink:1.18-java17` from Docker Hub and adds it to `MODULE.bazel`.
- Specifies **SHA-256 digest** to ensure reproducibility and security.
2. **Pipeline Build Adjustments**:
- Changes the **base image** for the pipeline's `oci_image` from `@openjdk_java` to `@flink_java17` in `BUILD.bazel`.
- **Aligns the container runtime with Flink 1.18**, which is optimized for Java 17.
- Ensures that the **Flink runtime dependencies** are pre-installed in the container, reducing setup overhead.
- Provides **cross-platform support** for both `linux/amd64` and `linux/arm64/v8`.
- The pipeline container …
> Switch Base Image to Flink 1.18 with Java 17

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- charts/tradestream/values.yaml
This PR fixes an issue where the pipeline image name was incorrect in the CI and Release workflows, and updates the workflows to use the correct image name. It also updates the Helm chart values to reflect the correct image repository.
- **`.github/workflows/ci.yaml`**:
- Updated the `bazel run` command to push the correct image name `tradestream-data-pipeline`.
- Updated the `docker pull` and `docker tag` commands to use the correct image name `tradestream-data-pipeline`.
- **`.github/workflows/release.yaml`**:
- Updated the `PIPELINE_REPO` env variable to `tradestreamhq/tradestream-data-pipeline`.
- **`charts/tradestream/values.yaml`**:
- Updated `pipeline.image.repository` to `tradestreamhq/tradestream-data-pipeline`.
- N/A - This is a configuration change. Implicitly tested by CI.
- …
> Fix pipeline image name and update CI/Release workflows

- src/main/java/com/verlumen/tradestream/pipeline/App.java
The Flink application fails to start with error:
"The class com.verlumen.tradestream.pipeline.App must be public"
- Made the App class public to allow Flink to properly instantiate and execute it
- No functional changes to the application logic
- Verified Flink application starts successfully after the change
- No changes to existing behavior, only fixing access modifier
```
Caused by: org.apache.flink.client.program.ProgramInvocationException: The class com.verlumen.tradestream.pipeline.App must be public.
```
```
> fix: Make App class public to allow Flink execution

- charts/tradestream/templates/pipeline.yaml
This PR updates the **Flink job naming convention** in the Helm chart to enhance clarity and consistency across deployments.
1. **Renames Flink deployment**
- `flink-beam` → `data-pipeline`
- Ensures naming aligns with **Tradestream's data processing pipeline**.
2. **Updates Helm labels**
- `component: flink-beam` → `component: data-pipeline`
- Maintains uniformity with other Tradestream services.
3. **No functional impact**
- The underlying pipeline behavior remains **unchanged**.
- This is purely a **naming refactor** for **better readability and maintainability**.
- Avoids confusion with **Apache Beam**, which is also used in the project.
- More accurately reflects **data processing responsibilities**.
This PR is a **small but meaningful step** toward a more intuitive infrastructure! 🚀
> Refactor Flink Job Naming for Data Pipeline Consistency

- charts/tradestream/templates/pipeline.yaml
- charts/tradestream/values.yaml
This PR moves **Flink job arguments** from `values.yaml` directly into the Helm template, ensuring cleaner configuration and reducing redundancy.
1. **Moves Flink job arguments** from `values.yaml` → `pipeline.yaml`:
- `--bootstrapServers` and `--runner=FlinkRunner` are now **hardcoded** in the Helm template.
- Reduces complexity in `values.yaml` while keeping arguments **explicitly defined** in the deployment template.
2. **Removes unused `args` block** from `values.yaml`:
- Prevents duplication and unnecessary overrides.
- **Better maintainability** – Avoids unnecessary overrides in `values.yaml` while keeping the Helm template self-contained.
- **Consistent deployment behavior** – Ensures required arguments are always included in deployments without risk of accidental omission.
- …
> Refactor Flink Job Arguments in Helm Chart for Better Maintainability

- src/main/java/com/verlumen/tradestream/kafka/DryRunKafkaReadTransform.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransform.java
- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml
This PR updates the **Tradestream pipeline** to **read data from Kafka** instead of generating static elements, improving realism in data ingestion.
1. **Replace static "Hello, World!" with Kafka Read Transform**
- The pipeline now reads from Kafka instead of hardcoded test data.
- `buildPipeline` applies the `KafkaReadTransform`, integrating real-time Kafka ingestion.
2. **Update `DryRunKafkaReadTransform`**
- Ensures **mock data** better reflects actual Kafka messages.
- Updates test messages to "Hello" and "World!" for consistency.
3. **Modify container structure test**
- Adds `--runMode=dry` to simulate a Kafka read in **dry run mode**.
- Ensures the expected output still matches.
- **Moves towards real-world pipeline execution** by integrating Kafka as the data source.
- **Improves …
> Integrate Kafka Read Transform into Pipeline Execution

- charts/tradestream/templates/pipeline.yaml
- src/main/java/com/verlumen/tradestream/pipeline/App.java
This PR enhances the **Flink-based Tradestream pipeline** by adding **writable Flink configuration support** and improving **pipeline execution**.
1. **Introduce a writable `/opt/flink/conf` directory**
- Adds a `podTemplate` in the **Helm chart** for the pipeline.
- **Mounts an empty volume** at `/opt/flink/conf`, allowing runtime modifications.
- Ensures Flink can update configuration files dynamically.
2. **Remove unnecessary import (`java.util.Arrays`)**  
- Cleans up the `App.java` file for better maintainability.  
- **Enables dynamic Flink configuration updates** without rebuilding the container.  
- **Prepares for future custom Flink settings** (e.g., tuning parallelism, task slots, etc.).  
- **Enhances flexibility** for scaling and fine-tuning Flink job execution.  
This update …
> Enable Writable Flink Configuration in Pipeline Deployment  

- src/main/java/com/verlumen/tradestream/pipeline/App.java
This PR optimizes the execution behavior of the Flink-based data pipeline by modifying the pipeline execution method:
- Removed `.waitUntilFinish()` in `runPipeline()`, allowing the pipeline to execute asynchronously.
- `waitUntilFinish()` blocks execution until the pipeline completes, which is unnecessary in streaming jobs.
- Flink streaming pipelines are meant to run indefinitely, and blocking execution can lead to undesired behavior in managed deployments.
- Ensures proper behavior for long-running streaming pipelines.
- Aligns with Flink’s best practices for executing streaming jobs.
- Avoids unnecessary blocking that could interfere with Kubernetes job lifecycle management.
> Optimize Flink Pipeline Execution by Removing `waitUntilFinish()`

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
This PR modifies the Flink pipeline execution settings to ensure proper behavior in a streaming environment.
- **Set `attachedMode(false)`**:  
- Flink pipelines were previously running in attached mode by default.  
- Detached mode prevents blocking and allows the job to run independently.
- **Explicitly set `setStreaming(true)`**:  
- Ensures that the Flink runner treats the pipeline as a streaming job.  
- Prevents potential issues with execution mode inference.
- **Updated `BUILD` dependencies**:  
- Ensures `beam_runners_flink_java` is included in `deps`, not `runtime_deps`, to guarantee proper linkage at build time.
- Prevents jobs from being interrupted when the process exits.
- Aligns with best practices for Flink-based streaming applications.
- Ensures the pipeline can be …
> Ensure Flink Pipeline Runs in Detached Streaming Mode

- src/main/java/com/verlumen/tradestream/kafka/BUILD
- src/main/java/com/verlumen/tradestream/kafka/DryRunKafkaReadTransform.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransform.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransformFactory.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransformImpl.java
- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
- src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml
- src/test/java/com/verlumen/tradestream/kafka/BUILD
- src/test/java/com/verlumen/tradestream/kafka/KafkaReadTransformImplTest.java
This PR enhances the **KafkaReadTransform** implementation by introducing **generic support for key and value types**, allowing for greater flexibility when reading from Kafka topics. The main motivation behind this refactor is to **support various deserialization strategies dynamically** while maintaining compatibility with Beam's KafkaIO.
1. **Refactored `KafkaReadTransform` to Support Generic Types (K, V)**
- Previously, it was hardcoded to read `Long` keys and `String` values.
- Now it allows users to **specify their own key and value deserializers**.
- Enables usage with different data formats (e.g., JSON, Avro, Protobuf).
2. **Updated `KafkaReadTransformImpl` to Support Configurable Deserializers**
- Added `keyDeserializerClass()` and `valueDeserializerClass()` in AutoValue.
- Reads …
> Refactor Kafka Read Transform to Support Generic Key-Value Types

- src/main/java/com/verlumen/tradestream/kafka/BUILD
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransformFactory.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaReadTransformImpl.java
This PR improves **KafkaReadTransformImpl** by adding **Beam coders** for key-value deserialization, enabling **efficient and type-safe message processing** within Apache Beam pipelines.
1. **Introduced Automatic Coder Selection for Kafka Keys and Values**
- Added an **immutable mapping of Kafka deserializers to Beam coders**.
- Currently supports:
- `StringDeserializer` → `StringUtf8Coder`
- `ByteArrayDeserializer` → `ByteArrayCoder`
- Prevents unnecessary type conversions, reducing processing overhead.
2. **Updated `KafkaReadTransformImpl` to Use `withKeyDeserializerAndCoder` and `withValueDeserializerAndCoder`**
- This ensures that Kafka messages are decoded **correctly and efficiently** in Beam.
3. **Implemented `getCoderForDeserializer()` for Dynamic Coder Selection**
- Throws an …
> Enhance Kafka Read Transform with Coder Support for Key and Value Types

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/TradePublisher.java
- src/main/java/com/verlumen/tradestream/marketdata/TradePublisherImpl.java
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/TradePublisherImplTest.java
This PR introduces the `TradePublisher` component, which provides a structured and reliable mechanism for publishing `Trade` messages to Kafka. It includes:
- A new `TradePublisher` interface
- An implementation `TradePublisherImpl`
- Corresponding unit tests to validate its functionality
---
- Defines a contract for publishing trades.
- Supports graceful shutdown via `close()` method.
- Uses **KafkaProducer** to send trade data to Kafka.
- Supports **Google Flogger** for structured logging.
- Implements **assisted injection** to allow dynamic topic assignment.
- Logs trade metadata before sending.
- Provides detailed logging on **success** (topic, partition, offset).
- Handles **failures gracefully**, logging errors.
- **Mocks KafkaProducer** to validate interactions.
- **Verifies trade …
> Add `TradePublisher` for Publishing Trades to Kafka

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
This PR adds `MarketDataModule`, a Guice module for managing market data-related dependencies in a structured and centralized manner.
---
- Provides a **dedicated module** for market data components.
- Acts as a single entry point for injecting dependencies.
- Supports **future extensions** for additional market data services.
- Added `market_data_module` target.
- Declares `TradePublisher` and other related dependencies.
---
✅ **Encapsulates market data logic** into a single DI module.  
✅ **Improves maintainability** by **reducing coupling** between components.  
✅ **Facilitates easier testing** by allowing mock injections.  
✅ **Scales well** as more market data features are added.
This is a foundational improvement to enhance **dependency management and modularity** in the …
> Introduce `MarketDataModule` for Dependency Injection

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
This PR reorders the dependencies in `IngestionModule` within Bazel's `BUILD` file for improved **readability** and **consistency**.
---
1. **Reorganized Dependencies**  
- Moved `guice`, `auto_value`, `guava`, and `guice_assistedinject` **after** ingestion-specific modules.
- Ensured `kafka_module` and `run_mode` appear **after ingestion components**, aligning with project structure.
2. **No Functional Changes**  
- This is a **non-breaking change** with **zero functional impact** on execution.
- Strictly improves **maintainability** and **logical grouping** in the build file.
---
✅ **Improves Code Readability** — Groups dependencies logically.  
✅ **Enhances Maintainability** — Keeps the dependency structure **predictable**.  
✅ **Aligns with Best Practices** — Ensures **framework …
> Reorder Dependencies in `IngestionModule` for Consistency  

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/ParseTrades.java
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/ParseTradesTest.java
This PR introduces the `ParseTrades` transform, which parses raw Kafka byte arrays into `Trade` protobuf messages. It also includes a full suite of **unit tests** to validate functionality.
---
1. **New `ParseTrades` Transform**
- Converts `byte[]` messages into `Trade` protobuf objects.
- Uses **Apache Beam's `ParDo`** for efficient parallel processing.
- Logs errors and prevents pipeline crashes on malformed messages.
2. **Comprehensive Unit Tests**
- Added **`ParseTradesTest`** with **five test cases**:
✅ **Valid Trade Parsing**: Ensures correct deserialization.  
✅ **Invalid Trade Handling**: Ensures invalid messages are dropped.  
✅ **Mixed Input Handling**: Valid messages pass, invalid messages are skipped.  
✅ **Empty Input Handling**: Ensures no output for an empty input.  
✅ …
> Add `ParseTrades` Transform and Unit Tests for Trade Deserialization

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This PR integrates the `MarketDataModule` into the `IngestionModule`, ensuring that market data dependencies (e.g., trade parsing and publishing) are properly injected for real-time data ingestion.
---
1. **Updated `IngestionModule.java`**
- Installed `MarketDataModule` alongside `KafkaModule`.
- This enables dependency injection for trade processing components.
2. **Modified `BUILD` Files**
- Added `//src/main/java/com/verlumen/tradestream/marketdata:market_data_module` as a dependency in `ingestion/BUILD`.
---
✅ **Ensures Proper Dependency Injection** — `MarketDataModule` is now available within the ingestion pipeline.  
✅ **Prepares for Future Expansion** — Facilitates modular trade processing and market data integration.  
✅ **Enhances Code Maintainability** — Keeps dependencies clean …
> Integrate `MarketDataModule` into `IngestionModule`

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
The `FORWARD_SLASH` constant was unused in `RealTimeDataIngestionImpl.java`, so this removes it to clean up the code. 🚀
> Remove Unused `FORWARD_SLASH` Constant

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
Reorganizes dependencies in `BUILD` files to maintain consistency and readability. Ensures third-party dependencies and internal modules follow a structured order. 🚀
> Reorder Dependencies in `BUILD` for Consistency  

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- Renames `BytesToStringDoFn` to `PrintBytesAsString` for clarity.  
- Simplifies byte processing by removing unnecessary exception handling and protobuf parsing.  
- Ensures Kafka messages are printed as strings while keeping the pipeline output unchanged. 🚀
> Rename and Simplify Kafka Byte Processing

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
This PR updates **`RealTimeDataIngestionImpl`** to transition from publishing trades indirectly via the **candle publisher** to using a dedicated **trade publisher**. This is part of an ongoing migration to improve data separation and maintainability.  
---
1. **Introduced `tradePublisher.publishTrade(trade);`**  
- Trades are now **published separately** before candle aggregation.  
- Enables better **scalability and flexibility** in trade data handling.  
2. **Updated Logging Messages**  
- Changed references from `"candle publisher"` to `"trade publisher"` to reflect the **new separation**.  
- Improves **debugging clarity** when tracking published trade events.  
3. **Ensured Proper Shutdown of Trade Publisher**  
- Calls `tradePublisher.close();` during shutdown to **prevent resource …
> Migrate Trade Publishing to New Publisher in Real-Time Data Ingestion  

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
This PR updates the **TradeStream pipeline** to consume trade data directly from the **`trades`** Kafka topic instead of the previous **`candles`** topic. This change aligns with the recent separation of **trade and candle processing**, ensuring a dedicated trade pipeline.
---
1. **Renamed `candleTopic` → `tradeTopic`**  
- Updated `Options` and `PipelineModule` to reflect the new trade topic.  
- Default Kafka topic is now `"trades"` instead of `"candles"`.  
2. **Updated Pipeline Module and Injection**  
- Now **reads raw trade data** from Kafka instead of candle data.  
- Ensures the **correct Kafka topic is injected** during pipeline creation.  
3. **Preserved Dry Run Mode Compatibility**  
- `DryRunKafkaReadTransform` now simulates trades instead of candles.  
- Uses the **predefined …
> Migrate Pipeline from Candle Topic to Trade Topic  

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml
This PR cleans up redundant debug logging within the **TradeStream pipeline** and updates test expectations to align with **expected error output behavior**.
---
1. **Removed `PrintBytesAsString` Transform**  
- Previously used for logging raw Kafka messages before parsing.  
- No longer needed as trade parsing is now the primary operation.  
2. **Updated Container Structure Test Expectations**  
- **Changed `expectedOutput` → `expectedError`** to correctly match the new Flink error stream behavior.  
- Ensures `"DRY/RUN"` appears in the expected error logs instead of standard output.  
---
✅ **Eliminates unnecessary logging** – Avoids cluttering output logs.  
✅ **Improves pipeline efficiency** – Trade parsing now executes without intermediate logging.  
✅ **Fixes test validation** – …
> Remove Redundant Debug Logging and Adjust Test Expectations  

- charts/tradestream/templates/data-ingestion.yaml
This PR updates the **Data Ingestion Kubernetes configuration** to reflect the migration from **candle-based ingestion** to **trade-based ingestion**.  
---
1. **Removed `candlePublisherTopic` from Helm Chart**  
- Data ingestion now **publishes trade data** instead of candles.  
2. **Introduced `tradeTopic` Configuration**  
- `tradeTopic` is now passed as a command-line argument to the container.  
3. **Reordered Arguments for Clarity**  
- Ensured `runMode` appears before `tradeTopic` for **better readability**.  
---
✅ **Aligns with pipeline migration** – The system is now ingesting **trades instead of candles**.  
✅ **Ensures consistency** – Matches the `tradeTopic` parameter used in the **Flink-based pipeline**.  
✅ **Improves Helm Chart maintainability** – Keeps configurations …
> Migrate Data Ingestion to Use `tradeTopic` Instead of `candlePublisherTopic`

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/CreateCandles.java
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
- src/test/java/com/verlumen/tradestream/marketdata/CreateCandlesTest.java
This PR refactors `CreateCandles` to support **dependency injection (DI) via Guice**, removing the static factory method (`CreateCandles.create()`).  
---
1. **Dependency Injection via Guice**  
- Replaced `CreateCandles.create()` with direct `@Inject` constructor.  
- Removed explicit binding in `MarketDataModule`.  
- Ensures better **testability and configurability**.
2. **Updated Tests for Constructor Invocation**  
- All test cases now use `new CreateCandles()` instead of `CreateCandles.create()`.  
- This allows greater flexibility in test setup.  
3. **Removed Unused Binding in `MarketDataModule`**  
- Eliminated explicit binding for `CreateCandles` as Guice now **automatically injects** it.  
---
✅ **Aligns with DI Best Practices** – Removes **unnecessary static factory methods**. …
> Refactor `CreateCandles` for Dependency Injection & Remove Static Factory Method

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
This PR integrates the **`CreateCandles`** transform into the `App` pipeline, allowing the system to **aggregate trade data into candlestick representations**.
---
1. **Injected `CreateCandles` into `App`**
- Added `CreateCandles` as a dependency via **Guice**.
- Ensures **modular design** by separating trade parsing and aggregation.
2. **Updated Pipeline Construction**
- Applied `CreateCandles` after `ParseTrades` in the data flow.
- Allows **real-time trade data aggregation**.
3. **Updated `BUILD` Dependencies**
- Included `CreateCandles` as a dependency in `BUILD`.
- Ensures **correct compilation and linkage** in Bazel.
---
✅ **Enables Candle Generation** – Converts individual trades into meaningful candlestick data.  
✅ **Improves Readability & Separation of Concerns** – Keeps …
> Integrate `CreateCandles` into Pipeline for Trade Data Aggregation  

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
This PR **removes `CandleManager` from `RealTimeDataIngestionImpl`**, transitioning **candle aggregation responsibilities** to the pipeline.  
---
1. **Removed `CandleManager` from `RealTimeDataIngestionImpl`**
- Eliminates direct candle processing from ingestion logic.  
- **Trades are now only published**, allowing downstream services to handle aggregation.
2. **Updated `RealTimeDataIngestionImplTest`**
- **Replaced `CandleManager` assertions** with `TradePublisher`.  
- Ensures **trade publication is still validated**.
3. **Updated `BUILD` Files**
- **Removed `CandleManager` dependencies** in:
- `src/main/java/com/verlumen/tradestream/ingestion/BUILD`
- `src/test/java/com/verlumen/tradestream/ingestion/BUILD`
- Prevents unnecessary compilation of unused code.
---
✅ **Decouples trade …
> Remove `CandleManager` from Real-Time Data Ingestion  

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
This PR **removes a redundant logging statement** in `RealTimeDataIngestionImpl` that logs every trade before publishing. Since trade processing is already well-monitored by **downstream logging and metrics**, this log statement is **unnecessary and adds noise**.
---
- **Removed the `Processing new trade` log statement**
- Trades are **already logged** when they are **published** and **processed by the pipeline**.
- Reduces **log clutter** in high-frequency trading environments.
---
✅ **Reduces redundant logs**, improving **log signal-to-noise ratio**.  
✅ **Enhances system performance** by avoiding unnecessary logging overhead.  
✅ **Ensures cleaner logs** that focus on actionable errors and insights.
---
- Monitor logs to confirm that **critical trade processing logs remain intact**. …
> Remove Redundant Trade Processing Log Statement in `RealTimeDataIngestionImpl`

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
This PR **removes `CandlePublisher` from `RealTimeDataIngestionImpl`**, further streamlining **trade ingestion responsibilities** and shifting candle aggregation fully to the data pipeline.
---
1. **Removed `CandlePublisher` from `RealTimeDataIngestionImpl`**
- **No longer publishing candles** from the ingestion layer.
- Trades are **only published** to Kafka, **candle aggregation now occurs in the pipeline**.
2. **Updated `RealTimeDataIngestionImplTest`**
- Removed `CandlePublisher` from mock dependencies.
- **Assertions now verify `TradePublisher` behavior** instead.
3. **Updated `BUILD` Files**
- **Removed `CandlePublisher` dependencies** in:
- `src/main/java/com/verlumen/tradestream/ingestion/BUILD`
- `src/test/java/com/verlumen/tradestream/ingestion/BUILD`
- **Prevents compilation of …
> Remove `CandlePublisher` from Real-Time Data Ingestion

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
This PR **removes the `TradeProcessor` dependency** from `RealTimeDataIngestionImpl`, simplifying the trade ingestion process by eliminating the duplicate trade check.
---
✅ **Removed `TradeProcessor`** from:
- **`RealTimeDataIngestionImpl`** (constructor, `processTrade` method).
- **Tests (`RealTimeDataIngestionImplTest`)** related to trade deduplication.
- **`BUILD` files** to clean up unused dependencies.
---
📉 **Reduces latency**—Previously, each trade was checked for duplication before publishing, adding unnecessary overhead.  
🚀 **Improves scalability**—Trade ingestion now handles trades directly without coordination delays.  
✅ **Simplifies the architecture**—We now assume the Kafka consumer or downstream services handle deduplication.  
---
1. **Verify trade deduplication logic in …
> Remove `TradeProcessor` from `RealTimeDataIngestionImpl`

- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
This PR **removes an unused `Timer` binding** from `IngestionModule` to clean up unnecessary dependencies.
---
✅ **Deleted `import java.util.Timer;`** – The `Timer` class was imported but never used.  
✅ **Removed `bind(Timer.class).toProvider(Timer::new);`** – The module no longer binds `Timer` as it was **unused**.
---
🔹 **Reduces unnecessary dependencies**—Avoids binding objects that are not actually used.  
🔹 **Improves maintainability**—Keeps `IngestionModule` clean and focused on essential dependencies.  
🔹 **Prevents potential confusion**—Future developers won’t assume that `Timer` is required.
---
1. **Verify module functionality remains unchanged.**  
2. **Confirm no other parts of the codebase rely on this `Timer` binding.**  
🚀 **Leaner, cleaner dependency management!**
> Remove Unused Timer Binding from `IngestionModule`

- charts/tradestream/values.yaml
- **Removed `candlePublisherTopic`** from `values.yaml` as it is no longer needed.  
- **Added `tradeTopic`** under `dataIngestion` to ensure the correct topic is referenced.  
- This change **aligns the Helm chart configuration** with the recent refactoring in the ingestion module.
> Remove `candlePublisherTopic` from Helm Chart Values  

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
- **Removed `market_data_config` dependency** from `BUILD` as it's no longer required.  
- **Refactored `MarketDataModule.create()`** to accept `tradeTopic` directly instead of `MarketDataConfig`.  
- **Updated `IngestionModule`** to pass `tradeTopic` directly, simplifying configuration.  
- This change **streamlines initialization** by reducing unnecessary dependencies.
> Remove `MarketDataConfig` Dependency from Ingestion Module

- src/main/java/com/verlumen/tradestream/ingestion/App.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java
- **Removed `candleIntervalMillis` from `IngestionConfig`** as it is no longer needed.  
- **Deleted `--candleIntervalSeconds` argument** from CLI options in `App.java`.  
- **Updated `IngestionConfig` constructor** to exclude the redundant field.  
- This simplifies the ingestion configuration by eliminating an unused parameter.
> Remove `candleIntervalMillis` from Ingestion Configuration

- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
This PR enhances the **real-time data ingestion** in `RealTimeDataIngestionImpl` by introducing a **blocking queue** and a **dedicated background thread** for publishing trades. Instead of publishing trades directly from the exchange client callback, trades are now enqueued and processed asynchronously in a separate executor service.  
✅ **Introduced a `BlockingQueue<Trade>`** to store incoming trades before publishing.  
✅ **Added a single-threaded executor (`tradePublisherExecutor`)** to process trades from the queue.  
✅ **Updated `start()` method** to queue trades instead of publishing them immediately.  
✅ **Implemented a background task using `Stream.generate()`** to continuously take trades from the queue and publish them.  
✅ **Ensured proper shutdown handling** by stopping the …
> Improve Trade Ingestion with Blocking Queue and Background Processing  

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- **Removed unused imports** (e.g., `InvalidProtocolBufferException`, `Candle`).  
- **Refactored formatting** for better readability and consistency.  
- **Simplified pipeline transformation** by directly applying `ParseTrades`.  
- **No functional changes**, just cleanup and minor code style improvements.
> Cleanup `App.java` in TradeStream Pipeline

- src/main/java/com/verlumen/tradestream/pipeline/PipelineConfig.java
- **Increased `allowedTimestampSkew`** from **1 second to 5 minutes** to accommodate late-arriving trades.  
- **Refactored duration constants** for better clarity and maintainability.  
- **Ensures more accurate trade aggregation** by reducing data loss due to minor delays in trade ingestion.
> Adjust Allowed Timestamp Skew for Late Arriving Trades  

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
- src/main/java/com/verlumen/tradestream/marketdata/LastCandlesFn.java
- src/main/java/com/verlumen/tradestream/marketdata/SlidingCandleAggregator.java
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaultsTest.java
This composite transform, CandleStreamWithDefaults, unites real trades with synthetic default trades, aggregates them into candles using our SlidingCandleAggregator, and then buffers the last N candles using LastCandlesFn. (Missing candles are filled by using the previous candle’s close.) Its tests cover scenarios with real trades, with no real trades (thin markets), and buffer size enforcement.
> Add Composite Transform CandleStreamWithDefaults

- src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
This PR **improves the windowing logic** in `CandleStreamWithDefaults` by ensuring that buffered candle outputs are correctly **re-windowed into GlobalWindows** before applying `GroupByKey`.  
---
✅ **Re-windowing Buffered Candles into GlobalWindows**  
- Ensures **GroupByKey correctly consolidates** buffered outputs from multiple sliding windows.  
- Uses `DefaultTrigger.of()` and `discardingFiredPanes()` to avoid stale data accumulation.  
✅ **Updated Documentation for Clarity**  
- **Clarifies each step** of the pipeline, ensuring better maintainability.  
- Highlights how **default trades trigger candle generation** when no real trades exist.  
✅ **Preserved Data Integrity**  
- Prevents unintended duplicate grouping.  
- Guarantees a **consistent output structure** across the …
> Improve Windowing for Buffered Candles in `CandleStreamWithDefaults` 

- src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
This PR **enhances the windowing mechanism** in `CandleStreamWithDefaults` by introducing **processing-time triggers** for buffered candle aggregation within **GlobalWindows**.  
---
✅ **Updated Rewindowing Logic for Buffered Candles**  
- **Uses `Repeatedly.forever(AfterProcessingTime.pastFirstElementInPane().plusDelayOf(1s))`**  
- Ensures **low-latency emission** while avoiding unnecessary accumulation.  
- Provides a **consistent cadence** for candle updates.  
- **Explicitly sets `withAllowedLateness(Duration.ZERO)`**  
- Prevents outdated elements from lingering in the pipeline.  
- Ensures strict adherence to real-time processing.  
✅ **Improved Grouping Efficiency**  
- `GroupByKey` now operates **only on recently emitted elements** rather than accumulating indefinitely.  
✅ …
> Improve Windowing for Buffered Candles Using Processing-Time Trigger

- src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
This PR **replaces GlobalWindows with 1-day FixedWindows** in `CandleStreamWithDefaults` to improve **data partitioning, parallelism, and resource efficiency** in Beam's streaming pipeline.  
---
✅ **Replaced GlobalWindows with `FixedWindows.of(Duration.standardDays(1))`**  
- **Why?**  
- GlobalWindows required **triggers and complex state management** for bounded processing.  
- FixedWindows **naturally partition** candle updates while still grouping per key.  
- **Benefit:**  
- **Better parallel processing** – candles for different days can be computed independently.  
- **Reduced stateful processing overhead** – Beam **manages retention efficiently**.  
✅ **Simplified Re-windowing Logic**  
- **Old:**  
- Used **GlobalWindows** + a **processing-time trigger** …
> Use Fixed 1-Day Windows for Buffered Candles Instead of GlobalWindows 

- charts/tradestream/values.yaml
This PR **increases Kafka replicas from 2 to 3**, configures **controller quorum voters**, adds **pod security context**, and sets **resource limits** to enhance **Kafka cluster resilience, security, and performance**.  
---
✅ **Increased Kafka replicas from 2 ➝ 3**  
- **Why?**  
- Avoids **split-brain scenarios** in a 2-node setup.  
- Ensures a **majority (quorum) can be reached** during failures.  
- **Benefit:**  
- **More resilient leader elections & higher availability.**  
✅ **Defined `controller.quorum.voters` for the new 3-node setup**  
- **Why?**  
- Kafka **KRaft mode** needs explicit voter configuration.  
- **Benefit:**  
- Prevents misconfigurations in **controller elections**.  
✅ **Added `podSecurityContext` to enforce `runAsUser: 1001` and `fsGroup: 1001`**  
- **Why?** …
> Increase Kafka Replicas to 3 & Optimize Resource Requests

- src/main/java/com/verlumen/tradestream/pipeline/PipelineConfig.java
This change updates the `PipelineConfig` class to increase the `allowedTimestampSkew` duration from 5 minutes to 15 minutes. This adjustment ensures greater tolerance for out-of-order events while processing trade streams.  
- Updated the constant `FIVE_MINUTES` to `FIFTEEN_MINUTES` (15 minutes).  
- Modified the `create` factory method to use the new `FIFTEEN_MINUTES` value.  
This change is intended to improve resilience in scenarios where trades arrive with higher delays. Let me know if further adjustments are needed!
> Increase allowed timestamp skew to 15 minutes in PipelineConfig  

- src/main/java/com/verlumen/tradestream/marketdata/SlidingCandleAggregator.java
This refactor improves the clarity and efficiency of the `extractOutput` method in `SlidingCandleAggregator` by directly returning `Candle.getDefaultInstance()` when no trades are present. Previously, an unnecessary `Candle.Builder` was created and populated with default values.  
- Directly return `Candle.getDefaultInstance()` when no trades are found.  
- Remove redundant `Candle.Builder` instantiation for the default case.  
- Improve code readability by restructuring the conditional logic.  
- Maintain logging for better traceability.  
This change simplifies the method while preserving functionality and logging behavior.
> Refactor `extractOutput` to Return Default Candle Directly

- src/main/java/com/verlumen/tradestream/ta4j/BUILD
- src/main/java/com/verlumen/tradestream/ta4j/BarSeriesBuilder.java
- src/test/java/com/verlumen/tradestream/ta4j/BUILD
- src/test/java/com/verlumen/tradestream/ta4j/BarSeriesBuilderTest.java
This PR introduces the `BarSeriesBuilder` class, which converts a list of `Candle` protobuf objects into a TA4J `BarSeries`.  
- Added `BarSeriesBuilder.java` to create `BarSeries` from `Candle` data.  
- Uses `BaseBarSeries` and `BaseBar` from TA4J.  
- Converts `Candle` timestamps to `ZonedDateTime` using UTC.  
- Maps `Candle` fields to `Bar` properties.  
- Added unit tests in `BarSeriesBuilderTest.java`.  
- Verifies correct conversion of `Candle` fields to `Bar`.  
- Tests various scenarios including empty lists, single/multiple candles, and timestamp conversion.  
- Added corresponding `BUILD` files for both main and test sources.  
- Added dependencies on TA4J, Protobuf, and Guava in `BUILD` files.  
- Unit tests cover multiple edge cases.  
- All tests pass, confirming expected …
> Add `BarSeriesBuilder` for converting `Candle` data to `BarSeries`  

- src/main/java/com/verlumen/tradestream/backtesting/BacktestRunner.java
This update modifies the `BacktestRunner` interface to extend `Serializable`. This change ensures that implementations of `BacktestRunner` can be serialized, which may be useful for distributed processing, caching, or persistence purposes.
- Updated `BacktestRunner` to implement `Serializable`.
- Added the corresponding import statement for `java.io.Serializable`.
This change improves the flexibility of `BacktestRunner` in scenarios requiring object serialization.
> Add Serializable Interface to BacktestRunner

- src/test/java/com/verlumen/tradestream/backtesting/BacktestRunnerImplTest.java
This PR updates `BacktestRunnerImplTest` to use Guice for dependency injection instead of manually instantiating `BacktestRunnerImpl`. Key changes include:
- Adding `@Inject` annotation to `backtestRunner` to allow Guice to inject dependencies.
- Removing the manual instantiation of `BacktestRunnerImpl` in `setUp()`.
- Using `Guice.createInjector().injectMembers(this);` to initialize dependencies.
These changes improve test maintainability and ensure consistency with Guice-based dependency management in the codebase.
> Refactor `BacktestRunnerImplTest` to use Guice dependency injection

- src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java
This PR improves the Javadoc documentation for the `StrategyManager` interface by adding detailed descriptions, proper formatting, and clarifications for method parameters and return values. Key enhancements include:
- **Class-Level Javadoc**: Introduced a comprehensive overview of the `StrategyManager` interface, explaining its role in managing trading strategies within the TradeStream system.
- **Method Annotations & Formatting**: 
- Improved clarity in method descriptions.
- Ensured proper usage of `{@link}` for referencing related classes like `Strategy`, `StrategyType`, and `StrategyFactory`.
- Standardized parameter descriptions and formatted return type explanations.
- **New Javadoc Additions**:
- Added documentation for `getDefaultParameters()`, detailing its role in retrieving …
> Enhance Javadoc Documentation for `StrategyManager` Interface  

- .github/workflows/release.yaml
This update modifies the GitHub Actions release workflow by removing prerelease versioning. Specifically:  
- Eliminates `enable_prerelease_mode: true`.  
- Updates `version_format` to exclude the `-prerelease${increment}` suffix.  
This ensures that all generated versions follow the standard `major.minor.patch` format without prerelease identifiers.  
This change is intended to streamline the versioning strategy and align with a stable release process. Let me know if further adjustments are needed!
> Remove prerelease versioning from release workflow  

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestRunner.java
This PR removes unused dependencies from the backtesting module to streamline the build and reduce unnecessary imports.  
- **BUILD file cleanup**: Removed dependencies on:
- `//protos:strategies_java_proto`
- `//third_party:auto_value`
- `//third_party:guice`
- `//third_party:ta4j_core`
- **Code cleanup**: Removed unused imports from `BacktestRunner.java`, specifically:
- `com.google.auto.value.AutoValue`
- `com.verlumen.tradestream.strategies.StrategyType`
- `org.ta4j.core.BarSeries`
- `org.ta4j.core.Strategy`
This update improves maintainability by eliminating unused dependencies, reducing potential build overhead, and making the codebase cleaner.
> (MINOR) Remove unused dependencies from backtesting module  

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestServiceClient.java
- src/main/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImpl.java
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImplTest.java
This PR refactors the backtesting execution flow by removing `BacktestServiceClient` and replacing it with `BacktestRunner`. The key changes include:
- **Removed `BacktestServiceClient.java`** and its associated `java_library` target from the build files.
- **Updated `GeneticAlgorithmOrchestratorImpl`** to use `BacktestRunner` instead of `BacktestServiceClient` for running backtests.
- **Modified test files**:
- Replaced references to `BacktestServiceClient` with `BacktestRunner`.
- Adjusted Mockito-based stubbing and verifications accordingly.
- **Updated BUILD dependencies** to remove `backtest_service_client` and add `backtest_runner`.
This change simplifies the backtesting workflow by directly integrating `BacktestRunner`, reducing unnecessary abstraction.
> Refactor Backtest Execution: Replace `BacktestServiceClient` with `BacktestRunner`

- protos/backtesting.proto
- src/main/java/com/verlumen/tradestream/backtesting/BacktestRunnerImpl.java
- src/main/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImpl.java
- src/test/java/com/verlumen/tradestream/backtesting/BacktestRunnerImplTest.java
- src/test/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImplTest.java
- src/test/java/com/verlumen/tradestream/backtesting/RunBacktestTest.java
This PR refactors the `BacktestResult` structure and modifies the scoring logic in `BacktestRunnerImpl`. Key changes include:
- **Proto Changes**:
- Merged `TimeframeResult` into `BacktestResult`, eliminating multi-timeframe evaluations.
- Introduced `strategy_score` as a primary evaluation metric.
- Removed `BacktestService` and `GAService` definitions from `backtesting.proto`.
- **BacktestRunner Implementation Updates**:
- Removed predefined timeframe evaluations and simplified backtest execution to focus on overall strategy performance.
- Adjusted the scoring mechanism to compute a single `strategy_score` based on Sharpe ratio, drawdowns, win rate, annualized return, and profit factor.
- **Genetic Algorithm Integration**:
- Updated `GeneticAlgorithmOrchestratorImpl` to use …
> Refactor BacktestResult and Scoring Logic in BacktestRunner

- src/main/java/com/verlumen/tradestream/backtesting/params/ParamConfigManager.java
This PR updates the `ParamConfigManager` interface by extending `Serializable`. This change ensures that implementations of `ParamConfigManager` can be serialized, which may be necessary for distributed processing, caching, or persistence.  
- Modified `ParamConfigManager` to implement `Serializable`.  
- Added the necessary `java.io.Serializable` import.  
This change improves compatibility with frameworks or systems that require serialization of configuration managers.
> Enhance `ParamConfigManager` with `Serializable` Implementation  

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/GenotypeConverter.java
This PR introduces the `GenotypeConverter` interface in the `backtesting` package. The interface defines a method for converting genotypes from a genetic algorithm into strategy parameters, making the conversion logic reusable and testable.  
- **Added `GenotypeConverter.java`**  
- Defines an interface with a `convertToParameters` method to transform genetic algorithm-generated genotypes into strategy parameters.  
- Uses `Genotype<DoubleGene>` from Jenetics and `Any` from Protobuf to enable flexible parameter conversion.  
- **Updated `BUILD` file**  
- Added a new `java_library` target (`genotype_converter`) for `GenotypeConverter.java`.  
- Declared dependencies on:  
- `//protos:strategies_java_proto`  
- `//third_party:jenetics`  
- `//third_party:protobuf_java`  
- Facilitates …
> Add `GenotypeConverter` interface for genotype-to-strategy parameter conversion  

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/GAEngineFactory.java
- Introduced `GAEngineFactory` interface to define a contract for creating genetic algorithm engines.  
- Added `GAEngineFactory.java`, which specifies a method `createEngine(GAOptimizationRequest request)` returning a configured `Engine<DoubleGene, Double>`.  
- Updated `BUILD` file to include a new `java_library` target (`ga_engine_factory`), with dependencies on `//protos:backtesting_java_proto` and `//third_party:jenetics`.  
These changes facilitate the modularization of genetic algorithm engine creation, improving extensibility and maintainability within the backtesting module.
> Add GAEngineFactory interface for genetic algorithm engine creation

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
This PR introduces a new Java library, `ga_constants`, to the `backtesting` module. The library includes `GAConstants.java` as a source file. 
- Added a new `java_library` target named `ga_constants` in `BUILD`
- Included `GAConstants.java` as the source for the `ga_constants` library
This change improves modularity by separating constant definitions into a dedicated library, which can be reused across other components in the `backtesting` module.
> Add `ga_constants` Java library to Backtesting module

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java
- src/main/java/com/verlumen/tradestream/backtesting/GenotypeConverter.java
- src/main/java/com/verlumen/tradestream/backtesting/GenotypeConverterImpl.java
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/GenotypeConverterImplTest.java
This PR introduces support for genotype conversion in the backtesting module by implementing `GenotypeConverterImpl`. The changes facilitate the transformation of genetic algorithm genotypes into strategy parameters, improving modularity and testability.
- **Added `GenotypeConverterImpl`**: Implements `GenotypeConverter` to convert genotypes into strategy parameters using `ParamConfigManager`.
- **Updated `BacktestingModule`**: Binds `GenotypeConverter` to `GenotypeConverterImpl` using Guice for dependency injection.
- **Updated `BUILD` files**:
- Added `genotype_converter_impl` target.
- Included necessary dependencies such as `protobuf_java`, `jenetics`, and `params_lib`.
- **Added unit tests (`GenotypeConverterImplTest`)**:
- Validates correct genotype conversion behavior.
- Ensures …
> Add genotype conversion support in backtesting module

- src/main/java/com/verlumen/tradestream/strategies/BUILD
This PR refactors the `BUILD` dependencies in the `strategies` package by reordering and reorganizing dependencies for clarity and maintainability. Key changes include:  
- Adjusted the order of dependencies to improve readability.  
- Moved `market_data_consumer` dependency within `market_data_consumer_impl`.  
- Reordered dependencies in `strategies_module` to maintain consistency.  
- Refactored `strategy_engine_impl`, `strategy_manager`, and `strategy_manager_impl` to ensure dependencies are listed logically.  
These changes enhance maintainability by providing a clearer structure for dependencies without altering functionality.
> Refactor BUILD Dependencies for Strategy Modules  

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyState.java
This PR introduces the `StrategyState` interface, which provides a standardized way to manage and persist the state of trading strategies in the `tradestream` module. It enables tracking strategy performance, selecting the best-performing strategy, and reconstructing a strategy based on stored parameters.  
- **Added `StrategyState.java`**  
- Defines methods for retrieving and selecting strategies.  
- Supports performance tracking via `updateRecord`.  
- Converts strategy state to a message format for persistence.  
- **Updated `BUILD` file**  
- Added a new `strategy_state` Java library with dependencies on `strategy_manager`, `protobuf_java`, and `ta4j_core`.  
This change enhances the flexibility of the trading strategy module by enabling strategy persistence and selection based on …
> Add `StrategyState` interface for managing strategy state and performance tracking  

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyState.java
This PR removes the `StrategyManager` dependency from the `StrategyState` interface, streamlining its design by reducing unnecessary coupling.  
- **Modified `StrategyState` Interface:**  
- Removed `StrategyManager` parameter from `getCurrentStrategy` and `selectBestStrategy` methods.  
- Updated method signatures accordingly.  
- Changed interface visibility from `public` to package-private for better encapsulation.  
- **Updated BUILD File:**  
- Removed `:strategy_manager` dependency from `strategy_state` target.  
These changes improve modularity and maintainability by ensuring `StrategyState` does not directly depend on `StrategyManager`, making it easier to manage and test.
> Refactor `StrategyState` Interface: Remove `StrategyManager` Dependency  

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyRecord.java
This PR introduces a new `StrategyRecord` class in the `com.verlumen.tradestream.strategies` package. The class serves as an immutable record to encapsulate strategy parameters and performance scores.  
- **Added `StrategyRecord.java`**  
- Defines `StrategyRecord`, which implements `Serializable`.  
- Stores a `StrategyType`, `Any` parameters, and a performance score (`double`).  
- Enforces non-null strategy type using `Preconditions.checkNotNull()`.  
- **Updated `BUILD` file**  
- Added a new `java_library` target named `strategy_record`.  
- Included necessary dependencies (`guava`, `protobuf_java`, and `strategies_java_proto`).  
The introduction of `StrategyRecord` provides a structured way to store and track strategy configurations and their effectiveness, facilitating better …
> Add `StrategyRecord` for strategy parameter and performance tracking  

- src/main/java/com/verlumen/tradestream/strategies/StrategyState.java
This update enhances `StrategyState` by making it `Serializable`, allowing instances to be serialized for persistence or distributed processing. Additionally, a new `Factory` interface is introduced within `StrategyState`, providing a structured way to create instances of `StrategyState`. This ensures a standardized approach to instantiating strategy state objects, which is beneficial for dependency injection and strategy initialization.
- Implemented `Serializable` in `StrategyState` to support serialization.
- Added an inner `Factory` interface that also extends `Serializable`, providing a method to create new `StrategyState` instances.
- Updated JavaDocs to document the new interface and its intended use.
These changes improve the flexibility and maintainability of the strategy state …
> Add Serializable Support and Factory Interface to StrategyState

- src/main/java/com/verlumen/tradestream/strategies/StrategyRecord.java
This PR introduces factory methods to simplify the instantiation of `StrategyRecord`. The changes include:  
- Adding a `create` method with default score initialization (`Double.NEGATIVE_INFINITY`).
- Providing an overloaded `create` method that allows setting a custom score.
- Moving the `checkNotNull` validation inside the constructor for `strategyType`.
- Reordering imports to align with convention.  
These changes improve usability by providing a more flexible way to create `StrategyRecord` instances while ensuring immutability remains intact.
> Add factory methods for StrategyRecord instantiation  

- src/test/java/com/verlumen/tradestream/signals/BUILD
This PR modifies the `BUILD` file for trade signal tests by adjusting the dependencies:
- Moves `trade_signal_publisher` and `trade_signal_publisher_impl` within the `deps` list to maintain proper ordering.
- Ensures consistency and readability in the test dependencies.
This change improves maintainability without affecting functionality.
> Refactor test dependencies in trade signal test BUILD file

- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
This PR removes the binding of `ExecutorService` in `StrategiesModule`, as it is no longer required. The unnecessary dependency was previously instantiated using `Executors::newSingleThreadExecutor`, but it is now redundant and has been removed to simplify the module configuration.  
This change improves maintainability by eliminating unused bindings without affecting the existing strategy engine functionality.
> Remove unused ExecutorService binding in StrategiesModule  

- src/main/java/com/verlumen/tradestream/signals/TradeSignalPublisher.java
This PR updates the `TradeSignalPublisher` interface to extend `Serializable`. This change ensures that instances of implementing classes can be serialized, which may be necessary for distributed processing, persistence, or network communication.  
- Added `import java.io.Serializable;`  
- Modified `TradeSignalPublisher` to extend `Serializable`  
- Enables serialization for classes implementing `TradeSignalPublisher`  
- Supports potential use cases such as distributed messaging or caching  
No functional changes were introduced, and existing behavior remains unaffected.
> Add `Serializable` to `TradeSignalPublisher` interface  

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/ChromosomeSpec.java
- src/main/java/com/verlumen/tradestream/backtesting/DoubleChromosomeSpec.java
- src/main/java/com/verlumen/tradestream/backtesting/GAEngineFactoryImpl.java
- src/main/java/com/verlumen/tradestream/backtesting/IntegerChromosomeSpec.java
- src/main/java/com/verlumen/tradestream/backtesting/params/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/params/ParamConfig.java
- src/main/java/com/verlumen/tradestream/backtesting/params/SmaRsiParamConfig.java
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/GenotypeConverterImplTest.java
- src/test/java/com/verlumen/tradestream/backtesting/params/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/params/SmaRsiParamConfigTest.java
This PR refactors the `ChromosomeSpec` classes by moving them from the `params` package to the main `backtesting` package. The changes include:
- **File Relocation**:  
- `ChromosomeSpec.java`, `DoubleChromosomeSpec.java`, and `IntegerChromosomeSpec.java` have been moved from `backtesting/params` to `backtesting`.
- Their package declarations have been updated accordingly.
- **Build System Updates**:  
- A new `chromosome_spec` Java library target is added in `BUILD` files to group related classes.
- Dependencies in `backtesting/BUILD` and `params/BUILD` have been updated to reference `chromosome_spec`.
- **Import Adjustments**:  
- All references to `com.verlumen.tradestream.backtesting.params.ChromosomeSpec` have been updated to `com.verlumen.tradestream.backtesting.ChromosomeSpec` in …
> Refactor: Move ChromosomeSpec classes and update dependencies

- .github/workflows/ci.yaml
This update modifies the CI workflow to improve efficiency by deleting the `/opt/hostedtoolcache` directory before checking out the code. This folder contains cached tools that are not required for the build process and can take up significant space. Removing it helps optimize disk usage and potentially speeds up CI runs.  
No changes to the build logic or test execution were made.
> Optimize CI workflow by removing unnecessary tools folder  

- src/main/java/com/verlumen/tradestream/strategies/StrategyManager.java
This update modifies the `StrategyManager` interface to extend `Serializable`. 
- Added `java.io.Serializable` import.
- Updated `StrategyManager` to implement `Serializable`, enabling object serialization.
- Ensuring `StrategyManager` is serializable facilitates its use in distributed systems, caching mechanisms, or scenarios where instances need to be persisted or transmitted.
This change introduces new behavior, so it's marked as a **minor version update**.
> Extend `StrategyManager` to Implement `Serializable` Interface (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
This PR updates the `StrategyFactory` interface to extend `Serializable`, ensuring that strategy implementations can be serialized when needed.  
- **Updated** `StrategyFactory<T>` to extend `Serializable`.
- **Added** the necessary `java.io.Serializable` import.  
- Allows instances of `StrategyFactory` to be serialized, which is useful for distributed processing, caching, or persistence.  
- Aligns with best practices for interfaces that may be used in serialization-sensitive contexts.  
This is a **patch-level** update as it does not introduce new functionality but improves compatibility.
> Enhance `StrategyFactory` with `Serializable` Interface  

- src/main/java/com/verlumen/tradestream/backtesting/GenotypeConverter.java
This change updates the `GenotypeConverter` interface by making it extend `Serializable`. This modification ensures that implementations of `GenotypeConverter` can be serialized, which may be necessary for distributed processing, caching, or persistence.  
- Updated `GenotypeConverter` to implement `Serializable`.  
- No functional changes; this is purely a structural improvement for future compatibility.  
This change enhances the flexibility of `GenotypeConverter` in scenarios requiring serialization.
> Add `Serializable` to `GenotypeConverter` interface for compatibility  

- src/main/java/com/verlumen/tradestream/kafka/KafkaProducerProvider.java
This PR removes an unused import statement for `KafkaProperties` in `KafkaProducerProvider.java`. The import was unnecessary and has been cleaned up to improve code readability and maintainability. No functional changes were made.
> Remove unused import in `KafkaProducerProvider`  

- src/main/java/com/verlumen/tradestream/kafka/BUILD
- src/main/java/com/verlumen/tradestream/kafka/KafkaModule.java
- src/main/java/com/verlumen/tradestream/kafka/KafkaProducerSupplier.java
- src/main/java/com/verlumen/tradestream/marketdata/TradePublisherImpl.java
- src/main/java/com/verlumen/tradestream/signals/TradeSignalPublisherImpl.java
- src/test/java/com/verlumen/tradestream/marketdata/TradePublisherImplTest.java
- src/test/java/com/verlumen/tradestream/signals/TradeSignalPublisherImplTest.java
This update refactors the Kafka producer dependency to use `Supplier<KafkaProducer<String, byte[]>>` instead of direct `KafkaProducer` injection. The primary changes include:
- **Renamed** `KafkaProducerProvider` to `KafkaProducerSupplier`, implementing `Supplier<KafkaProducer<String, byte[]>>` instead of `Provider`.
- **Updated** `KafkaModule`:
- Replaced direct `KafkaProducer` binding with a `@Provides` method supplying a memoized supplier using `Suppliers.memoize()`.
- Added `//third_party:guava` dependency to support memoization.
- **Refactored** `TradePublisherImpl` and `TradeSignalPublisherImpl`:
- Changed Kafka producer field to `Supplier<KafkaProducer<String, byte[]>>`.
- Updated method calls to `kafkaProducer.get()` for lazy evaluation.
- **Updated tests** to reflect the …
> Refactor Kafka Producer to Use Supplier for Improved Caching and Dependency Management (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/StrategyStateFactoryImpl.java
- src/test/java/com/verlumen/tradestream/strategies/StrategyStateFactoryImplTest.java
This PR removes the caching mechanism for `org.ta4j.core.Strategy` instances in `StrategyStateFactoryImpl`. Specifically:
- Eliminates the `AtomicReference<org.ta4j.core.Strategy>` field.
- Removes logic related to caching and reusing strategy instances.
- Adjusts `getCurrentStrategy` to always create a new strategy instance instead of returning a cached one.
- Simplifies `selectBestStrategy` by removing logic for clearing and recreating cached strategies.
Additionally, corresponding unit tests relying on strategy caching have been removed, including:
- `testGetCurrentStrategyReturnsSameInstanceOnSubsequentCalls`
- `testUpdateRecordDoesNotChangeCurrentStrategyUntilReselect`
- `testSelectBestStrategyThrowsWhenStrategyCreationFails`
These changes streamline strategy state management by …
> Remove strategy caching for simplified state management

- src/main/java/com/verlumen/tradestream/strategies/StrategyFactories.java
This update modifies the visibility of the `StrategyFactories` class and its `ALL_FACTORIES` field:  
- **Removed `public` modifier** from `StrategyFactories`, making it package-private to enforce better encapsulation.  
- **Removed `public` modifier** from `ALL_FACTORIES`**, limiting access within the package to prevent unintended external usage.  
These changes improve encapsulation and maintainability by restricting direct access to internal strategy factory aggregation.
> Refactor `StrategyFactories` Visibility for Encapsulation  

- src/main/java/com/verlumen/tradestream/strategies/oscillators/OscillatorStrategies.java
Refactored the initialization of `ALL_FACTORIES` in `OscillatorStrategies` to use an explicit builder pattern (`ImmutableList.builder()`). This improves readability and maintainability, especially if additional factories need to be added in the future.  
- Replaced direct `ImmutableList.of(...)` instantiation with `ImmutableList.builder().add(...).build()`.  
- Ensured the code remains functionally identical while improving structure.  
No changes in behavior; this is a readability and maintainability improvement.
> Refactor oscillator strategy factory initialization for improved readability  

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/ParamConfigs.java
- src/main/java/com/verlumen/tradestream/backtesting/oscillators/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/oscillators/OscillatorParams.java
- src/main/java/com/verlumen/tradestream/backtesting/oscillators/SmaRsiParamConfig.java
- src/test/java/com/verlumen/tradestream/backtesting/oscillators/SmaRsiParamConfigTest.java
- Introduced `ParamConfigs` and `OscillatorParams` to centralize param configurations for backtesting.
- Added `oscillator_params` and `param_configs` Java libraries in the `BUILD` files.
- Implemented `OscillatorParams` to maintain an immutable list of all oscillator-based parameter configurations.
- Refactored `SmaRsiParamConfig`:
- Added a static factory method `create()` to enforce immutability.
- Made the constructor private to prevent direct instantiation.
- Updated `SmaRsiParamConfigTest` to use `SmaRsiParamConfig.create()`.
These changes improve code organization, enhance immutability, and simplify the integration of new oscillator-based configurations.
> Add centralized oscillator param configurations and factory method for SmaRsiParamConfig

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestingModule.java
- **Added Dependencies:**  
- Included `//third_party:guava` in `BUILD` file to support the use of `ImmutableList`.  
- Added `param_config` and `param_configs` dependencies.  
- **Updated `BacktestingModule`:**  
- Imported `ImmutableList` from Guava.  
- Used Guice’s `TypeLiteral` to bind `ImmutableList<ParamConfig>` to `ParamConfigs.ALL_CONFIGS`.  
These changes enhance dependency management and improve configuration binding for backtesting.
> Add Guava dependency and bind ParamConfigs in BacktestingModule

- src/main/java/com/verlumen/tradestream/pipeline/BUILD
This update modifies the OCI image base in the BUILD file, replacing `@flink_java17` with `@openjdk_java`. The change ensures compatibility with OpenJDK instead of the previously used Flink-specific Java runtime. 
- Updated the `oci_image` rule to use `@openjdk_java` as the base.
- Maintains the same entry point configuration.
This update may impact runtime behavior depending on differences between Flink's Java distribution and OpenJDK. Reviewers should verify compatibility with the application’s dependencies.
> Update OCI image base from Flink Java 17 to OpenJDK

- patches/java/conf/services/BUILD
- patches/java/conf/services/java.util.random.RandomGenerator
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml
This PR introduces a new configuration for Java's `RandomGenerator` service and updates the build and runtime settings accordingly.
- **Added `RandomGenerator` service file**  
- Created `patches/java/conf/services/BUILD` to export the `java.util.random.RandomGenerator` service file.  
- Defined supported random generator implementations in `patches/java/conf/services/java.util.random.RandomGenerator`.
- **Updated `BUILD` file for the pipeline**  
- Added JVM flag `-Djava.util.random.provider=java.util.Random` to explicitly set the random provider in `java_binary` and `oci_image` entrypoint.
- Introduced `filegroup` (`random_generator_patch`) to include the `RandomGenerator` configuration in the workspace.
- Created a `tar` rule (`patch_layer`) to package the service configuration for …
> Add RandomGenerator service configuration and update JVM random provider settings

- src/main/java/com/verlumen/tradestream/backtesting/GAConstants.java
- src/main/java/com/verlumen/tradestream/backtesting/GAEngineFactoryImpl.java
- **Refactored `GAConstants`** to include `TOURNAMENT_SIZE` for better configurability.  
- **Reordered constants** to maintain logical grouping and improve readability.  
- **Updated `GAEngineFactoryImpl`** to use `GAConstants.TOURNAMENT_SIZE` instead of a hardcoded value, improving maintainability.  
- **Removed redundant constructor visibility modifier in `GAEngineFactoryImpl`** (package-private is sufficient).  
- **Minor formatting improvements** for better code clarity.  
This change enhances flexibility and code maintainability by centralizing tournament size configuration.
> Refactor GAConstants and Improve Tournament Selector Configuration  

- .github/workflows/bazel-test.yaml
This update modifies the Bazel test step in the `.github/workflows/bazel-test.yaml` file by adding the `--experimental_ui_max_stdouterr_bytes=2097152` flag. This increases the maximum size of standard output and error logs captured by Bazel to 2MB, helping to retain more detailed logs for debugging test failures.  
Other existing test flags (`--test_output=all` and `--verbose_failures`) remain unchanged to ensure verbose output and better failure diagnostics. This change is intended to improve visibility into test failures within CI.
> Increase Bazel test output limit in GitHub Actions workflow  

- src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml
This PR updates `container-structure-test.yaml` by renaming the command test from `test` to `"Dry pipeline run"`. This improves clarity by providing a more descriptive name for the test, making it easier to understand its purpose. No functional changes were made.
> Update container-structure-test.yaml to improve test naming  

- MODULE.bazel
This change adds the `rules_kotlin` dependency (version 2.1.3) to `MODULE.bazel`. This enables Kotlin support within the Bazel build system. No other dependencies were modified.
**Changes:**
- Added `rules_kotlin` version 2.1.3 to `MODULE.bazel`.
**Context:**
This update is necessary for projects that require Kotlin support in Bazel builds. The addition does not affect existing dependencies or configurations.
> Add `rules_kotlin` dependency to `MODULE.bazel`

- charts/tradestream/values.yaml
This update modifies `values.yaml` in the `tradestream` Helm chart to include custom Java options for both the JobManager and TaskManager. Specifically, it sets the default random generator for Jenetics to `Random`, ensuring deterministic behavior in Flink-based workloads.  
- Added `env.java.opts.jobmanager` with `-Dio.jenetics.util.defaultRandomGenerator=Random`  
- Added `env.java.opts.taskmanager` with `-Dio.jenetics.util.defaultRandomGenerator=Random`  
These changes help control randomness in genetic algorithm operations, improving reproducibility and debugging.
> Add custom random generator setting for JobManager and TaskManager in Tradestream  

- MODULE.bazel
This PR updates the `rules_oci` Bazel dependency from version `2.0.1` to `2.2.3` in `MODULE.bazel`. 
- Bumped `rules_oci` from `2.0.1` to `2.2.3`.
- Ensures compatibility with the latest features and fixes in `rules_oci`.
- Potential improvements in performance, security, or stability.
No other dependencies were modified, and Java toolchain settings remain unchanged.
> Update `rules_oci` Bazel dependency to v2.2.3

- src/main/java/com/verlumen/tradestream/backtesting/trendfollowing/TrendFollowingParams.kt
This update populates `TrendFollowingParams.allConfigs` with a predefined parameter configuration by adding `IchimokuCloudParamConfig.create()`. Previously, the list was empty. This change enables support for the Ichimoku Cloud strategy within the trend-following backtesting module.
No version bump label is required, as this is a patch-level update that does not introduce new public API surface or behavior changes.
> Add Ichimoku Cloud configuration to TrendFollowingParams

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategyConstants.kt
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/ParamConfigsTest.java
- Introduced a new Kotlin source file `StrategyConstants.kt` containing a constant set of supported `StrategyType` values.
- Added a corresponding `kt_jvm_library` target `strategy_constants` to the `strategies/BUILD` file.
- Created a new test `ParamConfigsTest.java` to validate that supported strategy types are associated with non-null parameter configurations.
- Registered the test via a new `java_test` target in the `backtesting/BUILD` file.
This change introduces shared strategy-related constants in Kotlin, enabling safer and centralized validation logic across the codebase. The `ParamConfigsTest` ensures that for each supported strategy type, there exists a corresponding configuration, reinforcing correctness in strategy registration and parameter binding.
**Label:** (MINOR) — …
> Add `StrategyConstants` Kotlin library and test coverage for strategy-specific param configs (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/OptimizeEachStrategyDoFn.java
- src/main/java/com/verlumen/tradestream/strategies/OptimizeStrategies.java
- src/main/java/com/verlumen/tradestream/strategies/OptimizeStrategiesIsolated.java
- src/main/java/com/verlumen/tradestream/strategies/SplitByStrategyType.java
- src/main/java/com/verlumen/tradestream/strategies/StrategyProcessingRequest.kt
This PR introduces a new pipeline mode for optimizing strategies in isolation, enabling finer control and modular processing of each strategy type. Key additions include:
- **New pipeline components:**
- `OptimizeEachStrategyDoFn`: A stateful Beam `DoFn` that processes individual `StrategyProcessingRequest` records, optimizes a single strategy type, and updates shared `StrategyState`.
- `SplitByStrategyType`: A transform that splits incoming candle lists into separate processing requests per `StrategyType`.
- `OptimizeStrategiesIsolated`: A composite transform that uses the above components to run isolated optimization pipelines.
- **Supporting classes and changes:**
- Added `StrategyProcessingRequest.kt` as a Kotlin data class to carry strategy type and associated candle data.
- Updated …
> Add support for isolated strategy optimization via per-strategy splitting and processing (MINOR)

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/CoinMarketCapConfig.java
This change refactors `CoinMarketCapConfig` to use a Java record instead of an AutoValue class. As a result, the AutoValue dependency is removed from the corresponding Bazel `BUILD` target.
- Replaced `@AutoValue`-based implementation of `CoinMarketCapConfig` with a Java record.
- Updated the `create()` method to construct a new record instance.
- Removed the `//third_party:auto_value` dependency from the `coin_market_cap_config` target in the Bazel `BUILD` file.
This update simplifies the code by leveraging Java's native record feature for immutable data structures and reduces the need for external dependencies.
> Migrate `CoinMarketCapConfig` to Java record, remove AutoValue dependency

- src/main/java/com/verlumen/tradestream/pipeline/PipelineConfig.java
This patch increases the default `allowedTimestampSkew` in `PipelineConfig` from 15 minutes to 30 minutes. The change is applied by replacing the `FIFTEEN_MINUTES` constant with a new `THIRTY_MINUTES` constant set to `Duration.standardMinutes(30)`.
This adjustment may impact how late-arriving events are handled in the pipeline, potentially increasing tolerance for out-of-order or delayed data.
> Update default allowed timestamp skew to 30 minutes

- src/main/java/com/verlumen/tradestream/ingestion/BUILD
- src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java
- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/CoinbaseStreamingClient.java
- src/main/java/com/verlumen/tradestream/marketdata/ExchangeStreamingClient.java
- src/main/java/com/verlumen/tradestream/marketdata/ExchangeStreamingClientFactory.java
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataConfig.java
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
- src/test/java/com/verlumen/tradestream/ingestion/BUILD
- src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/CoinbaseStreamingClientTest.java
This change reorganizes the `ExchangeStreamingClient`, its factory, and related implementations and tests by relocating them from the `ingestion` package to the `marketdata` package. This aligns the code structure with logical module responsibilities and improves separation of concerns between ingestion and market data handling.
- **Moved Classes:**
- `ExchangeStreamingClient`, `ExchangeStreamingClientFactory`, `CoinbaseStreamingClient`, and their corresponding tests were moved from `ingestion` to `marketdata`.
- **BUILD File Updates:**
- Removed associated targets from `ingestion/BUILD` and added them to `marketdata/BUILD`.
- Updated test dependencies and package paths accordingly.
- **Dependency Injection Adjustments:**
- Updated `IngestionModule` to rely on `MarketDataModule` for …
> (MINOR) Move exchange streaming client components to marketdata package

- src/main/java/com/verlumen/tradestream/strategies/StrategyConstants.kt
- src/test/java/com/verlumen/tradestream/strategies/OptimizeStrategiesTest.java
- **Added** `StrategyType.ADX_STOCHASTIC` to `supportedStrategyTypes` in `StrategyConstants.kt`, enabling support for the ADX Stochastic strategy.
- **Updated** unit tests in `OptimizeStrategiesTest.java`:
- Modified assertions in `expand_nonEmptyCandleList_callsOrchestratorAndOutputsState` and `expand_multipleStrategies_callsOrchestratorForEachStrategy` to verify that `StrategyType.ADX_STOCHASTIC` is being used correctly.
- This change introduces a new strategy type to the system, expanding available trading strategies. The corresponding tests ensure that the orchestrator is properly handling the new strategy.
- Marked as a **minor** version update due to the addition of new functionality.
> (MINOR) Add ADX Stochastic Strategy Support

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
This PR updates the `BUILD` file in the `marketdata` module with the following changes:  
- Corrected indentation and aligned dependencies consistently across all `java_library` and `kt_jvm_library` targets.  
- Reordered dependencies for `candle_stream_with_defaults` to maintain a logical order.  
- Removed unnecessary blank lines between target definitions.  
These changes improve the readability and maintainability of the `BUILD` file without introducing any functional changes.
> Format and reorder dependencies in marketdata BUILD file  

- charts/tradestream/templates/pipeline.yaml
- Updated `charts/tradestream/templates/pipeline.yaml` to inject the `COINMARKETCAP_API_KEY` as an environment variable in the `flink-main-container`.  
- The API key is retrieved from the `coinmarketcap` secret under the `apiKey` key.  
- This change introduces a new environment variable required for accessing the CoinMarketCap API.  
- Ensures that the Flink container has the necessary credentials to communicate with the API for relevant data operations.  
- Marked as a **minor** version update since it introduces new functionality without breaking existing behavior.
> (MINOR) Add CoinMarketCap API key as environment variable in Flink container  

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/TradeSource.java
- **Added `TradeSource.java`**  
- Introduced an abstract class `TradeSource` that extends `PTransform<PBegin, PCollection<Trade>>`.
- This class is designed to act as a base class for creating Beam sources for trade data.
- **Updated `BUILD` file**  
- Added a new `java_library` target named `trade_source`.
- Included `TradeSource.java` in the `srcs` list.
- Added the necessary dependencies:
- `//protos:marketdata_java_proto`
- `//third_party:beam_sdks_java_core`
This change introduces a foundational class for integrating trade data as a Beam source, enabling further extensions and data ingestion capabilities. The new build target ensures that the source can be compiled and utilized effectively in future pipelines.
Since this PR introduces a new class and functionality, it qualifies as a …
> (MINOR) Add `TradeSource` class and corresponding build target

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientTradeSource.java
- Added a new Java class `ExchangeClientTradeSource` in `src/main/java/com/verlumen/tradestream/marketdata/`.
- Extends `TradeSource` and uses `ExchangeClientUnboundedSource` to read trade data.
- Applies `Read.from(source)` to read trades directly from the exchange.
- Updated `BUILD` file to include a new `java_library` target named `exchange_client_trade_source`.
- Added dependencies for Guice, Beam SDK, trade parsing, and Kafka transform.
This change introduces a new trade source to support reading trade data from an exchange using an unbounded source. The addition allows for seamless integration of exchange data into the pipeline.
- Added dependencies to `BUILD` file:
- `exchange_client_unbounded_source`
- `trade_source`
- `protos:marketdata_java_proto`
- `kafka_read_transform`
- Beam …
> (MINOR) Add `ExchangeClientTradeSource` to read trades from exchange using unbounded source

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/DryRunTradeSource.java
- Added a new `DryRunTradeSource` class to simulate trade data for testing and dry-run purposes.
- Defined `DryRunTradeSource` as an `AutoValue` class extending `TradeSource`, applying a list of trades using `Create.of()`.
- Registered the new `dry_run_trade_source` Java library in the `BUILD` file, including necessary dependencies:
- `:trade_source`
- `//protos:marketdata_java_proto`
- `//third_party:auto_value`
- `//third_party:beam_sdks_java_core`
- `//third_party:guava`
- This change introduces functionality to create and apply simulated trade data, which can be useful for testing pipeline behavior without relying on real market data.
- The new library ensures seamless integration with the existing pipeline infrastructure.
- No breaking changes introduced.
- Adds new functionality, …
> (MINOR) Add DryRunTradeSource for Simulated Trade Data in Market Data Pipeline

- src/main/java/com/verlumen/tradestream/marketdata/KafkaTradeSource.java
- Removed the unused `Pipeline` parameter from the `KafkaTradeSource` constructor.
- Updated the constructor signature to exclude `Pipeline` and modified the class to reflect this change.
- Cleaned up the unnecessary import of `Pipeline`.
This change simplifies the `KafkaTradeSource` constructor by removing a redundant dependency that was not being utilized. This enhances code maintainability and reduces unnecessary coupling.
No functional impact is expected as the `Pipeline` was not being used.
> Remove Unused Pipeline Dependency from KafkaTradeSource Constructor

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataConfig.java
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
- Removed `MarketDataConfig.java` and its associated `market_data_config` target from the build.
- Refactored `MarketDataModule` to eliminate the use of `MarketDataConfig` and replaced it with direct usage of `exchangeName` and `tradeTopic` parameters.
- Updated provider methods in `MarketDataModule` to use `exchangeName` and `tradeTopic` directly.
- `MarketDataConfig` was an unnecessary abstraction, as the configuration values can be passed directly to `MarketDataModule`. This change simplifies the module's structure and improves maintainability.
- The `BUILD` file was updated to remove the `market_data_config` target and its dependencies.
- This change is backward-compatible and does not affect external APIs.
- The module now directly references the configuration parameters, which …
> (MINOR) Remove `MarketDataConfig` and refactor `MarketDataModule` to directly use configuration parameters

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
- **Protobuf Integration:**
- Updated `BUILD` file to include new dependencies:
- `//protos:marketdata_java_proto`
- `//third_party:protobuf_java_util`
- **MarketDataModule Enhancements:**
- Imported `Timestamps.fromMillis` from `com.google.protobuf.util`.
- Added a `DRY_RUN_TRADE` constant to simulate a dry run trade for testing and validation purposes.
- `DRY_RUN_TRADE` includes mock trade data with a preset timestamp, price, and volume.
- These changes introduce Protobuf support to enable serialization and deserialization of market data.
- The addition of `DRY_RUN_TRADE` provides a default trade for testing and validation, helping ensure the correctness of downstream processing.
- Minimal risk; backward compatible with existing functionality.
- New Protobuf dependencies are required …
> Add Protobuf Support and Introduce Dry Run Trade in MarketDataModule

- src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
- **MarketDataModule**:  
- Updated the `create()` method to include a new `RunMode` parameter.
- Added `runMode()` as an abstract method to support the new parameter.
- **IngestionModule**:  
- Refactored the `MarketDataModule.create()` call by extracting it into a separate method `marketDataModule()`.
- Passed `RunMode` from `ingestionConfig()` to the newly modified `MarketDataModule.create()` method.
- **BUILD File**:  
- Updated the `BUILD` file to include a new dependency on `//src/main/java/com/verlumen/tradestream/execution:run_mode`.
This change introduces support for `RunMode` to control different execution modes in `MarketDataModule`, enhancing configuration flexibility during ingestion.
- No breaking changes; the refactored module injection and additional `RunMode` parameter …
> (MINOR) Add run mode configuration to MarketDataModule and IngestionModule

- src/main/java/com/verlumen/tradestream/pipeline/App.java
This PR introduces new configuration options and enhancements to the `App` class in the `tradestream` pipeline:  
- Added support for CoinMarketCap API by introducing two new options:  
- `getCoinMarketCapApiKey()`: Retrieves the API key, defaulting to the value from the `COINMARKETCAP_API_KEY` environment variable if not provided.
- `getCoinMarketCapTopCurrencyCount()`: Specifies the number of top cryptocurrencies to track, with a default value of 10.
- Introduced a new configuration option:  
- `getExchangeName()`: Defines the exchange name, defaulting to `coinbase`.
- Reordered and grouped `Options` methods for improved readability.
These changes enhance the pipeline by enabling external data integration and providing more flexibility for configuring the trade and signal processing …
> (MINOR) Add CoinMarketCap API support and exchange name configuration 

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/PipelineConfig.java
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
- src/main/java/com/verlumen/tradestream/pipeline/TimingConfig.java
- **Refactored Timing Logic:** Moved timing-related fields (`allowedLateness`, `windowDuration`, and `allowedTimestampSkew`) from `PipelineConfig` to a new `TimingConfig` class.
- **Updated Constructor:** Updated `App` to accept `TimingConfig` instead of `PipelineConfig` for timing parameters.
- **Created New `TimingConfig` Class:**
- Introduced `TimingConfig` with default values (`FIVE_SECONDS`, `ONE_MINUTE`, `THIRTY_MINUTES`).
- Added `create()` method to instantiate `TimingConfig` with these defaults.
- **Updated Dependency Configurations:**
- Added `timing_config` as a new `java_library` in `BUILD` file.
- Updated `PipelineModule` to provide `TimingConfig` via Dagger.
- Removed `joda_time` dependency from `pipeline_config` since it's now included in `timing_config`.
- **App.java:** …
> Refactor Timing Configuration by Extracting `TimingConfig` from `PipelineConfig` (MINOR)

- src/main/java/com/verlumen/tradestream/pipeline/App.java
This PR refactors the `App` class to consolidate the timing-related configuration (`allowedLateness`, `allowedTimestampSkew`, and `windowDuration`) into a single `TimingConfig` class. 
- Removed individual `Duration` fields (`allowedLateness`, `allowedTimestampSkew`, and `windowDuration`) from `App.java`.
- Introduced a new `timingConfig` field, injected via the constructor.
- Updated references to timing configurations in the `buildPipeline` method to use `timingConfig` directly.
- Simplified logging and configuration by encapsulating all timing-related logic in `TimingConfig`.
This refactor improves maintainability and reduces redundancy by centralizing timing configuration in `TimingConfig`. This change will make it easier to modify timing settings in the future.
No functionality …
> Refactor: Consolidate Timing Configuration into `TimingConfig` Class

- src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedSourceImpl.kt
This PR enhances the `ExchangeClientUnboundedSourceImpl` by introducing a serializable provider for the reader factory and ensuring the correct initialization of transient fields upon deserialization.
- **Serializable Implementation:**  
- Marked `ExchangeClientUnboundedSourceImpl` as `Serializable` to allow proper object serialization.
- Declared `readerFactory` as `@Transient` to prevent serialization issues.
- **Reader Factory Initialization:**  
- Added `ensureReaderFactoryInitialized()` to initialize `readerFactory` from the provider when necessary.
- Updated `createReader()` to invoke the initialization method before creating a reader.
- **Deserialization Handling:**  
- Added `readObject()` method to reinitialize transient fields after deserialization.
- Added appropriate logging …
> (MINOR) Improve ExchangeClientUnboundedSourceImpl with Serializable Factory and Reader Initialization

- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
]#### Summary
- Refactored `provideTradeSource` method in `MarketDataModule.java` to use a `switch` statement for handling `RunMode` values.
- Replaced the previous `if` condition that checked for `RunMode.DRY` with a `switch` block that:
- Returns `DryRunTradeSource` for `DRY` mode.
- Returns `exchangeClientTradeSource` for `WET` mode.
- Throws an `UnsupportedOperationException` for any unsupported mode.
- This change improves code readability and maintainability by making the run mode handling more explicit and robust.
- No changes to functionality, only structural improvements.
> Refactor trade source initialization with switch statement for run modes

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- Introduced a new method `getCmcApiKey(Options options)` to retrieve the CoinMarketCap (CMC) API key.
- The method checks if the API key is provided in the `options` object. If the value is null or empty, it falls back to the `CMC_API_KEY_ENV_VAR` environment variable.
- Updated the `PipelineModule.create()` method in `main()` to use the new `getCmcApiKey` method.
- Added `isNullOrEmpty` import from `com.google.common.base.Strings` to validate API key presence.
- This change ensures that the application gracefully falls back to an environment variable when the API key is not explicitly provided via options.
- Improves robustness by preventing invalid API key scenarios and provides a default value of `"INVALID_API_KEY"` if neither source is available.
> Add fallback mechanism for CMC API key from environment variables

- src/main/java/com/verlumen/tradestream/instruments/CurrencyPairSupply.java
- Updated `CurrencyPairSupply` interface to extend `Serializable` in addition to `Supplier<ImmutableList<CurrencyPair>>`.
- Ensures that implementations of `CurrencyPairSupply` can be serialized, improving compatibility with distributed systems and caching mechanisms.
- This change is beneficial when instances of `CurrencyPairSupply` need to be transmitted or stored in a serialized form.
- No breaking changes expected, as this addition only enhances the interface's functionality.
> Add Serializable to CurrencyPairSupply interface (MINOR)

- src/main/java/com/verlumen/tradestream/instruments/BUILD
- src/main/java/com/verlumen/tradestream/instruments/CurrencyPairSupply.java
- src/main/java/com/verlumen/tradestream/instruments/InstrumentsModule.java
- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedReader.kt
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedSourceImplTest.java
This PR refactors the `CurrencyPairSupply` interface to simplify its implementation by removing the default method `currencyPairs()` and directly relying on the `Supplier<ImmutableList<CurrencyPair>>` interface.
1. **Refactored `CurrencyPairSupply`:**
- Removed the `currencyPairs()` method and retained only the `Supplier` interface, simplifying the class structure.
2. **Updated Dependency Injection:**
- Modified `InstrumentsModule` to provide `Supplier<ImmutableList<CurrencyPair>>` via `CurrencyPairSupplyProvider`.
- Adjusted binding in `InstrumentsModule` to replace the use of `CurrencyPairSupply` with `Supplier<ImmutableList<CurrencyPair>>`.
3. **Updated `ExchangeClientUnboundedReader`:**
- Replaced all instances of `CurrencyPairSupply` with `Supplier<ImmutableList<CurrencyPair>>` in …
> Refactor `CurrencyPairSupply` to Use `Supplier` Interface and Simplify Dependency Injection

- src/main/java/com/verlumen/tradestream/instruments/BUILD
- src/main/java/com/verlumen/tradestream/instruments/InstrumentsModule.java
- Added a caching mechanism for the `CurrencyPair` supplier using `Suppliers.memoizeWithExpiration`, with a 1-day expiration interval.
- Introduced a constant `INSTRUMENT_REFRESH_INTERVAL` set to `Duration.ofDays(1)`.
- Updated `provideCurrencyPairSupplier` to use the memoized supplier to reduce redundant calls and improve performance.
- Marked the supplier provider with `@Singleton` to ensure a single instance is used.
- This change optimizes performance by caching the result of `CurrencyPairSupplyProvider` for 24 hours, reducing unnecessary calls to external APIs or data sources.
- No breaking changes introduced; the behavior of the module remains consistent aside from the improved efficiency.
- Marked as (MINOR) because the update introduces new functionality (caching) without …
> (MINOR) Add caching mechanism for currency pair supplier with 1-day expiration

- src/main/java/com/verlumen/tradestream/instruments/CurrencyPairMetadata.java
- Updated `CurrencyPairMetadata` to implement `Serializable` to enable object serialization.
- This change allows instances of `CurrencyPairMetadata` to be serialized and deserialized when necessary, ensuring compatibility with systems that require object persistence or transmission.
- `CurrencyPairMetadata` now explicitly implements `Serializable`, which is often essential for distributing or persisting objects in distributed systems.
- No changes were made to the core functionality or structure of the class beyond the implementation of `Serializable`.
- Adding `Serializable` ensures that `CurrencyPairMetadata` can be safely serialized, which is a common requirement in trading systems or services that rely on object transmission or persistence.
- No breaking changes expected.
- …
> Add Serializable to CurrencyPairMetadata for object serialization

- src/main/java/com/verlumen/tradestream/instruments/BUILD
- src/main/java/com/verlumen/tradestream/instruments/Currency.java
- src/main/java/com/verlumen/tradestream/instruments/CurrencyPair.java
- Migrated `Currency` and `CurrencyPair` classes to use Java records, replacing the previous `@AutoValue` implementation.
- Removed `AutoValue` dependency and related annotations.
- Updated `Currency.java`:
- Converted to a record implementing `Serializable`.
- Simplified the `create` method to directly return a `Currency` instance.
- Removed `symbol()` method, as records automatically generate accessor methods.
- Updated `CurrencyPair.java`:
- Converted to a record implementing `Serializable`.
- Simplified the `fromSymbol` method to instantiate `CurrencyPair` directly.
- Removed `base()` and `counter()` methods, as records automatically provide these.
- Updated `BUILD` file:
- Removed `auto_value` dependency from both `currency` and `currency_pair` targets.
- Migrating to Java records …
> (MINOR) Migrate `Currency` and `CurrencyPair` to Java Records and Remove AutoValue Dependency

- src/main/java/com/verlumen/tradestream/marketdata/ExchangeStreamingClient.java
- Updated `ExchangeStreamingClient` interface to extend `Serializable` to ensure compatibility with object serialization.
- This change allows instances of `ExchangeStreamingClient` to be serialized, which may be required for distributed systems or caching frameworks.
- Adding `Serializable` provides greater flexibility for handling instances of the interface, especially when transmitting objects or persisting state.
- No breaking changes introduced, as this modification only enhances the existing functionality.
- Affects `ExchangeStreamingClient.java` in the `marketdata` package.
- Marked as (MINOR) due to the introduction of enhanced functionality without altering existing behavior.
> Add Serializable to ExchangeStreamingClient interface (MINOR)

- src/main/java/com/verlumen/tradestream/marketdata/CoinbaseStreamingClient.java
- Updated the `WebSocketConnector` class in `CoinbaseStreamingClient.java` to implement `Serializable`.
- This change allows instances of `WebSocketConnector` to be serialized, which is useful for scenarios where object persistence or transmission is required.
- Implementing `Serializable` ensures that the `WebSocketConnector` can be stored or transferred reliably.
- No changes were made to the behavior or functionality of the class, maintaining compatibility with existing WebSocket operations.
> Add `Serializable` to `WebSocketConnector` for serialization support

- src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedSourceImpl.kt
- Implemented `writeObject` and `readObject` methods to customize serialization and deserialization for `ExchangeClientUnboundedSourceImpl`.  
- `writeObject(ObjectOutputStream)` and `readObject(ObjectInputStream)` use default serialization to handle object state.  
- Ensured that the class remains serializable by adhering to the Java serialization protocol.  
These changes improve the robustness of object serialization for `ExchangeClientUnboundedSourceImpl`, ensuring that object state is properly maintained during serialization and deserialization. This is essential for distributed processing scenarios where the object might be transmitted across different nodes.  
No version bump required, as this is a patch-level change.
> Add custom serialization methods to ExchangeClientUnboundedSourceImpl  

- src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedReader.kt
- src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedSourceImpl.kt
- Added `Serializable` interface to `ExchangeClientUnboundedReader` to allow object serialization.
- Implemented `writeObject` and `readObject` methods to manage serialization and deserialization.
- Ensured `incomingMessagesQueue` is cleared and repopulated correctly during deserialization to prevent inconsistencies.
- Declared `ExchangeClientUnboundedReader` as `Serializable` by adding `implements Serializable`.
- Added `writeObject()` and `readObject()` methods for custom serialization logic.
- Added logic in `readObject()` to ensure `incomingMessagesQueue` is properly handled after deserialization.
These changes enable the object to be serialized, which is required for scenarios where the reader instance needs to be persisted or transferred. Proper queue handling prevents potential …
> (MINOR) Add Serializable Implementation to ExchangeClientUnboundedReader

- src/main/java/com/verlumen/tradestream/pipeline/TimingConfig.java
This PR updates the default duration values in `TimingConfig.java` to reduce the timing thresholds:  
- `allowedLateness` duration is decreased from **5 seconds** to **2 seconds**.  
- `allowedTimestampSkew` duration is decreased from **30 minutes** to **2 minutes**.  
These adjustments aim to improve responsiveness and reduce delays in the trade stream pipeline by tightening the allowed timing window.  
No functional changes beyond the timing adjustments are introduced.
> Reduce TimingConfig Duration for Allowed Lateness and Timestamp Skew 

- src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
This pull request removes unused imports from the `CandleStreamWithDefaults.java` file, including:
- `java.util.Arrays`
- `org.apache.beam.sdk.transforms.windowing.AfterProcessingTime`
- `org.apache.beam.sdk.transforms.windowing.Repeatedly`
These imports were not utilized in the current implementation, and their removal helps maintain cleaner and more efficient code. This change is purely a cleanup with no impact on functionality.
> Remove unused imports in `CandleStreamWithDefaults.java`

- charts/tradestream/templates/pipeline.yaml
This pull request updates the Flink pipeline configuration in `pipeline.yaml` to ensure that Flink uses a writable directory for its temporary I/O operations. The changes include:
- Setting `io.tmp.dirs` to `/opt/flink/writable-tmp` in the `flinkConfiguration` section.
- Adding the `TMPDIR` environment variable to point to `/opt/flink/writable-tmp` in the main container configuration.
- Explicitly marking the volume mount `/opt/flink/writable-tmp` as writable (`readOnly: false`).
These changes ensure that Flink can perform temporary I/O operations in a writable directory, improving stability and preventing potential file system permission issues.
> Add writable directory configuration for Flink I/O temp in pipeline.yaml

- src/main/java/com/verlumen/tradestream/instruments/CurrencyPairSupplyProvider.java
- **Summary:**  
The `Gson` dependency was removed from `CurrencyPairSupplyProvider` as it was no longer used in the class.  
- Updated the constructor to remove the `Gson` parameter.
- Cleaned up unused import statements in `CurrencyPairSupplyProvider.java`.
- **Context:**  
This change simplifies the class by eliminating an unnecessary dependency, improving maintainability and reducing the risk of potential errors from unused components.
- **Testing:**  
- Verified that the application builds successfully.
- Ensured that all existing unit and integration tests pass without modification.
No version bump required as this is a minor cleanup.
> Remove unused Gson dependency from CurrencyPairSupplyProvider

- src/main/java/com/verlumen/tradestream/instruments/CurrencyPairSupplier.kt
- src/main/java/com/verlumen/tradestream/instruments/InstrumentsModule.java
This patch resolves a type mismatch issue by replacing Java's `java.util.function.Supplier` with Guava's `com.google.common.base.Supplier` in `CurrencyPairSupplier`. The change ensures compatibility with the `Suppliers.memoizeWithExpiration` utility in `InstrumentsModule`, which expects a Guava `Supplier`.
**Summary of changes:**
- Replaced `java.util.function.Supplier` with Guava's `Supplier` in `CurrencyPairSupplier`.
- Adjusted the class signature to use `@JvmSuppressWildcards` to avoid Kotlin-Java wildcard issues.
- Updated the `InstrumentsModule` binding to pass the supplier instance directly, now compatible with Guava's memoization API.
No new functionality was introduced, so this qualifies as a patch-level change.
> Fix type incompatibility in Guice provider by switching to Guava's `Supplier`

- src/main/java/com/verlumen/tradestream/instruments/CoinMarketCapConfig.java
This change modifies the `CoinMarketCapConfig` record to implement `Serializable`. This is necessary to support scenarios where the configuration needs to be serialized—for example, when caching or distributing configuration objects across JVM boundaries.
- Added `implements Serializable` to the `CoinMarketCapConfig` record.
- Added the necessary `import java.io.Serializable`.
No behavior or logic changes were introduced. This update ensures compatibility with systems or libraries that require serialization of configuration objects.
> Implement `Serializable` for `CoinMarketCapConfig` record

- src/main/java/com/verlumen/tradestream/http/HttpClient.java
This change updates the `HttpClient` interface to extend `Serializable`. This allows implementations of `HttpClient` to be safely serialized, which is often required for distributed systems, caching, or session persistence mechanisms.
No changes were made to the interface methods; this is a structural update to support broader use cases such as Java serialization and compatibility with frameworks that require serializable dependencies.
> Make `HttpClient` Interface Serializable

- src/main/java/com/verlumen/tradestream/instruments/BUILD
- src/main/java/com/verlumen/tradestream/instruments/InstrumentsModule.java
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
This change updates the `InstrumentsModule` to accept `RunMode` as a constructor parameter. This allows environment-specific logic within the module, specifically:
- When `RunMode.DRY` is active, the module returns a stubbed currency pair (`DRY/RUN`) instead of querying real data.
- The module is now instantiated with `runMode` in `PipelineModule`, aligning it with other environment-sensitive modules.
- Updated the `BUILD` file to include the `run_mode` dependency.
This refactor improves testability and supports safer dry runs or sandboxed environments.
> Inject `RunMode` into `InstrumentsModule` to enable environment-specific behavior

- src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/test/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaultsTest.java
This change refactors the `CandleStreamWithDefaults` transform to accept a `Supplier<List<String>>` for the `currencyPairs` parameter instead of a direct list. This provides greater flexibility for deferred or dynamic evaluation of currency pairs at pipeline execution time.
- Updated the constructor of `CandleStreamWithDefaults` to accept a `Supplier<List<String>>`.
- Replaced direct list usage in the transform with a `.get()` invocation.
- Updated instantiations in `App.java` and unit tests to use `Suppliers.ofInstance(...)` for consistent behavior.
This is a non-breaking internal refactor aimed at improving configurability and aligning with lazy evaluation patterns. No behavioral changes to the transform logic or output.
_No version label is needed; this is a patch-level update._
> Refactor CandleStreamWithDefaults to Use Supplier for Currency Pairs

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaultsTest.java
This change replaces the use of raw `String` symbols for currency pairs with strongly-typed `CurrencyPair` objects within the `CandleStreamWithDefaults` transform and associated test cases.
- Updated `CandleStreamWithDefaults` constructor to accept `Supplier<List<CurrencyPair>>` instead of `Supplier<List<String>>`.
- Modified pipeline logic to extract currency pair symbols via `CurrencyPair::symbol` before creating keys.
- Updated test code to construct `CurrencyPair` instances using `CurrencyPair.fromSymbol(...)`.
- Adjusted Bazel build targets to include the `currency_pair` dependency.
This refactor improves type safety and consistency when handling currency pair data across the system.
(MINOR) – Introduces a backward-compatible improvement by using a dedicated data structure.
> Refactor CandleStreamWithDefaults to use `CurrencyPair` objects instead of raw strings

- .github/workflows/bazel-test.yaml
This PR updates the GitHub Actions workflow for Bazel testing by upgrading the `bazel-contrib/setup-bazel` action from version `0.9.1` to `0.14.0`.  
- Ensures compatibility with newer Bazel versions and benefits from recent improvements and bug fixes in the setup-bazel action.
- No changes to the build or test logic itself; this is an infrastructure maintenance update.
> chore(ci): update Bazel setup action to v0.14.0

- .github/workflows/bazel-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
This PR updates the Bazel configurations across GitHub Actions workflows (`bazel-test.yaml`, `ci.yaml`, and `release.yaml`) to integrate BuildBuddy remote caching and results reporting. It also improves Bazel build reliability and performance through additional build flags.
- Replaced local disk and repository cache settings with BuildBuddy remote caching integration via `.bazelrc` entries:
- Configured `--remote_cache` and `--bes_backend` with BuildBuddy endpoints.
- Enabled log and artifact uploads without remote cache writes.
- Set remote timeout and authentication header using a GitHub secret (`BUILDBUDDY_API_KEY`).
- Added Bazel build optimizations:
- `--nolegacy_important_outputs`
- `--experimental_remote_cache_compression`
- `--experimental_remote_cache_compression_threshold=100`
- …
> Integrate BuildBuddy Remote Caching and Enhance Bazel Build Settings (MINOR)

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
This PR removes the unused `CandleStreamWithDefaults` import from `App.java` and cleans up the corresponding build dependency in `BUILD`.  
No functional changes were made to the application. This is a simple cleanup to improve code hygiene and maintain an accurate build specification.
> Remove unused CandleStreamWithDefaults import and dependency

- .bazelrc
- .github/workflows/bazel-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- Enhanced `.bazelrc` with additional build and test flags for improved debugging and caching:
- Added `--verbose_failures`, `--sandbox_debug`, `--test_output=all`, `--experimental_ui_max_stdouterr_bytes`, and remote cache compression flags.
- Cleaned up GitHub Actions workflows:
- Removed redundant Bazel flags (`--verbose_failures`, `--sandbox_debug`, etc.) from `bazel-test.yaml`, `ci.yaml`, and `release.yaml` since they are now configured globally via `.bazelrc`.
- Removed obsolete Kotlin test target `TradeToCandleTest` from `marketdata/BUILD`.
These updates centralize Bazel configuration for better maintainability and simplify CI workflows by reducing duplicated flag definitions. The `TradeToCandleTest` was removed as it appears to no longer be in use or necessary.
> Improve Bazel build/test configuration and clean up obsolete test target

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml
- Integrated `TradeToCandle` transformation into the Beam pipeline to aggregate trades into 1-minute candles.
- Injected `TradeToCandle.Factory` into the `App` constructor for configurable candle creation.
- Updated the `BUILD` file to include the `trade_to_candle` target as a dependency.
- Enhanced `container-structure-test.yaml` to validate the expected log output for the new `TradeToCandle` transform.
This enhancement enables the pipeline to automatically generate and process 1-minute candlestick data from the incoming trade stream, facilitating downstream analytical operations. The change is backward-compatible and introduces new functionality, warranting a (MINOR) version increment.
> Add TradeToCandle Transform to Pipeline for 1-Minute Candle Aggregation (MINOR)

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/CandleLookbackDoFn.kt
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/CandleLookbackDoFnTest.kt
This change introduces a new Kotlin-based Beam `DoFn`, `CandleLookbackDoFn`, that buffers per-key `Candle` elements and emits lookback windows of configurable sizes upon window timer firing. The core components include:
- **`SerializableArrayDeque`**: A custom, Beam-compatible, bounded deque for managing a fixed-size buffer of serialized elements with a corresponding custom coder.
- **`CandleLookbackDoFn`**:
- Maintains per-key state for candle queues using Beam's `ValueState`.
- Supports configurable lookback sizes, emitting multiple lookbacks (e.g., last 1, 3, 5 elements) per key.
- Emits output as `KV<String, KV<Int, ImmutableList<Candle>>>` at the end of the event-time window.
- Beam build target added under `kt_jvm_library(name = "candle_lookback_do_fn")`.
Additionally, a …
> Add CandleLookbackDoFn for buffered candle lookbacks in Beam pipelines

- src/main/java/com/verlumen/tradestream/pipeline/App.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
This change introduces support for configurable candle lookback processing in the Beam pipeline, using Fibonacci-based default values approximating the number of minutes in a Gregorian year.
- **(MINOR)**: Added `getCandleLookbackSizes()` to the `Options` interface, with a default set of Fibonacci values under ~526,000 minutes.
- Integrated a new `CandleLookbackDoFn` that computes multiple candle lookbacks based on configured sizes.
- Applied fixed-windowing to the candle stream to support stateful lookback processing.
- Implemented `LogLookbacksDoFn` for logging lookback results for debugging purposes.
- Updated `buildPipeline()` and `runPipeline()` to pass and utilize pipeline options.
- Modified BUILD file to include the new `candle_lookback_do_fn` dependency.
This enhancement enables …
> Add configurable candle lookback support using Fibonacci defaults (MINOR)

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestRequestFactory.kt
This PR introduces a new Kotlin interface, `BacktestRequestFactory`, to the `backtesting` module. The interface defines a contract for constructing `BacktestRequest` instances from a list of `Candle` objects and a `Strategy`. This supports more flexible and testable backtest construction logic.
Additionally, the corresponding Bazel target `kt_jvm_library(name = "backtest_request_factory")` has been added to the `BUILD` file, with necessary dependencies on the related proto libraries.
No behavior changes were made to existing components.
> Add `BacktestRequestFactory` interface and Bazel target for backtesting module

- src/main/java/com/verlumen/tradestream/backtesting/BUILD
- src/main/java/com/verlumen/tradestream/backtesting/BacktestRequestFactoryImpl.kt
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/backtesting/BacktestRequestFactoryImplTest.kt
This PR introduces a new implementation of the `BacktestRequestFactory` interface:
- **New Kotlin class**: `BacktestRequestFactoryImpl` implements logic for constructing `BacktestRequest` objects from provided candle data and strategy configurations. It leverages the builder pattern from protobuf and includes structured logging via FluentLogger.
- **New Bazel target**: `backtest_request_factory_impl` added to the `BUILD` file for inclusion in builds.
- **Unit tests added**: `BacktestRequestFactoryImplTest` validates correct construction of requests, including cases for populated and empty candle lists.
- **Test target defined**: A new `kt_jvm_test` Bazel rule has been added to run the test.
(MINOR) version bump justified due to the introduction of a new factory implementation, which …
> Add `BacktestRequestFactoryImpl` and corresponding test for constructing backtest requests (MINOR)

- charts/tradestream/templates/checkpoint-pvc.yaml
- charts/tradestream/templates/ha-pvc.yaml
- charts/tradestream/templates/pipeline.yaml
This PR introduces support for Flink checkpointing and high availability (HA) by adding the following key changes:
- **PersistentVolumeClaims**:  
- Added `checkpoint-pvc.yaml` and `ha-pvc.yaml` templates to provision storage for Flink checkpoints and HA metadata respectively.
- **Pipeline Configuration Enhancements**:  
- Enabled Flink checkpointing with configurable intervals, timeout, and exactly-once semantics.
- Configured a filesystem-based state backend with defined directories for checkpoints and savepoints.
- Enabled resource and latency monitoring with custom probing intervals.
- Activated Kubernetes-based HA using Flink’s Kubernetes HA Services Factory, with specified leader election settings.
- **Volume Mounts**:  
- Mounted the new PVCs into the Flink container for …
> Enable Flink Checkpointing and High Availability with Persistent Volumes (MINOR)

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/CandleLookbackDoFn.kt
This patch refactors the `CandleLookbackDoFn` to improve memory management, logging, and maintainability:
* **Replaces** the custom `SerializableArrayDeque` class with Guava's `EvictingQueue` to simplify bounded queue handling.
* **Removes** the need for custom serialization and coder logic by leveraging Beam's `SerializableCoder` with `EvictingQueue`.
* **Adds** structured logging via Google Flogger for better traceability and debugging.
* **Eliminates** the use of Beam `Timer` APIs and processes lookbacks immediately upon each element arrival.
* **Cleans up** unused imports and legacy debug statements, replacing them with consistent, leveled logs.
This is a patch-level change focused on code simplification and operational observability. No new functionality or interfaces are introduced.
> Refactor CandleLookbackDoFn to use Guava EvictingQueue and Flogger for improved efficiency and logging

- src/main/java/com/verlumen/tradestream/pipeline/App.java
This patch adds support for configuring the Tiingo API key in the application. A new constant `TIINGO_API_KEY_ENV_VAR` is introduced, and the `Options` interface now includes getter and setter methods for `TiingoApiKey`, with a corresponding description and default value. A helper method `getTiingoApiKey()` was added to resolve the API key from the options or fallback to the environment variable.
> Add support for Tiingo API key via options and environment variable

- MODULE.bazel
- third_party/BUILD
This change introduces support for Kotlin-based unit testing by adding the `org.mockito.kotlin:mockito-kotlin:5.4.0` dependency to the Bazel build configuration:
* Updated `MODULE.bazel` to include the `mockito-kotlin` artifact in the Maven install list.
* Added a new `java_library` target for `mockito_kotlin` in `third_party/BUILD`, exposing the dependency for use in tests.
This prepares the codebase for future Kotlin test development or migration and ensures compatibility with Mockito in Kotlin contexts.
No (MAJOR) or (MINOR) version tag is required as this is a patch-level change.
> Add `mockito-kotlin` dependency for Kotlin-based testing

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/TiingoCryptoFetcherFn.kt
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/TiingoCryptoFetcherFnTest.kt
This change introduces a new Beam `DoFn`, `TiingoCryptoFetcherFn`, which retrieves historical cryptocurrency candle data from the Tiingo API. It accepts currency pairs as input and emits parsed `Candle` objects downstream.
* **New Kotlin Transform:**
* Implemented `TiingoCryptoFetcherFn`, a Beam `DoFn` that:
* Accepts `KV<String, Void?>` input for currency pairs.
* Constructs Tiingo API requests based on configurable granularity and API key.
* Parses the API response using existing `TiingoResponseParser`.
* Emits `KV<String, Candle>` for each parsed candle.
* Handles invalid API keys and I/O exceptions gracefully with proper logging.
* **Build File Updates:**
* Added new Bazel targets for `tiingo_crypto_fetcher_fn` and its corresponding test.
* **Unit Tests:**
* Added …
> Add `TiingoCryptoFetcherFn` for Fetching and Emitting Tiingo Crypto Candles

- BUILD
- MODULE.bazel
- src/main/java/com/verlumen/tradestream/marketdata/CandleLookbackDoFn.kt
This pull request introduces the Kotlin toolchain configuration and addresses Kotlin-specific nullability handling in a critical data processing function.
* **Toolchain Configuration:**
* Registered the Kotlin toolchain via `define_kt_toolchain` in `BUILD` with Kotlin `1.9` and `jvm_target` set to `17`.
* Updated `MODULE.bazel` to register the new Kotlin toolchain for Bazel builds.
* **Code Fixes (Kotlin Interop):**
* Updated `CandleLookbackDoFn.kt` to explicitly handle nullable `queue` values with safe calls (`queue!!`) to ensure runtime safety and proper behavior.
* Adjusted all operations on `queue` within `processElement` to use non-null assertions, indicating the assumption that state is correctly initialized before use.
These changes are necessary to enable Kotlin support in the …
> Register Kotlin toolchain and fix nullability issues in CandleLookbackDoFn

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/CandleSource.java
This PR introduces the `CandleSource` abstract class to the `marketdata` module and defines its corresponding Bazel build target.
* Created `CandleSource.java` in `src/main/java/com/verlumen/tradestream/marketdata/`.
* It extends `PTransform` to represent a Beam transform for producing `PCollection` of key-value pairs of `String` and `Candle`.
* Serves as a base class for different candle data sources.
* Updated the Bazel `BUILD` file:
* Added a new `java_library` target named `candle_source`.
* Included necessary dependencies: `marketdata_java_proto` and `beam_sdks_java_core`.
These changes lay the groundwork for integrating various streaming candle sources into the processing pipeline.
> Add CandleSource Abstract Class and Bazel Build Target

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
- src/main/java/com/verlumen/tradestream/marketdata/TiingoCryptoFetcherFn.kt
- src/test/java/com/verlumen/tradestream/marketdata/BUILD
- src/test/java/com/verlumen/tradestream/marketdata/TiingoCryptoFetcherFnTest.kt
This PR introduces the `AssistedInject` factory pattern for `TiingoCryptoFetcherFn`, enhancing dependency injection and enabling testable, modular creation of instances with different configurations.
1. **AssistedInject Integration:**
* Added `@Assisted` annotations to constructor parameters in `TiingoCryptoFetcherFn`.
* Created a `Factory` interface for assisted injection.
* Registered `FactoryModuleBuilder` in Guice modules to bind the factory.
2. **BUILD File Updates:**
* Added `guice_assistedinject` as a dependency in both main and test `BUILD` files.
3. **Test Suite Enhancements:**
* Refactored tests to utilize Guice-assisted factory injection for cleaner instantiation.
* Replaced direct instantiation with `FetcherFactory` to manage dependencies.
* Introduced `@Before` setup method …
> Add AssistedInject Factory for `TiingoCryptoFetcherFn` and Update Tests

- MODULE.bazel
- third_party/BUILD
This PR introduces several updates to the Bazel build configuration:
1. **MODULE.bazel**:
* Removed the `requirements_windows` dependency, streamlining the dependency configuration for cross-platform compatibility.
2. **third\_party/BUILD**:
* Added `py_library` targets for:
* `absl_py` → Maps to the `absl-py` PyPI package.
* `influxdb_client` → Maps to the `influxdb-client` PyPI package.
* `requests` → Maps to the `requests` PyPI package.
* Included necessary Bazel `load` statements to support `py_library` targets.
The added Python dependencies are necessary for upcoming features that require integration with `absl-py`, `influxdb-client`, and `requests`. The removal of the Windows-specific requirements file is part of a broader effort to simplify dependency management and eliminate …
> Add Python dependencies for `absl-py`, `influxdb-client`, and `requests`; remove Windows-specific requirements file

- services/candle_ingestor/BUILD
- services/candle_ingestor/main.py
- services/candle_ingestor/main_test.py
This PR introduces a **real-time polling loop** for the `candle_ingestor` service to continually fetch and process new market candles from the Tiingo API. It builds on the existing backfill logic and allows seamless transition from historical data ingestion to live market polling.
---
1. **Polling Loop Implementation (`run_polling_loop` in `main.py`):**
* Introduced a new `run_polling_loop` function that fetches new, fully-closed candles from the Tiingo API at a specified granularity.
* Integrated with `InfluxDBManager` to write new candles directly to InfluxDB.
* Polling loop intelligently tracks the last processed timestamp per ticker and aligns to granularity boundaries for efficient querying.
* Automatically initializes timestamps if backfill is skipped or incomplete using the …
> (MINOR) Add Polling Loop for Real-Time Candle Ingestion and Associated Tests

- services/candle_ingestor/influx_client.py
- services/candle_ingestor/influx_client_test.py
- services/candle_ingestor/ingestion_helpers.py
- services/candle_ingestor/main.py
- services/candle_ingestor/main_test.py
This PR introduces persistent resume functionality for both backfill and polling operations in the candle ingestor service by leveraging InfluxDB to store and retrieve the last processed timestamps for each symbol and ingestion type.
* **InfluxDBManager Enhancements:**
* Added `get_last_processed_timestamp(symbol, ingestion_type)` to query the latest processed timestamp from InfluxDB.
* Added `update_last_processed_timestamp(symbol, ingestion_type, timestamp_ms)` to persist the latest processed timestamp after successful writes.
* Improved exception handling with specific `InfluxDBError` logging.
* **Backfill Pipeline Improvements:**
* Modified `run_backfill` to initialize and incrementally update the last processed timestamp in InfluxDB.
* Ensures the backfill resumes …
> Add state tracking to InfluxDBManager and integrate persistent resume support for backfill and polling (MINOR)

- requirements.in
- requirements_lock.txt
- services/candle_ingestor/BUILD
- services/candle_ingestor/cmc_client.py
- services/candle_ingestor/influx_client.py
- services/candle_ingestor/influx_client_test.py
- services/candle_ingestor/main.py
- services/candle_ingestor/main_test.py
- services/candle_ingestor/tiingo_client.py
- third_party/BUILD
This PR introduces robust retry handling across the `candle_ingestor` service by integrating the `tenacity` library. It enhances the system’s resilience to transient failures in external dependencies such as InfluxDB and Tiingo.
* **Dependency Additions:**
* Added `tenacity==9.1.2` to `requirements.in` and `BUILD` files.
* **Retry Integration:**
* Wrapped InfluxDB operations (`connect`, `write_candles_batch`, `get_last_processed_timestamp`, `update_last_processed_timestamp`) in retry decorators with exponential backoff and exception filtering.
* Added retry logic to Tiingo API requests with custom handling of HTTP 429 (rate limiting), including support for `Retry-After` headers.
* Introduced retry-wrapped data fetcher for CMC in `cmc_client.py`.
* **Graceful Shutdown …
> Add retry logic using Tenacity for robust InfluxDB and Tiingo API interactions (MINOR)

- protos/BUILD
- protos/discovery.proto
This PR introduces a new `discovery.proto` definition along with associated Bazel build targets to support strategy discovery via optimization algorithms. Key changes include:
* **New Proto Definitions:**
* `GAConfig`: Configuration message for Genetic Algorithm-based strategy optimization.
* `StrategyDiscoveryRequest`: Request structure to initiate strategy discovery, including time range, strategy type, and optimization configuration.
* `DiscoveredStrategy`: Captures a discovered strategy instance, including score and metadata.
* `StrategyDiscoveryResult`: Response containing the list of top discovered strategies.
* **BUILD File Updates:**
* Added `discovery_proto` and `discovery_py_proto` targets.
* Declared dependencies on `strategies_proto` and the Protobuf timestamp library.
These …
> Add Discovery Proto for Strategy Optimization Requests and Results

- charts/tradestream/templates/candle-ingestor.yaml
- charts/tradestream/values.yaml
- services/candle_ingestor/BUILD
- services/candle_ingestor/container-structure-test.yaml
- services/candle_ingestor/main.py
- services/candle_ingestor/main_test.py
This PR introduces a structural and functional update to the `candle-ingestor` component:
* **Helm Chart Migration:**
* Replaces the `Deployment` resource with a `CronJob` to better suit the periodic nature of candle ingestion tasks.
* Adds support for job-specific configuration: `schedule`, `restartPolicy`, `backoffLimit`, `ttlSecondsAfterFinished`, and `args`.
* **Redis Integration (MINOR):**
* Replaces CoinMarketCap (CMC) client usage with a Redis-based approach (`RedisCryptoClient`) to fetch the top cryptocurrency symbols.
* Adds new flags and environment variables for Redis configuration (`--redis_host`, `--redis_port`, etc.).
* Adjusts the data source default to only "tiingo", reflecting the shift in symbol discovery responsibilities.
* **Flag and Env Config Enhancements:**
* Adds …
> Migrate Candle Ingestor from Deployment to CronJob and Replace CMC Client with Redis (MINOR)

- third_party/python/BUILD
This change introduces new `py_library` targets in the `third_party/python/BUILD` file to support the following dependencies:
* `kafka-python`
* `protobuf`
Both libraries are now exposed with `//visibility:public`, enabling use in other Bazel targets throughout the project. This setup facilitates dependency management and consistent builds for components relying on Kafka and Protocol Buffers.
No functional changes to application logic are introduced in this patch.
> Add Bazel targets for `kafka-python` and `protobuf` third-party dependencies

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- charts/tradestream/templates/strategy-discovery-request-factory.yaml
- charts/tradestream/values.yaml
- services/strategy_discovery_request_factory/BUILD
- services/strategy_discovery_request_factory/container-structure-test.yaml
This PR integrates the `strategy-discovery-request-factory` service into the CI/CD pipeline and Helm deployment for the `tradestream` project. Key updates include:
* **CI Workflow (`ci.yaml`):**
* Added Bazel target to build and push the service's container image.
* Pulled and tagged the image for Minikube and loaded it into the cluster.
* Verified the associated CronJob is created and not suspended.
* **Release Workflow (`release.yaml`):**
* Defined environment variables for repository and config section keys.
* Built and pushed the version-tagged image for the service.
* Updated Helm values file with the new image tag and repository.
* **Helm Chart:**
* Added a new CronJob template (`strategy-discovery-request-factory.yaml`) under `charts/tradestream/templates`.
* Enabled configuration …
> Add deployment and release pipeline support for strategy-discovery-request-factory service (MINOR)

- charts/tradestream/values.yaml
Expanded the default exchange list and set a fixed minimum exchange requirement for the candle ingestor.
> Update CCXT exchange list and raise minimum required exchanges to 3 (MINOR)

- charts/tradestream/templates/candle-ingestor.yaml
Add `--exchanges` and `--min_exchanges_required` flags to the candle ingestor Helm chart args.
> Add exchange configuration flags to candle ingestor Helm template (MINOR)

- shared/persistence/influxdb_last_processed_tracker.py
- shared/persistence/influxdb_last_processed_tracker_test.py
Replaced the incorrect use of `WritePrecision.MS` with `SYNCHRONOUS` in the InfluxDB write API and updated related test coverage.
> Switch InfluxDB write API to use SYNCHRONOUS option

- services/candle_ingestor/ccxt_client.py
- services/candle_ingestor/ccxt_client_test.py
- services/candle_ingestor/main.py
- services/candle_ingestor/symbol_validation_test.py
Standardized the normalized output for USD-based trading pairs to use "USD" instead of "USDT".
> Switch default normalized symbol format from USDT to USD

- charts/tradestream/values.yaml
Expanded the default exchange list for the candle ingestor to include Crypto.com and Gemini.
> Add Crypto.com and Gemini to candle ingestor exchange list

- MODULE.bazel
- third_party/java/BUILD
Added InfluxDB Java and Kotlin clients to MODULE.bazel and exposed them via new `java_library` targets.
> Add InfluxDB Java and Kotlin client dependencies to Bazel build (MINOR)

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/GAEngineFactory.kt
- src/main/java/com/verlumen/tradestream/discovery/GAEngineFactoryImpl.java
- src/main/java/com/verlumen/tradestream/discovery/GAEngineParams.kt
- src/test/java/com/verlumen/tradestream/backtesting/BUILD
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/GAEngineFactoryImplTest.java
This change refactors the `GAEngineFactory` and related components to decouple the factory from the `GAOptimizationRequest` protocol buffer. A new `GAEngineParams` Kotlin data class has been introduced to represent the necessary configuration for creating a genetic algorithm engine.
* Introduced `GAEngineParams` as a serializable Kotlin data class to encapsulate `strategyType`, `candlesList`, and `populationSize`.
* Updated `GAEngineFactory` and `GAEngineFactoryImpl` to use `GAEngineParams` instead of `GAOptimizationRequest`.
* Adjusted dependent build targets to reflect new dependencies on `marketdata_java_proto` and `strategies_java_proto`.
* Added a new Bazel target for `ga_engine_params`.
* Updated tests in `GAEngineFactoryImplTest` to construct and use `GAEngineParams`, removing …
> Refactor GAEngineFactory to Use GAEngineParams Instead of GAOptimizationRequest (MINOR)

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/DeserializeStrategyDiscoveryRequestFn.kt
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/DeserializeStrategyDiscoveryRequestFnTest.kt
This change introduces a new Apache Beam `DoFn` transform that deserializes Kafka message payloads into `StrategyDiscoveryRequest` protobufs:
* **New component:** `DeserializeStrategyDiscoveryRequestFn`, a `DoFn<KV<String, ByteArray>, StrategyDiscoveryRequest>`, which:
* Parses incoming Kafka message values.
* Emits successfully parsed protos.
* Logs and discards malformed inputs.
* **Unit tests:** `DeserializeStrategyDiscoveryRequestFnTest` added with full coverage of:
* Valid deserialization.
* Handling of malformed data.
* Null value edge cases.
* **Build updates:**
* Added `kt_jvm_library` and `kt_jvm_test` rules for the new class and test.
* Updated dependencies to support Beam, protobuf, and logging.
This introduces new reusable deserialization logic for `StrategyDiscoveryRequest` …
> Add Beam transform and tests for deserializing StrategyDiscoveryRequest from Kafka (MINOR)

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/ExtractDiscoveredStrategiesFn.kt
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/ExtractDiscoveredStrategiesFnTest.kt
This change introduces a new Apache Beam `DoFn`, `ExtractDiscoveredStrategiesFn`, which extracts individual `DiscoveredStrategy` elements from a `StrategyDiscoveryResult`. This flattening enables more granular downstream processing of discovered strategies.
* **New transform:** `ExtractDiscoveredStrategiesFn` outputs each strategy from the `topStrategiesList` field.
* **Test coverage:** Added `ExtractDiscoveredStrategiesFnTest` with cases covering:
* Multiple strategies
* Single strategy
* Empty discovery result
* Null input handling
* **BUILD targets:** Updated `BUILD` files to include the new library and corresponding test.
This transformation facilitates finer-grained pipeline stages and simplifies processing of strategy results. Since this is new functionality usable by downstream …
> Add Beam transform to extract individual strategies from discovery results (MINOR)

- MODULE.bazel
- third_party/java/BUILD
This change introduces the PostgreSQL JDBC driver (`org.postgresql:postgresql:42.7.6`) as a new Maven dependency in the Bazel `MODULE.bazel` file. A corresponding `java_library` target named `postgresql` has been added to `third_party/java/BUILD`, exposing the driver via `@tradestream_maven`.
This addition enables Bazel targets to depend on PostgreSQL for database connectivity and integration.
No functional changes to application logic were made—this is a dependency-only update.
> Add PostgreSQL JDBC Driver Dependency to Bazel Build

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/FitnessFunction.kt
- src/main/java/com/verlumen/tradestream/discovery/FitnessFunctionFactory.kt
- src/main/java/com/verlumen/tradestream/discovery/FitnessFunctionFactoryImpl.kt
This patch refactors the `FitnessFunction` type alias to use `java.util.function.Function` instead of a Kotlin lambda. This change ensures better Java interoperability and clarifies the functional contract of fitness functions within the genetic algorithm context.
* Updated `FitnessFunction` to alias `Function<Genotype<*>, Double>`.
* Refactored `FitnessFunctionFactory` and `FitnessFunctionFactoryImpl` to use the new alias.
* Removed unnecessary direct imports of `Genotype` and `Function` where no longer required.
* Cleaned up `BUILD` targets by:
* Removing the unused `jenetics` dependency.
* Adding explicit dependency on the local `:fitness_function` target where needed.
These updates help improve modularity, remove unused dependencies, and maintain clearer functional interfaces between …
> Refactor FitnessFunction type to alias java.util.function.Function and remove unused jenetics dependency

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt
This PR introduces a new Beam `DoFn`, `WriteDiscoveredStrategiesToPostgresFn`, which performs high-throughput writes of `DiscoveredStrategy` records to a PostgreSQL database using the `COPY` command. This implementation significantly improves performance over traditional `JdbcIO`, enabling throughput of 50K+ records/sec.
* **New Library Target**: Added `write_discovered_strategies_to_postgres_fn` to the discovery BUILD file with appropriate dependencies.
* **Core DoFn Implementation**:
* Uses PostgreSQL's `COPY` command via `BaseConnection.copyAPI` for efficient batch inserts.
* Handles retries with exponential backoff on failure.
* Performs upserts using temporary tables and `ON CONFLICT`.
* Uses Guice for dependency injection of the `DataSource`.
* **Test Suite**:
* Introduced …
> Add Beam DoFn for Writing Discovered Strategies to PostgreSQL via Bulk COPY

- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
- src/main/java/com/verlumen/tradestream/postgres/BUILD
This change integrates the `PostgresModule` into the `PipelineModule` by:
* Adding `PostgresModule` installation in `PipelineModule.configure()`.
* Declaring `postgres_module` as a dependency in the pipeline's `BUILD` file.
* Updating the `postgres_module` and `postgre_sql_data_source_factory` visibility to include the pipeline package, allowing for direct usage.
This enables pipeline-level access to PostgreSQL-backed data sources, laying the groundwork for database-related features or persistence.
No version bump necessary—changes are limited to dependency wiring and do not introduce new functionality exposed outside the pipeline module.
> Add PostgresModule integration to PipelineModule and BUILD dependencies

- src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
This patch removes the unused `BoundedWindow` parameter from the `processElement` method in `WriteDiscoveredStrategiesToPostgresFn.kt`. The parameter was not referenced in the method body and was safely eliminated to reduce clutter and improve readability.
No behavioral changes are introduced; this is a cleanup-level update.
> Remove unused `BoundedWindow` parameter from Beam DoFn process method

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/DiscoveryModule.kt
- src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
- src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt
This PR refactors the `WriteDiscoveredStrategiesToPostgresFn` class and its factory to use a single `DataSourceConfig` object for configuration, replacing multiple individual parameters. This change simplifies the constructor signature, reduces boilerplate, and enhances maintainability.
* **Consolidated constructor parameters** in `WriteDiscoveredStrategiesToPostgresFn` to a single `@Assisted DataSourceConfig`.
* **Updated `WriteDiscoveredStrategiesToPostgresFnFactory`** interface to match the new constructor signature.
* **Modified `DiscoveryModule`** to use `FactoryModuleBuilder` for assisted injection of `WriteDiscoveredStrategiesToPostgresFn`.
* **Adjusted test setup** in `WriteDiscoveredStrategiesToPostgresFnTest` to pass a `DataSourceConfig` object.
* Reordered and regrouped Bazel …
> Refactor PostgreSQL Write Fn to Use Single Config Object via Assisted Injection (MINOR)

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- charts/tradestream/templates/strategy-discovery-pipeline.yaml
- charts/tradestream/values.yaml
- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/StrategyDiscoveryPipelineRunner.kt
- src/main/java/com/verlumen/tradestream/discovery/container-structure-test.yaml
This pull request introduces the Strategy Discovery Pipeline as a new Flink deployment in the Tradestream platform. It includes full CI/CD integration, Helm chart configuration, and Bazel-based image building and publishing.
* **Helm/Chart Updates:**
* Added `strategyDiscoveryPipeline` configuration block to `values.yaml` with job, image, and DB parameters.
* Created `strategy-discovery-pipeline.yaml` template for FlinkDeployment resource.
* Hooked up Helm values for image tag/repo, Flink configs, and secrets.
* **CI Pipeline (`ci.yaml`):**
* Added Docker image build and push for `strategy-discovery-pipeline`.
* Included minikube loading and Helm chart injection for the new component.
* Created Kubernetes secret for Postgres password used by the pipeline.
* **Release Pipeline …
> Add Strategy Discovery Pipeline Flink Deployment and CI/CD Integration (MINOR)

- src/main/java/com/verlumen/tradestream/marketdata/DryRunTradeSource.java
- src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
- src/main/java/com/verlumen/tradestream/marketdata/TradeSource.java
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
This PR introduces a refactor to improve configurability and dependency injection support for market data components, particularly around trade and candle sources.
* **Refactored `MarketDataModule`:**
* Removed AutoValue usage and its parameters.
* Simplified to a parameterless instantiation (`MarketDataModule.create()`).
* Removed `@Provides` methods for `CandleSource` and `TradeSource`.
* **Introduced DI bindings in `PipelineModule`:**
* Added `@Provides` methods for `CandleSource` and `TradeSource` based on `RunMode`.
* In DRY mode, creates a mock trade using `DryRunTradeSource`.
* **Modified visibility of key components:**
* `TradeSource`, `DryRunTradeSource` are now `public` to support external instantiation.
* Made `DryRunTradeSource.create(...)` public.
* **BUILD file updates:**
* …
> Refactor MarketDataModule and Expose TradeSource for DI Integration (MINOR)

- src/main/java/com/verlumen/tradestream/discovery/BUILD
Introduced a new `kt_jvm_library` Bazel target named `dry_run_discovery_request_source` in the discovery module's build file. This target includes the `DryRunDiscoveryRequestSource.kt` source file and its associated dependencies, such as core discovery components, Guice for dependency injection, Beam SDK, and required proto definitions.
This update prepares the module for incorporating dry-run logic into the discovery request handling pipeline. No functional changes to runtime behavior are introduced in this patch.
> Add Bazel target for `DryRunDiscoveryRequestSource` implementation

- src/main/java/com/verlumen/tradestream/discovery/BUILD
This update alphabetizes the targets within the `BUILD` file for the strategy discovery pipeline to enhance readability and maintainability.
Key changes:
* Reordered `tar`, `oci_image`, `multi_arch`, `oci_image_index`, `oci_push`, and `container_structure_test` targets to follow alphabetical order.
* Adjusted positioning of `kt_jvm_library` and `java_library` targets where necessary to maintain consistent sorting.
No functional changes were introduced; this is a purely organizational improvement.
> Alphabetize targets in BUILD file for improved maintainability

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/TemporaryCurrencyPairModule.kt
This patch introduces `TemporaryCurrencyPairModule`, a Guice module that provides a temporary binding for `Supplier<List<CurrencyPair>>`. This module returns an empty `ImmutableList` and is intended to support transitional use cases where the currency pair dependency is still required.
A corresponding `kt_jvm_library` target has been added to the `BUILD` file to support module compilation.
**Note:** This module is marked for future removal once all dependent usages are eliminated.
> Add TemporaryCurrencyPairModule for transitional binding support

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/DiscoveredStrategySink.kt
- src/main/java/com/verlumen/tradestream/discovery/DryRunDiscoveredStrategySink.kt
This change introduces a new `DryRunDiscoveredStrategySink` class, which provides a dry-run implementation of `DiscoveredStrategySink`. Instead of persisting discovered strategies, it logs their symbol and score using Flogger. This is useful for testing and validation without affecting the persistent store.
The corresponding Bazel target `dry_run_discovered_strategy_sink` has also been added to the `BUILD` file, including all necessary dependencies.
This change introduces new functionality without altering existing behavior, and is therefore marked as (MINOR).
> Add DryRunDiscoveredStrategySink for logging strategy outputs during dry runs (MINOR)

- src/main/java/com/verlumen/tradestream/influxdb/InfluxDbClientFactory.kt
This update modifies the `InfluxDbClientFactoryImpl` class to implement the `Serializable` interface. A `serialVersionUID` is defined to ensure serialization compatibility.
**Summary of Changes:**
* Implemented `Serializable` in `InfluxDbClientFactoryImpl`.
* Added `serialVersionUID` with a value of `1L`.
This change enables the factory implementation to be safely serialized, which may be necessary for certain distributed or cached application contexts. No functional logic has been modified.
> Add `Serializable` support to `InfluxDbClientFactoryImpl`

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/DiscoveredStrategySink.kt
- src/main/java/com/verlumen/tradestream/discovery/DiscoveryModule.kt
- src/main/java/com/verlumen/tradestream/discovery/DryRunDiscoveredStrategySink.kt
- src/main/java/com/verlumen/tradestream/discovery/StrategyDiscoveryPipeline.kt
- src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/StrategyDiscoveryPipelineTest.kt
This pull request introduces a new abstraction for writing discovered strategies by replacing direct usage of `WriteDiscoveredStrategiesToPostgresFn` with a more flexible `DiscoveredStrategySink` interface. Key changes include:
* Introduced `DiscoveredStrategySink` as a common base class.
* Refactored `WriteDiscoveredStrategiesToPostgresFn` to extend `DiscoveredStrategySink`.
* Created `DryRunDiscoveredStrategySink`, a new implementation of `DiscoveredStrategySink` that logs strategies instead of persisting them.
* Replaced the factory `WriteDiscoveredStrategiesToPostgresFnFactory` with `DiscoveredStrategySinkFactory` to accommodate both implementations.
* Updated `StrategyDiscoveryPipeline` and corresponding tests to utilize the new factory and abstraction.
* Modified module bindings in …
> Refactor Strategy Sink to Use Abstract Interface and Add Dry-Run Implementation (MINOR)

- src/main/java/com/verlumen/tradestream/influxdb/InfluxDbConfig.kt
This change adds `Serializable` to the `InfluxDbConfig` data class. This allows instances of `InfluxDbConfig` to be serialized, enabling scenarios where configuration objects need to be transmitted or persisted, such as distributed systems or caching.
No functional logic has been altered—this is a structural enhancement to support broader usage patterns.
> Make `InfluxDbConfig` Serializable

- src/main/java/com/verlumen/tradestream/sql/DataSourceFactory.kt
This patch makes the `DataSourceConfig` data class implement the `Serializable` interface. This change enables the class to be used in contexts where object serialization is required, such as distributed caching or remote method invocation.
No functional logic is altered; the change is limited to class declaration. This is a patch-level update and does not introduce new features or breaking changes.
> Make `DataSourceConfig` Serializable

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpec.kt
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecManager.kt
This pull request introduces two new Kotlin classes to the `tradestream.strategies` package:
* **`StrategySpec`**: Encapsulates the configuration (`ParamConfig`) and factory for constructing ta4j strategy instances. It provides a cohesive specification model for individual strategies.
* **`StrategySpecManager`**: A manager class injected with a map of `StrategyType` to `StrategySpec`. It enables runtime lookup and validation of supported strategy types, improving modularity and access to strategy configurations.
Additional changes:
* Added a new `kt_jvm_library` target `strategy_spec` to the `BUILD` file under `strategies`, including dependencies on `strategy_factory`, `param_config`, and `guice`.
* Extended visibility of `param_config` in the discovery BUILD file to allow access from the …
> Add `StrategySpec` and `StrategySpecManager` for Encapsulating Strategy Configuration and Access

- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/smarsi/SmaRsiParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/smarsi/SmaRsiStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/smarsi/SmaRsiParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/smarsi/SmaRsiStrategyFactoryTest.java
Refactored the `SmaRsiParamConfig` and `SmaRsiStrategyFactory` classes to use public constructors directly, removing the now-unnecessary static `create()` factory methods and private constructors. This change simplifies instantiation and aligns with common object creation practices.
**Summary of Changes:**
* Removed `create()` static factory methods from `SmaRsiParamConfig` and `SmaRsiStrategyFactory`.
* Made their constructors public.
* Updated all usages across production and test code to instantiate via `new`.
This is a patch-level update with no changes to functionality or behavior.
> Refactor SmaRsi Config and Factory to Use Public Constructors

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/adxstochastic/BUILD
- src/main/java/com/verlumen/tradestream/strategies/emamacd/BUILD
- src/main/java/com/verlumen/tradestream/strategies/emamacd/EmaMacdParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/emamacd/EmaMacdStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/smarsi/BUILD
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
This update re-enables the EMA-MACD strategy by fully integrating its configuration and factory components into the strategy spec map. Key changes include:
* Activated `EmaMacdParamConfig` and `EmaMacdStrategyFactory` in `StrategySpecs.kt`.
* Removed deprecated `spec` targets from `BUILD` files for `adxstochastic`, `emamacd`, and `smarsi` strategies.
* Defined explicit `param_config` and `strategy_factory` targets with appropriate visibility settings.
* Adjusted test in `StrategySpecsTest` to reflect the newly included strategy.
These changes enhance modularity and clarity in strategy configuration while expanding the set of active trading strategies.
(MINOR) – introduces new functionality via re-enabled strategy support.
> Enable and Refactor EMA-MACD Strategy Integration

- src/main/java/com/verlumen/tradestream/strategies/doubleemacrossover/BUILD
- src/main/java/com/verlumen/tradestream/strategies/doubleemacrossover/DoubleEmaCrossoverStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/movingaverages/MovingAverageStrategies.java
- src/test/java/com/verlumen/tradestream/strategies/doubleemacrossover/BUILD
- src/test/java/com/verlumen/tradestream/strategies/doubleemacrossover/DoubleEmaCrossoverStrategyFactoryTest.java
- src/test/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
This patch relocates the `DoubleEmaCrossoverStrategyFactory` and its corresponding test from the `movingaverages` package to a new `doubleemacrossover` package. The change improves modularity by organizing strategy implementations into distinct, strategy-specific packages.
* Moved `DoubleEmaCrossoverStrategyFactory.java` and its test to `doubleemacrossover` package.
* Updated package declarations accordingly.
* Added new Bazel `BUILD` files for the `doubleemacrossover` main and test directories.
* Removed the strategy and its test from the `movingaverages` package and associated `BUILD` targets.
* Removed `DoubleEmaCrossoverStrategyFactory.create()` from the `MovingAverageStrategies.ALL_FACTORIES` list.
This is a structural refactor with no functional impact, intended to improve code …
> Refactor DoubleEmaCrossoverStrategy to Dedicated Package

- src/main/java/com/verlumen/tradestream/strategies/smaemacrossover/BUILD
- src/main/java/com/verlumen/tradestream/strategies/smaemacrossover/SmaEmaCrossoverParamConfig.java
- src/test/java/com/verlumen/tradestream/strategies/smaemacrossover/BUILD
- src/test/java/com/verlumen/tradestream/strategies/smaemacrossover/SmaEmaCrossoverParamConfigTest.java
This PR introduces the `SmaEmaCrossoverParamConfig` class to support parameterized configuration for the SMA-EMA crossover strategy. The new configuration enables genetic algorithm-based optimization by specifying chromosome specifications for SMA and EMA periods.
* Added `SmaEmaCrossoverParamConfig.java` implementing `ParamConfig` for SMA-EMA strategies.
* Defined chromosome specs for two integer parameters (SMA and EMA periods).
* Included logic to convert chromosomes to `SmaEmaCrossoverParameters` proto.
* Registered the param config in the strategy's Bazel `BUILD` file.
* Added `SmaEmaCrossoverParamConfigTest.java` with unit tests for:
* Chromosome spec generation.
* Parameter creation from chromosomes.
* Strategy type validation.
* Updated the test `BUILD` file to include the new …
> Add `SmaEmaCrossoverParamConfig` for parameterized SMA-EMA crossover strategy support

- src/main/java/com/verlumen/tradestream/strategies/tripleemacrossover/BUILD
- src/main/java/com/verlumen/tradestream/strategies/tripleemacrossover/TripleEmaCrossoverParamConfig.java
- src/test/java/com/verlumen/tradestream/strategies/tripleemacrossover/BUILD
- src/test/java/com/verlumen/tradestream/strategies/tripleemacrossover/TripleEmaCrossoverParamConfigTest.java
This change introduces a new `TripleEmaCrossoverParamConfig` class implementing `ParamConfig` to define parameterization logic for the Triple EMA Crossover strategy. Key elements include:
* **Chromosome specs** for short, medium, and long EMA periods using `ChromosomeSpec.ofInteger`.
* **Parameter creation** from chromosomes, returning packed `TripleEmaCrossoverParameters`.
* **Integration** in the build system (`BUILD` files) with appropriate dependencies.
* **Unit tests** (`TripleEmaCrossoverParamConfigTest`) validating spec retrieval, parameter creation, and strategy type consistency.
This enhancement enables consistent genetic algorithm configuration for the strategy, laying groundwork for optimized parameter tuning. *(MINOR)*
> Add `TripleEmaCrossoverParamConfig` for strategy parameterization and testing

- src/main/java/com/verlumen/tradestream/strategies/parabolicsarr/BUILD
- src/main/java/com/verlumen/tradestream/strategies/parabolicsarr/ParabolicSarParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/parabolicsarr/ParabolicSarStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/parabolicsarr/BUILD
- src/test/java/com/verlumen/tradestream/strategies/parabolicsarr/ParabolicSarParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/parabolicsarr/ParabolicSarStrategyFactoryTest.java
This pull request introduces a new trading strategy based on the Parabolic SAR indicator. It includes:
* `ParabolicSarParamConfig`: Defines chromosome specifications and parameter creation for PSAR optimization.
* `ParabolicSarStrategyFactory`: Builds TA4J strategies using the PSAR indicator with provided parameters.
* Bazel `BUILD` files for both main and test packages to define new libraries and tests.
* Unit tests for both `ParabolicSarParamConfig` and `ParabolicSarStrategyFactory` to validate correctness and integration.
This update introduces a new strategy module, warranting a (MINOR) version bump due to the addition of new functionality.
> Add Parabolic SAR strategy support with configurable parameters and tests (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/atrtrailingstop/AtrTrailingStopParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/atrtrailingstop/AtrTrailingStopStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/atrtrailingstop/BUILD
- src/test/java/com/verlumen/tradestream/strategies/atrtrailingstop/AtrTrailingStopParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/atrtrailingstop/AtrTrailingStopStrategyFactoryTest.java
- src/test/java/com/verlumen/tradestream/strategies/atrtrailingstop/BUILD
This pull request introduces the ATR Trailing Stop strategy implementation within the `tradestream` platform. It includes:
* **Strategy Factory (`AtrTrailingStopStrategyFactory`)**:
* Implements the logic for the ATR trailing stop strategy.
* Defines entry and exit rules based on price movements relative to ATR-based trailing stop levels.
* Includes a custom `TrailingStopIndicator` for dynamic exit logic.
* Provides default strategy parameters and validation.
* **Parameter Configuration (`AtrTrailingStopParamConfig`)**:
* Specifies chromosome specs for ATR period (int: 5–30) and multiplier (double: 1.0–5.0).
* Supports creation and unpacking of strategy parameters using ProtoBuf `Any`.
* **Testing**:
* Comprehensive JUnit tests for both factory and parameter configuration.
* Includes …
> Add ATR Trailing Stop strategy with parameter configuration and unit tests (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/atrcci/AtrCciParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/atrcci/AtrCciStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/atrcci/BUILD
- src/main/java/com/verlumen/tradestream/strategies/atrtrailingstop/BUILD
- src/test/java/com/verlumen/tradestream/strategies/atrcci/AtrCciParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/atrcci/AtrCciStrategyFactoryTest.java
- src/test/java/com/verlumen/tradestream/strategies/atrcci/BUILD
This PR introduces a new trading strategy implementation based on the Average True Range (ATR) and Commodity Channel Index (CCI) indicators. It includes both the parameter configuration and strategy logic, as well as corresponding unit tests and Bazel build files.
* **Strategy Implementation:**
* `AtrCciStrategyFactory`: Defines a strategy where:
* Entry signal triggers when CCI crosses above -100 and ATR is increasing.
* Exit signal triggers when CCI crosses below +100 and ATR is decreasing.
* Default parameters set to ATR period = 14, CCI period = 20.
* **Parameter Configuration:**
* `AtrCciParamConfig`: Defines chromosome specs for the ATR and CCI periods using integer ranges (ATR: 5–30, CCI: 10–50).
* Generates initial chromosomes and packs/unpacks parameters using Protobuf.
* …
>  Add ATR-CCI Strategy Implementation and Configuration

- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/StrategyDiscoveryPipelineRunner.kt
- src/main/java/com/verlumen/tradestream/pipeline/BUILD
- src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.kt
This change removes the unused `StrategiesModule` and its associated references from the codebase. The following updates were made:
* Deleted `StrategiesModule.kt`.
* Removed the `strategies_module` target from the `strategies/BUILD` file.
* Cleaned up dependencies and module installations in:
* `StrategyDiscoveryPipelineRunner.kt`
* `PipelineModule.java`
* Corresponding BUILD files under `discovery` and `pipeline`.
No functional changes were introduced. This is a cleanup to reduce dead code and simplify the dependency graph.
> Remove unused `StrategiesModule` and associated build targets

- protos/strategies.proto
This update introduces a new `COMPOSITE` strategy type to the `StrategyType` enum, enabling composition of two existing strategies using logical operators for entry and exit rules. The corresponding `CompositeStrategyParameters` message defines:
* `left_strategy` and `right_strategy`: The two strategies to be combined.
* `entry_operator` and `exit_operator`: Enum-based logical operators (`AND`, `OR`) for determining composite entry and exit conditions.
This enhancement allows for greater flexibility and reusability in strategy design by enabling complex strategy combinations without hardcoding each variant.
(MINOR) – Introduces a new feature with backward-compatible schema additions.
> Add COMPOSITE strategy type with configurable logical operators (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/adxdmi/AdxDmiParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/adxdmi/AdxDmiStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/adxdmi/BUILD
- src/test/java/com/verlumen/tradestream/strategies/adxdmi/AdxDmiParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/adxdmi/AdxDmiStrategyFactoryTest.java
- src/test/java/com/verlumen/tradestream/strategies/adxdmi/BUILD
This PR introduces a new technical trading strategy based on the ADX (Average Directional Index) and DMI (Directional Movement Index) indicators. Key components include:
* **`AdxDmiParamConfig`**: Defines the parameter space for the ADX and DI periods using `ChromosomeSpec`. Provides serialization via Protobuf.
* **`AdxDmiStrategyFactory`**: Implements the strategy logic using TA4J indicators and rules. It constructs buy/sell signals based on trend strength and DI crossovers.
* **Tests**: Unit tests for both parameter configuration and strategy factory ensure correctness of behavior and robustness against invalid input.
* **Build files**: Includes Bazel targets for building and testing the new components.
This update introduces new strategy functionality and integration into the system, …
> Add ADX-DMI strategy with parameter configuration and tests (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/aroonmfi/AroonMfiParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/aroonmfi/AroonMfiStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/aroonmfi/BUILD
- src/test/java/com/verlumen/tradestream/strategies/aroonmfi/AroonMfiParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/aroonmfi/AroonMfiStrategyFactoryTest.java
- src/test/java/com/verlumen/tradestream/strategies/aroonmfi/BUILD
This PR introduces a new trading strategy based on the Aroon and Money Flow Index (MFI) indicators.
* **Strategy Implementation:**
* Added `AroonMfiStrategyFactory` with custom implementations of `AroonUpIndicator`, `AroonDownIndicator`, and `MFIIndicator`.
* Implements entry and exit rules combining Aroon crossovers with MFI thresholds.
* **Parameter Configuration:**
* Introduced `AroonMfiParamConfig` to define and generate parameter chromosomes for the strategy.
* Supports parameter serialization via protobuf (`AroonMfiParameters`).
* **Build and Dependency Management:**
* Added Bazel `BUILD` files for both implementation and test targets.
* **Tests:**
* Added unit tests for `AroonMfiParamConfig` to verify chromosome specs and parameter creation.
* Added integration-like tests for …
> Add Aroon-MFI Strategy Implementation with Custom Indicators and Tests (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/MomentumIndicator.kt
This patch refactors the `MomentumIndicator` class to improve code clarity and maintainability:
* Converts `calculate` from a block body to an expression body for conciseness.
* Extracts percentage change computation into a dedicated private method `calculatePercentageChange`.
* Reorders method definitions to place `getUnstableBars` below the overridden `calculate`.
* Replaces usage of `numOf(100)` with `getBarSeries().numOf(100)` for consistency.
This is a non-functional change that improves readability without altering behavior.
> Refactor MomentumIndicator to streamline calculation logic

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/ichimokucloud/BUILD
- src/main/java/com/verlumen/tradestream/strategies/ichimokucloud/IchimokuCloudParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/ichimokucloud/IchimokuCloudStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
- src/test/java/com/verlumen/tradestream/strategies/ichimokucloud/BUILD
- src/test/java/com/verlumen/tradestream/strategies/ichimokucloud/IchimokuCloudParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/ichimokucloud/IchimokuCloudStrategyFactoryTest.java
This PR introduces the Ichimoku Cloud trading strategy into the Tradestream strategy framework.
* **Strategy Integration:**
* Registered `ICHIMOKU_CLOUD` in `StrategySpecs.kt` with its corresponding `ParamConfig` and `StrategyFactory`.
* Added required BUILD targets for the new strategy components.
* **Parameter Configuration:**
* Implemented `IchimokuCloudParamConfig` with defined ranges for Tenkan-sen, Kijun-sen, Senkou Span B, and Chikou Span periods.
* Refactored parameter class for public construction and updated tests accordingly.
* **Strategy Factory Implementation:**
* Added `IchimokuCloudStrategyFactory` with full support for indicator logic and strategy rules using ta4j.
* Includes custom implementations of Tenkan-sen, Kijun-sen, Senkou Span A & B, and Kumo Cloud indicators.
* …
> Add Ichimoku Cloud Strategy Support to Strategy Framework (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/stochasticema/BUILD
- src/main/java/com/verlumen/tradestream/strategies/stochasticema/StochasticEmaParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/stochasticema/StochasticEmaStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
- src/test/java/com/verlumen/tradestream/strategies/stochasticema/BUILD
- src/test/java/com/verlumen/tradestream/strategies/stochasticema/StochasticEmaParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/stochasticema/StochasticEmaStrategyFactoryTest.java
**Summary**
This PR introduces a new “Stochastic EMA” trading strategy, which combines the Stochastic Oscillator with an Exponential Moving Average to detect overbought/oversold conditions and trend direction. Key changes include:
* **BUILD rule updates**
* Registered new targets `stochasticema:param_config` and `stochasticema:strategy_factory` in the main `strategies/BUILD`.
* Added a dedicated `BUILD` file in `strategies/stochasticema/` defining both `java_library` and `java_test` targets for the new components.
* **StrategySpecs registration**
* Imported and mapped `StochasticEmaParamConfig` and `StochasticEmaStrategyFactory` to `StrategyType.STOCHASTIC_EMA` in `StrategySpecs.kt`.
* **New Java implementations**
* **`StochasticEmaParamConfig.java`**: Defines five chromosome specs and …
> Add Stochastic EMA strategy support (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/linearregressionchannels/BUILD
- src/main/java/com/verlumen/tradestream/strategies/linearregressionchannels/LinearRegressionChannelsParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/linearregressionchannels/LinearRegressionChannelsStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
- src/test/java/com/verlumen/tradestream/strategies/linearregressionchannels/BUILD
- src/test/java/com/verlumen/tradestream/strategies/linearregressionchannels/LinearRegressionChannelsParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/linearregressionchannels/LinearRegressionChannelsStrategyFactoryTest.java
This pull request introduces support for the Linear Regression Channels strategy in the trading strategy framework. The following updates are included:
* **New Strategy Added**: Implemented `LinearRegressionChannelsStrategyFactory` using a custom `LinearRegressionChannelsIndicator` with upper and lower channel logic based on linear regression and standard deviation.
* **Parameter Configuration**: Created `LinearRegressionChannelsParamConfig` with chromosome specs for `period` and `multiplier` parameters, integrated with the discovery module.
* **Integration**:
* Registered the new strategy in `StrategySpecs.kt`.
* Updated the BUILD files to include the new strategy and its components.
* Incremented the strategy count in the corresponding test to reflect the two newly added entries.
* …
> Add Linear Regression Channels Strategy Implementation and Integration

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/rainbowoscillator/BUILD
- src/main/java/com/verlumen/tradestream/strategies/rainbowoscillator/RainbowOscillatorParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/rainbowoscillator/RainbowOscillatorStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
- src/test/java/com/verlumen/tradestream/strategies/rainbowoscillator/BUILD
- src/test/java/com/verlumen/tradestream/strategies/rainbowoscillator/RainbowOscillatorParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/rainbowoscillator/RainbowOscillatorStrategyFactoryTest.java
This pull request introduces the Rainbow Oscillator strategy into the trading system, including configuration, factory implementation, and test coverage.
* **Strategy Integration:**
* Registered `RainbowOscillatorParamConfig` and `RainbowOscillatorStrategyFactory` in `StrategySpecs.kt`.
* Added corresponding dependencies in the `BUILD` files.
* **New Strategy Implementation:**
* Created `RainbowOscillatorParamConfig.java` defining parameter bounds and default chromosome settings.
* Implemented `RainbowOscillatorStrategyFactory.java`, including:
* A custom `RainbowOscillatorIndicator`.
* Strategy entry/exit rules based on crossovers of the oscillator around a zero baseline.
* **Test Coverage:**
* Added unit tests for both parameter config and strategy factory:
* Verifies parameter …
> Add Rainbow Oscillator Strategy to StrategySpecs and StrategyFactory

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/doubletopbottom/BUILD
- src/main/java/com/verlumen/tradestream/strategies/doubletopbottom/DoubleTopBottomParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/doubletopbottom/DoubleTopBottomStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
- src/test/java/com/verlumen/tradestream/strategies/doubletopbottom/BUILD
- src/test/java/com/verlumen/tradestream/strategies/doubletopbottom/DoubleTopBottomParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/doubletopbottom/DoubleTopBottomStrategyFactoryTest.java
This PR introduces the new `DoubleTopBottom` trading strategy into the tradestream platform. The following components have been added:
* **Strategy integration**:
* `DoubleTopBottomParamConfig`: Defines chromosome specifications and parameter generation.
* `DoubleTopBottomStrategyFactory`: Implements logic to create strategy instances using TA4J EMA indicators.
* **Build configuration**:
* Added necessary entries in the `BUILD` files to support the new strategy and its tests.
* **StrategySpecs.kt**:
* Registered `DoubleTopBottom` in the global `strategySpecMap`.
* **Test coverage**:
* Unit tests for both `DoubleTopBottomParamConfig` and `DoubleTopBottomStrategyFactory` ensure correctness and validation logic.
This change qualifies as a **(MINOR)** version update due to the addition of …
> Add DoubleTopBottom strategy with param config, factory, and test coverage (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/gannswing/BUILD
- src/main/java/com/verlumen/tradestream/strategies/gannswing/GannSwingParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/gannswing/GannSwingStrategyFactory.java
- src/main/java/com/verlumen/tradestream/strategies/rangebars/RangeBarsParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/renkochart/RenkoChartParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/renkochart/RenkoChartStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/BUILD
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
- src/test/java/com/verlumen/tradestream/strategies/gannswing/BUILD
- src/test/java/com/verlumen/tradestream/strategies/gannswing/GannSwingParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/gannswing/GannSwingStrategyFactoryTest.java
This PR introduces the initial implementation of the Gann Swing strategy to the strategy framework. Key changes include:
Added GannSwingParamConfig for parameter configuration with Jenetics integration.
Implemented GannSwingStrategyFactory returning a stub strategy for now.
Registered the strategy in StrategySpecs.kt and updated associated build files.
Created corresponding unit tests for both ParamConfig and StrategyFactory.
Incremented the total strategy count in StrategySpecsTest.
The actual trading logic is yet to be implemented; the current strategy returns dummy results, laying the groundwork for future development.
Tag: (MINOR) – This adds new functionality by introducing a new strategy type.
> Add Gann Swing strategy with configuration, factory, and tests (MINOR)

- src/main/java/com/verlumen/tradestream/strategies/BUILD
- src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
- src/main/java/com/verlumen/tradestream/strategies/variableperiodema/BUILD
- src/main/java/com/verlumen/tradestream/strategies/variableperiodema/VariablePeriodEmaParamConfig.java
- src/main/java/com/verlumen/tradestream/strategies/variableperiodema/VariablePeriodEmaStrategyFactory.java
- src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
- src/test/java/com/verlumen/tradestream/strategies/variableperiodema/BUILD
- src/test/java/com/verlumen/tradestream/strategies/variableperiodema/VariablePeriodEmaParamConfigTest.java
- src/test/java/com/verlumen/tradestream/strategies/variableperiodema/VariablePeriodEmaStrategyFactoryTest.java
- Implement VariablePeriodEmaParamConfig with chromosome specs for period parameters
- Implement VariablePeriodEmaStrategyFactory with ta4j-based EMA crossover logic
- Add strategy registration to StrategySpecs.kt
- Update StrategySpecsTest.kt expected count
- Include BUILD files for main and test targets
> Add Variable Period EMA trading strategy implementation

- charts/tradestream/templates/strategy-discovery-pipeline.yaml
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/StrategyDiscoveryPipelineRunnerTest.kt
This patch corrects configuration issues in the strategy discovery pipeline deployment and adds comprehensive test coverage to validate argument parsing behavior:
* Updated Flink job argument keys in the Helm chart to match expected property names:
* Renamed `--bootstrapServers` to `--kafkaBootstrapServers`
* Renamed `--isStreaming` to `--streaming`
* Added a new test suite `StrategyDiscoveryPipelineRunnerTest.kt` with 10 targeted test cases:
* Validates correct argument format handling by `PipelineOptionsFactory`
* Replicates and documents production errors caused by malformed argument strings
* Confirms default values, partial input handling, and error messaging for invalid properties
These changes address a production issue caused by improper argument formatting and provide a validated …
> Fix argument format and property naming in strategy discovery pipeline (PATCH)

- MODULE.bazel
- charts/tradestream/values.yaml
- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
- src/main/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistry.kt
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt
- src/test/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistryTest.kt
- third_party/java/BUILD
This PR removes the StrategyRepository abstraction that was causing build failures due to missing files.
- Remove StrategyRepository.kt and PostgresStrategyRepository.kt files
- Update WriteDiscoveredStrategiesToPostgresFn to work without repository dependency
- Remove Guice binding for StrategyRepository in DiscoveryModule
- Update BUILD file to remove references to deleted files
- Fix WriteDiscoveredStrategiesToPostgresFnTest to work without repository abstraction
- Remove InMemoryStrategyRepository test implementation
- All tests now pass successfully
- Build completes without errors
- No functional changes to the core strategy discovery pipeline
This is a cleanup PR that resolves build failures without changing the core functionality. The strategy discovery pipeline continues to work …
> fix: Remove StrategyRepository abstraction to resolve build failures

- MODULE.bazel
- charts/tradestream/values.yaml
- src/main/java/com/verlumen/tradestream/discovery/BUILD
- src/main/java/com/verlumen/tradestream/discovery/DiscoveryModule.kt
- src/main/java/com/verlumen/tradestream/discovery/PostgresStrategyRepository.kt
- src/main/java/com/verlumen/tradestream/discovery/StrategyCsvUtil.kt
- src/main/java/com/verlumen/tradestream/discovery/StrategyRepository.kt
- src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
- src/main/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistry.kt
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/PostgresStrategyRepositoryTest.kt
- src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt
- src/test/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistryTest.kt
- third_party/java/BUILD
This PR fixes the parameter serialization to be more robust and production-appropriate:
- Always emit error markers for unknown/invalid parameter types instead of fallback base64
- Update tests to expect the new behavior
- Ensure CSV compatibility for PostgreSQL COPY operations
- All tests now pass with the new serialization logic
> Robust parameter JSON serialization: always emit error marker for unknown/invalid types

- src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToKafkaFn.kt
- src/test/java/com/verlumen/tradestream/discovery/BUILD
- src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToKafkaFnTest.kt
This PR replaces the stub Kafka sink with a production-ready implementation using KafkaProducer.\n\n- Implements setup/teardown and error handling\n- Serializes DiscoveredStrategy as protobuf\n- Partitions by symbol\n- Adds tests and formatting\n- Updates BUILD files as needed\n\nAll tests and builds pass. Ready for review!
> fix(discovery): implement real Kafka sink for discovered strategies

- services/strategy_consumer/BUILD
- services/strategy_consumer/kafka_consumer.py
- services/strategy_consumer/kafka_consumer_test.py
- src/main/java/com/verlumen/tradestream/discovery/DiscoveredStrategySinkFactoryImpl.kt
- src/main/java/com/verlumen/tradestream/discovery/DiscoveredStrategySinkParams.kt
The strategy-consumer was failing with UTF-8 decode errors because it was trying to decode binary Protocol Buffer messages as text.
- Strategy-discovery-pipeline produces binary Protocol Buffer messages ()
- Strategy-consumer was using UTF-8 deserializers expecting JSON text
- Data format mismatch caused  errors
- ✅ Remove UTF-8 deserializers from Kafka consumer
- ✅ Add Protocol Buffer imports and deserialization logic
- ✅ Update message parsing to handle binary  protobuf messages
- ✅ Add helper methods for timestamp conversion and parameter extraction
- ✅ Update tests to use actual protobuf messages instead of JSON
- ✅ Add protobuf dependencies to BUILD files
- ****: Updated to deserialize binary protobuf messages
- ****: Updated tests to use protobuf messages
- ****: Added protobuf …
> fix: Update strategy-consumer to handle binary Protocol Buffer messages

- services/strategy_consumer/kafka_consumer.py
- services/strategy_consumer/kafka_consumer_test.py
Strategy consumer was failing to parse all messages with error: 'int' object has no attribute 'name'
The code was trying to call  on , but this returns an integer enum value, not an enum object.
Use  to properly convert the enum value to its string name.
After deployment, the consumer should successfully parse and store strategies in the database.
- : Fix enum parsing in
> Fix strategy consumer enum parsing error

- src/main/java/com/verlumen/tradestream/marketdata/BUILD
This change removes the `kt_jvm_library` target named `trade_checkpoint_mark` from the `BUILD` file in the `marketdata` module. The deleted target included the `TradeCheckpointMark.kt` source file and dependencies on Beam SDK and Joda-Time. This cleanup eliminates unused or obsolete build configurations, improving maintainability of the build definition.
No functional code changes are included in this patch.
> Remove deprecated `trade_checkpoint_mark` library target from marketdata BUILD file

- charts/tradestream/values.yaml
Removes the global.imageTag configuration to enforce explicit individual image tags for better control and clarity.
- Removed `global.imageTag` from `charts/tradestream/values.yaml`
- ArgoCD Image Updater now uses only explicit individual tags:
- `candleIngestor.image.tag`
- `topCryptoUpdaterCronjob.image.tag`
- `strategyDiscoveryRequestFactory.image.tag`
- `strategyDiscoveryPipeline.image.tag`
- `strategyConsumer.image.tag`
- Enforces explicit configuration over global defaults
- Improves clarity and control over individual service image versions
- Aligns with best practices for Helm chart configuration
> Remove global.imageTag to enforce explicit individual image tags

- .github/workflows/release.yaml
This PR reverts the codebase back to commit 894c49178c0511acb6ef622b0ce7f98ad932db31 by reverting the following commits:
- 0615b83d: Merge optimize-release-workflow-parallel-push into main
- 3d58d9e4: fix: move tag push to after all images are successfully pushed
This will restore the codebase to the state it was in before these changes were merged.
> Revert to commit 894c4917

- .github/workflows/release.yaml
The current parallel release workflow pushes the git tag **before** building and pushing images. This creates several issues:
- **Orphaned Tags**: If image builds/pushes fail, the tag exists but points to broken release
- **Rollback Confusion**: Failed releases still get tagged, making rollback scenarios unclear  
- **Release Integrity**: Tag creation should confirm successful deployment, not just intent
Move tag creation from  job to  job:
1. : Generate version + **Push tag immediately**
2. : Build/push 8 images in parallel  
3. : Notify completion
1. : Generate version only
2. : Build/push 8 images in parallel
3. : **Push tag only after successful deployment** + Notify completion
- **🛡️ Release Integrity**: Tags only exist for successful deployments
- **🔄 Better Rollbacks**: Clean tag …
> fix: push git tag only after successful image deployment

- charts/tradestream/templates/_helpers.tpl
ArgoCD was failing to sync due to missing Helm template functions in the chart.
- Add  template function
- Add  template function  
- Add  template function
- Resolves ArgoCD sync issue with strategy-monitor templates
- Template error:
> fix: add missing Helm template functions

- .github/workflows/ci.yaml
- services/candle_ingestor/BUILD
- services/strategy_consumer/BUILD
- services/strategy_discovery_request_factory/BUILD
- services/strategy_monitor_api/BUILD
- services/top_crypto_updater/BUILD
- src/main/java/com/verlumen/tradestream/discovery/BUILD
- ui/strategy-monitor/BUILD
This PR simplifies the CI workflow by leveraging the  functionality from the  Bazel rules to generate proper OCI tarballs instead of manually creating them.
-  -  + 
-  -  + 
-  -  + 
-  -  + 
-  -  + 
-  -  + 
-  -  + 
The new CI workflow now:
1. **Build & Export Images job**: Builds tarballs using 
2. **Deploy and Test job**: Downloads artifacts and loads tarballs into Docker/minikube
- **Eliminated complexity**: Removed local registry service and manual tarball creation
- **Better reliability**: Uses Bazel's built-in OCI functionality
- **Cleaner workflow**: Much easier to understand and maintain
- **Faster execution**: No need to wait for artifact uploads/downloads between jobs
The workflow leverages the [rules_oci documentation](https://github.com/bazel-contrib/rules_oci/blob/main/doc …
> Simplify CI workflow using oci_load tarballs

- ui/strategy-monitor/container-structure-test.yaml
- ui/strategy-monitor/nginx.conf
The strategy-monitor-ui container was experiencing a CrashLoopBackOff due to a port mismatch:
- **nginx configuration**: Listening on port 80
- **Kubernetes deployment**: Expecting port 8080
- **Health checks**: Failing with connection refused on port 8080
This caused the container to start successfully but fail readiness probes, leading to continuous restarts.
1. **nginx.conf**: Changed `listen 80;` → `listen 8080;`
2. **container-structure-test.yaml**: Updated all test URLs from `:80` → `:8080`
- **Immediate**: Fixes CrashLoopBackOff in strategy-monitor-ui pods
- **Long-term**: Ensures consistent port configuration between nginx and Kubernetes
- **CI/CD**: Resolves the same issue affecting GitHub Actions minikube tests
After merge:
1. Build new image with this fix
2. Deploy updated …
> fix: Update strategy-monitor-ui nginx to listen on port 8080

- ui/strategy-monitor/nginx.conf
The Strategy Monitor UI was showing 'API service temporarily unavailable' because nginx was using external DNS (8.8.8.8) to resolve Kubernetes internal services, which fails.
✅ **DNS Resolver**: Use Kubernetes cluster DNS ()
✅ **FQDN Backend**: Use full service name ()
✅ **Reliability**: Increased timeouts from 1s to 5s  
✅ **Error Handling**: Maintains graceful fallback with CORS headers
🎯 **Enables Live Data**: Strategy Monitor UI can now connect to real trading data
🚀 **Production Ready**: Proper Kubernetes service resolution
🛡️ **Robust**: Better error handling and timeouts
- Container tests pass
- nginx starts successfully in all environments  
- Graceful fallback when backend unavailable
- Live API connectivity in Kubernetes cluster
> Fix nginx DNS resolver for live API connectivity
