charts/tradestream/values.yaml

This pull request updates the Helm chart `values.yaml` to use an ARM-compatible version of Kafka for better compatibility with ARM-based deployments, such as those on Raspberry Pi or ARM-based cloud instances.
- **Updated Image Repository:**
- Changed from `confluentinc/cp-kafka` to `bitnami/kafka` for better ARM architecture support.
- **Updated Image Tag:**
- Updated the tag from `7.0.0` (Confluent version) to `3.4.0-debian-11-r0`, which is known to be compatible with ARM.
- The previous image (`confluentinc/cp-kafka`) may not provide full compatibility or optimization for ARM architecture.
- The `bitnami/kafka` image is chosen due to its reliability, frequent updates, and ARM-compatible versions.
- This change ensures that the TradeStream platform can run seamlessly on ARM-based …

Update Kafka Image to ARM-Compatible Bitnami Version

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD

- **Dependency Injection:** Added Guice to inject `RealTimeDataIngestion` into `App`.
- **Library Refactor:** Renamed `real-time-data-ingestion-lib` to `real-time-data-ingestion` and updated `app-lib` dependencies accordingly.
This update leverages Guice for dependency injection, improving modularity and testability in the `TradeStream` ingestion module.

Integrate Guice Injection for `RealTimeDataIngestion` in `App`

---

src/main/java/com/verlumen/tradestream/ingestion/App.java

- **`run` Method:** Introduced an empty `run` method in `App` to encapsulate the application’s startup sequence, preparing for future logic additions.
- **Dependency Injection:** Switched `main` to use Guice for instantiating `App` with injected dependencies.
This update improves `App`'s structure by centralizing startup logic and enabling dependency injection for easier testing and future expansion.

Add `run` Method and Guice Injection to `App` Initialization

---

src/main/java/com/verlumen/tradestream/ingestion/App.java

This PR refactors the `App` class to use Guice for dependency injection. 
**Changes:**
* Introduced Guice for managing dependencies.
* Removed manual instantiation of `RealTimeDataIngestion` in `App`.
* Created a `run()` method to encapsulate the application logic.
**Benefits:**
* Improved code organization and readability.
* Enhanced testability by enabling easier mocking of dependencies.
* Promotes a more modular and maintainable codebase.
This refactor sets the stage for future improvements and additions to the application, making it easier to manage and extend its functionality.

Refactor: Use Guice for Dependency Injection in App

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/ingestion/MarketDataIngestion.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

- **Added `IngestionModule`:** Created a new Guice module (`IngestionModule.java`) to manage bindings. Specifically, it binds `MarketDataIngestion` to `RealTimeDataIngestion`, facilitating more flexible and maintainable dependency injection.
- **Introduced `MarketDataIngestion` interface:** Defined a new interface (`MarketDataIngestion.java`) to abstract the market data ingestion functionality. This promotes loose coupling and enhances the testability of the codebase.
- **Modified `RealTimeDataIngestion`:** Updated `RealTimeDataIngestion.java` to implement the new `MarketDataIngestion` interface, aligning it with the abstraction and ensuring compliance with the contract defined by the interface.
- **Updated `App.java`:** Changed the Guice injector in `App.java` to include the new …

Introduce `IngestionModule` and `MarketDataIngestion` interface for improved dependency injection

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD

- **Added `IngestionModule`:** Created a new Guice module (`IngestionModule.java`) to manage bindings. It binds `MarketDataIngestion` to `RealTimeDataIngestion`, facilitating flexible and maintainable dependency injection.
- **Introduced `MarketDataIngestion` interface:** Defined a new interface (`MarketDataIngestion.java`) to abstract market data ingestion functionality. This promotes loose coupling and enhances testability.
- **Modified `RealTimeDataIngestion`:** Updated `RealTimeDataIngestion.java` to implement the new `MarketDataIngestion` interface, aligning it with the abstraction and ensuring compliance with the interface contract.
- **Updated `App.java`:** 
- **Injector Modification:** Changed the Guice injector in `App.java` to include the new `IngestionModule`, ensuring …

Introduce `IngestionModule` and `MarketDataIngestion` interface; update `App` to use interface for dependency injection

---

MODULE.bazel

Updated `MODULE.bazel` to include `guice-testlib` (version 7.0.0) for improved dependency injection support in unit tests, facilitating cleaner test setup and mocking with Google Guice.

Add Guice TestLib for Enhanced Dependency Injection in Tests

---

.github/workflows/release.yaml

Enhanced `release.yaml` by adding branch extraction and conditional suffix logic. Applies `-develop` suffix for `develop` branch and `-prod` for `main` branch, allowing distinct versioning across branches. This update enables clear differentiation between production and development artifacts.

Add Branch-Based Suffix Logic for `main` and `develop` in Release Workflow

---

.github/workflows/release.yaml

Enhanced `release.yaml` to automate the update of `values.yaml` with the newly generated Docker image tag. Installed `yq` to modify the `values.yaml` file, setting the repository and tag based on branch-specific image tags. Committed and pushed any updates to `values.yaml` to the branch, ensuring the Helm chart always references the latest image.

Automate `values.yaml` Update with New Docker Image Tag in Release Workflow

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

This pull request updates the indentation in the `RealTimeDataIngestion.java` file to adhere to the project's coding standards. The changes reduce the indentation from 6 spaces to 4 spaces for annotations and method declarations, ensuring consistent and readable code formatting across the codebase.
**Changes:**
- Adjusted indentation for the `@Inject` annotation and constructor.
- Corrected indentation for the `@Override` annotations and corresponding methods (`start` and `shutdown`).

Standardize Indentation in `RealTimeDataIngestion` Class

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandleBuilder.java
src/main/java/com/verlumen/tradestream/ingestion/CandleBuilderTest.java

This pull request introduces the `CandleBuilder` class, which constructs `Candle` objects from incoming `Trade` data. The builder accurately calculates the open, high, low, close prices, and total volume based on the trades received. Additionally, comprehensive unit tests (`CandleBuilderTest`) have been added to ensure the reliability and correctness of the `CandleBuilder` functionality. The `BUILD` configuration has been updated to include the new library and test targets.
**Changes:**
- **Added:**
- `CandleBuilder.java`:
- Implements the logic to build `Candle` objects from `Trade` data.
- `CandleBuilderTest.java`:
- Contains unit tests validating the behavior of `CandleBuilder`.
- **Updated:**
- `BUILD` file:
- Added `java_library` target for `candle-builder`.
- Added `java_test` …

Add `CandleBuilder` Class and Corresponding Unit Tests

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandlePublisher.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/CandlePublisherTest.java

This pull request introduces the `CandlePublisher` class, which facilitates the publishing of `Candle` objects to a specified Kafka topic. By leveraging the Apache Kafka `KafkaProducer`, the `CandlePublisher` ensures efficient and reliable transmission of candle data within the trade ingestion pipeline. Additionally, comprehensive unit tests (`CandlePublisherTest`) have been implemented to verify the correctness and robustness of the publishing functionality. The `BUILD` configurations have been updated accordingly to include the new library and its associated tests, along with the necessary dependencies.
**Changes:**
- **Added:**
- `CandlePublisher.java`:
- Implements the logic to publish `Candle` objects to a Kafka topic using `KafkaProducer`.
- Handles serialization of `Candle` objects …

Add `CandlePublisher` Class for Kafka Integration with Unit Tests

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/PriceTracker.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/PriceTrackerTest.java

This pull request introduces the `PriceTracker` class, which is responsible for maintaining and managing the latest prices for various currency pairs in a thread-safe manner. By utilizing a `ConcurrentHashMap`, `PriceTracker` ensures efficient and safe updates and retrievals of price data in concurrent environments. Additionally, comprehensive unit tests (`PriceTrackerTest`) have been added to validate the functionality and reliability of the `PriceTracker` class. The `BUILD` configurations have been updated to include the new library and its corresponding tests, ensuring seamless integration within the project's build system.
**Changes:**
- **Added:**
- `PriceTracker.java`:
- Implements a thread-safe mechanism to track the latest prices for currency pairs using `ConcurrentHashMap`.
- …

Add `PriceTracker` Class with Unit Tests

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandleManager.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/CandleManagerTest.java

This pull request introduces the `CandleManager` class, which serves as the central coordinator for managing candle creation, publishing, and price tracking within the trade ingestion pipeline. By integrating `CandleBuilder`, `CandlePublisher`, and `PriceTracker`, the `CandleManager` ensures efficient processing of trades, timely publication of candles to Kafka, and accurate tracking of the latest prices for currency pairs. Comprehensive unit tests (`CandleManagerTest`) have been added to validate the functionality and reliability of the `CandleManager`. Additionally, the `BUILD` configurations have been updated to include the new library and its corresponding tests, ensuring seamless integration within the project's build system.
**Changes:**
- **Added:**
- `CandleManager.java`:
- …

Add `CandleManager` Class with Coordination Logic and Unit Tests

---

BUILD
MODULE.bazel
charts/tradestream/values.yaml

This pull request sets up the build configurations for using AutoFactory and AutoValue with Gson in the project. By adding the necessary `java_library` and `java_plugin` targets, along with updating the `MODULE.bazel` file to include required Maven artifacts, the build system is now prepared to support code generation and value object creation seamlessly. This setup facilitates the creation of immutable data classes and factory patterns, enhancing code maintainability and reducing boilerplate.
**Changes:**
- **Added:**
- **`BUILD` File:**
- **`java_library` Targets:**
- `autofactory`:
- Exports AutoFactory dependencies.
- Configured as `neverlink` to prevent inclusion in dependent binaries.
- `autovalue`:
- Exports AutoValue dependencies.
- Configured as `neverlink`.
- `autovalue_gson`:
- …

Configure AutoFactory and AutoValue with Gson Integration in Build System

---

src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/PriceTrackerTest.java

1. **Removed Test Parameter Injector:**
- Removed the `com_google_testparameterinjector_test_parameter_injector` dependency from the test `BUILD` file.
- Replaced `TestParameterInjector` with `JUnit4` in `PriceTrackerTest`.
2. **Updated Test Class:**
- Simplified the setup process in `PriceTrackerTest` by using the `JUnit4` runner instead of parameter injection, as it was unnecessary.
**Benefits:**
- Reduced complexity by eliminating unused dependencies.
- Streamlined test configuration for better maintainability.

 Simplify PriceTrackerTest Setup

---

src/main/java/com/verlumen/tradestream/ingestion/CandlePublisherImpl.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/CandleManagerTest.java
src/test/java/com/verlumen/tradestream/ingestion/CandlePublisherImplTest.java

- Added `@AutoFactory` to `CandlePublisherImpl` for automatic factory generation.  
- Annotated `KafkaProducer` dependency with `@Provided` for cleaner injection.  
- Updated `CandleManagerTest` and `CandlePublisherImplTest` to align with the new factory pattern and dependency injection.  
- Modified `BUILD` files to ensure consistent dependency naming (`candle_publisher` replaces `candle_publisher_impl` where appropriate).  
- Enhanced test coverage to reflect the refactored code structure.  
This change streamlines object construction, improves test modularity, and ensures adherence to updated architectural conventions.

Refactor `CandlePublisherImpl` with AutoFactory and Update Dependencies

---

src/main/java/com/verlumen/tradestream/ingestion/CandlePublisherImpl.java

- Updated the `@AutoFactory` annotation in `CandlePublisherImpl` to specify an implementing interface (`CandlePublisher.Factory`).  
- Ensures the factory adheres to the `CandlePublisher.Factory` interface, improving type safety and consistency.  
This enhancement aligns the factory implementation with project standards, streamlining future integrations and maintaining clear contract adherence.

Enhance AutoFactory Implementation for CandlePublisherImpl

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandleManager.java

Changes:
- Added AutoFactory dependency in BUILD file
- Annotated CandleManager constructor with @AutoFactory
- Marked PriceTracker parameter with @Provided annotation to indicate it should be injected
This change simplifies object creation by generating a factory class for CandleManager, reducing boilerplate code and making dependency injection more maintainable.

Add AutoFactory annotation to CandleManager to automate dependency injection and factory creation.

---

MODULE.bazel

- Reorganized test dependencies in `MODULE.bazel` for better readability and maintainability.  
- Grouped all test-related libraries together under a clear "Test Dependencies" comment.  
- Added slight spacing adjustments to enhance clarity in dependency management.
This change improves the structure and maintainability of the Bazel module configuration, making it easier to identify and manage test-related dependencies.

Reorganize Test Dependencies in `MODULE.bazel`

---

MODULE.bazel
charts/tradestream/values.yaml

- Upgraded the `auto-factory` dependency from version `1.0.1` to `1.1.0` in `MODULE.bazel`.
- Ensures compatibility with the latest features and improvements provided by `auto-factory`.
This change keeps the project dependencies up to date and aligns with modern library versions for better performance and support.

Update `auto-factory` Dependency to Version 1.1.0

---

MODULE.bazel

Added `guice-assistedinject` to `MODULE.bazel` for enhanced dependency injection support. Prepares for Guice factory integration.

Add Guice AssistedInject to Dependencies

---

MODULE.bazel
src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandlePublisher.java
src/main/java/com/verlumen/tradestream/ingestion/CandlePublisherImpl.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/CandlePublisherImplTest.java

Added Guice AssistedInject for `CandlePublisherImpl` and refactored `IngestionModule` to use a factory. Updated tests to support the new injection model. Improves flexibility and testability.

Integrate Guice AssistedInject for Dependency Injection

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandleManager.java
src/main/java/com/verlumen/tradestream/ingestion/CandleManagerImpl.java

This pull request introduces a new `CandleManager` interface and updates the existing `CandleManagerImpl` to implement it, enhancing modularity and flexibility in the trade processing pipeline. The following changes are included:  
1. **New Interface: `CandleManager`**  
- Defines the contract for managing and processing trade data:
- `processTrade(Trade trade)`: Processes individual trades.
- `handleThinlyTradedMarkets(List<String> currencyPairs)`: Handles scenarios for markets with low trading volume.
2. **Implementation: `CandleManagerImpl`**  
- Updated `CandleManagerImpl` to implement the `CandleManager` interface.
- Retains existing functionality with added structure for adherence to the new interface.
3. **Build Configuration Updates:**  
- Added a new `java_library` rule for …

Add CandleManager Interface and Integrate with CandleManagerImpl  

---

.github/workflows/bazel-test.yaml

Reverts tradestreamhq/tradestream#125

Revert "Enhance Bazel Test Workflow with Caching for Faster Builds"

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

Injected `CandlePublisher.Factory` into `RealTimeDataIngestion` for improved modularity and dependency management. Updated `BUILD` file to include the necessary dependency. Prepares for dynamic publisher creation.

Add CandlePublisher Factory to RealTimeDataIngestion

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandleManager.java
src/main/java/com/verlumen/tradestream/ingestion/CandleManagerImpl.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/CandleManagerImplTest.java

- Added `AssistedInject` for `CandleManagerImpl` and implemented `CandleManager.Factory`.
- Updated `IngestionModule` to bind `CandleManager` with a factory.
- Refactored tests to use the factory for creating `CandleManagerImpl` instances.
- Enhanced modularity and testability by integrating Guice-assisted dependency injection.

Refactor CandleManager with AssistedInject and Add Factory Integration

---

.github/workflows/bazel-test.yaml

- Replaced `actions/cache` with `bazel-contrib/setup-bazel` for streamlined Bazel setup.
- Enabled Bazelisk cache, disk cache, and repository cache for improved workflow efficiency.
- Updated `bazel test` to show errors for cleaner test outputs.

Optimize Bazel Workflow with Setup-Bazel Action

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

- Injected `CandleManager.Factory` into `RealTimeDataIngestion` alongside `CandlePublisher.Factory`.
- Enhances modularity and prepares for dynamic `CandleManager` creation.

Add CandleManager Factory to RealTimeDataIngestion

---

src/main/java/com/verlumen/tradestream/ingestion/TradeProcessor.java
src/test/java/com/verlumen/tradestream/ingestion/TradeProcessorTest.java

This PR refactors the `TradeProcessor` class to leverage Google's AutoValue for immutability and cleaner code.  
- Converted `TradeProcessor` to an abstract class annotated with `@AutoValue`.
- Replaced the constructor with a static `create` method for initialization.
- Updated internal fields (`candleIntervalMillis` and `processedTrades`) to be managed by AutoValue.
- Modified `isProcessed` and `getMinuteTimestamp` methods to use AutoValue-managed fields.
- Updated `TradeProcessorTest` to use the new `create` method for initialization.
- Improved immutability and thread safety.
- Cleaner, more concise code with reduced boilerplate.
- Consistent initialization via the `create` factory method.  
This refactor enhances maintainability and aligns with modern Java best practices.

Refactor TradeProcessor to Use AutoValue

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

This update incorporates the `TradeProcessor` into the `RealTimeDataIngestion` class, enabling enhanced processing of trade data within the ingestion pipeline. The constructor of `RealTimeDataIngestion` has been updated to accept a `TradeProcessor` instance, and the build file now includes `trade_processor` as a dependency for seamless integration. This change improves the modularity and functionality of real-time data ingestion.

Integrate `TradeProcessor` into RealTimeDataIngestion 

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD

This update corrects syntax and formatting issues in the `BUILD` file by:  
- Ensuring proper closure of dependency lists with commas and square brackets.  
- Removing redundant lines like `visibility = ["//visibility:public"]` where unnecessary.  
These adjustments improve readability and maintain compliance with Bazel build file standards.

Fix Syntax and Cleanup BUILD File Formatting

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

This update enhances the `RealTimeDataIngestion` class with trade processing functionality:  
1. **Trade Protobuf Integration**:  
- Adds a dependency on `marketdata_java_proto` in the build file to enable the use of the `Trade` Protobuf message.  
2. **Trade Processing Method**:  
- Implements an `onTrade` method to handle trades.  
- Checks if a trade is already processed using `TradeProcessor`.  
- For unprocessed trades, it delegates the processing to `CandleManager`.  
These changes facilitate efficient and structured trade handling while leveraging Protobuf for robust data representation.

Add Trade Processing in RealTimeDataIngestion

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
src/main/java/com/verlumen/tradestream/ingestion/RunMode.java
src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml
src/test/java/com/verlumen/tradestream/ingestion/AppTest.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD

This update introduces the `RunMode` feature, enabling configurable application execution modes (`WET` and `DRY`) to support flexible workflows.  
Key Changes:  
- **RunMode Enum:** Created `RunMode` enum with `WET` (full execution) and `DRY` (validation-only mode).  
- **Command-Line Argument:** Added `--runMode` argument, defaulting to `wet`, to specify the execution mode.  
- **App Integration:** Updated the `App` class to respect the `RunMode`. Execution is skipped in `DRY` mode.  
- **Dependency Injection:** Modified `IngestionModule` to provide the `RunMode` using parsed command-line arguments.  
- **Test Coverage:** Added unit tests for `App` to validate behavior under both `WET` and `DRY` modes.  
- **Container Structure Test:** Updated test configuration to validate `DRY` mode …

Add `RunMode` for Configurable Application Execution

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/ThinMarketTimer.java

This update introduces the `ThinMarketTimer` interface to standardize the management of timers for monitoring thinly traded markets. The changes lay the groundwork for implementing robust timer-based functionality in the real-time data ingestion pipeline.  
1. **`ThinMarketTimer` Interface:**
- Added a new interface `ThinMarketTimer` with two methods:
- `start()`: To initiate the timer.
- `stop()`: To terminate the timer.
2. **Build File Update:**
- Updated the `BUILD` file to include the new `ThinMarketTimer` interface as a standalone library dependency.
This addition provides a clear contract for timer implementations, ensuring consistency and flexibility for future extensions. It simplifies the integration of timer-based logic into components managing thinly traded markets.

Introduce `ThinMarketTimer` Interface for Managing Market Timers

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/ThinMarketTimerTaskImpl.java

This update introduces a new implementation class, `ThinMarketTimerTaskImpl`, extending the `ThinMarketTimerTask` for handling specific actions during thin market conditions. It adds the necessary build configuration and integrates it into the TradeStream system.
1. **`ThinMarketTimerTaskImpl` Implementation**:
- Created the `ThinMarketTimerTaskImpl` class extending `ThinMarketTimerTask`.
- Provides an extensible foundation for defining behavior during thin market conditions.
2. **Updated `BUILD` Configurations**:
- Added a new build target `thin_market_timer_task_impl` in the `BUILD` file.
- Ensures modular integration and future extensibility.
- **Separation of Concerns**: Differentiates the implementation details of the task logic from the scheduling mechanism.
- **Extensibility**: …

Add `ThinMarketTimerTaskImpl` for Thin Market Handling

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java

This update integrates the newly added `ThinMarketTimerTaskImpl` into the `IngestionModule` for dependency injection, ensuring seamless integration into the TradeStream application. It also modifies the `BUILD` file to include dependencies for `thin_market_timer_task` and `thin_market_timer_task_impl` in the appropriate library configurations.
1. **Dependency Injection**:
- Updated `IngestionModule` to bind `ThinMarketTimerTask` to its implementation class `ThinMarketTimerTaskImpl`.
2. **Build Configuration Update**:
- Modified the `BUILD` file to include `:thin_market_timer_task` and `:thin_market_timer_task_impl` as dependencies in the relevant Java library configurations.
- **Streamlined Integration**: Ensures that `ThinMarketTimerTaskImpl` is correctly injected and utilized within the …

Integrate `ThinMarketTimerTaskImpl` into Ingestion Module

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

Reorganized imports in `RealTimeDataIngestion` to ensure they are grouped logically and unnecessary lines are removed. This cleanup improves code readability and aligns with standard conventions for maintaining a concise and organized import section.

Optimize Imports in `RealTimeDataIngestion`

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java

Introduces `ThinMarketTimer` as a dependency in `RealTimeDataIngestion`, enabling scheduled handling of low-activity trading conditions. Updates the `BUILD` file to include the `thin_market_timer` dependency. Enhances functionality, scalability, and code maintainability by centralizing thin market management through dependency injection.

Integrate `ThinMarketTimer` into `RealTimeDataIngestion`

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

This update finalizes the renaming of `RealTimeDataIngestion` to `RealTimeDataIngestionImpl` for consistency with implementation naming conventions. Changes include updating the source file name, build target, and references in the `IngestionModule` bindings. This ensures clarity in distinguishing interfaces from their implementations across the codebase.

Complete Rename of RealTimeDataIngestion to RealTimeDataIngestionImpl  

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestion.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
src/test/java/com/verlumen/tradestream/ingestion/AppTest.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD

This update renames the `MarketDataIngestion` interface to `RealTimeDataIngestion` to better align with its purpose. Corresponding adjustments are made across the application, including class and build file updates. The `App` class now directly uses `RealTimeDataIngestion` instead of its previous abstraction, streamlining references and improving code readability.

Refactor MarketDataIngestion to RealTimeDataIngestion for Better Clarity  

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

This update refactors `RealTimeDataIngestionImpl` to use the newly introduced `CurrencyPairSupply` class, replacing `CurrencyPairSupplier`. Key changes include:  
- **Dependency Injection Update:** A `Provider<CurrencyPairSupply>` is now injected into `RealTimeDataIngestionImpl`.  
- **Method Refactor:** References to `currencyPairSupplier` are replaced with `currencyPairSupply`, aligning with the new abstraction.  
- **Build File Update:** Replaces the `currency_pair_supplier` dependency with `currency_pair_supply` in the Bazel build configuration.  
These changes improve consistency and make better use of the modular `CurrencyPairSupply` class, enhancing maintainability and clarity.

Update RealTimeDataIngestionImpl to Use CurrencyPairSupply 

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CoinMarketCapConfig.java

This update introduces the `CoinMarketCapConfig` class to encapsulate configuration details for integrating with the CoinMarketCap API. Key features include:  
- **AutoValue Integration:** Provides immutability and a clean API for object creation.  
- **Configuration Properties:** Includes `apiKey` for API authentication and `topN` to specify the number of top cryptocurrencies to fetch.  
- **Build Configuration:** Adds a new `coin_market_cap_config` target to the Bazel build system with a dependency on `AutoValue`.  
This addition simplifies managing CoinMarketCap API settings and ensures consistent usage across the application.

Add CoinMarketCapConfig Class for API Configuration

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java

Reverts tradestreamhq/tradestream#208

Revert "Switch to `CurrencyPairSupplyProvider`"

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java

Reverts tradestreamhq/tradestream#226

Revert "Add CoinMarketCap Configuration Support"

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java

Reverts tradestreamhq/tradestream#230

Add CoinMarketCap Configuration Support

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

Enhanced the `start` method in `RealTimeDataIngestionImpl` to include robust error handling for the `connect` method of the `StreamingExchange`.  
- Replaced the blocking call with a reactive `subscribe` block.  
- Logs successful connection and triggers subsequent actions (subscribe to trade streams, start timer).  
- Handles errors by logging the cause and allowing for customizable error responses (e.g., retry or exit).  
Improves application stability and ensures graceful error recovery.

Add Reactive Error Handling to `RealTimeDataIngestionImpl` Connection Logic

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

Add structured logging to RealTimeDataIngestionImpl to track connection status, trade stream subscriptions, and error conditions. This will help with monitoring the health and performance of the real-time ingestion pipeline.

Add logging to RealTimeDataIngestionImpl for better observability

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandleManagerImpl.java

Add detailed logging to CandleManager implementation to track candle creation, updates, and publishing events. This will help diagnose issues with candle generation and thin market handling.

Enhance CandleManager logging for better debugging

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/TradeProcessor.java

Implement logging in TradeProcessor to track trade processing performance metrics and duplicate detection. This will help identify potential bottlenecks and optimize trade handling.

Add performance logging to TradeProcessor

---

src/main/java/com/verlumen/tradestream/ingestion/CandleBuilder.java

Enhances code documentation for core data model classes and builders
to improve code maintainability and developer onboarding. Key changes:
- Adds detailed Javadoc for CandleBuilder explaining its role and behavior
- Documents thread-safety considerations and state management
- Clarifies parameter requirements and validation
- Adds inline comments explaining key calculations and business logic

Add comprehensive documentation for core data models and builders

---

src/main/java/com/verlumen/tradestream/ingestion/TradeProcessor.java

- Added detailed logging to `TradeProcessor` and `CandleKey` to improve observability.  
- Key updates:
- Logs the creation of `TradeProcessor` instances with the configured candle interval.
- Logs detailed information when checking if a trade is processed, including trade ID, timestamp, and currency pair.
- Logs whether a trade is new or a duplicate.
- Added logging for the conversion of timestamps to interval timestamps.
- `CandleKey` creation now logs its parameters.
- Adjusted log levels:
- `INFO` for major state changes (e.g., creation, duplicates).
- `FINE` for detailed operational information.  
- Improves transparency into trade processing logic and state for debugging and monitoring.

Enhance TradeProcessor with Logging

---

src/main/java/com/verlumen/tradestream/ingestion/CandleManagerImpl.java

Enhanced logging in `CandleManagerImpl` to provide detailed visibility into its operations, improving observability and aiding debugging.
- **Initialization:**
- Logs the initialization of `CandleManager` with the specified candle interval.
- **Trade Processing:**
- Logs trade details, including the key, trade ID, price, and volume.
- Logs updates to the candle builder and price tracker for each trade.
- Confirms when an interval is complete and candles are published.
- **Thin Market Handling:**
- Logs the handling of thinly traded markets, including pairs processed and empty candle generation.
- Skips logging for active pairs with trades and highlights cases with no last price available.
- **Candle Publishing:**
- Logs details of published candles, including OHLC and volume data.
- …

 Improved Logging in `CandleManagerImpl`

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

Refactored `RealTimeDataIngestionImpl` to improve logging for better traceability and debugging, covering initialization, startup, shutdown, and core functionality.
- Logs initialization progress, including setting up components like the trade processor and candle publisher.
- Logs connection status with the exchange and the status of trade stream subscriptions and thin market timers.
- Introduces detailed logs during the shutdown process, including:
- Disposal of subscriptions.
- Disconnecting from the exchange.
- Closing the candle publisher with retry logic for better error handling.
- Adds detailed logs for trade conversion and processing:
- Includes trade metadata like ID, price, volume, and timestamp.
- Logs generated UUIDs for trades with missing IDs.
- Differentiates between …

Enhanced Observability in `RealTimeDataIngestionImpl`

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/ThinMarketTimerImpl.java

This update integrates detailed logging into `ThinMarketTimerImpl` using FluentLogger to enhance visibility during timer operations, including start, stop, and error scenarios.
- Logs the initialization and readiness of the `ThinMarketTimer` instance.
- Logs attempts to start the timer.
- Provides detailed information about the scheduling interval.
- Logs success or failure when scheduling the timer task, with error handling for scheduling exceptions.
- Logs attempts to stop the timer.
- Indicates whether the timer was running or inactive during the stop request.
- Logs success or failure when canceling the timer.
- Logs severe-level errors during start or stop operations.
- Includes contextual details about exceptions, aiding in debugging.
- **Improved Traceability:** Logs provide …

Enhanced Logging in `ThinMarketTimerImpl` for Robust Timer Management

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/HttpClientImpl.java

This update introduces detailed and structured logging to `HttpClientImpl` using FluentLogger for enhanced observability during HTTP GET operations. The logs provide insights into initialization, request details, response handling, and error conditions.
- Logs initialization and completion of the `HttpClient` instance to confirm readiness.
- Logs the URL and headers for each GET request at the `INFO` and `FINE` levels.
- Includes logs for setting individual request headers.
- Logs the HTTP response code upon receipt.
- Handles non-200 HTTP response codes with a warning log and descriptive error message.
- Logs the length of the response body for traceability.
- Logs severe-level errors for exceptions thrown during request execution, including stack traces.
- Provides contextual logs for …

Enhanced Logging in `HttpClientImpl` for Improved Debugging and Error Handling

---

src/main/java/com/verlumen/tradestream/ingestion/App.java

This update introduces comprehensive logging into the `App` class to improve clarity and robustness during application initialization, mode selection, and real-time data ingestion.  
1. **Startup Logging**  
- Logs the number of startup arguments received.  
- Provides details on Guice injector initialization and module setup.  
- Captures exceptions during startup with contextual error messages.  
2. **Mode Selection Logging**  
- Clearly logs the selected run mode (`DRY` or `WET`).  
- Explains behavior changes based on the selected mode (e.g., skipping ingestion in `DRY` mode).  
3. **Error Handling**  
- Wraps `realTimeDataIngestion.start()` in a `try-catch` block.  
- Logs severe-level messages for any exceptions during ingestion startup.  
4. **Real-Time Data Ingestion Logging**  
- …

Enhanced Logging for `App` Lifecycle in TradeStream

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java

This update simplifies and improves the structure of `RealTimeDataIngestionImpl` by refactoring the exchange connection logic. It removes the `ProductSubscription` provider from the `IngestionModule` and centralizes its creation within `RealTimeDataIngestionImpl`.
1. **Refactored Exchange Connection:**
- Moved `ProductSubscription` creation logic directly into `RealTimeDataIngestionImpl` using a private `createProductSubscription` method.
- Replaced the injected `ProductSubscription` provider with an inline creation based on the list of currency pairs.
2. **Centralized `connectToExchange`:**
- Added a dedicated `connectToExchange` method that encapsulates connection logic, including `ProductSubscription` creation and blocking connection.
3. **Removed Redundancies:**
- Removed the …

Refactor Exchange Connection and ProductSubscription in `RealTimeDataIngestionImpl`

---

src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java

Enhanced the `CoinbaseStreamingClient` by implementing non-blocking `CompletableFuture` for WebSocket connections, replacing synchronous `join()` calls. Improved logging granularity for better traceability, including finer-grained debug logs for message processing and error handling. Added explicit WebSocket flow control with `request(1)` for better backpressure management. Updated error messages and field references to align with JSON structure. This refactor improves robustness, diagnostics, and async handling of WebSocket connections.

Refactor Coinbase WebSocket Connection Handling with Improved Async Flow and Enhanced Logging

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/CandleBuilder.java
src/main/java/com/verlumen/tradestream/ingestion/CandleManagerImpl.java

Introduced `FluentLogger` to `CandleBuilder` to log key state changes and trade integration during candle construction. Added contextual logs for:
- Initializing the first trade's OHLC values.
- Updating high, low, close prices, and volume.
- Debugging the internal state after each trade.
- Logging the creation of the final immutable candle with all OHLCV data.
This improvement provides better traceability and insights into candle aggregation, aiding debugging and analysis in real-time data processing workflows. Adjusted `BUILD` dependencies to include the logging backend for runtime use.

Enhance `CandleBuilder` with Detailed Logging for OHLCV Construction

---

src/main/java/com/verlumen/tradestream/instruments/Currency.java

This update refines the `Currency` class to better align with industry terminology and improve clarity. Key changes include:
1. **Terminology Update**:  
- Renamed the parameter and field from `name` to `symbol` to accurately represent currency identifiers (e.g., "USD", "BTC").
- Updated associated documentation to reflect this semantic change.
2. **Validation Updates**:  
- Improved exception messaging to specify that the "currency symbol" must not be null or empty.
3. **Implementation Adjustments**:  
- Updated internal logic and AutoValue references to use `symbol` consistently across the class.
This change improves the expressiveness and accuracy of the `Currency` model, ensuring it aligns with standard practices in financial applications.

Refactor Currency Class for Symbol Semantics

---

src/main/java/com/verlumen/tradestream/instruments/Currency.java

Reverts tradestreamhq/tradestream#276

Revert "Refactor Currency Class for Symbol Semantics"

---

src/main/java/com/verlumen/tradestream/instruments/CurrencyPair.java

This update introduces a structured approach to parsing and handling currency pair symbols in the `CurrencyPair` class. Key changes include:
1. **SymbolParts Abstraction**:  
- Added a nested `SymbolParts` class to encapsulate the delimiter and currency components extracted from a currency pair symbol.  
- Improved parsing logic to handle symbol validation and extraction more robustly, ensuring clarity and reusability.
2. **Delimiter Support**:  
- Extended support for recognizing the delimiter used in currency pairs (e.g., `/` or `-`).  
- Added a new `delimiter()` method to retrieve the delimiter for the pair.
3. **Symbol Generation**:  
- Introduced a `symbol()` method that formats the currency pair into its original string representation.
4. **Validation Improvements**:  
- Refined …

Enhance CurrencyPair Parsing with SymbolParts Abstraction

---

src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java

This update improves the `CoinbaseStreamingClient` by explicitly initializing the `WebSocketListener`'s `messageBuffer` through a constructor. Key changes include:
1. **Constructor for WebSocketListener**:
- Introduced a no-argument constructor for the `WebSocketListener` class.
- The constructor initializes the `messageBuffer`, ensuring clarity in the initialization process.
2. **Improved Code Readability**:
- The explicit initialization of `messageBuffer` makes the code more maintainable and easier to understand.
This enhancement ensures better encapsulation and clarity in the WebSocket event handling mechanism. It paves the way for more robust and testable WebSocket interactions.

Enhance `WebSocketListener` Initialization in `CoinbaseStreamingClient`

---

src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java

This refactor introduces the `WebSocketConnector` inner class to modularize the connection logic in `CoinbaseStreamingClient`. Key updates include:
1. **Encapsulation of WebSocket Logic**:
- Extracted WebSocket connection and subscription logic into the new `WebSocketConnector` class.
- Improved separation of concerns by isolating WebSocket-specific tasks.
2. **Simplified `CoinbaseStreamingClient`**:
- Removed the `connectToWebSocket` method from `CoinbaseStreamingClient`, delegating its responsibilities to `WebSocketConnector`.
- Streamlined the `startStreaming` method to call `connector.connect`.
3. **Enhanced Maintainability**:
- Encapsulation of connection and subscription processes makes the codebase more modular and easier to extend.
- Reduces the complexity of the primary class, …

Refactor CoinbaseStreamingClient with WebSocketConnector for Improved Modularity

---

src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java

This update improves the design and structure of the `CoinbaseStreamingClient` class by refactoring inner classes and improving dependency injection for greater modularity and maintainability.  
---
1. **Improved Dependency Injection**:  
- Both `MessageHandler` and `WebSocketConnector` now receive a reference to the parent `CoinbaseStreamingClient` instance during instantiation, simplifying access to shared resources.  
2. **Static Class Refactoring**:  
- Converted `MessageHandler` and `WebSocketConnector` to `static` inner classes with explicit references to `CoinbaseStreamingClient` passed during construction.  
3. **Simplified WebSocketListener Initialization**:  
- Added support for passing the parent `CoinbaseStreamingClient` and product IDs to the `WebSocketListener`, reducing …

Refactor `CoinbaseStreamingClient` for Enhanced Modularity and Maintainability 

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

- **Extracted Method**: Moved streaming logic to `startMarketDataIngestion()` for better readability and separation of concerns.  
- **Cleaner Start Flow**: Simplifies the `start()` method by isolating responsibilities.  
- **Maintainable**: Easier to modify or extend data ingestion logic without impacting initialization.  
Improves code clarity and modularity.

Refactor `RealTimeDataIngestionImpl` to Extract Market Data Ingestion  

---

charts/tradestream/values.yaml

Reverts tradestreamhq/tradestream#304

Revert "Add Kafka Bootstrap Server Argument in `values.yaml` for Helm Chart"

---

src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml

1. Changed `args` to a multiline format.
2. Updated arguments to include `--candlePublisherTopic=fakeTopic` and `--runMode=dry`.

Update `container-structure-test.yaml` for Config Arguments

---

src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml

Remove the default value for `--candlePublisherTopic` in `ConfigArguments.java`.

Remove Default for `--candlePublisherTopic`

---

charts/tradestream/templates/data-ingestion-deployment.yaml
charts/tradestream/values.yaml

1. Updated `data-ingestion-deployment.yaml` to explicitly quote args in the deployment template.
2. Included `--kafka.bootstrap.servers` dynamically in the args list.

Simplify Args and Add Kafka Bootstrap Server

---

charts/tradestream/values.yaml
src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml

1. **`values.yaml`**: Added `--exchangeName=coinbase` to the `dataIngestion.args` list.
2. **`ConfigArguments.java`**: Removed the default value for `--exchangeName`.
3. **`container-structure-test.yaml`**: Included `--exchangeName=coinbase` in test args.

Add Exchange Name Argument and Remove Default

---

charts/tradestream/templates/data-ingestion-deployment.yaml

Reverts tradestreamhq/tradestream#311

Revert "Simplify Args and Add Kafka Bootstrap Server"

---

src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml

Reverts tradestreamhq/tradestream#308

Revert "Remove Kafka Bootstrap Servers Default and Update Tests"

---

charts/tradestream/templates/data-ingestion-deployment.yaml

Reverts tradestreamhq/tradestream#313

Revert "Revert "Simplify Args and Add Kafka Bootstrap Server""

---

src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml

Reverts tradestreamhq/tradestream#314

Revert "Revert "Remove Kafka Bootstrap Servers Default and Update Tests""

---

src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml

Reverts tradestreamhq/tradestream#316

Revert "Revert "Revert "Remove Kafka Bootstrap Servers Default and Update Tests"""

---

charts/tradestream/values.yaml
src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java
src/main/java/com/verlumen/tradestream/ingestion/container-structure-test.yaml

Reverts tradestreamhq/tradestream#307

Revert "Add Exchange Name Argument and Remove Default"

---

src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java

Reverts tradestreamhq/tradestream#305

Revert "Remove Default for `--candlePublisherTopic`"

---

.github/workflows/ci.yaml

1. **`ci.yaml`**:
- Reformatted the Helm installation command for better readability.
- Added line breaks and indentation for arguments passed to the `helm install` command.

Refactor Helm Chart Installation Command in CI Workflow

---

.github/workflows/ci.yaml
charts/tradestream/templates/data-ingestion-deployment.yaml
charts/tradestream/values.yaml

1. **Added Local Docker Registry:**
- Configured a `registry:2` service for image management during testing.
2. **Minikube Integration:**
- Set up Minikube to ensure Kubernetes compatibility.
- Enabled direct loading of locally built images into the Minikube cluster.
3. **Repository-Driven Image Builds:**
- Used Bazel to build `Data Ingestion` images directly from the repository source.
- Ensured the workflow pushes these images to the local registry for testing.
4. **Simplified Helm Deployment:**
- Updated Helm to reference locally built images, ensuring the tested version matches the repository state.
5. **Enhanced Pod Readiness Check:**
- Refined pod status monitoring and log collection for non-ready pods.
1. **Deployment Template (`data-ingestion-deployment.yaml`):**
- Made …

Ensure Reliable CI by Testing Against Repository Version

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java

Enhanced `RealTimeDataIngestionImpl` by logging supported currency pairs during ingestion and introduced test coverage for `supportedCurrencyPairs`.

Add Supported Currency Pairs Logging

---

src/main/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClient.java
src/main/java/com/verlumen/tradestream/instruments/CurrencyPair.java

1. Updated `CurrencyPair` to add a `withCustomDelimiter` method that creates a new instance with a specified delimiter.  
2. Adjusted `symbolWithCustomDelimiter` visibility to private.  
3. Refactored `CoinbaseStreamingClient` to use `withCustomDelimiter` for better encapsulation and clarity.

Improve CurrencyPair Delimiter Handling

---

src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java

Reverts tradestreamhq/tradestream#337

Revert "Simplify Streaming Test Assertions"

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

1. Consolidated `supportedCurrencyPairs` and `requestedPairs` using `ImmutableSet`.  
2. Converted `requestedPairs` to a list for compatibility.

Enhance Supported Currency Pairs Logic

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

1. Logged unsupported pairs by calculating the set difference between requested and supported pairs.

Log Unsupported Currency Pairs

---

src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java

Reverts tradestreamhq/tradestream#341

Revert "Revert "Simplify Streaming Test Assertions""

---

src/test/java/com/verlumen/tradestream/ingestion/KafkaPropertiesTest.java

1. Simplified and clarified test names to focus on specific scenarios.  
2. Grouped tests into sections for:
- Key presence.
- Prefix removal and property values.
- Handling of empty or non-Kafka properties.  
3. Improved arrangement and comments for better readability.  
4. Ensured all scenarios are covered for `KafkaProperties`.

Refactor Kafka Properties Test

---

charts/tradestream/values.yaml

- **Key Changes**:
- Removed redundant `configurationOverrides` and inlined configuration for Kafka.
- Simplified listener configuration under `kafka.listeners`:
- Added explicit `client.protocol` and `controller.protocol` fields with default values set to `PLAINTEXT`.
- **Purpose**:
- Improves readability and maintainability of the Kafka Helm chart configuration.
- Reduces clutter by centralizing listener configurations under a structured format.
- **Impact**:
- No change in default behavior; the updated configuration retains existing functionality while making it more user-friendly.

Simplify Kafka Configuration in Helm Chart

---

src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java

Reverts tradestreamhq/tradestream#364

Revert "Update Default Kafka Security Protocol to SASL_PLAINTEXT"

---

.github/workflows/release.yaml

Reverts tradestreamhq/tradestream#367

Revert "Add Branch Name to Git Tags in Release Workflow"

---

src/main/java/com/verlumen/tradestream/ingestion/ConfigArguments.java

Reverts tradestreamhq/tradestream#329

Revert "Remove Default Kafka Topic and Enforce Explicit Configuration"

---

charts/tradestream/values.yaml

- Updated the `strategyEngine.image.repository` and `strategyEngine.image.tag` fields in `values.yaml`:
- Added quotes (`"`) around the values for consistency.
- Standardizes YAML formatting by quoting all string values.
- Improves compatibility with YAML parsers that might misinterpret unquoted strings.
- Ensures uniformity in the Helm chart configuration.
- Prevents potential parsing errors in strict YAML environments.

Standardize Repository and Tag Strings in Helm Chart

---

src/main/java/com/verlumen/tradestream/strategies/movingaverages/TripleEmaCrossoverStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
src/test/java/com/verlumen/tradestream/strategies/movingaverages/TripleEmaCrossoverStrategyFactoryTest.java

This PR introduces the `TripleEmaCrossoverStrategyFactory`, enabling the creation of trading strategies based on a triple EMA crossover. The strategy generates entry and exit signals when short EMA crosses medium EMA or medium EMA crosses long EMA, and vice versa. Comprehensive unit tests are included to validate functionality and parameter constraints.
**Changes Include:**  
1. **Factory Implementation:**
- `TripleEmaCrossoverStrategyFactory` added to the `movingaverages` package.
- Validates EMA periods to ensure proper ordering and positive values.
- Uses `BaseStrategy` to manage entry and exit rules.
- Generates descriptive strategy names with EMA periods for better debugging.
2. **Unit Tests:**
- Added `TripleEmaCrossoverStrategyFactoryTest`.
- Validates strategy type.
- Verifies …

Add `TripleEmaCrossoverStrategyFactory` with Comprehensive Unit Tests

---

src/main/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
src/test/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactoryTest.java

This PR introduces the `SmaEmaCrossoverStrategyFactory` for creating strategies that identify trading opportunities based on the crossover between SMA (Simple Moving Average) and EMA (Exponential Moving Average) indicators. It also includes comprehensive unit tests to verify functionality and parameter validation.
**Changes Include:**
1. **Implementation:**
- Added `SmaEmaCrossoverStrategyFactory` to the `movingaverages` package.
- Validates SMA and EMA periods to ensure they are positive values.
- Implements entry and exit rules based on SMA crossing above or below EMA.
- Uses `BaseStrategy` to define and manage strategy behavior.
2. **Unit Tests:**
- Added `SmaEmaCrossoverStrategyFactoryTest` to ensure correctness and robustness.
- Tests for:
- Proper detection of SMA and EMA crossovers …

Add `SmaEmaCrossoverStrategyFactory` with Unit Tests

---

src/main/java/com/verlumen/tradestream/strategies/StrategyFactory.java
src/main/java/com/verlumen/tradestream/strategies/movingaverages/SmaEmaCrossoverStrategyFactory.java
src/main/java/com/verlumen/tradestream/strategies/oscillators/SmaRsiStrategyFactory.java

This PR introduces several updates and refinements to the `StrategyFactory` interface and its implementations. It standardizes the creation of strategies, improves naming conventions for strategies, and removes unnecessary boilerplate methods. The goal is to enhance code clarity, maintainability, and adherence to best practices.
1. **Refactored `StrategyFactory` Interface**:
- Removed the `createStrategy` method that accepted `Rule` objects directly to streamline the interface.
- Simplified method signatures and removed unused imports.
2. **Updated `SmaEmaCrossoverStrategyFactory`**:
- Converted the class to `final` for immutability and clarity.
- Added a formatted strategy name in the `BaseStrategy` creation logic, including the SMA and EMA periods.
3. **Refactored …

Refactor Strategy Factory Interfaces and Update Strategy Creation Logic

---

src/main/java/com/verlumen/tradestream/strategies/movingaverages/MomentumIndicator.java
src/main/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/movingaverages/BUILD
src/test/java/com/verlumen/tradestream/strategies/movingaverages/MomentumSmaCrossoverStrategyFactoryTest.java

This PR introduces a new strategy factory, `MomentumSmaCrossoverStrategyFactory`, and a custom indicator, `MomentumIndicator`, to enable momentum-based trading strategies in the TradeStream system.
1. **Custom Momentum Indicator**:
- Added a new `MomentumIndicator` that calculates price momentum as a percentage change over a specified period.
- Provides an essential building block for momentum-based strategies.
2. **Momentum-SMA Crossover Strategy**:
- Added `MomentumSmaCrossoverStrategyFactory` to create strategies based on the crossover between the `MomentumIndicator` and its Simple Moving Average (SMA).
- Entry Rule: Momentum crosses above its SMA and is positive.
- Exit Rule: Momentum crosses below its SMA and is negative.
3. **Testing Enhancements**:
- Added …

Add Momentum-SMA Crossover Strategy and Custom Momentum Indicator

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
third_party/BUILD

This PR updates the `ingestion/BUILD` file to replace hardcoded Maven dependencies with modularized third-party library definitions from the `third_party/BUILD` file. Additionally, the `third_party/BUILD` file has been refined for clarity and reusability.
1. **Dependency Refactoring in `ingestion/BUILD`**:
- Replaced direct Maven dependency declarations with corresponding targets from `third_party/BUILD` (e.g., `flogger`, `guava`, `guice`, etc.).
- Ensured runtime dependencies also use modularized definitions (e.g., `flogger_system_backend`).
2. **Updates to `third_party/BUILD`**:
- Removed the `neverlink = 1` attribute from the `flogger_system_backend` target for consistency.
- No other functional changes were made, ensuring compatibility across all build targets.
3. **Improved Build …

Refactor `ingestion/BUILD` to Use Modularized Third-Party Dependencies

---

MODULE.bazel

This PR revises the configuration for Python dependencies in the `MODULE.bazel` file to improve dependency management and clarity.  
1. **Pip Extension Update:**  
- Replaced the deprecated `@rules_python//python/extensions:pip.bzl` extension with the updated `@rules_python//python:extensions.bzl`.  
2. **Streamlined Pip Repository Setup:**  
- Removed the redundant `use_repo(pip, "whl_mods_hub")` configuration.  
3. **Lockfile Integration:**  
- Introduced a `requirements_lock` file reference (`//third_party:requirements_lock.txt`) to ensure reproducible builds by locking Python dependencies for `python_version = "3.10"`.  
- **Modernized Setup:**  
- Aligns with the latest `rules_python` standards, ensuring compatibility with recent updates and best practices.  
- **Simplified …

Update Pip Extension and Configure Python Dependency Management

---

protos/backtesting.proto
src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/BacktestRunnerImpl.java
src/main/java/com/verlumen/tradestream/backtesting/BacktestServiceImpl.java
src/test/java/com/verlumen/tradestream/backtesting/BUILD
src/test/java/com/verlumen/tradestream/backtesting/BacktestRunnerImplTest.java
src/test/java/com/verlumen/tradestream/backtesting/BacktestServiceImplTest.java

This update refactors the backtesting system and introduces a new Genetic Algorithm (GA) service for parameter optimization. The changes focus on enhancing modularity, simplifying the service interface, and expanding functionality.
1. **Proto Definitions:**
- Consolidated `BacktestRequest` to include candles, strategy type, and universal strategy parameters (`google.protobuf.Any`).
- Introduced `GAOptimizationRequest` and `BestStrategyResponse` for the new GA service.
- Added `GAService` to support genetic algorithm-based parameter optimization.
- Simplified proto syntax by changing from `edition = "2023"` to `syntax = "proto3"`.
2. **Service Implementations:**
- Renamed `ParameterizedBacktestServiceImpl` to `BacktestServiceImpl` for clarity.
- Unified backtest methods into a single …

Backtest Service Refactoring and Genetic Algorithm Integration

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/GAServiceImpl.java
src/main/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestrator.java

This update introduces a Genetic Algorithm (GA) service to the backtesting framework, enabling automated parameter optimization for trading strategies. The implementation leverages a modular design to extend functionality without disrupting existing systems.
---
1. **Bazel Build Configuration:**
- Added `ga_service_impl` and `genetic_algorithm_orchestrator` to the `BUILD` file with appropriate dependencies, including gRPC and the genetic algorithm orchestrator interface.
- Integrated the `jenetics` library for evolutionary computation support.
2. **New Classes:**
- **`GAServiceImpl`:** Implements the `GAService` gRPC service, handling optimization requests.
- Calls the orchestrator to perform parameter optimization.
- Uses `BacktestService` iteratively for candidate evaluation.
- Provides …

Integration of Genetic Algorithm Service for Strategy Optimization

---

src/test/java/com/verlumen/tradestream/backtesting/BUILD
src/test/java/com/verlumen/tradestream/backtesting/GAServiceImplTest.java

This update introduces a comprehensive test suite for the `GAServiceImpl` class, validating the genetic algorithm-based optimization workflow in the TradeStream backtesting module.  
- **`BUILD` File Changes:**  
- Added a `java_test` target for `GAServiceImplTest` with all necessary dependencies, including `mockito_core`, `grpc_java_api`, and `truth`.  
- **`GAServiceImplTest.java` Highlights:**  
- **Success Scenario:** Verifies that `requestOptimization` processes requests and completes with the expected response when `GeneticAlgorithmOrchestrator` succeeds.  
- **Error Handling:** Ensures that internal errors thrown by `GeneticAlgorithmOrchestrator` result in appropriate `INTERNAL` gRPC errors being sent to the client.  
- **Test Utilities:** Includes a helper method to generate valid …

Add Unit Tests for GAServiceImpl in TradeStream Backtesting

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/BacktestServiceClient.java

This update adds a `BacktestServiceClient` to the TradeStream backtesting module to provide an interface for interacting with the backtesting service.  
- **`BUILD` File Updates:**  
- Added a new `java_library` target named `backtest_service_client`.  
- Declared dependency on the `backtesting_java_proto` for seamless interaction with backtest protobuf definitions.  
- **`BacktestServiceClient` Highlights:**  
- Defines a single method, `runBacktest`, which takes a `BacktestRequest` and returns a `BacktestResult`.  
- Offers a clean and extensible interface to standardize client interactions with the backtesting service.  
This addition lays the groundwork for modular and testable backtesting client implementations, improving maintainability and integration potential.

Introduce BacktestServiceClient for Enhanced Backtesting Interactions 

---

src/test/java/com/verlumen/tradestream/ingestion/CoinbaseStreamingClientTest.java

- **Context:** This change refactors the import statements in `CoinbaseStreamingClientTest.java` for improved code organization and readability.
- **Changes:**
- Reordered import statements to group similar types and improve visual clarity.
- No functional changes were made to the test logic.
- Improves code maintainability by making imports easier to scan.
- Has no impact on the functionality or behavior of the test.

Refactor Imports in `CoinbaseStreamingClientTest`

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/GAServiceClient.java

- **Context:** This change introduces the `GAServiceClient` interface, which defines a client for interacting with the Genetic Algorithm (GA) service. This provides a clear abstraction for triggering parameter optimization runs.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/backtesting/GAServiceClient.java`: This new interface defines the `requestOptimization` method for initiating a parameter optimization run.
- Modified `src/main/java/com/verlumen/tradestream/backtesting/BUILD`: Added a build target for the `GAServiceClient`, making it available for use as a dependency.
- Provides a clear and consistent API for clients to request parameter optimization via the GA service.
- Decouples the clients from the specific implementation of the GA service.
- …

Introduce `GAServiceClient` Interface for Genetic Algorithm Service

---

protos/strategies.proto

- **Context:** This change refactors the whitespace in `strategies.proto` file to improve readability.
- **Changes:**
- Only whitespace changes were introduced.
- No functional changes were made to the code.
- Improves code maintainability by making the file more readable.
- Has no impact on the functionality or behavior of the code.

Whitespace Changes in `strategies.proto`

---

src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java

- **Context:** This change introduces the concrete implementation of the `StrategyEngine` interface: `StrategyEngineImpl`. This component is responsible for coordinating strategy optimization, candlestick processing, and trade signal generation.
- **Changes:**
- Created `src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java`: This new class implements the `StrategyEngine` interface. It currently contains placeholder implementations, throwing `UnsupportedOperationException`.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a build target for `strategy_engine_impl` and its dependencies.
- Provides a concrete implementation of the `StrategyEngine` interface, allowing for further development of its logic.
- Sets the foundation for …

Introduce `StrategyEngineImpl` Implementation

---

src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java

- **Context:** This change applies formatting to `StrategyEngineImpl.java`, ensuring code style consistency.
- **Changes:**
- The changes are purely whitespace and formatting.
- No functional changes were made to the class logic.
- Improves code maintainability by adhering to a consistent code style.
- Enhances the readability of the code.

Apply Formatting to `StrategyEngineImpl.java`

---

src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java

- **Context:** This change adds a dependency on `GAServiceClient` to `StrategyEngineImpl`. This dependency allows the Strategy Engine to trigger the Genetic Algorithm service for parameter optimization.
- **Changes:**
- Modified `src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java`: Added a `GAServiceClient` field and updated the constructor to inject it.
- Modified `src/main/java/com/verlumen/tradestream/strategies/BUILD`: Added a dependency on `//src/main/java/com/verlumen/tradestream/backtesting:ga_service_client` to the `strategy_engine_impl` target.
- Enables `StrategyEngineImpl` to initiate parameter optimization through the GA service.
- Sets up the necessary dependency for the future implementation of the strategy optimization logic.

Add `GAServiceClient` Dependency to `StrategyEngineImpl`

---

src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java

- **Context:** The `StrategyEngineImpl` class required an internal mechanism to handle strategy optimization, with a placeholder implementation for future development.  
- **Changes:**  
- Added a private `optimizeAndSelectBestStrategy` method, intended to perform optimization for all strategy types.  
- Updated the `optimizeStrategy` method to call `optimizeAndSelectBestStrategy` instead of throwing an `UnsupportedOperationException`.  
- Retained `UnsupportedOperationException` in `optimizeAndSelectBestStrategy` as a placeholder for the actual optimization logic.  
- No changes were made to the `getCurrentStrategy` method, which still throws `UnsupportedOperationException`.  
- **Benefits:**  
- Provides a clear and structured entry point for implementing strategy optimization logic. …

Introduce `optimizeAndSelectBestStrategy` in `StrategyEngineImpl`

---

src/test/java/com/verlumen/tradestream/backtesting/BacktestServiceImplTest.java

- **Context:** This change applies formatting to the `BacktestServiceImplTest.java` file to improve its readability. It also improves the test assertions to verify the correct values are in the created `BarSeries` instead of just the number of bars.
- **Changes:**
- Applied formatting to improve readability.
- Improved the `verify_barSeriesCreation` test to assert the correctness of values in the `BarSeries` and not just the size.
- No functional changes have been made.
- Improves code maintainability and readability by adhering to a consistent style.
- Enhances the quality of the test by verifying the correctness of the generated bar series.

Format `BacktestServiceImplTest.java` and Improve Assertions

---

src/main/java/com/verlumen/tradestream/execution/BUILD
src/main/java/com/verlumen/tradestream/execution/ExecutionModule.java

Reverts tradestreamhq/tradestream#540

Introduce `ExecutionModule` for Runtime Configuration

---

src/main/java/com/verlumen/tradestream/strategies/oscillators/SmaRsiStrategyFactory.java

- **Context:** This change applies formatting to `SmaRsiStrategyFactory.java`, ensuring code style consistency.
- **Changes:**
- The changes are purely whitespace and formatting.
- No functional changes were made to the class logic.
- Improves code maintainability by adhering to a consistent code style.
- Enhances the readability of the code.

Format `SmaRsiStrategyFactory` for Consistency

---

src/main/java/com/verlumen/tradestream/time/Timestamps.java
src/test/java/com/verlumen/tradestream/time/TimestampsTest.java

Reverts tradestreamhq/tradestream#576

Revert "Add `toTimestamp(long)` Method to `Timestamps`"

---

src/main/java/com/verlumen/tradestream/strategies/StrategyEngine.java

This update enhances the `StrategyEngine` interface by introducing a `Factory` interface, enabling dynamic creation of `StrategyEngine` instances with configurable topics.  
1. **Factory Interface**:  
- Added `StrategyEngine.Factory` to facilitate the creation of `StrategyEngine` instances.  
- Factory method `create` accepts `candleTopic` and `signalTopic` as parameters for customized initialization.  
- **Flexibility**: Allows dynamic configuration of `StrategyEngine` with specific topics for candles and signals.  
- **Modularity**: Simplifies integration with dependency injection frameworks or runtime configurations.  
- **Extensibility**: Prepares the interface for potential enhancements without altering existing implementations.  
This addition is backward-compatible and enhances …

Add Factory Interface to StrategyEngine

---

src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java

This update refactors the `IngestionModule` to improve readability and maintainability by replacing `Namespace` lookups with strongly-typed parameters, simplifying dependency injection, and consolidating configuration logic.  
- **Strong Typing:** Introduced explicitly typed fields (`candlePublisherTopic`, `coinMarketCapApiKey`, etc.) replacing runtime string lookups.
- **Centralized Construction:** Added a static factory method to initialize `IngestionModule` from `Namespace`.
- **Enhanced Dependency Injection:** Replaced repetitive `Namespace` lookups with pre-parsed fields in `@Provides` methods.
- **Simplified Kafka Integration:** Retained existing Kafka configurations while enhancing maintainability.
- **Formatting Improvements:** Organized method definitions and module installations …

Simplify `IngestionModule` with Strong Typing and Enhanced Configuration  

---

charts/tradestream/templates/data-ingestion-deployment.yaml
charts/tradestream/values.yaml
src/main/java/com/verlumen/tradestream/ingestion/App.java

This update simplifies the Helm chart for the Data Ingestion deployment and enhances the argument parsing in the Java application, improving maintainability and usability.  
1. **Helm Chart Refactor:**
- Changed `dataIngestion.args` in `values.yaml` to a key-value structure for better readability and scalability.
- Updated `data-ingestion-deployment.yaml` to dynamically generate arguments based on key-value pairs.
- Retained support for the Kafka bootstrap server argument.
2. **Java Application Updates:**
- Added `String.class` type enforcement for the `--candlePublisherTopic` argument in `App.java`.
3. **Benefits:**
- **Improved Scalability:** Key-value argument structure allows easier addition or modification of arguments.
- **Consistency:** Aligns Helm chart values with argument …

Improve Data Ingestion Helm Chart and Argument Parsing 

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java

This refactor centralizes all configuration values for `IngestionModule` into a new `IngestionConfig` class, streamlining initialization and improving maintainability.  
1. **Introduced `IngestionConfig`:**  
- Created a new `record` class to encapsulate all configuration values (e.g., `candlePublisherTopic`, `coinMarketCapApiKey`, `kafkaProperties`).  
- Simplifies parameter passing and improves code readability.
2. **Updated `App.java`:**  
- Extracted configuration parsing logic into an `IngestionConfig` instance.  
- Passed `IngestionConfig` to `IngestionModule.create()`.
3. **Simplified `IngestionModule`:**  
- Replaced individual configuration fields with a single `IngestionConfig` object.  
- Updated provider methods to access configuration values through `ingestionConfig()`.
4. …

Refactor `IngestionModule` with Centralized `IngestionConfig`  

---

charts/tradestream/templates/data-ingestion-deployment.yaml
charts/tradestream/values.yaml
src/main/java/com/verlumen/tradestream/ingestion/App.java

Reverts tradestreamhq/tradestream#589

Revert "Improve Data Ingestion Helm Chart and Argument Parsing "

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/strategies/App.java

This update introduces a delay mechanism in the `RunMode.DRY` execution path for both the **Data Ingestion** and **Strategies** applications, ensuring sufficient visibility into logs during dry runs and a graceful shutdown process.  
1. **Added Sleep in Dry Run Mode:**
- In both `ingestion/App.java` and `strategies/App.java`, the system now sleeps for one minute before exiting dry run mode to provide better observability.
- Implemented `Thread.sleep(60_000L)` with error handling for interruptions.
2. **Graceful Error Handling:**
- Captures and logs `InterruptedException` with detailed warnings.
- Restores the thread's interrupted status using `Thread.currentThread().interrupt()`.
3. **Log Enhancements:**
- Additional log messages to notify when the application is pausing and resuming …

Enhance Dry Run Behavior with Graceful Exit Delay 

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/kafka/BUILD
src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java
src/test/java/com/verlumen/tradestream/kafka/BUILD
src/test/java/com/verlumen/tradestream/kafka/KafkaPropertiesTest.java

This update refactors the `KafkaProperties` class to simplify its construction and testing by transitioning from map-based property extraction to explicit parameter definitions.  
1. **Explicit Parameterization in `KafkaProperties`:**  
- Replaced the `createFromKafkaPrefixedProperties` method with a constructor accepting explicit parameters for Kafka configuration.
- Simplified property handling by directly setting known Kafka properties.
2. **Updated `App.java`:**  
- Adjusted `KafkaProperties` instantiation in the ingestion app to use the new constructor, improving readability and type safety.
3. **Refined Tests for `KafkaProperties`:**  
- Eliminated dynamic map construction in tests.
- Simplified test cases by using direct instantiation of `KafkaProperties`.
4. **Dependency …

Refactor `KafkaProperties` for Explicit Parameter Handling and Improved Testing  

---

charts/tradestream/templates/strategy-engine.yaml
charts/tradestream/values.yaml

This update refines the argument formatting for the **Strategy Engine** in the Helm chart configuration, ensuring consistency and better readability.  
1. **Revised Argument Handling in Deployment Template:**
- Updated the `strategy-engine.yaml` template to:
- Use clean and readable syntax for argument rendering with `range`.
- Eliminate unnecessary quoting for each argument.
2. **Modified Arguments in `values.yaml`:**
- Changed the `--runMode=wet` format to a split-key-value format:
- `"--runMode"` and `"wet"` are now provided as separate arguments for better flexibility and compatibility.
- **Improved Readability:** Arguments are easier to interpret in both the template and values file.
- **Enhanced Flexibility:** The split format allows more straightforward handling of arguments in …

Standardize Strategy Engine Argument Formatting

---

charts/tradestream/templates/data-ingestion-deployment.yaml
charts/tradestream/values.yaml

This update refines the configuration for **Data Ingestion** in the Helm chart, ensuring consistent and explicit argument formatting across both the deployment template and `values.yaml` file.  
1. **Deployment Template (`data-ingestion-deployment.yaml`):**
- Adjusted the argument loop to use a cleaner and more readable `range` syntax without unnecessary quoting.
2. **Values File (`values.yaml`):**
- Reformatted arguments from inline key-value pairs (e.g., `--runMode=wet`) to separate key and value entries:
- Example: `"--runMode"` and `"wet"` are now distinct list items.
- Enhanced readability and clarity of argument definitions.
- **Improved Readability:** Simplifies understanding of the argument structure in both the deployment template and values file.
- **Enhanced Maintainability:** …

Standardize Data Ingestion Argument Formatting in Helm Chart

---

charts/tradestream/templates/data-ingestion-deployment.yaml
charts/tradestream/templates/strategy-engine.yaml
charts/tradestream/values.yaml

This update improves the argument formatting in the Helm chart templates and `values.yaml` file, enhancing readability and standardizing the configuration.
1. **Deployment Templates:**
- **Data Ingestion (`data-ingestion-deployment.yaml`):**
- Adjusted the `range` loop formatting for arguments to include `-` for better YAML alignment and consistency.
- Removed redundant hardcoded Kafka bootstrap servers argument.
- **Strategy Engine (`strategy-engine.yaml`):**
- Updated the `range` loop to use `-` for alignment consistency with the data ingestion template.
2. **Values File (`values.yaml`):**
- Updated `dataIngestion.args` to follow the inline key-value format:
- Replaced structured keys with a flat list of arguments (`--key=value`).
- Reformatted `strategyEngine.args` to match the same …

Refactor Helm Chart Argument Formatting for Data Ingestion and Strategy Engine  

---

src/main/java/com/verlumen/tradestream/ingestion/App.java

Reverts tradestreamhq/tradestream#600

Revert "Remove Default Value for `--candlePublisherTopic` in Data Ingestion App"

---

charts/tradestream/values.yaml
src/main/java/com/verlumen/tradestream/strategies/App.java
src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
src/main/java/com/verlumen/tradestream/strategies/StrategyEngine.java
src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java
src/main/java/com/verlumen/tradestream/strategies/container-structure-test.yaml

Reverts tradestreamhq/tradestream#587

Revert "Enhance `StrategyEngine` with Configurable Topics and Assisted Injection"

---

charts/tradestream/values.yaml
src/main/java/com/verlumen/tradestream/strategies/App.java
src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java
src/main/java/com/verlumen/tradestream/strategies/StrategyEngine.java
src/main/java/com/verlumen/tradestream/strategies/StrategyEngineImpl.java
src/main/java/com/verlumen/tradestream/strategies/container-structure-test.yaml

Reverts tradestreamhq/tradestream#607

Revert "Revert "Enhance `StrategyEngine` with Configurable Topics and Assisted Injection""

---

src/main/java/com/verlumen/tradestream/pipeline/App.java

This PR contains no code changes, it just includes formatting changes.
- No code changes
- N/A - This is a formatting change

No code changes, formatting changes only

---

src/main/java/com/verlumen/tradestream/pipeline/App.java
src/main/java/com/verlumen/tradestream/pipeline/BUILD
src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java

This PR integrates Google Guice into the `App` class to enhance modularity and testability.
- **App.java:**
- Imported `com.google.inject.Inject`.
- Made the `App` class `final`.
- Added an `@Inject` constructor.
- Updated the `main` method to use `PipelineModule`.
```diff
+import com.google.inject.Inject;
-public class App {
+final class App {
+  @Inject
+  App() {}
-    App app = Guice.createInjector().getInstance(App.class);
+    App app = Guice.createInjector(PipelineModule.create()).getInstance(App.class);
```
- **BUILD File:**
- Added `":pipeline_module"` to dependencies.
```diff
+    ":pipeline_module",
```
- **PipelineModule.java:**
- Created `PipelineModule` with a `create()` method.
```java
class PipelineModule extends AbstractModule {
static PipelineModule …
```

Add Guice Dependency Injection to App Class

---

src/main/java/com/verlumen/tradestream/pipeline/App.java
src/main/java/com/verlumen/tradestream/pipeline/BUILD
src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java

This PR enhances the data pipeline by introducing Kafka integration and configurable dynamic read options. Key changes include:
1. **Kafka Integration**:
- Adds support for reading data from Kafka topics using a newly created `KafkaReadTransform` class.
- Provides configurable options for Kafka, including `bootstrap.servers`, `candleTopic`, and dynamic read intervals.
2. **PipelineModule Enhancements**:
- Refactors `PipelineModule` to use dependency injection for `KafkaReadTransform`.
- Introduces configuration via `PipelineModule.create()` for Kafka bootstrap servers, topic name, and dynamic read intervals.
3. **Options Class Updates**:
- Adds new command-line arguments for Kafka integration:
- `--bootstrapServers`: Specify Kafka bootstrap servers (default: `localhost:9092`).
- …

Add Kafka Integration to Data Pipeline with Dynamic Read Configuration

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/kafka/KafkaModule.java

Reverts tradestreamhq/tradestream#646

Revert "Use default Kafka properties in Kafka module"

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java

Reverts tradestreamhq/tradestream#645

Revert "Use default Kafka properties in Ingestion app"

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/kafka/KafkaProperties.java

Reverts tradestreamhq/tradestream#650

Revert "Revert "Use default Kafka properties in Ingestion app""

---

src/main/java/com/verlumen/tradestream/ingestion/App.java
src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/IngestionConfig.java
src/main/java/com/verlumen/tradestream/ingestion/IngestionModule.java
src/main/java/com/verlumen/tradestream/kafka/KafkaModule.java

Reverts tradestreamhq/tradestream#649

Revert "Revert "Use default Kafka properties in Kafka module""

---

.github/workflows/ci.yaml

This PR enhances the CI workflow by adding more detailed logging, debugging information, and improved error handling. It provides better visibility into the build and deployment processes, making it easier to identify and fix issues.
- Added a "Setup Debugging Environment" step to set up immediate failure and command echoing.
- Added verbose logging to the `minikube start` command.
- Added dry-run to the create namespace command.
- Added a tee to capture output of `kubectl create secret`
- Added a logger to capture all output of the bazel command.
- Added `docker images` to the log output.
- Tee'd the output from the minikube load and kubectl wait commands
- Added a trap to output cert-manager diagnostics.
- Added a trap to output helm diagnostics.
- Added a trap to output failure …

Improve CI workflow logging and debugging

---

.github/workflows/ci.yaml

Reverts tradestreamhq/tradestream#658

Revert "Update ci.yaml"

---

src/main/java/com/verlumen/tradestream/pipeline/App.java
src/main/java/com/verlumen/tradestream/pipeline/BUILD

This PR integrates **Protocol Buffers (Protobuf)** for structured Kafka message processing within the **TradeStream data pipeline**. It introduces **protobuf-based parsing for market data candles** while ensuring backward compatibility with raw byte messages.
1. **Added Protobuf Parsing for Market Data Candles**
- Introduced `Candle.parseFrom(element)` to decode messages into structured objects.
- Allows real-time **deserialization of market data** instead of relying on raw strings.
- Prints both the **original string and parsed Protobuf message** for debugging.
2. **Improved Error Handling in Kafka Processing**
- Catches **InvalidProtocolBufferException** explicitly for parsing errors.
- Logs **unexpected runtime exceptions** to prevent silent failures.
3. **Updated Build Dependencies** …

Enhance Kafka Data Processing with Protocol Buffers and Protobuf Parsing

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

This PR improves the trade processing logic in `RealTimeDataIngestionImpl` by refactoring the conditional flow to enhance clarity and efficiency.
---
- **Previous logic:**  
- Checked if a trade **was NOT processed** before logging and processing.
- **Updated logic:**  
- **Checks if a trade IS processed early**, logs the skip message, and **returns immediately**.
- This prevents unnecessary indentation and **clarifies the control flow**.
- Reduces **nested conditions** to make the function **more readable**.
- Eliminates redundant logging and ensures **trades are only processed if necessary**.
- The fundamental behavior remains the same:  
- **Duplicate trades are ignored.**  
- **New trades are logged and processed.**

Optimize Trade Processing Logic in `RealTimeDataIngestionImpl`

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java

This PR enhances the `MarketDataModule` by explicitly binding `CandleAuthor` and enabling assisted injection for `TradePublisher` using `FactoryModuleBuilder`. This improves dependency injection management, making it more robust and modular.
---
1. **Updated `MarketDataModule.java`:**
- Added a binding for `CandleAuthor` using `.toProvider(CandleAuthor::create)`.
- Introduced `FactoryModuleBuilder` to enable assisted injection for `TradePublisher`.
2. **Updated `BUILD` Dependencies:**
- Added `candle_author`, `trade_publisher`, and `trade_publisher_impl` to the `market_data_module` target.
- Included `guice_assistedinject` for assisted injection support.
---
✅ **Improves Dependency Management** — Explicit bindings make it clear how dependencies are provided.  
✅ **Enhances Testability** — …

Enhance `MarketDataModule` with Assisted Injection and Explicit Bindings

---

src/main/java/com/verlumen/tradestream/marketdata/ParseTrades.java

This PR enhances the `ParseTrades` transformation by adding structured logging for successfully parsed trade messages. This provides better visibility into the processing pipeline by logging key trade attributes such as timestamp, currency pair, and volume.
---
1. **Added Structured Logging for Trade Messages:**  
- Logs the timestamp, currency pair, and volume of successfully parsed trades using FluentLogger.
2. **Preserved Existing Error Handling:**  
- Invalid trades continue to be logged at the `SEVERE` level without affecting pipeline execution.
---
✅ **Improves Observability** – Helps debug data pipeline issues and monitor trade ingestion in real-time.  
✅ **Minimal Performance Overhead** – Logging is lightweight and only occurs on successful parsing.  
✅ **Maintains Robust Error …

Enhance `ParseTrades` with Logging for Trade Metadata  

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

Removes unnecessary initialization logs from `RealTimeDataIngestionImpl`, keeping logging concise while maintaining clarity. 🚀

Remove Redundant Logging in `RealTimeDataIngestionImpl`  

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/ParseTrades.java
src/main/java/com/verlumen/tradestream/pipeline/App.java
src/main/java/com/verlumen/tradestream/pipeline/BUILD

This PR **integrates trade parsing into the data pipeline** by introducing the `ParseTrades` transform, which **converts Kafka byte stream data into structured `Trade` protobuf messages**. The goal is to enhance **data processing capabilities** within the **market data ingestion pipeline**.
---
1. **Added `ParseTrades` Transform** (`ParseTrades.java`)
- A new Beam `PTransform` that **deserializes byte arrays into `Trade` protobuf objects**.
- Uses **Google Protobuf** for structured message handling.
- Includes **Flogger-based logging** for error handling.
- Now **injectable** using Guice for better modularity.
2. **Updated `App.java` to Integrate Trade Parsing**
- Injects `ParseTrades` and applies it after reading from Kafka.
- First **prints raw byte data** (`PrintBytesAsString`).
- …

Integrate Trade Parsing into Pipeline with `ParseTrades` Transform

---

src/main/java/com/verlumen/tradestream/pipeline/BUILD
src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml

This PR enhances the **dry-run mode** for the TradeStream pipeline by replacing **dummy byte values** with a properly structured **Protobuf-based `Trade` object**. This improves testing and debugging by ensuring that **mock trade data** closely resembles real-world messages.
---
1. **Introduced `DRY_RUN_TRADE`** in `PipelineModule.java`
- Uses **Google Protobuf** to create a **fake but structured trade object**.
- Fields include:
- **Exchange:** `"FakeExchange"`
- **Currency Pair:** `"DRY/RUN"`
- **Trade ID:** `"trade-123"`
- **Timestamp:** **`1234567 ms`** (mock timestamp)
- **Price:** `$50,000`
- **Volume:** `0.1`
2. **Replaced Dummy Bytes with Protobuf-encoded Trade**
- The dry-run transform (`DryRunKafkaReadTransform`) now **outputs Protobuf-serialized trades instead of generic …

Enhance Pipeline Dry Run with Protobuf-based Trade Simulation

---

src/main/java/com/verlumen/tradestream/ingestion/BUILD
src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java
src/test/java/com/verlumen/tradestream/ingestion/BUILD
src/test/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImplTest.java

This PR **removes the `ThinMarketTimer` dependency** from `RealTimeDataIngestionImpl`, simplifying the ingestion pipeline by eliminating unnecessary scheduling logic.
---
✅ **Removed `ThinMarketTimer`** from:
- **`RealTimeDataIngestionImpl`** (constructor, start, and shutdown methods).
- **Tests (`RealTimeDataIngestionImplTest`)** that validated `ThinMarketTimer` functionality.
- **`BUILD` files** to clean up unused dependencies.
---
🚀 **Simplifies system architecture** by removing an unused component.  
📉 **Reduces runtime overhead** by eliminating unnecessary scheduled tasks.  
✅ **Improves test reliability** by avoiding dependency on external timers.  
---
1. **Verify that removal does not impact trade processing or performance.**  
2. **Ensure that existing monitoring mechanisms …

Remove `ThinMarketTimer` Dependency from `RealTimeDataIngestionImpl`

---

src/main/java/com/verlumen/tradestream/ingestion/RealTimeDataIngestionImpl.java

This PR **refactors `RealTimeDataIngestionImpl`** to improve **code consistency, formatting, and readability** without modifying functionality.
---
✅ **Standardized indentation and formatting**:
- Converted indentation to **2 spaces** for consistency with other files.
- Reformatted method signatures and bodies for **better readability**.
✅ **Improved logging clarity**:
- **Retained** meaningful log statements.
- **Ensured consistency** in log formatting across methods.
✅ **Refactored method structure**:
- **Grouped methods logically** to enhance readability.
- **Removed redundant whitespace** and adjusted method spacing.
---
📏 **Ensures consistent formatting**—Improves maintainability and aligns with best practices.  
📝 **Enhances readability**—Reduces cognitive load when reviewing or …

Refactor `RealTimeDataIngestionImpl` for Code Consistency and Readability

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/CreateCandles.java

- **Added FluentLogger** to `CreateCandles` for better traceability.  
- **Logged key steps** in the candle aggregation process, including element processing, state updates, and timer execution.  
- **Included aggregate state tracking** to log updates in real-time.  
- **Added `toString` method** to `Aggregate` for easier debugging output.  
- This enhances visibility into how candles are formed and helps troubleshoot potential issues.

Improve Logging in `CreateCandles` for Better Debugging

---

src/main/java/com/verlumen/tradestream/pipeline/App.java
src/main/java/com/verlumen/tradestream/pipeline/PipelineConfig.java

- **Introduced `allowedTimestampSkew`** in `PipelineConfig` to handle out-of-order trade events gracefully.  
- **Updated `WithTimestamps`** to use `withAllowedTimestampSkew` for better event alignment.  
- **Enhanced logging** to track timestamp assignments, including skew handling.  
- **Refactored `PipelineConfig`** to encapsulate `allowedTimestampSkew` for centralized configuration.

 Improve Event Timestamp Handling with Allowed Skew 

---

src/main/java/com/verlumen/tradestream/pipeline/PipelineConfig.java

Reverts tradestreamhq/tradestream#735

Revert "Adjust Allowed Timestamp Skew for Late Arriving Trades  "

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/MultiTimeframeCandleTransform.java

This PR introduces **Guice dependency injection** to `MultiTimeframeCandleTransform` and updates the **BUILD file** to reflect necessary dependencies.  
---
- **Added `@Inject` constructor** for `MultiTimeframeCandleTransform`.  
- Enables **automatic dependency management** via Guice.  
- Improves **testability** by allowing **mocking of injected components**.  
- Added `//third_party:guice` to **marketdata module dependencies**.  
- Ensures proper Guice binding and dependency resolution.  
---
✔ **Encapsulates Dependency Management** – No manual instantiation needed.  
✔ **Improves Testability** – Supports unit testing with mocks.  
✔ **Enhances Code Maintainability** – Ensures consistency across the pipeline.  
This **lays the groundwork for more modular and scalable transformations** …

Add Dependency Injection to MultiTimeframeCandleTransform

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaults.java
src/main/java/com/verlumen/tradestream/marketdata/DefaultTradeGenerator.java
src/main/java/com/verlumen/tradestream/marketdata/LastCandlesFn.java
src/main/java/com/verlumen/tradestream/marketdata/MarketDataConfig.java
src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
src/main/java/com/verlumen/tradestream/marketdata/MultiTimeframeCandleTransform.java
src/main/java/com/verlumen/tradestream/marketdata/ParseTrades.java
src/main/java/com/verlumen/tradestream/marketdata/SlidingCandleAggregator.java
src/main/java/com/verlumen/tradestream/marketdata/TradePublisher.java
src/main/java/com/verlumen/tradestream/marketdata/TradePublisherImpl.java
src/main/java/com/verlumen/tradestream/pipeline/App.java
src/main/java/com/verlumen/tradestream/pipeline/BUILD
src/main/java/com/verlumen/tradestream/pipeline/PipelineConfig.java
src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java
src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml
src/test/java/com/verlumen/tradestream/marketdata/BUILD
src/test/java/com/verlumen/tradestream/marketdata/CandleStreamWithDefaultsTest.java
src/test/java/com/verlumen/tradestream/marketdata/DefaultTradeGeneratorTest.java
src/test/java/com/verlumen/tradestream/marketdata/LastCandlesFnTest.java
src/test/java/com/verlumen/tradestream/marketdata/MultiTimeframeCandleTransformTest.java
src/test/java/com/verlumen/tradestream/marketdata/ParseTradesTest.java
src/test/java/com/verlumen/tradestream/marketdata/SlidingCandleAggregatorTest.java
src/test/java/com/verlumen/tradestream/marketdata/TradePublisherImplTest.java

Reverts tradestreamhq/tradestream#759

Revert "Delete src/main/java/com/verlumen/tradestream/marketdata directory"

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/MultiTimeframeCandleTransform.java

This PR **adds structured logging** to `MultiTimeframeCandleTransform`, improving **observability, debugging, and monitoring** of the candle aggregation process.  
---
✅ **Added FluentLogger for structured logging**  
- **Why?**  
- Enables **fine-grained visibility** into each transformation step.  
- **Benefit:**  
- **Debugging time is reduced**, and **unexpected behavior is easier to diagnose**.  
✅ **Logged key steps in the transformation pipeline**  
1. **Grouping by key** (log when grouping occurs).  
2. **Consolidating candles** (log the last candle per key).  
3. **Branching candles into multiple timeframes** (log buffer size and timeframe label).  
4. **Applying GlobalWindows to branches** (log rewindowing).  
5. **Flattening branches** (log before merging).  
✅ **Reworded and …

 Improve Logging & Add Debugging to Multi-Timeframe Candle Transform  

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/LastCandlesFn.java

This PR **enhances debugging and traceability** for `LastCandlesFn.BufferLastCandles` by adding **structured logging using FluentLogger**.  
---
✅ **Added detailed logging at key transformation steps**  
- Logs when a **candle is added**, **a default candle is detected**, and **when a buffer exceeds its size limit**.  
- **Logs the buffer content before and after modifications** for debugging.  
✅ **Improved handling of default candles**  
- **Prevents duplicate default candles** from being added.  
- **Fills missing candles** by carrying forward the last close price if needed.  
✅ **Ensures buffer maintains the correct order**  
- **Logs sorting operations** to ensure **candles are in ascending timestamp order**.  
- Helps prevent **out-of-order processing bugs**.  
✅ **Provides better …

Improve Debugging & Logging for Candle Buffering

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/SlidingCandleAggregator.java

This PR **improves logging and traceability** in the `SlidingCandleAggregator` and `CandleAccumulator` by adding **structured logging using FluentLogger**.  
---
✅ **Added detailed logging for SlidingCandleAggregator**  
- Logs when **the sliding window is applied** and **when trades are aggregated into candles**.  
- Provides **visibility into Combine operations** for debugging.  
- Logs **input and output PCollections** to help trace transformations.  
✅ **Enhanced CandleCombineFn logging**  
- Logs **each trade being added to the accumulator**, making it easier to debug anomalies.  
- **Ensures synthetic/default trades are correctly ignored** if real trades exist.  
- Logs when **accumulators are merged**, providing insight into the final output.  
✅ **Better visibility into buffer …

Enhance Logging & Debugging for SlidingCandleAggregator and Candle Accumulator

---

README.md

This PR significantly expands the `README.md` to provide a more comprehensive overview of the TradeStream platform. Key updates include:  
- **Detailed Architecture Overview**:  
- Breakdown of major components, including data ingestion, processing pipeline, strategy engine, and monitoring.  
- Added a **Mermaid diagram** to visualize data flow through Kafka and Flink.  
- **Installation and Configuration**:  
- Step-by-step instructions for deploying the platform using Helm on Kubernetes.  
- Introduced a configuration table for key parameters (e.g., Kafka replicas, run modes).  
- **Project Structure**:  
- Organized directory structure with descriptions of key modules and their functions.  
- **CI/CD Pipeline**:  
- Overview of GitHub Actions workflows for testing, Kubernetes …

Enhance README with Detailed Architecture, Installation, and CI/CD Information  

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImpl.java
src/test/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImplTest.java

This PR enhances the **GeneticAlgorithmOrchestratorImpl** by:  
- **Refactoring `createBarSeries`** to use `BarSeriesBuilder`, simplifying bar series creation.  
- **Improving documentation** with JavaDoc comments for better maintainability and clarity.  
- **Adding `currencyPair` field** to test candle creation for improved test accuracy.  
- **Optimizing test setup** by initializing timestamps once, preventing inconsistent test results.  
- **Updating `BUILD` file** to include the new `bar_series_builder` dependency.  
These changes improve **code clarity, maintainability, and test reliability** while streamlining backtesting functionality.  
- Existing tests were updated and validated.  
- No breaking changes expected.

Improve Genetic Algorithm Backtesting with BarSeriesBuilder & Enhanced Docs  

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/FitnessCalculator.java

This PR introduces a new `FitnessCalculator` interface in the `backtesting` package to define a contract for fitness score evaluation in genetic algorithms. The interface provides a method, `createFitnessFunction`, which takes a `GAOptimizationRequest` and returns a function to evaluate the fitness of a genotype.
- **Added `FitnessCalculator.java`**:  
- Defines an interface for calculating fitness scores using backtesting.  
- Uses `jenetics` library for genotype representation (`DoubleGene`).  
- Introduces `createFitnessFunction` method for fitness function creation.  
- **Updated `BUILD` file**:  
- Added a new `java_library` target for `fitness_calculator`.  
- Declared dependencies on `//protos:backtesting_java_proto` and `//third_party:jenetics`.  
This change is part of the …

Add FitnessCalculator interface for genetic algorithm fitness evaluation 

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/FitnessCalculatorImpl.java
src/test/java/com/verlumen/tradestream/backtesting/BUILD
src/test/java/com/verlumen/tradestream/backtesting/FitnessCalculatorImplTest.java

This PR introduces the `FitnessCalculatorImpl` class, which implements the `FitnessCalculator` interface to evaluate fitness scores for genetic algorithm individuals using backtesting. Key changes include:
- **New Implementation:**
- Added `FitnessCalculatorImpl.java` to `backtesting` package.
- Uses `BacktestRunner` and `GenotypeConverter` to compute strategy scores.
- Handles exceptions by returning `Double.NEGATIVE_INFINITY` to penalize invalid genotypes.
- **Build & Dependency Updates:**
- Updated `BUILD` files to include `fitness_calculator_impl` as a new Java library.
- Added necessary dependencies such as `guice`, `jenetics`, and `protobuf_java`.
- **Unit Tests:**
- Introduced `FitnessCalculatorImplTest.java` to validate behavior.
- Tests include:
- Valid genotype producing …

Add `FitnessCalculatorImpl` for Genetic Algorithm Backtesting (MINOR)

---

.github/workflows/ci.yaml

This PR streamlines the CI workflow by removing unnecessary debug steps, redundant logging, and excessive diagnostic commands. The key improvements include:
- **Refactored Namespace and Secret Creation:** Combined into a single step to reduce redundancy.
- **Simplified Image Build and Load Process:** Removed redundant logging and unnecessary function wrappers, while ensuring images are built and loaded efficiently.
- **Fixed Helm Chart Installation:** Corrected pipeline image repository reference from `tradestream-data-ingestion` to `tradestream-data-pipeline`.
- **Removed Excessive Debugging Steps:** Eliminated unnecessary debugging, such as manual logging, diagnostic traps, and masked echo commands.
- **Ensured Consistent Error Handling:** Added `set -eo pipefail` where appropriate for …

Simplify CI Workflow and Improve Stability in Minikube Deployment  

---

src/main/java/com/verlumen/tradestream/signals/BUILD
src/main/java/com/verlumen/tradestream/signals/SignalsModule.java
src/main/java/com/verlumen/tradestream/strategies/StrategiesModule.java

This PR introduces changes to `SignalsModule` to improve its design and dependency injection approach. The key modifications include:
- **AutoValue Integration:**  
- `SignalsModule` is now an `@AutoValue` class, allowing for immutable object creation.
- A new `signalTopic()` method is introduced to store a required configuration value.
- **Dependency Injection Improvements:**  
- Added a `@Provides` method to supply a `TradeSignalPublisher` instance using the `signalTopic()`.  
- Removed the manual `SignalsModule.create()` installation in `StrategiesModule`, instead passing `signalTopic()` dynamically.
- **BUILD File Update:**  
- Added a dependency on `//third_party:auto_value` to support `@AutoValue`.
These changes enhance code maintainability, reduce boilerplate, and ensure better …

Refactor SignalsModule to Use AutoValue and Improve Dependency Injection

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/BacktestRunnerImpl.java
src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/OptimizeStrategies.java
src/main/java/com/verlumen/tradestream/ta4j/BUILD
src/main/java/com/verlumen/tradestream/ta4j/BarSeriesBuilder.java
src/main/java/com/verlumen/tradestream/ta4j/BarSeriesFactory.java
src/main/java/com/verlumen/tradestream/ta4j/Ta4jModule.java
src/test/java/com/verlumen/tradestream/backtesting/BUILD
src/test/java/com/verlumen/tradestream/backtesting/BacktestRunnerImplTest.java
src/test/java/com/verlumen/tradestream/strategies/BUILD
src/test/java/com/verlumen/tradestream/strategies/OptimizeStrategiesTest.java
src/test/java/com/verlumen/tradestream/ta4j/BUILD

This PR introduces a refactor by replacing direct usage of `BarSeriesBuilder` with a new `BarSeriesFactory` interface, allowing for better flexibility and dependency injection. Key changes include:
- **Introduced `BarSeriesFactory`** as an interface for creating `BarSeries` instances from market data candles.
- **Updated `BacktestRunnerImpl` and `OptimizeStrategiesDoFn`** to use `BarSeriesFactory` instead of the static `BarSeriesBuilder`.
- **Added `Ta4jModule`** to facilitate dependency injection for `BarSeriesFactory` using Guice.
- **Modified BUILD files** across multiple packages to include `bar_series_factory` and `ta4j_module`.
- **Updated unit tests** to incorporate `Ta4jModule` for proper dependency injection.
This change improves code maintainability, testability, and adherence …

Refactor `BarSeriesBuilder` to `BarSeriesFactory` and Introduce Dependency Injection

---

src/main/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestrator.java

This PR modifies the `GeneticAlgorithmOrchestrator` interface to extend `Serializable`, ensuring that instances of implementing classes can be serialized. 
- **Added `Serializable` import** in `GeneticAlgorithmOrchestrator.java`.
- **Updated `GeneticAlgorithmOrchestrator` to extend `Serializable`**, enabling object serialization.
- This change facilitates the persistence or transmission of objects implementing this interface, which can be useful in distributed processing or caching scenarios.
- Marking interfaces as `Serializable` ensures that implementing classes are aware of potential serialization requirements.
- This is a **minor enhancement** since it adds new functionality (serialization support) without breaking existing implementations.
Let me know if you'd like any refinements! 🚀

Enhance GeneticAlgorithmOrchestrator with Serializable Interface (MINOR)

---

src/main/java/com/verlumen/tradestream/backtesting/FitnessCalculator.java

This update modifies the `FitnessCalculator` interface to extend `Serializable`. This change ensures that implementations of `FitnessCalculator` can be serialized, which may be useful for scenarios involving distributed processing or caching of genetic algorithm configurations.  
- Added `Serializable` to `FitnessCalculator` to enable object serialization.
This change enhances flexibility in handling fitness calculation logic while maintaining compatibility with Java serialization mechanisms.

Add Serializable to FitnessCalculator for improved persistence  

---

src/main/java/com/verlumen/tradestream/backtesting/GAEngineFactory.java

This PR updates the `GAEngineFactory` interface to extend `Serializable`. This change ensures that implementations of `GAEngineFactory` can be serialized, which may be necessary for distributed processing or persistence scenarios.  
- Updated `GAEngineFactory` to extend `Serializable`.
- Allows instances of `GAEngineFactory` to be serialized when required.
- Enhances compatibility with frameworks that rely on serialization for object persistence or distribution.
No functional changes to existing behavior are introduced.

Enhance GAEngineFactory with Serializable Implementation

---

src/main/java/com/verlumen/tradestream/kafka/KafkaProducerProvider.java

Reverts tradestreamhq/tradestream#838

Revert "Remove unused import in `KafkaProducerProvider`  "

---

src/main/java/com/verlumen/tradestream/pipeline/BUILD

Reverts tradestreamhq/tradestream#850

Revert "Update OCI image base from Flink Java 17 to OpenJDK"

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/ParamConfig.java
src/main/java/com/verlumen/tradestream/backtesting/ParamConfigManagerImpl.java

Reverts tradestreamhq/tradestream#852

Revert "Enhance `ParamConfigManagerImpl` Initialization and Add Serializable Support to `ParamConfig`"

---

src/main/java/com/verlumen/tradestream/pipeline/BUILD

This update refactors the `BUILD` file in the `tradestream.pipeline` module to ensure consistent indentation and formatting. The changes include:
- Adjusting indentation to improve readability and maintain consistency.
- Ensuring dependencies and runtime dependencies are properly aligned.
- Formatting list elements (`deps`, `runtime_deps`, `args`, `tars`) with uniform spacing.
No functional changes were introduced, only improvements in structure and clarity for better maintainability.

Refactor BUILD file for consistent indentation and formatting

---

patches/java/conf/services/BUILD
patches/java/conf/services/java.util.random.RandomGenerator
src/main/java/com/verlumen/tradestream/pipeline/BUILD
src/main/java/com/verlumen/tradestream/pipeline/container-structure-test.yaml

Reverts tradestreamhq/tradestream#855

Revert "Add RandomGenerator service configuration and update JVM random provider settings"

---

src/main/java/com/verlumen/tradestream/backtesting/ParamConfig.java

This change updates `ParamConfig` to implement `Serializable`, ensuring better compatibility with distributed processing frameworks and potential persistence needs.  
- Added `Serializable` to the `ParamConfig` interface to support object serialization.  
- This enhancement enables easier storage and transmission of `ParamConfig` instances in distributed systems.  
This update introduces a minor version change as it extends functionality without breaking existing implementations.

(MINOR) Make ParamConfig Serializable for Improved Compatibility

---

src/main/java/com/verlumen/tradestream/pipeline/App.java

This PR introduces several improvements to `App.java` by enhancing code consistency, readability, and formatting. The changes include:
- **Organized Imports**: Reordered imports to maintain logical grouping (e.g., `ImmutableList` and `MultiTimeframeCandleTransform` adjustments).
- **Consistent Spacing & Formatting**:
- Adjusted blank lines for improved readability.
- Reformatted multi-line function calls and logging statements for better alignment.
- **Lambda Expression Cleanup**:
- Used method reference and consistent formatting in `WithTimestamps` and `MapElements` calls.
- Ensured proper indentation and readability in inline lambda functions.
- **Comment Formatting**: Standardized Javadoc-style comments and aligned them properly with method definitions.
- **Logging Improvements**:
- …

Refactor `App.java` for Code Consistency and Readability

---

src/main/java/com/verlumen/tradestream/backtesting/ParamConfigManagerImpl.java

This update improves the `ParamConfigManagerImpl` class by adding detailed JavaDoc comments and refining error handling.  
- Added class-level documentation explaining its role in managing parameter configurations for strategies.  
- Documented the `getParamConfig` method, clarifying its purpose and expected behavior.  
- Improved error handling in `getParamConfig` by including a descriptive message in `checkArgument`, making debugging easier when a configuration is missing.  
These enhancements improve code readability, maintainability, and usability.

Enhance `ParamConfigManagerImpl` with Documentation and Error Handling  

---

protos/strategies.proto

This update enhances the `StrategyType` enum in `strategies.proto` by adding detailed documentation for each strategy type. The documentation now includes a description of indicators, entry and exit conditions, and configurable parameters for each strategy. 
- Added structured comments for all strategies, improving clarity and usability.
- Introduced an `UNSPECIFIED` default strategy type for better handling of unknown values.
- Expanded descriptions for existing strategies, providing more in-depth explanations.
- Standardized parameter names across different strategy types for consistency.
These improvements will enhance developer experience, making it easier to understand and implement various trading strategies.

(MINOR) Enhance StrategyType Enum with Detailed Documentation and Additional Strategy Parameters

---

src/main/java/com/verlumen/tradestream/backtesting/BUILD
src/main/java/com/verlumen/tradestream/backtesting/FitnessCalculator.java
src/main/java/com/verlumen/tradestream/backtesting/FitnessCalculatorImpl.java
src/main/java/com/verlumen/tradestream/backtesting/GAEngineFactory.java
src/main/java/com/verlumen/tradestream/backtesting/GAEngineFactoryImpl.java
src/main/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImpl.java
src/main/java/com/verlumen/tradestream/backtesting/GenotypeConverter.java
src/main/java/com/verlumen/tradestream/backtesting/GenotypeConverterImpl.java
src/main/java/com/verlumen/tradestream/backtesting/oscillators/SmaRsiParamConfig.java
src/test/java/com/verlumen/tradestream/backtesting/FitnessCalculatorImplTest.java
src/test/java/com/verlumen/tradestream/backtesting/GAEngineFactoryImplTest.java
src/test/java/com/verlumen/tradestream/backtesting/GeneticAlgorithmOrchestratorImplTest.java
src/test/java/com/verlumen/tradestream/backtesting/GenotypeConverterImplTest.java

This PR refactors the genetic algorithm implementation to improve type safety, enhance flexibility, and introduce better logging and error handling.  
- **Generalization of `Genotype` Types**:  
- Replaced `Genotype<DoubleGene>` with `Genotype<?>` across multiple classes (`FitnessCalculator`, `GAEngineFactory`, `GenotypeConverter`) to allow for broader genetic representations.  
- Updated method signatures to handle generic chromosome types dynamically.  
- **Refactored `GAEngineFactoryImpl#createGenotype`**:  
- Improved chromosome initialization by checking for numeric chromosome types (`DoubleChromosome`, `IntegerChromosome`), ensuring type consistency.  
- Implemented better error handling and logging when unexpected chromosome types are encountered.  
- **Improved …

Refactor Genetic Algorithm Codebase for Improved Type Safety and Flexibility (MINOR)  

---

charts/tradestream/templates/pipeline.yaml

Reverts tradestreamhq/tradestream#875

Revert "Set default random generator for pipeline job  "

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java

- **BUILD File Updates:**
- Added dependencies for:
- `exchange_client_unbounded_reader`
- `exchange_client_unbounded_source`
- `exchange_client_unbounded_source_impl`
- **MarketDataModule.java Updates:**
- Bound `ExchangeClientUnboundedSource` to its implementation `ExchangeClientUnboundedSourceImpl`.
- Added a `FactoryModuleBuilder` to implement `ExchangeClientUnboundedReader` and build its factory.
These changes add support for unbounded data sources and readers in the `MarketDataModule`, enabling better handling of streaming exchange data.
- Introduces new dependencies, ensuring the module can handle unbounded data sources.
- Improves flexibility and scalability by allowing new types of readers and sources to be plugged in.
✅ Ready for review.

(MINOR) Add support for ExchangeClientUnboundedReader and UnboundedSource in MarketDataModule

---

README.md

This PR updates the `README.md` to reflect recent architectural changes that consolidate multiple components into a unified data pipeline. 
- Merged **Data Ingestion**, **Data Pipeline**, and **Strategy Engine** into a single **Data Pipeline** that handles data ingestion, processing, technical indicator computation, and strategy evaluation.
- Updated the component list to remove obsolete entries and streamline the architecture overview.
- Revised the data flow diagram to align with the new pipeline architecture.
- Updated the description of processing steps to reflect the consolidated data pipeline.
- Modified the configuration parameters to remove the now-redundant `dataIngestion.runMode` setting.
- Simplified project structure by removing `ingestion/` and reflecting updated pipeline …

Refactor README to reflect consolidated data pipeline and strategy engine

---

src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedSourceImpl.kt

Reverts tradestreamhq/tradestream#928

Revert "(MINOR) Improve ExchangeClientUnboundedSourceImpl with Serializable Factory and Reader Initialization"

---

src/main/java/com/verlumen/tradestream/marketdata/CoinbaseStreamingClient.java

]#### Summary
- Updated `CoinbaseStreamingClient` and its inner classes (`MessageHandler`, `WebSocketConnector`, and `WebSocketListener`) to support Java serialization.
- Marked non-serializable fields (`httpClient`, `tradeHandler`, `connector`, and `messageHandler`) as `transient` to prevent them from being serialized.
- Added `writeObject` and `readObject` methods to:
- Properly handle transient fields by recreating them during deserialization.
- Ensure that necessary objects (such as `HttpClient` and `WebSocketConnector`) are reinitialized correctly after deserialization.
- `httpClient`, `tradeHandler`, `connector`, and `messageHandler` marked as `transient` with logic to reinitialize in `readObject()`.
- `MessageHandler`, `WebSocketConnector`, and `WebSocketListener` updated to …

( MINOR ) Add serialization support to CoinbaseStreamingClient and WebSocket classes

---

src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedReader.kt

This PR refactors `ExchangeClientUnboundedReader` to improve code readability, modularity, and trade processing efficiency. Key changes include:
- **Refactored Streaming Initialization:**
- Extracted `getCurrencyPairs()` to obtain the list of currency pairs to stream.
- Extracted `startExchangeStreaming()` to encapsulate streaming setup logic.
- **Improved Trade Processing:**
- Moved trade processing logic to a new `processTrade()` method, enhancing readability and maintaining a clean streaming callback.
- Enhanced logging and error handling for trade processing, ensuring that errors are logged with relevant context.
- **Advance Method Improvements:**
- Refined `advance()` method to handle empty queues and idle watermark advancement more effectively.
- Ensured that trade processing logic …

Refactor ExchangeClientUnboundedReader to Improve Trade Processing and Streaming Management

---

src/main/java/com/verlumen/tradestream/marketdata/ExchangeClientUnboundedReader.kt

This PR introduces more detailed and informative logging to `ExchangeClientUnboundedReader.kt` to improve traceability and visibility of key operations. The changes enhance the logging for:
- **Initialization and First Advance:**
- Logs the initial attempt to call `advance()` and the result of that call.
- **Currency Pair Retrieval:**
- Upgraded the logging from `atFine` to `atInfo` to log the size and contents of the retrieved pairs.
- **Trade Processing:**
- Logs received trades with detailed attributes (ID, Exchange, Pair, Price).
- Logs when a null trade is encountered and skipped.
- Logs queue status after attempting to add a trade.
- **Advance and Current Trade:**
- Provides visibility when `advance()` is called, including the queue size and streaming status.
- Logs details when a …

Increase Logging Granularity in ExchangeClientUnboundedReader for Better Trade and State Visibility (MINOR)

---

.github/workflows/bazel-test.yaml
.github/workflows/ci.yaml
.github/workflows/release.yaml

Reverts tradestreamhq/tradestream#970

Revert "Integrate BuildBuddy Remote Caching and Enhance Bazel Build Settings (MINOR)"

---

MODULE.bazel
charts/tradestream/values.yaml
src/main/java/com/verlumen/tradestream/pipeline/App.java
src/main/java/com/verlumen/tradestream/pipeline/BUILD

Reverts tradestreamhq/tradestream#984

Revert "Revert 983 revert 974 tryagain"

---

.bazelrc
.github/workflows/bazel-test.yaml
.github/workflows/ci.yaml
.github/workflows/release.yaml
MODULE.bazel

Reverts tradestreamhq/tradestream#976

Revert "Integrate BuildBuddy for Remote Caching and Clean Up Bazel Configuration"

---

charts/tradestream/templates/checkpoint-pvc.yaml

Reverts tradestreamhq/tradestream#1013

Revert "Revert "Create checkpoint-pvc.yaml""

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/TiingoResponseParser.kt
src/test/java/com/verlumen/tradestream/marketdata/BUILD
src/test/java/com/verlumen/tradestream/marketdata/TiingoResponseParserTest.kt

This change introduces a new Kotlin component, `TiingoResponseParser`, for parsing candle data from the Tiingo Crypto Price API. The parser handles various edge cases including empty responses, malformed JSON, and missing fields, ensuring resilience in production use.
* Added `TiingoResponseParser.kt`, a utility object that:
* Parses candle data from Tiingo's JSON response format.
* Converts timestamps using `OffsetDateTime` and `java.time` for ISO 8601 compliance.
* Sorts parsed candles chronologically to ensure order integrity.
* Handles errors gracefully with warnings and fallbacks.
* Introduced a new `kt_jvm_library` target in the BUILD file for `tiingo_response_parser`.
* Created `TiingoResponseParserTest.kt` with comprehensive test coverage for:
* Valid candle parsing.
* Candle …

Add Tiingo Crypto Price Response Parser with Robust JSON Handling and Tests (MINOR)

---

src/main/java/com/verlumen/tradestream/marketdata/TiingoCryptoFetcherFn.kt
src/test/java/com/verlumen/tradestream/marketdata/TiingoCryptoFetcherFnTest.kt

This PR introduces significant enhancements to the `TiingoCryptoFetcherFn`:
1. **Incremental Fetch Logic**: The fetcher now incrementally updates the state to reflect the last successfully fetched timestamp, optimizing API calls and reducing redundant fetches.
2. **Forward-Filling of Missing Candles**: Implemented logic to fill forward missing candle data when gaps are detected. This is particularly important for maintaining time-series consistency in the absence of data from Tiingo.
3. **State Management Improvements**:
* Replaced the fixed `DEFAULT_START_DATE` with a dynamic computation of one year ago if no previous state exists.
* Introduced `StateTimestamp` as a serializable wrapper for state handling.
* Added state persistence for the last emitted candle to assist with incremental …

(MINOR) Enhance TiingoCryptoFetcherFn with incremental fetch, forward-filling, and state optimization

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/TiingoCandleSource.kt
src/main/java/com/verlumen/tradestream/marketdata/TiingoCryptoCandleSource.kt
src/main/java/com/verlumen/tradestream/marketdata/TiingoCryptoCandleTransform.kt

This PR introduces the following enhancements and modifications:
1. **New `TiingoCryptoCandleSource` implementation**:
* Created as a new `kt_jvm_library` in the `BUILD` file.
* Uses `PeriodicImpulse` to trigger API calls to Tiingo at specified intervals.
* Supports dependency injection via Guice with AssistedInject for `candleInterval` and `apiKey`.
2. **Integration of AssistedInject in `TiingoCryptoCandleTransform`**:
* Refactored `TiingoCryptoCandleTransform` to utilize AssistedInject for setting the `granularity` and `apiKey`.
* Introduced a `Factory` interface for flexible injection.
* Ensures proper instantiation of the `TiingoCryptoFetcherFn` using the factory pattern.
3. **BUILD File Changes**:
* Added `kt_jvm_library` definition for `tiingo_crypto_candle_source`.
* Updated …

Add `TiingoCryptoCandleSource` and integrate AssistedInject for `TiingoCryptoCandleTransform` (MINOR)

---

src/main/java/com/verlumen/tradestream/marketdata/BUILD
src/main/java/com/verlumen/tradestream/marketdata/MarketDataModule.java
src/main/java/com/verlumen/tradestream/pipeline/PipelineModule.java

This PR introduces integration with the **Tiingo Crypto API** within the `MarketDataModule`, enabling crypto candle data ingestion and transformation. Key changes include:
* **BUILD File Updates**:
* Added new dependencies for `:tiingo_crypto_candle_source`, `:tiingo_crypto_candle_transform`, and `:tiingo_crypto_fetcher_fn`.
* Included `joda_time` for duration handling.
* **MarketDataModule Enhancements**:
* Updated the `MarketDataModule.create` factory method to accept `Duration granularity` and `String tiingoApiKey`.
* Added `TiingoCryptoCandleSource`, `TiingoCryptoCandleTransform`, and `TiingoCryptoFetcherFn` factory installations.
* Implemented a new provider for `CandleSource` that conditionally initializes:
* `TradeBackedCandleSource` for DRY run mode.
* `TiingoCryptoCandleSource` …

Add Support for Tiingo Crypto Candle Source and Transform in MarketDataModule (MINOR)

---

services/candle_ingestor/BUILD
services/candle_ingestor/cmc_client.py
services/candle_ingestor/cmc_client_test.py
services/candle_ingestor/influx_client.py
services/candle_ingestor/influx_client_test.py
services/candle_ingestor/main.py

This PR introduces the integration of:
* **CoinMarketCap API** for fetching the top N cryptocurrency symbols and formatting them for Tiingo.
* **InfluxDB Client** for connecting and managing database interactions within the `candle_ingestor` service.
---
1. **BUILD File Enhancements**:
* Added `cmc_client_lib` and `influx_client_lib` as `py_library` targets.
* Updated `main` target dependencies to include the new libraries.
* Defined new `py_test` targets for unit testing `cmc_client` and `influx_client`.
2. **`cmc_client.py`:**
* Implements `get_top_n_crypto_symbols` which fetches and formats top cryptocurrency symbols from CoinMarketCap.
* Handles API errors gracefully with logging and retries if necessary.
3. **`influx_client.py`:**
* Defines `InfluxDBManager`, a wrapper around …

(MINOR) Integrate CoinMarketCap API and InfluxDB Client into Candle Ingestor Service

---

services/candle_ingestor/BUILD
services/candle_ingestor/influx_client.py
services/candle_ingestor/ingestion_helpers.py
services/candle_ingestor/ingestion_helpers_test.py
services/candle_ingestor/main.py
services/candle_ingestor/tiingo_client.py
services/candle_ingestor/tiingo_client_test.py

This PR introduces significant enhancements to the `candle_ingestor` service, primarily focused on enabling historical backfilling of candle data from the Tiingo API, along with the necessary helper utilities and InfluxDB write support. Key additions include:
---
1. **`ingestion_helpers.py`**:
* Added utility functions:
* `get_tiingo_resample_freq()`: Converts minute-based granularity into Tiingo-compatible resample strings.
* `parse_backfill_start_date()`: Parses flexible backfill start dates (e.g., "X\_days\_ago").
2. **`tiingo_client.py`**:
* Added:
* `get_top_n_crypto_symbols()`: Fetches the top N crypto symbols from CoinMarketCap.
* `get_historical_candles_tiingo()`: Pulls historical candle data from Tiingo for specified tickers and date ranges.
3. **`influx_client.py`**:
* Enhanced …

(MINOR) Introduce Ingestion Helpers, Tiingo Client, and Historical Backfill Support

---

services/candle_ingestor/main.py
services/candle_ingestor/main_test.py

This PR introduces significant improvements and refinements to the `candle_ingestor` service, focusing primarily on the **historical backfill** and **real-time polling** mechanisms. Key changes include:
---
1. **Chunked Backfill Logic Improvements**:
* Ensures that partially backfilled tickers resume from the last known timestamp.
* Prevents overlapping of date ranges, optimizing API calls and avoiding redundant writes.
* Enhanced logging to reflect accurate chunk ranges and timestamps.
2. **Resilience to Incomplete Data**:
* If no data is returned for a chunk, the logic now handles it gracefully and continues without interruptions.
* Added detailed logging to identify gaps during backfill for easier debugging.
---
1. **Improved Timestamp Initialization**:
* Tickers without backfill data …

(MINOR) Improve Candle Ingestor Backfill and Polling Logic for Robustness and Efficiency

---

.bazelrc

Reverts tradestreamhq/tradestream#1074

Revert "Enable remote build execution with Build Buddy"

---

services/candle_ingestor/cmc_client.py
services/candle_ingestor/cmc_client_test.py
services/candle_ingestor/influx_client.py
services/candle_ingestor/influx_client_test.py
services/candle_ingestor/ingestion_helpers.py
services/candle_ingestor/ingestion_helpers_test.py
services/candle_ingestor/main.py
services/candle_ingestor/main_test.py
services/candle_ingestor/tiingo_client.py
services/candle_ingestor/tiingo_client_test.py

This PR makes **whitespace-only** adjustments across multiple files in the `candle_ingestor` service. No functional or logic changes are introduced.
* Reformatted imports and function parameters for consistency and readability.
* Normalized spacing around comments, conditionals, and control structures.
* Aligned inline comments and block indentation for clarity.
* Removed unnecessary blank lines and ensured consistent newline placement.
* Updated test files to match formatting conventions used in main modules.
These changes are purely cosmetic and aim to improve code readability and maintain consistent style across the codebase.

Normalize whitespace and formatting across candle ingestion modules

---

shared/cryptoclient/BUILD
shared/cryptoclient/redis_crypto_client.py
shared/cryptoclient/redis_crypto_client_test.py

This PR introduces a Redis-backed client (`RedisCryptoClient`) to fetch top cryptocurrency pairs from a Redis store with robust retry logic and error handling. The client is designed to gracefully handle connection issues and malformed data, improving resilience in systems relying on Redis for crypto pair data.
* **New Python library**: `redis_crypto_client.py`
* Implements `RedisCryptoClient` with:
* Connection retries using `tenacity`
* Graceful degradation on connection failures
* JSON parsing and validation of data from Redis
* **New unit tests**: `redis_crypto_client_test.py`
* Thorough test coverage including:
* Successful and failed connections
* Data parsing edge cases
* Retry behavior
* Final fallback behavior when Redis is unavailable
* **BUILD file updates**:
* Added …

Add Redis-backed crypto client with retry logic and unit tests (MINOR)

---

services/strategy_discovery_request_factory/main.py

Replaced hardcoded InfluxDB flag defaults with values from environment variables.

Read InfluxDB config from environment variables in request factory

---

charts/tradestream/templates/strategy-discovery-request-factory.yaml
charts/tradestream/values.yaml
services/strategy_discovery_request_factory/BUILD
services/strategy_discovery_request_factory/container-structure-test.yaml
services/strategy_discovery_request_factory/main.py
services/strategy_discovery_request_factory/main_test.py

Strategy Discovery Request Factory now fetches cryptocurrency pairs from Redis instead of static config.

Replace hardcoded currency pair config with Redis-based retrieval (MINOR)

---

services/candle_ingestor/ccxt_client.py
services/candle_ingestor/ccxt_client_test.py

Introduce symbol availability caching in the CCXT client to avoid unnecessary API requests and improve efficiency.

Add CCXT symbol support caching to reduce redundant API calls (MINOR)

---

src/main/java/com/verlumen/tradestream/discovery/BUILD
src/main/java/com/verlumen/tradestream/discovery/FitnessCalculationParams.kt

Introduced a new Kotlin data class `FitnessCalculationParams` to encapsulate the inputs required for evaluating trading strategy fitness. This class includes the strategy type and a list of historical market data (`Candle` instances).
* Added `FitnessCalculationParams.kt` to define the new parameter model.
* Updated the `BUILD` file to:
* Add a new `kt_jvm_library` target for `fitness_calculation_params`.
* Include relevant proto dependencies (`backtesting_java_proto`, `strategies_java_proto`).
This addition lays the groundwork for more modular and type-safe handling of strategy evaluation inputs.

Add `FitnessCalculationParams` Kotlin data class for strategy evaluation

---

src/main/java/com/verlumen/tradestream/discovery/FitnessFunction.kt

Reverts tradestreamhq/tradestream#1187

Revert "Update FitnessFunction.kt"

---

src/test/java/com/verlumen/tradestream/marketdata/InfluxDbCandleFetcherTest.kt

Refactored the `testConfig` initialization in `InfluxDbCandleFetcherTest.kt` to improve readability by aligning the constructor parameters vertically and adding a trailing comma. This change ensures consistent formatting with Kotlin style conventions and facilitates easier future diffs. No functional changes were made.

Fix formatting in `InfluxDbCandleFetcherTest` for consistent parameter indentation

---

.github/workflows/ci.yaml
charts/tradestream/Chart.yaml
charts/tradestream/templates/strategy-discovery-pipeline.yaml
charts/tradestream/values.yaml

This PR integrates the Bitnami PostgreSQL Helm chart into the Tradestream deployment to manage PostgreSQL as part of the Helm release. Key changes include:
* Added `postgresql` as a chart dependency in `charts/tradestream/Chart.yaml`.
* Enabled PostgreSQL in the CI pipeline by setting `--set postgresql.enabled=true`.
* Updated `values.yaml` to configure PostgreSQL using the Helm-managed service and secret.
* Replaced hardcoded or manually created PostgreSQL secrets with templated references to auto-generated secrets.
* Adjusted template values in `strategy-discovery-pipeline.yaml` to use `tpl` for proper evaluation of templated secret names and hostnames.
These changes improve maintainability by managing PostgreSQL lifecycle through Helm and eliminate the need for manually applied …

Integrate Bitnami PostgreSQL Helm Chart into Tradestream Deployment (MINOR)

---

src/main/java/com/verlumen/tradestream/strategies/momentumsmacrossover/BUILD
src/main/java/com/verlumen/tradestream/strategies/momentumsmacrossover/MomentumSmaCrossoverParamConfig.java
src/test/java/com/verlumen/tradestream/strategies/momentumsmacrossover/BUILD
src/test/java/com/verlumen/tradestream/strategies/momentumsmacrossover/MomentumSmaCrossoverParamConfigTest.java

This change introduces parameter configuration support for the `MomentumSmaCrossover` strategy by implementing a dedicated `MomentumSmaCrossoverParamConfig` class. Key additions include:
* **New Java Library:** Defined `param_config` in the `BUILD` file to encapsulate the parameter configuration logic for this strategy.
* **Parameter Implementation:** Added `MomentumSmaCrossoverParamConfig.java` to specify chromosome specifications and parameter generation using `jenetics` and protocol buffers.
* **Unit Tests:** Added `MomentumSmaCrossoverParamConfigTest` to verify chromosome specs, parameter creation, and strategy type identification.
* **Test BUILD Update:** Updated the test `BUILD` file to include the new test target for `param_config`.
These changes integrate the strategy with the …

Add ParamConfig support for MomentumSmaCrossover strategy

---

src/main/java/com/verlumen/tradestream/strategies/macdcrossover/BUILD
src/main/java/com/verlumen/tradestream/strategies/macdcrossover/MacdCrossoverParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/macdcrossover/MacdCrossoverStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/macdcrossover/BUILD
src/test/java/com/verlumen/tradestream/strategies/macdcrossover/MacdCrossoverParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/macdcrossover/MacdCrossoverStrategyFactoryTest.java

This PR introduces a new trading strategy based on the MACD crossover technique. Key changes include:
* **Strategy Implementation:**
* `MacdCrossoverStrategyFactory`: Generates TA4J-compatible strategies using MACD and signal line crossovers.
* `MacdCrossoverParamConfig`: Defines genetic algorithm parameters for tuning short EMA, long EMA, and signal periods.
* **BUILD Configuration:**
* Added Bazel `BUILD` files for compiling and testing the strategy and its configuration.
* **Unit Tests:**
* `MacdCrossoverParamConfigTest`: Validates parameter generation and strategy type handling.
* `MacdCrossoverStrategyFactoryTest`: Tests strategy creation with synthetic price data and verifies validation logic.
These additions introduce new functionality and are marked with (MINOR) as per versioning …

Add MACD Crossover Strategy Implementation and Tests (MINOR)

---

src/main/java/com/verlumen/tradestream/strategies/awesomeoscillator/AwesomeOscillatorParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/awesomeoscillator/AwesomeOscillatorStrategyFactory.java
src/main/java/com/verlumen/tradestream/strategies/awesomeoscillator/BUILD
src/test/java/com/verlumen/tradestream/strategies/awesomeoscillator/AwesomeOscillatorParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/awesomeoscillator/AwesomeOscillatorStrategyFactoryTest.java
src/test/java/com/verlumen/tradestream/strategies/awesomeoscillator/BUILD

This PR introduces a new trading strategy based on the Awesome Oscillator indicator. The following components have been added:
* **Strategy Factory (`AwesomeOscillatorStrategyFactory`)**: Implements the Awesome Oscillator strategy using TA4J, with validation to ensure period consistency and default parameter support.
* **Parameter Configuration (`AwesomeOscillatorParamConfig`)**: Defines the chromosome specifications for short and long periods and translates them into `AwesomeOscillatorParameters`.
* **Tests**:
* `AwesomeOscillatorStrategyFactoryTest` verifies strategy creation and validation logic.
* `AwesomeOscillatorParamConfigTest` covers parameter creation, validation, and initialization.
* **Build Targets**: Added BUILD files for both main and test classes.
These additions enable …

Add Awesome Oscillator Strategy Implementation and Configuration

---

src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
src/main/java/com/verlumen/tradestream/strategies/momentumpinball/MomentumPinballStrategyFactory.java
src/main/java/com/verlumen/tradestream/strategies/volumeweightedmacd/BUILD
src/main/java/com/verlumen/tradestream/strategies/volumeweightedmacd/VolumeWeightedMacdLineIndicator.java
src/main/java/com/verlumen/tradestream/strategies/volumeweightedmacd/VolumeWeightedMacdParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/volumeweightedmacd/VolumeWeightedMacdStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
src/test/java/com/verlumen/tradestream/strategies/momentumpinball/MomentumPinballParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/volumeweightedmacd/BUILD
src/test/java/com/verlumen/tradestream/strategies/volumeweightedmacd/VolumeWeightedMacdParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/volumeweightedmacd/VolumeWeightedMacdStrategyFactoryTest.java

**Summary**
This PR introduces a new **VolumeWeighted MACD** trading strategy to the codebase and ensures all related components are wired up correctly. Additionally, it includes minor code cleanups and formatting adjustments to existing `MomentumPinball` classes.
**Changes**
* **New Strategy Implementation**
* Added `VolumeWeightedMacdParamConfig.java`, `VolumeWeightedMacdLineIndicator.java`, and `VolumeWeightedMacdStrategyFactory.java` under `strategies/volumeweightedmacd`.
* Created corresponding `BUILD` files for library and test targets.
* Defines default parameters (short, long, and signal periods) and chromosome specs for genetic optimization.
* Implements MACD line and signal line calculation using TA4J EMAs.
* **Integration**
* Updated …

Add VolumeWeighted MACD strategy support (MINOR)

---

src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
src/main/java/com/verlumen/tradestream/strategies/volumespreadanalysis/BUILD
src/main/java/com/verlumen/tradestream/strategies/volumespreadanalysis/VolumeSpreadAnalysisParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/volumespreadanalysis/VolumeSpreadAnalysisStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
src/test/java/com/verlumen/tradestream/strategies/volumespreadanalysis/BUILD
src/test/java/com/verlumen/tradestream/strategies/volumespreadanalysis/VolumeSpreadAnalysisParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/volumespreadanalysis/VolumeSpreadAnalysisStrategyFactoryTest.java

This change introduces a new trading strategy, **VolumeSpreadAnalysis**, into the Tradestream platform. Key additions include:
* **Strategy Implementation**: `VolumeSpreadAnalysisStrategyFactory` provides logic for generating strategies based on volume spread dynamics.
* **Parameter Configuration**: `VolumeSpreadAnalysisParamConfig` defines chromosome specs and generates parameters for the strategy using volume period configuration.
* **StrategySpecs Integration**: Registered the new strategy in `StrategySpecs.kt` with proper factory and param config.
* **BUILD Files**: Updated and added necessary Bazel targets for the new strategy's source and test components.
* **Tests**:
* Unit tests for param config correctness and edge handling.
* Strategy factory tests to verify behavior with both …

Add VolumeSpreadAnalysis Strategy with ParamConfig and Factory

---

src/main/java/com/verlumen/tradestream/strategies/tickvolumeanalysis/BUILD
src/main/java/com/verlumen/tradestream/strategies/tickvolumeanalysis/TickVolumeAnalysisParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/tickvolumeanalysis/TickVolumeAnalysisStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/tickvolumeanalysis/BUILD
src/test/java/com/verlumen/tradestream/strategies/tickvolumeanalysis/TickVolumeAnalysisParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/tickvolumeanalysis/TickVolumeAnalysisStrategyFactoryTest.java

This PR introduces a new strategy module, `TickVolumeAnalysis`, to the trading strategy framework. Key additions include:
* **Strategy Factory**: Implements `TickVolumeAnalysisStrategyFactory`, which constructs a strategy based on tick volume indicators and their moving average to generate entry and exit signals.
* **Parameter Configuration**: Adds `TickVolumeAnalysisParamConfig` to support dynamic configuration of the `tickPeriod` parameter using genetic algorithms.
* **BUILD Targets**: Adds Bazel `BUILD` files for both main and test sources to define Java libraries and test suites.
* **Unit Tests**: Includes test classes `TickVolumeAnalysisParamConfigTest` and `TickVolumeAnalysisStrategyFactoryTest` to verify configuration behavior and strategy logic.
These changes enhance the framework …

Add TickVolumeAnalysis strategy with configurable parameters and tests

---

src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
src/main/java/com/verlumen/tradestream/strategies/dematemacrossover/BUILD
src/main/java/com/verlumen/tradestream/strategies/dematemacrossover/DemaTemaCrossoverParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/dematemacrossover/DemaTemaCrossoverStrategyFactory.java
src/main/java/com/verlumen/tradestream/strategies/momentumpinball/MomentumPinballStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
src/test/java/com/verlumen/tradestream/strategies/dematemacrossover/BUILD
src/test/java/com/verlumen/tradestream/strategies/dematemacrossover/DemaTemaCrossoverParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/dematemacrossover/DemaTemaCrossoverStrategyFactoryTest.java

This PR introduces a new trading strategy based on the crossover of Double Exponential Moving Average (DEMA) and Triple Exponential Moving Average (TEMA). Key updates include:
* **Strategy Implementation:** Added `DemaTemaCrossoverStrategyFactory` and supporting `DEMAIndicator` and `TEMAIndicator` logic.
* **Parameter Configuration:** Created `DemaTemaCrossoverParamConfig` to define and generate strategy parameters.
* **Integration:** Registered the strategy in `StrategySpecs.kt` and updated the associated Bazel build targets.
* **Testing:** Included unit tests for both the parameter configuration and strategy logic, ensuring correct behavior and robustness.
(MINOR) – This introduces a new feature that expands the set of available strategies without altering existing behavior.

Add DEMA-TEMA crossover strategy implementation and integration

---

src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
src/main/java/com/verlumen/tradestream/strategies/pivot/BUILD
src/main/java/com/verlumen/tradestream/strategies/pivot/PivotParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/pivot/PivotStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
src/test/java/com/verlumen/tradestream/strategies/pivot/BUILD
src/test/java/com/verlumen/tradestream/strategies/pivot/PivotParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/pivot/PivotStrategyFactoryTest.java

This PR introduces the Pivot Point strategy into the trading system.
**Summary of Changes:**
* Implemented `PivotParamConfig` to define genetic algorithm chromosome specs and parameter creation for the Pivot strategy.
* Created `PivotStrategyFactory` that defines strategy logic based on Pivot Points using TA4J indicators and rules.
* Integrated the new strategy into `StrategySpecs.kt` with a corresponding `StrategyType`.
* Updated the `BUILD` configurations to include the new strategy in both main and test targets.
* Added unit tests for both parameter config (`PivotParamConfigTest`) and strategy factory (`PivotStrategyFactoryTest`).
* Adjusted `StrategySpecsTest` to account for the additional strategy.
**(MINOR)** This is a minor version update as it introduces a new strategy feature.

Add Pivot Point Strategy Implementation

---

src/main/java/com/verlumen/tradestream/strategies/BUILD
src/main/java/com/verlumen/tradestream/strategies/StrategySpecs.kt
src/main/java/com/verlumen/tradestream/strategies/dpocrossover/BUILD
src/main/java/com/verlumen/tradestream/strategies/dpocrossover/DpoCrossoverParamConfig.java
src/main/java/com/verlumen/tradestream/strategies/dpocrossover/DpoCrossoverStrategyFactory.java
src/test/java/com/verlumen/tradestream/strategies/StrategySpecsTest.kt
src/test/java/com/verlumen/tradestream/strategies/dpocrossover/BUILD
src/test/java/com/verlumen/tradestream/strategies/dpocrossover/DpoCrossoverParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/dpocrossover/DpoCrossoverStrategyFactoryTest.java
src/test/java/com/verlumen/tradestream/strategies/gannswing/GannSwingParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/gannswing/GannSwingStrategyFactoryTest.java
src/test/java/com/verlumen/tradestream/strategies/rangebars/RangeBarsParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/rangebars/RangeBarsStrategyFactoryTest.java
src/test/java/com/verlumen/tradestream/strategies/renkochart/RenkoChartParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/renkochart/RenkoChartStrategyFactoryTest.java
src/test/java/com/verlumen/tradestream/strategies/sarmfi/SarMfiParamConfigTest.java
src/test/java/com/verlumen/tradestream/strategies/sarmfi/SarMfiStrategyFactoryTest.java

This PR introduces a new strategy, **DPO Crossover**, into the tradestream strategies module.
* **Strategy Integration:**
* Added `DpoCrossoverParamConfig` and `DpoCrossoverStrategyFactory` for strategy configuration and instantiation.
* Registered the new strategy in `StrategySpecs.kt` and updated the `BUILD` file.
* **Supporting Code:**
* Defined Bazel build rules for the strategy and test files.
* Implemented `DpoCrossoverParameters` handling in the config class using `jenetics` for chromosome generation.
* **Testing:**
* Added unit tests for both `DpoCrossoverParamConfig` and `DpoCrossoverStrategyFactory` to verify proper configuration and strategy creation.
* **Validation:**
* Updated `StrategySpecsTest` to validate inclusion of the new strategy, increasing the expected count to 57. …

Add DPO Crossover strategy with configuration, factory, and tests

---

MODULE.bazel
src/test/java/com/verlumen/tradestream/discovery/BUILD
src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt
third_party/java/BUILD

This PR adds comprehensive testing for PostgreSQL JSON/CSV serialization to prevent future database errors.
- Add Apache Commons CSV dependency for CSV parsing tests
- Add comprehensive CSV format validation tests  
- Add JSON validation tests with proper regex escaping
- Add PostgreSQL COPY compatibility tests
- Add edge case testing for malformed JSON
- Add batch filtering tests for invalid rows
- Fix regex string escaping for Java/Kotlin compatibility
- Catches JSON/CSV formatting issues before they reach production
- Validates PostgreSQL COPY command compatibility
- Ensures robust error handling for malformed data
- All tests passing and production-ready
This addresses the root cause of the 'invalid input syntax for type json' errors by ensuring proper JSON formatting and CSV …

Add comprehensive PostgreSQL JSON/CSV testing

---

MODULE.bazel
src/main/java/com/verlumen/tradestream/discovery/BUILD
src/main/java/com/verlumen/tradestream/discovery/DiscoveryModule.kt
src/main/java/com/verlumen/tradestream/discovery/PostgresStrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/StrategyCsvUtil.kt
src/main/java/com/verlumen/tradestream/discovery/StrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
src/main/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistry.kt
src/test/java/com/verlumen/tradestream/discovery/BUILD
src/test/java/com/verlumen/tradestream/discovery/PostgresStrategyRepositoryTest.kt
src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt
src/test/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistryTest.kt
third_party/java/BUILD

This PR introduces a StrategyRepository abstraction to improve the architecture of the strategy discovery pipeline by separating persistence concerns from the Apache Beam DoFn.
- **StrategyRepository Interface**: Defines contract for discovered strategy persistence
- **PostgresStrategyRepository**: PostgreSQL implementation using bulk copy operations
- **StrategyCsvUtil**: Utility class for CSV row conversion with base64 JSON encoding
- **WriteDiscoveredStrategiesToPostgresFn**: Now uses repository pattern instead of direct CSV conversion
- **DiscoveryModule**: Binds StrategyRepository to PostgresStrategyRepository
- **StrategyParameterTypeRegistry**: Updated to use JSON serialization instead of TextProto
- Added comprehensive unit tests for PostgresStrategyRepository
- Updated …

feat: Add StrategyRepository abstraction with PostgresStrategyRepository implementation

---

src/main/java/com/verlumen/tradestream/discovery/BUILD
src/main/java/com/verlumen/tradestream/discovery/DiscoveryModule.kt
src/main/java/com/verlumen/tradestream/discovery/PostgresStrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/StrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt
src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt

This PR updates the strategy repository implementation and related tests to improve functionality and maintainability.

Update strategy repository implementation and tests

---

src/main/java/com/verlumen/tradestream/discovery/PostgresStrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/StrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFn.kt

This PR applies code formatting to Kotlin files using ktlint and Bazel files using buildifier. Changes include formatting improvements to discovery-related files.

Format code with ktlint and buildifier

---

src/main/java/com/verlumen/tradestream/discovery/BUILD
src/main/java/com/verlumen/tradestream/discovery/DiscoveryModule.kt
src/main/java/com/verlumen/tradestream/discovery/DryRunStrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/PostgresStrategyRepository.kt
src/main/java/com/verlumen/tradestream/discovery/StrategyCsvUtil.kt
src/main/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistry.kt
src/test/java/com/verlumen/tradestream/discovery/WriteDiscoveredStrategiesToPostgresFnTest.kt
src/test/java/com/verlumen/tradestream/strategies/StrategyParameterTypeRegistryTest.kt

This PR includes two main features:
- New DryRunStrategyRepository.kt implementation for testing and dry-run scenarios
- Implements the StrategyRepository interface without actual database persistence
- Useful for development, testing, and validation workflows
- Problem: Strategy parameters were being stored inconsistently (JSON vs base64)
- Solution: Standardize on base64 encoding for Protocol Buffer Any objects
- Write Path: Convert Protocol Buffer Any to base64 to JSON wrapper with base64_data field
- Read Path: Decode base64 to Protocol Buffer Any objects
- Benefits: More efficient, reliable, and consistent data serialization
Core Implementation:
- StrategyCsvUtil.kt: Updated to encode Protocol Buffer data as base64
- PostgresStrategyRepository.kt: Updated to decode base64 back to …

Add DryRunStrategyRepository and implement base64 encoding for strategy parameters

---

services/risk_adjusted_sizing/main.py
services/strategy_confidence_scorer/main.py
services/strategy_confidence_scorer/main_test.py
services/strategy_consumer/postgres_client.py
services/strategy_consumer/postgres_client_integration_test.py
services/strategy_consumer/strategy_inspector.py
services/strategy_ensemble/main.py
services/strategy_monitor_api/main.py
services/strategy_rotation/main.py
services/strategy_time_filter/main.py

This PR applies the black formatter to all Python files in the repository to ensure consistent code formatting.
- Applied black formatting to 10 Python files
- Ensures consistent code style across the codebase
- Improves readability and maintainability
- services/risk_adjusted_sizing/main.py
- services/strategy_confidence_scorer/main.py
- services/strategy_confidence_scorer/main_test.py
- services/strategy_consumer/postgres_client.py
- services/strategy_consumer/postgres_client_integration_test.py
- services/strategy_consumer/strategy_inspector.py
- services/strategy_ensemble/main.py
- services/strategy_monitor_api/main.py
- services/strategy_rotation/main.py
- services/strategy_time_filter/main.py
All formatting changes are purely cosmetic and do not affect functionality.

Format Python code with black formatter

---

.github/workflows/release.yaml

This PR implements an improved version of the parallel release workflow that addresses the issues from PR #1429. Instead of the complex artifact sharing approach that was reverted, this uses a GitHub Actions matrix strategy for a simpler and more reliable solution.
- **Matrix Strategy**: Uses GitHub Actions matrix to run 8 parallel jobs, one per service
- **Self-Contained Jobs**: Each job handles its own build and push (no artifact sharing)
- **Simpler Architecture**: Eliminates complex artifact upload/download dependencies
- **Better Reliability**: No issues with executable permissions or environment dependencies
- **Easier Debugging**: Each service has its own isolated job log
- **Proper Dependencies**: Clear job dependency chain with version passing
1. **prepare-release**: Handles …

feat: implement improved parallel release workflow with matrix strategy

---

ui/strategy-monitor/BUILD
ui/strategy-monitor/nginx.conf

This PR fixes the UI container issues that were preventing the Strategy Monitor UI from working correctly.
- **Fixed nginx.conf**: Updated root directory from  to 
- **Updated OCI image setup**: Added proper entrypoint and cmd to copy files to correct location
- **Added executable target**: Created  target for local development
- **Fixed file placement**: Static files now properly served from nginx container
✅ Tarball generation works: 
✅ Docker loading works: Loaded image: strategy-monitor-ui:latest
✅ Container execution works: Serves correct UI files (64KB vs 615 bytes for default nginx)
✅ CI workflow compatible: Uses correct tarball target
The issue was that static files were being placed in  instead of , and the nginx configuration wasn't being applied properly at startup.
The OCI …

Fix UI container issues: update nginx config and OCI image setup

---

ui/strategy-monitor/index.html
ui/strategy-monitor/nginx.conf

🎉 **Massive Milestone: Live Data Connection!**
This PR connects the Strategy Monitor UI to **real live data** from the PostgreSQL database via the strategy-monitor-api service.
- ✅ **Live Data**: Real strategy data from PostgreSQL (not mock data!)
- ✅ **Real-time Updates**: Connects to actual trading strategies  
- ✅ **Production Ready**: Works in Kubernetes with service discovery
- ✅ **Dev Compatible**: Still works with localhost for development
- Added proxy_pass for `/api/*` requests to `tradestream-dev-strategy-monitor-api:8080`
- Configured CORS headers for browser compatibility
- Maintains fallback to localhost for development
- Changed from hardcoded `http://localhost:8080/api/strategies`
- Now uses relative URLs: `/api/strategies` and `/api/metrics`
- Nginx handles routing to …

feat: Connect strategy-monitor-ui to live data
